# Code generated by qwick.

import numpy as np
from ebcc.util import pack_2e, einsum, direct_sum, Namespace

def energy(f=None, v=None, nocc=None, nvir=None, t1=None, t2=None, **kwargs):
    # energy
    e_cc = 0
    e_cc += np.einsum("ia,ia->", f.ov, t1)
    e_cc += np.einsum("ijab,ijab->", t2, v.oovv) * 0.25
    e_cc += np.einsum("ia,jb,ijab->", t1, t1, v.oovv) * 0.5

    return e_cc

def update_amps(f=None, v=None, nocc=None, nvir=None, t1=None, t2=None, **kwargs):
    # T amplitudes
    t1new = np.zeros((nocc, nvir), dtype=np.float64)
    t1new += np.einsum("ia->ia", f.ov)
    t1new += np.einsum("ij,ja->ia", f.oo, t1) * -1.0
    t1new += np.einsum("ab,ib->ia", f.vv, t1)
    t1new += np.einsum("jb,ijab->ia", f.ov, t2)
    t1new += np.einsum("jb,ibja->ia", t1, v.ovov) * -1.0
    t1new += np.einsum("jkab,jkib->ia", t2, v.ooov) * -0.5
    t1new += np.einsum("ijbc,jabc->ia", t2, v.ovvv) * -0.5
    t1new += np.einsum("jb,ib,ja->ia", f.ov, t1, t1) * -1.0
    t1new += np.einsum("jb,ka,jkib->ia", t1, t1, v.ooov)
    t1new += np.einsum("ib,jc,jabc->ia", t1, t1, v.ovvv) * -1.0
    t1new += np.einsum("ib,jkac,jkbc->ia", t1, t2, v.oovv) * -0.5
    t1new += np.einsum("ja,ikbc,jkbc->ia", t1, t2, v.oovv) * -0.5
    t1new += np.einsum("jb,ikac,jkbc->ia", t1, t2, v.oovv)
    t1new += np.einsum("ib,jc,ka,jkbc->ia", t1, t1, t1, v.oovv)
    t2new = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    t2new += np.einsum("ijab->ijab", v.oovv)
    t2new += np.einsum("ik,jkab->ijab", f.oo, t2)
    t2new += np.einsum("jk,ikab->ijab", f.oo, t2) * -1.0
    t2new += np.einsum("ac,ijbc->ijab", f.vv, t2) * -1.0
    t2new += np.einsum("bc,ijac->ijab", f.vv, t2)
    t2new += np.einsum("ka,ijkb->ijab", t1, v.ooov) * -1.0
    t2new += np.einsum("kb,ijka->ijab", t1, v.ooov)
    t2new += np.einsum("ic,jcab->ijab", t1, v.ovvv) * -1.0
    t2new += np.einsum("jc,icab->ijab", t1, v.ovvv)
    t2new += np.einsum("klab,ijkl->ijab", t2, v.oooo) * 0.5
    t2new += np.einsum("ikac,jckb->ijab", t2, v.ovov) * -1.0
    t2new += np.einsum("ikbc,jcka->ijab", t2, v.ovov)
    t2new += np.einsum("jkac,ickb->ijab", t2, v.ovov)
    t2new += np.einsum("jkbc,icka->ijab", t2, v.ovov) * -1.0
    t2new += np.einsum("ijcd,abcd->ijab", t2, v.vvvv) * 0.5
    t2new += np.einsum("kc,ic,jkab->ijab", f.ov, t1, t2)
    t2new += np.einsum("kc,jc,ikab->ijab", f.ov, t1, t2) * -1.0
    t2new += np.einsum("kc,ka,ijbc->ijab", f.ov, t1, t2)
    t2new += np.einsum("kc,kb,ijac->ijab", f.ov, t1, t2) * -1.0
    t2new += np.einsum("ka,lb,ijkl->ijab", t1, t1, v.oooo)
    t2new += np.einsum("ic,ka,jckb->ijab", t1, t1, v.ovov)
    t2new += np.einsum("ic,kb,jcka->ijab", t1, t1, v.ovov) * -1.0
    t2new += np.einsum("jc,ka,ickb->ijab", t1, t1, v.ovov) * -1.0
    t2new += np.einsum("jc,kb,icka->ijab", t1, t1, v.ovov)
    t2new += np.einsum("ic,jd,abcd->ijab", t1, t1, v.vvvv)
    t2new += np.einsum("ic,klab,kljc->ijab", t1, t2, v.ooov) * -0.5
    t2new += np.einsum("jc,klab,klic->ijab", t1, t2, v.ooov) * 0.5
    t2new += np.einsum("ka,ilbc,kljc->ijab", t1, t2, v.ooov)
    t2new += np.einsum("ka,jlbc,klic->ijab", t1, t2, v.ooov) * -1.0
    t2new += np.einsum("kb,ilac,kljc->ijab", t1, t2, v.ooov) * -1.0
    t2new += np.einsum("kb,jlac,klic->ijab", t1, t2, v.ooov)
    t2new += np.einsum("kc,ilab,kljc->ijab", t1, t2, v.ooov)
    t2new += np.einsum("kc,jlab,klic->ijab", t1, t2, v.ooov) * -1.0
    t2new += np.einsum("ic,jkbd,kacd->ijab", t1, t2, v.ovvv) * -1.0
    t2new += np.einsum("ic,jkad,kbcd->ijab", t1, t2, v.ovvv)
    t2new += np.einsum("jc,ikbd,kacd->ijab", t1, t2, v.ovvv)
    t2new += np.einsum("jc,ikad,kbcd->ijab", t1, t2, v.ovvv) * -1.0
    t2new += np.einsum("ka,ijcd,kbcd->ijab", t1, t2, v.ovvv) * -0.5
    t2new += np.einsum("kb,ijcd,kacd->ijab", t1, t2, v.ovvv) * 0.5
    t2new += np.einsum("kc,ijbd,kacd->ijab", t1, t2, v.ovvv) * -1.0
    t2new += np.einsum("kc,ijad,kbcd->ijab", t1, t2, v.ovvv)
    t2new += np.einsum("ikac,jlbd,klcd->ijab", t2, t2, v.oovv)
    t2new += np.einsum("ikab,jlcd,klcd->ijab", t2, t2, v.oovv) * -0.5
    t2new += np.einsum("ikbc,jlad,klcd->ijab", t2, t2, v.oovv) * -1.0
    t2new += np.einsum("ikcd,jlab,klcd->ijab", t2, t2, v.oovv) * -0.5
    t2new += np.einsum("ijac,klbd,klcd->ijab", t2, t2, v.oovv) * -0.5
    t2new += np.einsum("ijbc,klad,klcd->ijab", t2, t2, v.oovv) * 0.5
    t2new += np.einsum("ijcd,klab,klcd->ijab", t2, t2, v.oovv) * 0.25
    t2new += np.einsum("ic,ka,lb,kljc->ijab", t1, t1, t1, v.ooov) * -1.0
    t2new += np.einsum("jc,ka,lb,klic->ijab", t1, t1, t1, v.ooov)
    t2new += np.einsum("ic,jd,ka,kbcd->ijab", t1, t1, t1, v.ovvv) * -1.0
    t2new += np.einsum("ic,jd,kb,kacd->ijab", t1, t1, t1, v.ovvv)
    t2new += np.einsum("ic,jd,klab,klcd->ijab", t1, t1, t2, v.oovv) * 0.5
    t2new += np.einsum("ic,ka,jlbd,klcd->ijab", t1, t1, t2, v.oovv) * -1.0
    t2new += np.einsum("ic,kb,jlad,klcd->ijab", t1, t1, t2, v.oovv)
    t2new += np.einsum("ic,kd,jlab,klcd->ijab", t1, t1, t2, v.oovv) * -1.0
    t2new += np.einsum("jc,ka,ilbd,klcd->ijab", t1, t1, t2, v.oovv)
    t2new += np.einsum("jc,kb,ilad,klcd->ijab", t1, t1, t2, v.oovv) * -1.0
    t2new += np.einsum("jc,kd,ilab,klcd->ijab", t1, t1, t2, v.oovv)
    t2new += np.einsum("ka,lb,ijcd,klcd->ijab", t1, t1, t2, v.oovv) * 0.5
    t2new += np.einsum("kc,la,ijbd,klcd->ijab", t1, t1, t2, v.oovv)
    t2new += np.einsum("kc,lb,ijad,klcd->ijab", t1, t1, t2, v.oovv) * -1.0
    t2new += np.einsum("ic,jd,ka,lb,klcd->ijab", t1, t1, t1, t1, v.oovv)

    return {"t1new": t1new, "t2new": t2new}

def energy_perturbative(f=None, v=None, nocc=None, nvir=None, t1=None, t2=None, l1=None, l2=None, **kwargs):
    # T3 amplitude
    t3 = np.zeros((nocc, nocc, nocc, nvir, nvir, nvir), dtype=np.float64)
    t3 += einsum("ilab,jklc->ijkabc", t2, v.ooov) * -1.0
    t3 += einsum("ilac,jklb->ijkabc", t2, v.ooov)
    t3 += einsum("ilbc,jkla->ijkabc", t2, v.ooov) * -1.0
    t3 += einsum("jlab,iklc->ijkabc", t2, v.ooov)
    t3 += einsum("jlac,iklb->ijkabc", t2, v.ooov) * -1.0
    t3 += einsum("jlbc,ikla->ijkabc", t2, v.ooov)
    t3 += einsum("klab,ijlc->ijkabc", t2, v.ooov) * -1.0
    t3 += einsum("klac,ijlb->ijkabc", t2, v.ooov)
    t3 += einsum("klbc,ijla->ijkabc", t2, v.ooov) * -1.0
    t3 += einsum("ikad,jdbc->ijkabc", t2, v.ovvv)
    t3 += einsum("ikbd,jdac->ijkabc", t2, v.ovvv) * -1.0
    t3 += einsum("ikcd,jdab->ijkabc", t2, v.ovvv)
    t3 += einsum("ijad,kdbc->ijkabc", t2, v.ovvv) * -1.0
    t3 += einsum("ijbd,kdac->ijkabc", t2, v.ovvv)
    t3 += einsum("ijcd,kdab->ijkabc", t2, v.ovvv) * -1.0
    t3 += einsum("jkad,idbc->ijkabc", t2, v.ovvv) * -1.0
    t3 += einsum("jkbd,idac->ijkabc", t2, v.ovvv)
    t3 += einsum("jkcd,idab->ijkabc", t2, v.ovvv) * -1.0
    e_ia = direct_sum("i-a->ia", np.diag(f.oo), np.diag(f.vv))
    e_ijkabc = direct_sum("ia+jb+kc->ijkabc", e_ia, e_ia, e_ia)
    t3 /= e_ijkabc
    del e_ijkabc

    # energy
    e_pert = 0
    e_pert += einsum("ai,jkbc,ijkabc->", l1, v.oovv, t3) * 0.25
    e_pert += einsum("abij,kljc,iklabc->", l2, v.ooov, t3) * -0.25
    e_pert += einsum("abij,kbcd,ijkacd->", l2, v.ovvv, t3) * -0.25

    return e_pert

