"""
Code generated by `albert`:
https://github.com/obackhouse/albert

  * date: 2024-10-20T09:35:50.080302
  * python version: 3.10.15 (main, Sep  9 2024, 03:02:45) [GCC 11.4.0]
  * albert version: 0.0.0
  * caller: /opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/albert/codegen/einsum.py
  * node: fv-az985-968
  * system: Linux
  * processor: x86_64
  * release: 6.5.0-1025-azure
"""

from ebcc import numpy as np
from ebcc.util import pack_2e, einsum, dirsum, Namespace


def energy(t2=None, v=None, **kwargs):
    """
    Code generated by `albert` 0.0.0 on 2024-10-20T09:35:51.461592.

    Parameters
    ----------
    t2 : array
        T2 amplitudes.
    v : array
        Electron repulsion integrals.

    Returns
    -------
    e_cc : float
        Coupled cluster energy.
    """

    e_cc = einsum(v.oovv, (0, 1, 2, 3), t2, (0, 1, 2, 3), ()) * 0.25

    return e_cc

def update_amps(f=None, t2=None, v=None, vs=None, **kwargs):
    """
    Code generated by `albert` 0.0.0 on 2024-10-20T09:36:14.285612.

    Parameters
    ----------
    f : array
        Fock matrix.
    t2 : array
        T2 amplitudes.
    v : array
        Electron repulsion integrals.
    vs : array

    Returns
    -------
    t2new : array
        Updated T2 residuals.
    """

    t2new = einsum(t2, (0, 1, 2, 3), v.oooo, (4, 5, 0, 1), (4, 5, 2, 3)) * 0.5
    t2new += v.oovv
    t2new += einsum(t2, (0, 1, 2, 3), v.vvvv, (4, 5, 2, 3), (0, 1, 4, 5)) * 0.5
    tmp0 = einsum(v.ovov, (0, 1, 2, 3), t2, (4, 2, 5, 1), (4, 0, 5, 3))
    t2new += tmp0 * -1
    t2new += np.transpose(tmp0, (0, 1, 3, 2))
    t2new += np.transpose(tmp0, (1, 0, 2, 3))
    t2new += np.transpose(tmp0, (1, 0, 3, 2)) * -1
    del tmp0
    tmp1 = einsum(f.vv, (0, 1), t2, (2, 3, 4, 1), (2, 3, 0, 4))
    t2new += np.transpose(tmp1, (1, 0, 2, 3))
    t2new += np.transpose(tmp1, (1, 0, 3, 2)) * -1
    del tmp1
    tmp2 = einsum(v.oovv, (0, 1, 2, 3), t2, (0, 1, 4, 3), (4, 2))
    tmp3 = einsum(tmp2, (0, 1), t2, (2, 3, 4, 1), (2, 3, 4, 0))
    del tmp2
    tmp6 = np.copy(tmp3) * -0.25
    del tmp3
    tmp4 = einsum(vs, (0, 1, 2, 3), t2, (4, 1, 5, 3), (4, 0, 5, 2))
    tmp5 = einsum(tmp4, (0, 1, 2, 3), t2, (4, 1, 5, 3), (4, 0, 5, 2))
    del tmp4
    tmp6 += tmp5
    del tmp5
    t2new += tmp6
    t2new += np.transpose(tmp6, (0, 1, 3, 2)) * -1
    del tmp6
    tmp7 = einsum(v.oovv, (0, 1, 2, 3), t2, (4, 1, 2, 3), (4, 0))
    tmp8 = einsum(tmp7, (0, 1), t2, (2, 1, 3, 4), (2, 0, 3, 4))
    del tmp7
    t2new += np.transpose(tmp8, (0, 1, 3, 2)) * 0.25
    t2new += np.transpose(tmp8, (1, 0, 3, 2)) * -0.25
    del tmp8
    tmp9 = einsum(t2, (0, 1, 2, 3), f.oo, (4, 1), (4, 0, 2, 3))
    t2new += np.transpose(tmp9, (0, 1, 3, 2)) * -1
    t2new += np.transpose(tmp9, (1, 0, 3, 2))
    del tmp9

    return {f"t2new": t2new}

