# Code generated by qwick.

import numpy as np
from pyscf import lib
from types import SimpleNamespace
from ebcc.util import pack_2e

def energy(f=None, v=None, nocc=None, nvir=None, t1=None, t2=None, **kwargs):
    # energy
    x0 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x0 += lib.einsum("iajb->jiab", v.ovov) * -0.5
    x0 += lib.einsum("iajb->jiba", v.ovov)
    e_cc = 0
    e_cc += lib.einsum("ijab,ijab->", t2, x0) * 2
    del x0
    x1 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x1 += lib.einsum("iajb->jiab", v.ovov)
    x1 += lib.einsum("iajb->jiba", v.ovov) * -0.5
    x2 = np.zeros((nocc, nvir), dtype=np.float64)
    x2 += lib.einsum("ia,ijba->jb", t1, x1)
    del x1
    x2 += lib.einsum("ia->ia", f.ov)
    e_cc += lib.einsum("ia,ia->", t1, x2) * 2
    del x2

    return e_cc

def update_amps(f=None, v=None, nocc=None, nvir=None, t1=None, t2=None, **kwargs):
    # T1 and T2 amplitudes
    x0 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x0 += lib.einsum("ia,jbka->ijkb", t1, v.ovov)
    x1 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x1 += lib.einsum("ijka->ijka", x0) * 2
    x1 += lib.einsum("ijka->ikja", x0) * -1
    x24 = np.zeros((nocc, nocc, nocc, nocc), dtype=np.float64)
    x24 += lib.einsum("ia,jkla->jilk", t1, x0)
    del x0
    x25 = np.zeros((nocc, nocc, nocc, nocc), dtype=np.float64)
    x25 += lib.einsum("ijkl->lkji", x24)
    del x24
    x1 += lib.einsum("ijka->jika", v.ooov) * -1
    x1 += lib.einsum("ijka->jkia", v.ooov) * 2
    t1new = np.zeros((nocc, nvir), dtype=np.float64)
    t1new += lib.einsum("ijab,kjib->ka", t2, x1) * -2
    del x1
    x2 = np.zeros((nocc, nvir, nvir, nvir), dtype=np.float64)
    x2 += lib.einsum("iabc->ibac", v.ovvv) * -0.5
    x2 += lib.einsum("iabc->ibca", v.ovvv)
    t1new += lib.einsum("ijab,icba->jc", t2, x2) * 4
    del x2
    x3 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x3 += lib.einsum("iajb->jiab", v.ovov) * 2
    x3 -= lib.einsum("iajb->jiba", v.ovov)
    x4 = np.zeros((nocc, nvir), dtype=np.float64)
    x4 += lib.einsum("ia,ijba->jb", t1, x3)
    del x3
    x4 += lib.einsum("ia->ia", f.ov)
    x5 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x5 += lib.einsum("ijab->jiab", t2) * 2
    x5 -= lib.einsum("ijab->jiba", t2)
    t1new += lib.einsum("ia,ijba->jb", x4, x5) * 2
    del x4
    del x5
    x6 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x6 += lib.einsum("iabj->ijba", v.ovvo) * 2
    x6 -= lib.einsum("ijab->ijab", v.oovv)
    t1new += lib.einsum("ia,ijba->jb", t1, x6) * 2
    del x6
    x7 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x7 += lib.einsum("iajb->jiab", v.ovov)
    x7 += lib.einsum("iajb->jiba", v.ovov) * -0.5
    x9 = np.zeros((nocc, nvir), dtype=np.float64)
    x9 += lib.einsum("ia,ijba->jb", t1, x7) * 2
    x10 = np.zeros((nocc, nocc), dtype=np.float64)
    x10 += lib.einsum("ijab,ikba->kj", t2, x7) * 2
    del x7
    x8 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x8 += lib.einsum("ijka->ikja", v.ooov)
    x8 += lib.einsum("ijka->kija", v.ooov) * -0.5
    x10 += lib.einsum("ia,jika->jk", t1, x8) * 2
    del x8
    x9 += lib.einsum("ia->ia", f.ov)
    x10 += lib.einsum("ia,ja->ji", t1, x9)
    del x9
    x10 += lib.einsum("ij->ij", f.oo)
    t1new += lib.einsum("ia,ij->ja", t1, x10) * -2
    del x10
    x11 = np.zeros((nocc, nvir, nvir, nvir), dtype=np.float64)
    x11 += lib.einsum("iabc->ibac", v.ovvv) * 2
    x11 -= lib.einsum("iabc->ibca", v.ovvv)
    x12 = np.zeros((nvir, nvir), dtype=np.float64)
    x12 += lib.einsum("ia,ibac->bc", t1, x11)
    del x11
    x12 += lib.einsum("ab->ab", f.vv)
    t1new += lib.einsum("ia,ba->ib", t1, x12) * 2
    del x12
    x13 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x13 += lib.einsum("ij,kiab->jkab", f.oo, t2)
    x21 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x21 -= lib.einsum("ijab->ijab", x13)
    del x13
    x14 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x14 += lib.einsum("ab,ijcb->ijac", f.vv, t2)
    x21 += lib.einsum("ijab->ijab", x14)
    del x14
    x15 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x15 += lib.einsum("ia,bjca->ijbc", t1, v.vovv)
    x21 += lib.einsum("ijab->ijab", x15)
    del x15
    x16 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x16 += lib.einsum("ia,jkba->ijkb", t1, v.oovv)
    x19 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x19 += lib.einsum("ijka->ijka", x16)
    del x16
    x17 = np.zeros((nocc, nocc, nocc, nocc), dtype=np.float64)
    x17 += lib.einsum("ia,jkla->ijlk", t1, v.ooov)
    x18 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x18 += lib.einsum("ia,jkil->jkla", t1, x17)
    del x17
    x19 -= lib.einsum("ijka->ijka", x18)
    del x18
    x20 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x20 += lib.einsum("ia,jikb->jkba", t1, x19)
    del x19
    x21 -= lib.einsum("ijab->ijba", x20)
    del x20
    t2new = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    t2new -= lib.einsum("ijab->ijab", x21) * 2
    t2new += lib.einsum("ijab->ijba", x21) * 4
    t2new += lib.einsum("ijab->jiab", x21) * 4
    t2new -= lib.einsum("ijab->jiba", x21) * 2
    del x21
    x22 = np.zeros((nocc, nvir, nvir, nvir), dtype=np.float64)
    x22 += lib.einsum("ia,bacd->icbd", t1, v.vvvv)
    x23 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x23 += lib.einsum("ia,jbca->ijbc", t1, x22)
    del x22
    x28 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x28 += lib.einsum("ijab->ijab", x23)
    del x23
    x25 += lib.einsum("ijkl->kilj", v.oooo)
    x26 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x26 += lib.einsum("ia,ijkl->jkla", t1, x25)
    del x25
    x27 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x27 += lib.einsum("ia,ijkb->kjba", t1, x26)
    del x26
    x28 += lib.einsum("ijab->ijba", x27)
    del x27
    t2new += lib.einsum("ijab->ijab", x28) * 4
    t2new -= lib.einsum("ijab->ijba", x28) * 2
    del x28
    x29 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x29 += lib.einsum("ia,jbca->ijcb", t1, v.ovvv)
    x30 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x30 += lib.einsum("ijab->jiab", x29)
    del x29
    x30 += lib.einsum("iabj->ijba", v.ovvo)
    x31 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x31 += lib.einsum("ia,jkba->jkib", t1, x30)
    del x30
    x32 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x32 += lib.einsum("ijka->kija", x31)
    del x31
    x32 += lib.einsum("ijak->jika", v.oovo)
    x33 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x33 += lib.einsum("ia,jikb->jkba", t1, x32)
    del x32
    t2new -= lib.einsum("ijab->ijba", x33) * 4
    t2new += lib.einsum("ijab->ijab", x33) * 2
    t2new += lib.einsum("ijab->jiba", x33) * 2
    t2new -= lib.einsum("ijab->jiab", x33) * 4
    del x33
    t1new += lib.einsum("ai->ia", f.vo) * 2
    t2new -= lib.einsum("aibj->jiab", v.vovo) * 2
    t2new += lib.einsum("aibj->jiba", v.vovo) * 4

    return {"t1new": t1new, "t2new": t2new}

def update_lams(f=None, v=None, nocc=None, nvir=None, t1=None, t2=None, l1=None, l2=None, **kwargs):
    # L1 and L2 amplitudes
    x0 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x0 += lib.einsum("ia,jkba->ijkb", f.ov, t2)
    x18 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x18 += lib.einsum("ijka->kija", x0) * 0.9999999999999993
    x18 += lib.einsum("ijka->jika", x0) * -1.9999999999999987
    del x0
    x1 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x1 += lib.einsum("ijab,kbca->jikc", t2, v.ovvv)
    x9 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x9 += lib.einsum("ijka->ijka", x1) * -1.9999999999999987
    del x1
    x2 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x2 += lib.einsum("ia,jbca->ijcb", t1, v.ovvv)
    x3 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x3 += lib.einsum("ia,jkba->ijkb", t1, x2)
    x9 += lib.einsum("ijka->ijka", x3) * -1.9999999999999987
    del x3
    x47 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x47 += lib.einsum("ijab->jiab", x2)
    x78 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x78 += lib.einsum("ijab->ijab", x2)
    del x2
    x4 = np.zeros((nocc, nocc, nocc, nocc), dtype=np.float64)
    x4 += lib.einsum("ijab,kalb->ijkl", t2, v.ovov)
    x7 = np.zeros((nocc, nocc, nocc, nocc), dtype=np.float64)
    x7 += lib.einsum("ijkl->jilk", x4)
    del x4
    x5 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x5 += lib.einsum("ia,jakb->ikjb", t1, v.ovov)
    x6 = np.zeros((nocc, nocc, nocc, nocc), dtype=np.float64)
    x6 += lib.einsum("ia,jkla->ijkl", t1, x5)
    x7 += lib.einsum("ijkl->ijkl", x6)
    x8 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x8 += lib.einsum("ia,jkil->jkla", t1, x7) * 1.9999999999999987
    del x7
    x9 += lib.einsum("ijka->jika", x8)
    del x8
    x18 += lib.einsum("ijka->jkia", x9)
    x18 += lib.einsum("ijka->ikja", x9) * -0.5
    del x9
    x106 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x106 += lib.einsum("abij,jikl->klba", l2, x6)
    del x6
    x107 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x107 += lib.einsum("ijab->ijab", x106) * 2
    del x106
    x13 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x13 += lib.einsum("ijka->ikja", x5) * -0.5
    x13 += lib.einsum("ijka->ijka", x5)
    x14 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x14 += lib.einsum("ijka->ikja", x5) * 2
    x14 += lib.einsum("ijka->ijka", x5) * -1
    x22 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x22 -= lib.einsum("ijka->ikja", x5)
    x22 += lib.einsum("ijka->ijka", x5) * 2
    x53 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x53 += lib.einsum("ijka->jkia", x5) * -0.5
    x53 += lib.einsum("ijka->kjia", x5)
    x80 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x80 += lib.einsum("ijka->ijka", x5)
    x97 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x97 += lib.einsum("ai,ijkb->jkab", l1, x5)
    del x5
    x101 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x101 += lib.einsum("ijab->ijab", x97)
    del x97
    x10 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x10 += lib.einsum("iajb->jiba", v.ovov)
    x10 += lib.einsum("iajb->jiab", v.ovov) * -0.5
    x11 = np.zeros((nocc, nvir), dtype=np.float64)
    x11 += lib.einsum("ia,ijab->jb", t1, x10)
    x12 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x12 += lib.einsum("ia,jkab->jkib", x11, t2) * 1.9999999999999987
    del x11
    x18 += lib.einsum("ijka->ikja", x12)
    x18 += lib.einsum("ijka->jkia", x12) * -2
    del x12
    x54 = np.zeros((nocc, nvir), dtype=np.float64)
    x54 += lib.einsum("ia,ijab->jb", t1, x10) * 2
    del x10
    x55 = np.zeros((nocc, nvir), dtype=np.float64)
    x55 += lib.einsum("ia->ia", x54)
    del x54
    x13 += lib.einsum("ijka->jkia", v.ooov)
    x13 += lib.einsum("ijka->jika", v.ooov) * -0.5
    x18 += lib.einsum("ijab,klib->klja", t2, x13) * 1.9999999999999987
    del x13
    x14 += lib.einsum("ijka->jkia", v.ooov) * -1
    x14 += lib.einsum("ijka->jika", v.ooov) * 2
    x18 += lib.einsum("ijab,klia->kljb", t2, x14) * 0.9999999999999993
    del x14
    x15 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x15 += lib.einsum("ijab->ijab", v.oovv) * 2
    x15 += lib.einsum("iabj->ijba", v.ovvo) * -1
    x18 += lib.einsum("ia,jkba->ijkb", t1, x15) * -0.9999999999999993
    del x15
    x16 = np.zeros((nocc, nocc, nocc, nocc), dtype=np.float64)
    x16 += lib.einsum("ia,jkla->ijlk", t1, v.ooov)
    x17 = np.zeros((nocc, nocc, nocc, nocc), dtype=np.float64)
    x17 += lib.einsum("ijkl->jkil", x16) * -0.5
    x17 += lib.einsum("ijkl->kjil", x16)
    x25 = np.zeros((nocc, nocc, nocc, nocc), dtype=np.float64)
    x25 -= lib.einsum("ijkl->ikjl", x16)
    x25 += lib.einsum("ijkl->ijkl", x16) * 2
    x26 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x26 += lib.einsum("ia,jikl->jkla", t1, x25)
    del x25
    x98 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x98 += lib.einsum("abij,jkli->klba", l2, x16)
    del x16
    x101 -= lib.einsum("ijab->ijab", x98)
    del x98
    x17 += lib.einsum("ijkl->kijl", v.oooo) * -0.5
    x17 += lib.einsum("ijkl->kilj", v.oooo)
    x18 += lib.einsum("ia,ijkl->kjla", t1, x17) * 1.9999999999999987
    del x17
    x18 += lib.einsum("ijak->kija", v.oovo) * -1.9999999999999987
    x18 += lib.einsum("ijak->jika", v.oovo) * 0.9999999999999993
    l1new = np.zeros((nvir, nocc), dtype=np.float64)
    l1new += lib.einsum("abij,ikja->bk", l2, x18) * 2.0000000000000013
    del x18
    x19 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x19 += lib.einsum("abij->jiba", l2) * 2
    x19 -= lib.einsum("abij->jiab", l2)
    x20 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x20 -= lib.einsum("ijab,ikac->kjcb", t2, x19)
    x20 += lib.einsum("abij,kjbc->ikac", l2, t2)
    x21 = np.zeros((nocc, nvir, nvir, nvir), dtype=np.float64)
    x21 -= lib.einsum("iabc->ibac", v.ovvv)
    x21 += lib.einsum("iabc->ibca", v.ovvv) * 2
    x72 = np.zeros((nvir, nvir), dtype=np.float64)
    x72 += lib.einsum("ia,ibca->bc", t1, x21)
    x73 = np.zeros((nvir, nvir), dtype=np.float64)
    x73 += lib.einsum("ab->ab", x72)
    x90 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x90 += lib.einsum("ab,acij->ijcb", x72, l2)
    del x72
    x92 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x92 -= lib.einsum("ijab->jiab", x90)
    del x90
    l1new -= lib.einsum("ijab,jacb->ci", x20, x21) * 2
    del x20
    del x21
    x22 += lib.einsum("ijka->jkia", v.ooov) * 2
    x22 -= lib.einsum("ijka->jika", v.ooov)
    x23 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x23 -= lib.einsum("ijab->jiba", t2)
    x23 += lib.einsum("ijab->jiab", t2) * 2
    x26 -= lib.einsum("ijka,jlba->iklb", x22, x23)
    del x22
    del x23
    x24 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x24 += lib.einsum("iabj->ijba", v.ovvo) * 2
    x24 -= lib.einsum("ijab->ijab", v.oovv)
    x26 -= lib.einsum("ia,jkba->ijkb", t1, x24)
    l1new += lib.einsum("abij,ikjb->ak", l2, x26) * 2
    del x26
    l1new += lib.einsum("ai,jiab->bj", l1, x24) * 2
    del x24
    x27 = np.zeros((nocc, nvir, nvir, nvir), dtype=np.float64)
    x27 += lib.einsum("ia,bcda->ibdc", t1, v.vvvv)
    x28 = np.zeros((nocc, nvir, nvir, nvir), dtype=np.float64)
    x28 += lib.einsum("iabc->ibac", x27) * -0.5
    x28 += lib.einsum("iabc->iabc", x27)
    del x27
    x28 += lib.einsum("aibc->ibac", v.vovv)
    x28 += lib.einsum("aibc->iabc", v.vovv) * -0.5
    l1new += lib.einsum("abij,ibac->cj", l2, x28) * 4
    del x28
    x29 = np.zeros((nocc, nocc, nocc, nocc), dtype=np.float64)
    x29 += lib.einsum("abij,klab->ijkl", l2, t2)
    x32 = np.zeros((nocc, nocc, nocc, nocc), dtype=np.float64)
    x32 += lib.einsum("ijkl->jilk", x29)
    x51 = np.zeros((nocc, nocc, nocc, nocc), dtype=np.float64)
    x51 += lib.einsum("ijkl->jikl", x29) * -0.5
    x51 += lib.einsum("ijkl->jilk", x29)
    del x29
    l1new += lib.einsum("ijka,jlik->al", v.ooov, x51) * 4
    del x51
    x30 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x30 += lib.einsum("ia,bajk->jkib", t1, l2)
    x31 = np.zeros((nocc, nocc, nocc, nocc), dtype=np.float64)
    x31 += lib.einsum("ia,jkla->kjli", t1, x30)
    x32 += lib.einsum("ijkl->ijkl", x31)
    x33 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x33 += lib.einsum("ia,ijkl->jkla", t1, x32)
    del x32
    x38 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x38 += lib.einsum("ijka->ijka", x33) * -1
    x38 += lib.einsum("ijka->ikja", x33) * 2
    del x33
    x50 = np.zeros((nocc, nocc, nocc, nocc), dtype=np.float64)
    x50 += lib.einsum("ijkl->ijkl", x31) * -1
    x50 += lib.einsum("ijkl->ijlk", x31) * 2
    l1new += lib.einsum("ijka,ljik->al", v.ooov, x50) * 2
    del x50
    x105 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x105 += lib.einsum("iajb,klji->lkab", v.ovov, x31)
    del x31
    x107 += lib.einsum("ijab->ijab", x105) * 2
    del x105
    l2new = np.zeros((nvir, nvir, nocc, nocc), dtype=np.float64)
    l2new += lib.einsum("ijab->baij", x107) * -1
    l2new += lib.einsum("ijab->abij", x107) * 2
    del x107
    x34 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x34 += lib.einsum("ijka->ijka", x30)
    x34 += lib.einsum("ijka->jika", x30) * -0.5
    x42 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x42 += lib.einsum("ijab,ikla->kljb", t2, x34) * 2
    x40 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x40 += lib.einsum("ijka->ijka", x30) * -1
    x40 += lib.einsum("ijka->jika", x30) * 2
    x42 += lib.einsum("ijab,iklb->klja", t2, x40)
    del x40
    x43 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x43 -= lib.einsum("ijka->ijka", x30)
    x43 += lib.einsum("ijka->jika", x30) * 2
    x46 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x46 += lib.einsum("ijka->ijka", x30) * 2
    x46 -= lib.einsum("ijka->jika", x30)
    x77 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x77 += lib.einsum("iabc,jkib->kjac", v.ovvv, x30)
    x92 += lib.einsum("ijab->ijab", x77)
    del x77
    x35 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x35 += lib.einsum("ijab->jiba", t2) * -1
    x35 += lib.einsum("ijab->jiab", t2) * 2
    x38 += lib.einsum("ijka,ilba->jklb", x34, x35) * -2
    del x34
    del x35
    x36 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x36 += lib.einsum("ijab->jiba", t2) * -0.5
    x36 += lib.einsum("ijab->jiab", t2)
    x37 = np.zeros((nocc, nocc), dtype=np.float64)
    x37 += lib.einsum("abij,ikba->jk", l2, x36) * 2
    x38 += lib.einsum("ia,jk->jkia", t1, x37) * -2
    l1new += lib.einsum("iajb,kijb->ak", v.ovov, x38) * 2
    del x38
    x64 = np.zeros((nocc, nocc), dtype=np.float64)
    x64 += lib.einsum("ij->ij", x37)
    del x37
    x41 = np.zeros((nocc, nocc), dtype=np.float64)
    x41 += lib.einsum("abij,ikba->jk", l2, x36)
    x42 += lib.einsum("ia,jk->jkia", t1, x41) * 2
    x69 = np.zeros((nocc, nocc), dtype=np.float64)
    x69 += lib.einsum("ij->ij", x41)
    del x41
    x65 = np.zeros((nocc, nvir), dtype=np.float64)
    x65 += lib.einsum("ijka,ijba->kb", x30, x36)
    x67 = np.zeros((nvir, nvir), dtype=np.float64)
    x67 += lib.einsum("abij,ijca->bc", l2, x36) * 2
    del x36
    x39 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x39 += lib.einsum("ai,jkba->ijkb", l1, t2)
    x42 += lib.einsum("ijka->ikja", x39)
    x42 += lib.einsum("ijka->ijka", x39) * -2
    del x39
    l1new += lib.einsum("iajb,kija->bk", v.ovov, x42) * 2
    del x42
    x44 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x44 += lib.einsum("ia,jabc->ijbc", t1, v.ovvv)
    x45 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x45 += lib.einsum("ijab->jiab", x44)
    x82 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x82 += lib.einsum("ijab->ijab", x44)
    del x44
    x45 += lib.einsum("ijab->ijab", v.oovv)
    l1new -= lib.einsum("ijka,kiab->bj", x43, x45) * 2
    del x43
    del x45
    x47 += lib.einsum("iabj->ijba", v.ovvo)
    l1new -= lib.einsum("ijka,kiab->bj", x46, x47) * 2
    del x47
    x48 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x48 += lib.einsum("abij,kjac->ikbc", l2, t2)
    x49 = np.zeros((nocc, nvir, nvir, nvir), dtype=np.float64)
    x49 += lib.einsum("iabc->ibac", v.ovvv) * 2
    x49 -= lib.einsum("iabc->ibca", v.ovvv)
    l1new -= lib.einsum("ijab,jacb->ci", x48, x49) * 2
    del x48
    del x49
    x52 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x52 += lib.einsum("ijab->jiba", t2) * 2
    x52 += lib.einsum("ijab->jiab", t2) * -1
    x62 = np.zeros((nocc, nvir), dtype=np.float64)
    x62 += lib.einsum("iabc,ijac->jb", v.ovvv, x52) * -1
    x65 += lib.einsum("ai,ijab->jb", l1, x52) * -0.5
    x53 += lib.einsum("ijka->ikja", v.ooov)
    x62 += lib.einsum("ijab,ijkb->ka", t2, x53) * 2
    del x53
    x55 += lib.einsum("ia->ia", f.ov)
    x59 = np.zeros((nocc, nocc), dtype=np.float64)
    x59 += lib.einsum("ia,ja->ji", t1, x55)
    x62 += lib.einsum("ia,ijab->jb", x55, x52) * -1
    del x52
    x71 = np.zeros((nocc, nocc), dtype=np.float64)
    x71 += lib.einsum("ia,ja->ji", t1, x55) * 0.5
    del x55
    x56 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x56 += lib.einsum("iabj->ijba", v.ovvo) * 2
    x56 += lib.einsum("ijab->ijab", v.oovv) * -1
    x62 += lib.einsum("ia,ijba->jb", t1, x56) * -1
    del x56
    x57 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x57 += lib.einsum("iajb->jiba", v.ovov) * -0.5
    x57 += lib.einsum("iajb->jiab", v.ovov)
    x59 += lib.einsum("ijab,ikba->kj", t2, x57) * 2
    x71 += lib.einsum("ijab,ikba->kj", t2, x57)
    del x57
    x58 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x58 += lib.einsum("ijka->ikja", v.ooov) * -0.5
    x58 += lib.einsum("ijka->kija", v.ooov)
    x59 += lib.einsum("ia,ijka->jk", t1, x58) * 2
    x71 += lib.einsum("ia,ijka->jk", t1, x58)
    del x58
    x59 += lib.einsum("ij->ij", f.oo)
    x62 += lib.einsum("ia,ij->ja", t1, x59)
    del x59
    x60 = np.zeros((nocc, nvir, nvir, nvir), dtype=np.float64)
    x60 += lib.einsum("iabc->ibac", v.ovvv) * -0.5
    x60 += lib.einsum("iabc->ibca", v.ovvv)
    x61 = np.zeros((nvir, nvir), dtype=np.float64)
    x61 += lib.einsum("ia,ibca->bc", t1, x60) * 2
    del x60
    x61 += lib.einsum("ab->ab", f.vv)
    x62 += lib.einsum("ia,ba->ib", t1, x61) * -1
    del x61
    x62 += lib.einsum("ai->ia", f.vo) * -1
    x62 += lib.einsum("ijab,jkib->ka", t2, v.ooov) * -1
    l1new += lib.einsum("ia,ijab->bj", x62, x19) * -2
    del x62
    x63 = np.zeros((nocc, nocc), dtype=np.float64)
    x63 += lib.einsum("ai,ja->ij", l1, t1)
    x64 += lib.einsum("ij->ij", x63)
    x65 += lib.einsum("ia,ij->ja", t1, x64) * 0.5
    del x64
    x69 += lib.einsum("ij->ij", x63) * 0.5
    l1new += lib.einsum("ia,ji->aj", f.ov, x69) * -4
    x96 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x96 += lib.einsum("ij,kajb->ikab", x63, v.ovov)
    x101 += lib.einsum("ijab->ijab", x96)
    del x96
    x65 += lib.einsum("ia->ia", t1) * -0.5
    x66 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x66 += lib.einsum("iajb->jiba", v.ovov) * 2
    x66 += lib.einsum("iajb->jiab", v.ovov) * -1
    l1new += lib.einsum("ia,ijab->bj", x65, x66) * -4
    del x65
    del x66
    x67 += lib.einsum("ai,ib->ab", l1, t1)
    x68 = np.zeros((nocc, nvir, nvir, nvir), dtype=np.float64)
    x68 += lib.einsum("iabc->ibac", v.ovvv) * 2
    x68 += lib.einsum("iabc->ibca", v.ovvv) * -1
    l1new += lib.einsum("ab,iacb->ci", x67, x68) * 2
    del x67
    del x68
    x70 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x70 += lib.einsum("ijka->ikja", v.ooov)
    x70 += lib.einsum("ijka->kija", v.ooov) * -0.5
    l1new += lib.einsum("ij,jkia->ak", x69, x70) * -8
    del x69
    del x70
    x71 += lib.einsum("ij->ij", f.oo) * 0.5
    l1new += lib.einsum("ai,ji->aj", l1, x71) * -4
    del x71
    x73 += lib.einsum("ab->ab", f.vv)
    l1new += lib.einsum("ai,ab->bi", l1, x73) * 2
    del x73
    x74 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x74 += lib.einsum("iajb->jiba", v.ovov) * 2
    x74 -= lib.einsum("iajb->jiab", v.ovov)
    x75 = np.zeros((nocc, nvir), dtype=np.float64)
    x75 += lib.einsum("ia,ijab->jb", t1, x74)
    del x74
    x87 = np.zeros((nocc, nocc), dtype=np.float64)
    x87 += lib.einsum("ia,ja->ij", t1, x75)
    x88 = np.zeros((nocc, nocc), dtype=np.float64)
    x88 += lib.einsum("ij->ji", x87)
    del x87
    x91 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x91 += lib.einsum("ia,jkib->jkba", x75, x30)
    x92 += lib.einsum("ijab->ijab", x91)
    del x91
    x92 -= lib.einsum("ai,jb->ijab", l1, x75)
    l1new -= lib.einsum("ij,ja->ai", x63, x75) * 2
    del x75
    del x63
    x76 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x76 += lib.einsum("ai,jikb->jkab", l1, v.ooov)
    x92 += lib.einsum("ijab->ijab", x76)
    del x76
    x78 += lib.einsum("iabj->jiba", v.ovvo)
    x79 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x79 += lib.einsum("ijab,ikac->jkbc", x19, x78)
    del x19
    del x78
    x92 -= lib.einsum("ijab->ijab", x79)
    del x79
    x80 += lib.einsum("ijka->jkia", v.ooov)
    x81 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x81 += lib.einsum("ijka,jlkb->ilab", x46, x80)
    del x46
    x92 += lib.einsum("ijab->ijab", x81)
    del x81
    x84 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x84 += lib.einsum("ijka,jklb->ilab", x30, x80)
    x92 -= lib.einsum("ijab->ijab", x84)
    del x84
    x100 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x100 += lib.einsum("ijka,iklb->jlab", x30, x80)
    del x80
    del x30
    x101 -= lib.einsum("ijab->ijab", x100)
    del x100
    x82 += lib.einsum("ijab->jiab", v.oovv)
    x83 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x83 += lib.einsum("abij,ikac->jkbc", l2, x82)
    x92 += lib.einsum("ijab->ijab", x83)
    del x83
    x99 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x99 += lib.einsum("abij,ikbc->jkac", l2, x82)
    del x82
    x101 += lib.einsum("ijab->ijab", x99)
    del x99
    x85 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x85 -= lib.einsum("ijka->ikja", v.ooov)
    x85 += lib.einsum("ijka->kija", v.ooov) * 2
    x86 = np.zeros((nocc, nocc), dtype=np.float64)
    x86 += lib.einsum("ia,ijka->jk", t1, x85)
    del x85
    x88 += lib.einsum("ij->ij", x86)
    del x86
    x89 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x89 += lib.einsum("ij,abjk->kiab", x88, l2)
    del x88
    x92 += lib.einsum("ijab->ijba", x89)
    del x89
    x92 -= lib.einsum("ia,bj->ijab", f.ov, l1)
    l2new += lib.einsum("ijab->baij", x92) * 2
    l2new -= lib.einsum("ijab->abij", x92) * 4
    l2new -= lib.einsum("ijab->baji", x92) * 4
    l2new += lib.einsum("ijab->abji", x92) * 2
    del x92
    x93 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x93 += lib.einsum("ij,abkj->ikab", f.oo, l2)
    x101 += lib.einsum("ijab->ijab", x93)
    del x93
    x94 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x94 += lib.einsum("ab,acij->jibc", f.vv, l2)
    x101 -= lib.einsum("ijab->ijab", x94)
    del x94
    x95 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x95 += lib.einsum("ai,jbac->ijbc", l1, v.ovvv)
    x101 -= lib.einsum("ijab->ijab", x95)
    del x95
    l2new -= lib.einsum("ijab->baij", x101) * 4
    l2new += lib.einsum("ijab->abij", x101) * 2
    l2new += lib.einsum("ijab->baji", x101) * 2
    l2new -= lib.einsum("ijab->abji", x101) * 4
    del x101
    x102 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x102 += lib.einsum("abij,kilj->klab", l2, v.oooo)
    x104 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x104 += lib.einsum("ijab->jiba", x102) * 4
    del x102
    x103 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x103 += lib.einsum("abij,acbd->ijcd", l2, v.vvvv)
    x104 += lib.einsum("ijab->jiba", x103) * 4
    del x103
    l2new += lib.einsum("ijab->abij", x104)
    l2new += lib.einsum("ijab->baij", x104) * -0.5
    del x104
    l1new += lib.einsum("ia->ai", f.ov) * 2
    l2new += lib.einsum("iajb->baji", v.ovov) * 4
    l2new -= lib.einsum("iajb->abji", v.ovov) * 2

    return {"l1new": l1new, "l2new": l2new}

def make_rdm1_f(f=None, v=None, nocc=None, nvir=None, t1=None, t2=None, l1=None, l2=None, **kwargs):
    delta_oo = np.eye(nocc)
    delta_vv = np.eye(nvir)

    # 1RDM
    x0 = np.zeros((nocc, nocc), dtype=np.float64)
    x0 += lib.einsum("ai,ja->ij", l1, t1)
    x6 = np.zeros((nocc, nocc), dtype=np.float64)
    x6 += lib.einsum("ij->ij", x0)
    rdm1_f_oo = np.zeros((nocc, nocc), dtype=np.float64)
    rdm1_f_oo -= lib.einsum("ij->ij", x0) * 2
    del x0
    x1 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x1 += lib.einsum("ijab->jiab", t2) * 2
    x1 += lib.einsum("ijab->jiba", t2) * -1
    rdm1_f_oo += lib.einsum("abij,ikba->jk", l2, x1) * -2
    del x1
    x2 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x2 += lib.einsum("ia,abjk->kjib", t1, l2)
    x3 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x3 += lib.einsum("ijka->ijka", x2) * 2
    x3 += lib.einsum("ijka->jika", x2) * -1
    del x2
    rdm1_f_vo = np.zeros((nvir, nocc), dtype=np.float64)
    rdm1_f_vo += lib.einsum("ijab,ijka->bk", t2, x3) * -2
    del x3
    x4 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x4 -= lib.einsum("ijab->jiab", t2)
    x4 += lib.einsum("ijab->jiba", t2) * 2
    rdm1_f_vo += lib.einsum("ai,ijab->bj", l1, x4) * 2
    del x4
    x5 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x5 += lib.einsum("ijab->jiab", t2)
    x5 += lib.einsum("ijab->jiba", t2) * -0.5
    x6 += lib.einsum("abij,ikba->jk", l2, x5) * 2
    del x5
    rdm1_f_vo += lib.einsum("ia,ij->aj", t1, x6) * -2
    del x6
    x7 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x7 += lib.einsum("abij->jiab", l2) * -0.5
    x7 += lib.einsum("abij->jiba", l2)
    rdm1_f_vv = np.zeros((nvir, nvir), dtype=np.float64)
    rdm1_f_vv += lib.einsum("ijab,ijac->bc", t2, x7) * 4
    del x7
    rdm1_f_oo += lib.einsum("ij->ji", delta_oo) * 2
    rdm1_f_ov = np.zeros((nocc, nvir), dtype=np.float64)
    rdm1_f_ov += lib.einsum("ai->ia", l1) * 2
    rdm1_f_vo += lib.einsum("ia->ai", t1) * 2
    rdm1_f_vv += lib.einsum("ai,ib->ba", l1, t1) * 2

    rdm1_f = np.block([[rdm1_f_oo, rdm1_f_ov], [rdm1_f_vo, rdm1_f_vv]])

    return rdm1_f

def make_rdm2_f(f=None, v=None, nocc=None, nvir=None, t1=None, t2=None, l1=None, l2=None, **kwargs):
    delta_oo = np.eye(nocc)
    delta_vv = np.eye(nvir)

    # 2RDM
    x0 = np.zeros((nocc, nocc), dtype=np.float64)
    x0 += lib.einsum("ai,ja->ij", l1, t1)
    x8 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x8 += lib.einsum("ia,jk->jika", t1, x0)
    x13 = np.zeros((nocc, nvir), dtype=np.float64)
    x13 += lib.einsum("ia,ij->ja", t1, x0)
    x16 = np.zeros((nocc, nvir), dtype=np.float64)
    x16 += lib.einsum("ia->ia", x13)
    del x13
    x28 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x28 += lib.einsum("ij,kiab->jkab", x0, t2)
    x31 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x31 += lib.einsum("ijab->ijab", x28)
    del x28
    rdm2_f_oooo = np.zeros((nocc, nocc, nocc, nocc), dtype=np.float64)
    rdm2_f_oooo -= lib.einsum("ij,kl->jilk", delta_oo, x0) * 4
    rdm2_f_oooo += lib.einsum("ij,kl->lijk", delta_oo, x0) * 2
    rdm2_f_oooo += lib.einsum("ij,kl->jkli", delta_oo, x0) * 2
    rdm2_f_oooo -= lib.einsum("ij,kl->lkji", delta_oo, x0) * 4
    del x0
    x1 = np.zeros((nocc, nocc, nocc, nocc), dtype=np.float64)
    x1 += lib.einsum("abij,klab->ijkl", l2, t2)
    x21 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x21 += lib.einsum("ia,jikl->jkla", t1, x1)
    rdm2_f_ooov = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    rdm2_f_ooov += lib.einsum("ijka->jika", x21) * 4
    rdm2_f_ooov += lib.einsum("ijka->kija", x21) * -2
    rdm2_f_ovoo = np.zeros((nocc, nvir, nocc, nocc), dtype=np.float64)
    rdm2_f_ovoo += lib.einsum("ijka->jaki", x21) * -2
    rdm2_f_ovoo += lib.einsum("ijka->kaji", x21) * 4
    del x21
    rdm2_f_oooo += lib.einsum("ijkl->kjli", x1) * -2
    rdm2_f_oooo += lib.einsum("ijkl->ljki", x1) * 4
    x2 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x2 += lib.einsum("ia,abjk->kjib", t1, l2)
    x3 = np.zeros((nocc, nocc, nocc, nocc), dtype=np.float64)
    x3 += lib.einsum("ia,jkla->jkil", t1, x2)
    x18 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x18 += lib.einsum("ia,ijkl->jlka", t1, x3)
    x20 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x20 += lib.einsum("ijka->jika", x18)
    x35 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x35 += lib.einsum("ia,ijkb->jkab", t1, x18)
    del x18
    x37 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x37 += lib.einsum("ijab->ijab", x35)
    del x35
    x45 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x45 += lib.einsum("ijab,jikl->lkab", t2, x3)
    x48 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x48 += lib.einsum("ijab->ijab", x45) * 4.000000000000003
    del x45
    rdm2_f_oooo -= lib.einsum("ijkl->kjli", x3) * 2
    rdm2_f_oooo += lib.einsum("ijkl->ljki", x3) * 4
    del x3
    x7 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x7 += lib.einsum("ijab,kjla->klib", t2, x2)
    x8 -= lib.einsum("ijka->ijka", x7)
    x29 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x29 -= lib.einsum("ijka->ijka", x7)
    del x7
    x9 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x9 += lib.einsum("ijka->ijka", x2)
    x9 += lib.einsum("ijka->jika", x2) * -0.5
    x10 = np.zeros((nocc, nvir), dtype=np.float64)
    x10 += lib.einsum("ijab,jikb->ka", t2, x9)
    del x9
    x12 = np.zeros((nocc, nvir), dtype=np.float64)
    x12 += lib.einsum("ia->ia", x10)
    del x10
    x17 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x17 += lib.einsum("ijab,kjlb->klia", t2, x2)
    x20 += lib.einsum("ijka->jika", x17)
    x25 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x25 += lib.einsum("ijka->ijka", x17)
    del x17
    x50 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x50 -= lib.einsum("ijka->ijka", x2)
    x50 += lib.einsum("ijka->jika", x2) * 2
    x51 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x51 += lib.einsum("ia,jikb->jkba", t1, x50)
    rdm2_f_oovv = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    rdm2_f_oovv -= lib.einsum("ijab->jiab", x51) * 2
    rdm2_f_vvoo = np.zeros((nvir, nvir, nocc, nocc), dtype=np.float64)
    rdm2_f_vvoo -= lib.einsum("ijab->abji", x51) * 2
    del x51
    x56 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x56 += lib.einsum("ia,ijkb->jkba", t1, x50)
    del x50
    rdm2_f_ovvo = np.zeros((nocc, nvir, nvir, nocc), dtype=np.float64)
    rdm2_f_ovvo -= lib.einsum("ijab->jbai", x56) * 2
    rdm2_f_voov = np.zeros((nvir, nocc, nocc, nvir), dtype=np.float64)
    rdm2_f_voov -= lib.einsum("ijab->aijb", x56) * 2
    del x56
    x60 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x60 += lib.einsum("ia,jikb->jkba", t1, x2)
    x62 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x62 += lib.einsum("ijab->ijab", x60)
    del x60
    x67 = np.zeros((nocc, nvir, nvir, nvir), dtype=np.float64)
    x67 += lib.einsum("ijab,ijkc->kcab", t2, x2)
    rdm2_f_ovvv = np.zeros((nocc, nvir, nvir, nvir), dtype=np.float64)
    rdm2_f_ovvv += lib.einsum("iabc->ibac", x67) * 2
    rdm2_f_ovvv += lib.einsum("iabc->icab", x67) * -4
    rdm2_f_vvov = np.zeros((nvir, nvir, nocc, nvir), dtype=np.float64)
    rdm2_f_vvov += lib.einsum("iabc->abic", x67) * -4
    rdm2_f_vvov += lib.einsum("iabc->acib", x67) * 2
    del x67
    rdm2_f_oovo = np.zeros((nocc, nocc, nvir, nocc), dtype=np.float64)
    rdm2_f_oovo += lib.einsum("ijka->kiaj", x2) * 2
    rdm2_f_oovo -= lib.einsum("ijka->kjai", x2) * 4
    rdm2_f_vooo = np.zeros((nvir, nocc, nocc, nocc), dtype=np.float64)
    rdm2_f_vooo -= lib.einsum("ijka->aikj", x2) * 4
    rdm2_f_vooo += lib.einsum("ijka->ajki", x2) * 2
    x4 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x4 += lib.einsum("ijab->jiab", t2) * -0.5
    x4 += lib.einsum("ijab->jiba", t2)
    x5 = np.zeros((nocc, nocc), dtype=np.float64)
    x5 += lib.einsum("abij,ikab->jk", l2, x4)
    del x4
    x11 = np.zeros((nocc, nvir), dtype=np.float64)
    x11 += lib.einsum("ia,ij->ja", t1, x5)
    x12 += lib.einsum("ia->ia", x11)
    del x11
    x44 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x44 += lib.einsum("ia,jb->ijab", t1, x12) * 8.000000000000005
    rdm2_f_ooov += lib.einsum("ij,ka->jika", delta_oo, x12) * -8
    rdm2_f_ooov += lib.einsum("ij,ka->kjia", delta_oo, x12) * 4
    rdm2_f_ovoo += lib.einsum("ij,ka->jaki", delta_oo, x12) * 4
    rdm2_f_ovoo += lib.einsum("ij,ka->kaij", delta_oo, x12) * -8
    del x12
    x43 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x43 += lib.einsum("ij,ikab->kjab", x5, t2) * 8
    x44 += lib.einsum("ijab->ijba", x43)
    del x43
    rdm2_f_oooo += lib.einsum("ij,kl->jilk", delta_oo, x5) * -8
    rdm2_f_oooo += lib.einsum("ij,kl->jkli", delta_oo, x5) * 4
    rdm2_f_oooo += lib.einsum("ij,kl->ljik", delta_oo, x5) * 4
    rdm2_f_oooo += lib.einsum("ij,kl->lkij", delta_oo, x5) * -8
    rdm2_f_ooov += lib.einsum("ia,jk->ijka", t1, x5) * 4
    rdm2_f_ooov += lib.einsum("ia,jk->kjia", t1, x5) * -8
    rdm2_f_ovoo += lib.einsum("ia,jk->iakj", t1, x5) * -8
    rdm2_f_ovoo += lib.einsum("ia,jk->kaij", t1, x5) * 4
    del x5
    x6 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x6 += lib.einsum("ai,jkba->ijkb", l1, t2)
    x8 += lib.einsum("ijka->ijka", x6)
    rdm2_f_ooov += lib.einsum("ijka->jika", x8) * 2
    rdm2_f_ooov -= lib.einsum("ijka->kija", x8) * 4
    rdm2_f_ovoo -= lib.einsum("ijka->jaki", x8) * 4
    rdm2_f_ovoo += lib.einsum("ijka->kaji", x8) * 2
    del x8
    x29 += lib.einsum("ijka->ijka", x6)
    del x6
    x30 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x30 += lib.einsum("ia,ijkb->jkba", t1, x29)
    del x29
    x31 += lib.einsum("ijab->ijba", x30)
    del x30
    rdm2_f_ovov = np.zeros((nocc, nvir, nocc, nvir), dtype=np.float64)
    rdm2_f_ovov += lib.einsum("ijab->iajb", x31) * 2
    rdm2_f_ovov -= lib.einsum("ijab->ibja", x31) * 4
    rdm2_f_ovov -= lib.einsum("ijab->jaib", x31) * 4
    rdm2_f_ovov += lib.einsum("ijab->jbia", x31) * 2
    del x31
    x14 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x14 -= lib.einsum("ijab->jiab", t2)
    x14 += lib.einsum("ijab->jiba", t2) * 2
    x15 = np.zeros((nocc, nvir), dtype=np.float64)
    x15 += lib.einsum("ai,ijab->jb", l1, x14)
    x16 -= lib.einsum("ia->ia", x15)
    del x15
    x27 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x27 += lib.einsum("ia,jb->ijab", t1, x16)
    rdm2_f_ooov -= lib.einsum("ij,ka->jika", delta_oo, x16) * 4
    rdm2_f_ooov += lib.einsum("ij,ka->kjia", delta_oo, x16) * 2
    rdm2_f_ovoo += lib.einsum("ij,ka->jaki", delta_oo, x16) * 2
    rdm2_f_ovoo -= lib.einsum("ij,ka->kaij", delta_oo, x16) * 4
    del x16
    x19 = np.zeros((nocc, nocc, nocc, nvir), dtype=np.float64)
    x19 += lib.einsum("ijab,ikla->jklb", x14, x2)
    del x2
    x20 -= lib.einsum("ijka->kjia", x19)
    x25 -= lib.einsum("ijka->jkia", x19)
    del x19
    x26 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x26 += lib.einsum("ia,ijkb->jkba", t1, x25)
    del x25
    x27 -= lib.einsum("ijab->ijba", x26)
    del x26
    x61 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x61 += lib.einsum("abij,ikac->kjcb", l2, x14)
    x62 -= lib.einsum("ijab->jiba", x61)
    del x61
    rdm2_f_oovv -= lib.einsum("abij,ikcb->kjac", l2, x14) * 2
    del x14
    x20 += lib.einsum("ij,ka->jika", delta_oo, t1)
    rdm2_f_ooov += lib.einsum("ijka->ijka", x20) * 4
    rdm2_f_ooov -= lib.einsum("ijka->kjia", x20) * 2
    rdm2_f_ovoo -= lib.einsum("ijka->iakj", x20) * 2
    rdm2_f_ovoo += lib.einsum("ijka->kaij", x20) * 4
    del x20
    x22 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x22 -= lib.einsum("abij->jiab", l2)
    x22 += lib.einsum("abij->jiba", l2) * 2
    x23 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x23 += lib.einsum("ijab,ikac->kjcb", t2, x22)
    x24 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x24 += lib.einsum("ijab,ikbc->kjca", t2, x23)
    x27 += lib.einsum("ijab->ijab", x24)
    del x24
    rdm2_f_ovov -= lib.einsum("ijab->iajb", x27) * 4
    rdm2_f_ovov += lib.einsum("ijab->ibja", x27) * 2
    rdm2_f_ovov += lib.einsum("ijab->jaib", x27) * 2
    rdm2_f_ovov -= lib.einsum("ijab->jbia", x27) * 4
    del x27
    x36 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x36 += lib.einsum("ijab,ikac->kjcb", t2, x23)
    del x23
    x37 += lib.einsum("ijab->ijab", x36) * 2
    del x36
    rdm2_f_vvoo -= lib.einsum("ijab,ikcb->cajk", t2, x22) * 2
    del x22
    x32 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x32 += lib.einsum("ijab->jiba", t2)
    x32 += lib.einsum("ia,jb->ijab", t1, t1)
    rdm2_f_ovov -= lib.einsum("ijab->ibja", x32) * 2
    rdm2_f_ovov += lib.einsum("ijab->iajb", x32) * 4
    del x32
    x33 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x33 += lib.einsum("abij,kjbc->ikac", l2, t2)
    x34 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x34 += lib.einsum("ijab,jkac->ikbc", t2, x33)
    del x33
    x37 += lib.einsum("ijab->ijab", x34)
    del x34
    rdm2_f_ovov += lib.einsum("ijab->iajb", x37) * 4
    rdm2_f_ovov -= lib.einsum("ijab->ibja", x37) * 2
    del x37
    x38 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x38 += lib.einsum("abij,kjac->ikbc", l2, t2)
    x39 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x39 += lib.einsum("ijab,jkac->ikbc", t2, x38)
    rdm2_f_ovov -= lib.einsum("ijab->iajb", x39) * 2
    rdm2_f_ovov += lib.einsum("ijab->ibja", x39) * 4
    del x39
    x65 = np.zeros((nocc, nvir, nvir, nvir), dtype=np.float64)
    x65 += lib.einsum("ia,ijbc->jbac", t1, x38)
    del x38
    x66 = np.zeros((nocc, nvir, nvir, nvir), dtype=np.float64)
    x66 -= lib.einsum("iabc->iabc", x65)
    del x65
    x40 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x40 += lib.einsum("abij->jiab", l2) * -0.5
    x40 += lib.einsum("abij->jiba", l2)
    x41 = np.zeros((nvir, nvir), dtype=np.float64)
    x41 += lib.einsum("ijab,ijcb->ca", t2, x40)
    x42 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x42 += lib.einsum("ab,ijac->ijbc", x41, t2) * 8
    x44 += lib.einsum("ijab->jiba", x42)
    del x42
    rdm2_f_ovov += lib.einsum("ijab->iajb", x44) * -1
    rdm2_f_ovov += lib.einsum("ijab->ibja", x44) * 0.5
    rdm2_f_ovov += lib.einsum("ijab->jaib", x44) * 0.5
    rdm2_f_ovov += lib.einsum("ijab->jbia", x44) * -1
    del x44
    x53 = np.zeros((nvir, nvir), dtype=np.float64)
    x53 += lib.einsum("ab->ab", x41)
    rdm2_f_ovvv += lib.einsum("ia,bc->iabc", t1, x41) * 8
    rdm2_f_ovvv += lib.einsum("ia,bc->icba", t1, x41) * -4
    rdm2_f_vvov += lib.einsum("ia,bc->baic", t1, x41) * -4
    rdm2_f_vvov += lib.einsum("ia,bc->bcia", t1, x41) * 8
    del x41
    x57 = np.zeros((nvir, nvir), dtype=np.float64)
    x57 += lib.einsum("ijab,ijcb->ca", t2, x40) * 2
    del x40
    x58 = np.zeros((nvir, nvir), dtype=np.float64)
    x58 += lib.einsum("ab->ab", x57)
    del x57
    x46 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x46 += lib.einsum("ijab->jiba", t2)
    x46 += lib.einsum("ia,jb->ijab", t1, t1)
    x47 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x47 += lib.einsum("ijkl,ijab->klab", x1, x46) * 4
    del x1
    del x46
    x48 += lib.einsum("ijab->jiba", x47)
    del x47
    rdm2_f_ovov += lib.einsum("ijab->iajb", x48)
    rdm2_f_ovov += lib.einsum("ijab->ibja", x48) * -0.5
    del x48
    x49 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x49 += lib.einsum("ijab->jiab", t2) * 2
    x49 -= lib.einsum("ijab->jiba", t2)
    rdm2_f_oovv -= lib.einsum("abij,ikca->kjbc", l2, x49) * 2
    x52 = np.zeros((nvir, nvir), dtype=np.float64)
    x52 += lib.einsum("ai,ib->ab", l1, t1)
    x53 += lib.einsum("ab->ab", x52) * 0.5
    rdm2_f_oovv += lib.einsum("ij,ab->jiab", delta_oo, x53) * 8
    del x53
    x58 += lib.einsum("ab->ab", x52)
    rdm2_f_ovvo += lib.einsum("ij,ab->jbai", delta_oo, x58) * -2
    rdm2_f_voov += lib.einsum("ij,ab->aijb", delta_oo, x58) * -2
    rdm2_f_vvoo += lib.einsum("ij,ab->abji", delta_oo, x58) * 4
    del x58
    x66 += lib.einsum("ia,bc->ibac", t1, x52)
    del x52
    x54 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x54 += lib.einsum("abij->jiab", l2) * 2
    x54 -= lib.einsum("abij->jiba", l2)
    x55 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x55 += lib.einsum("ijab,ikcb->jkac", x49, x54)
    del x49
    rdm2_f_ovvo += lib.einsum("ijab->iabj", x55) * 2
    rdm2_f_voov += lib.einsum("ijab->bjia", x55) * 2
    del x55
    rdm2_f_vvoo -= lib.einsum("ijab,ikca->cbjk", t2, x54) * 2
    del x54
    x59 = np.zeros((nocc, nocc, nvir, nvir), dtype=np.float64)
    x59 += lib.einsum("abij,kjca->ikbc", l2, t2)
    x62 += lib.einsum("ijab->ijab", x59)
    del x59
    x63 = np.zeros((nocc, nvir, nvir, nvir), dtype=np.float64)
    x63 += lib.einsum("ia,ijbc->jbca", t1, x62)
    del x62
    rdm2_f_ovvv += lib.einsum("iabc->icab", x63) * 2
    rdm2_f_ovvv -= lib.einsum("iabc->ibac", x63) * 4
    rdm2_f_vvov -= lib.einsum("iabc->acib", x63) * 4
    rdm2_f_vvov += lib.einsum("iabc->abic", x63) * 2
    del x63
    x64 = np.zeros((nocc, nvir, nvir, nvir), dtype=np.float64)
    x64 += lib.einsum("ai,jibc->jabc", l1, t2)
    x66 += lib.einsum("iabc->iabc", x64)
    del x64
    rdm2_f_ovvv += lib.einsum("iabc->ibac", x66) * 4
    rdm2_f_ovvv -= lib.einsum("iabc->icab", x66) * 2
    rdm2_f_vvov -= lib.einsum("iabc->abic", x66) * 2
    rdm2_f_vvov += lib.einsum("iabc->acib", x66) * 4
    del x66
    x68 = np.zeros((nocc, nvir, nvir, nvir), dtype=np.float64)
    x68 += lib.einsum("ia,bcji->jbca", t1, l2)
    x70 = np.zeros((nvir, nvir, nvir, nvir), dtype=np.float64)
    x70 += lib.einsum("ia,ibcd->cbda", t1, x68)
    rdm2_f_vvvv = np.zeros((nvir, nvir, nvir, nvir), dtype=np.float64)
    rdm2_f_vvvv -= lib.einsum("abcd->bcad", x70) * 2
    rdm2_f_vvvv += lib.einsum("abcd->bdac", x70) * 4
    del x70
    rdm2_f_vovv = np.zeros((nvir, nocc, nvir, nvir), dtype=np.float64)
    rdm2_f_vovv += lib.einsum("iabc->aibc", x68) * 4
    rdm2_f_vovv -= lib.einsum("iabc->biac", x68) * 2
    rdm2_f_vvvo = np.zeros((nvir, nvir, nvir, nocc), dtype=np.float64)
    rdm2_f_vvvo -= lib.einsum("iabc->acbi", x68) * 2
    rdm2_f_vvvo += lib.einsum("iabc->bcai", x68) * 4
    del x68
    x69 = np.zeros((nvir, nvir, nvir, nvir), dtype=np.float64)
    x69 += lib.einsum("abij,ijcd->abcd", l2, t2)
    rdm2_f_vvvv += lib.einsum("abcd->bcad", x69) * -2
    rdm2_f_vvvv += lib.einsum("abcd->bdac", x69) * 4
    del x69
    rdm2_f_oooo += lib.einsum("ij,kl->jilk", delta_oo, delta_oo) * 4
    rdm2_f_oooo -= lib.einsum("ij,kl->ljik", delta_oo, delta_oo) * 2
    rdm2_f_oovo += lib.einsum("ij,ak->jiak", delta_oo, l1) * 4
    rdm2_f_oovo -= lib.einsum("ij,ak->jkai", delta_oo, l1) * 2
    rdm2_f_vooo -= lib.einsum("ij,ak->aijk", delta_oo, l1) * 2
    rdm2_f_vooo += lib.einsum("ij,ak->akji", delta_oo, l1) * 4
    rdm2_f_oovv -= lib.einsum("ai,jb->jiab", l1, t1) * 2
    rdm2_f_ovvo += lib.einsum("ai,jb->jbai", l1, t1) * 4
    rdm2_f_voov += lib.einsum("ai,jb->aijb", l1, t1) * 4
    rdm2_f_vvoo -= lib.einsum("ai,jb->abji", l1, t1) * 2
    rdm2_f_vovo = np.zeros((nvir, nocc, nvir, nocc), dtype=np.float64)
    rdm2_f_vovo -= lib.einsum("abij->ajbi", l2) * 2
    rdm2_f_vovo += lib.einsum("abij->bjai", l2) * 4

    rdm2_f = pack_2e(rdm2_f_oooo, rdm2_f_ooov, rdm2_f_oovo, rdm2_f_ovoo, rdm2_f_vooo, rdm2_f_oovv, rdm2_f_ovov, rdm2_f_ovvo, rdm2_f_voov, rdm2_f_vovo, rdm2_f_vvoo, rdm2_f_ovvv, rdm2_f_vovv, rdm2_f_vvov, rdm2_f_vvvo, rdm2_f_vvvv)

    return rdm2_f

