# Code generated by qwick.

import numpy as np
from ebcc.util import pack_2e, einsum, Namespace

def energy(f=None, v=None, nocc=None, nvir=None, t1=None, t2=None, t3=None, **kwargs):
    # energy
    x0 = np.zeros((nocc, nvir, nocc, nvir), dtype=np.float64)
    x0 += np.einsum("ia,jb->iajb", t1, t1)
    x1 = np.zeros((nocc, nvir, nocc, nvir), dtype=np.float64)
    x1 += np.einsum("ijab->iajb", t2)
    x1 += np.einsum("iajb->iajb", x0)
    del x0
    x2 = 0
    x2 += np.einsum("ia,ia->", f.ov, t1)
    e_cc = 0
    e_cc += np.einsum("->", x2) * 2.0
    del x2
    x3 = np.zeros((nocc, nvir, nocc, nvir), dtype=np.float64)
    x3 += np.einsum("iajb->iajb", x1) * 2.0
    x3 += np.einsum("ibja->iajb", x1) * -1.0
    del x1
    x4 = 0
    x4 += np.einsum("iajb,iajb->", v.ovov, x3)
    del x3
    e_cc += np.einsum("->", x4)
    del x4

    return e_cc

def update_amps(f=None, v=None, nocc=None, nvir=None, t1=None, t2=None, t3=None, **kwargs):
    return {"t1new": t1new, "t2new": t2new, "t3new": t3new}

