"""
Code generated by `albert`:
https://github.com/obackhouse/albert

  * date: 2024-10-20T09:35:50.499213
  * python version: 3.10.15 (main, Sep  9 2024, 03:02:45) [GCC 11.4.0]
  * albert version: 0.0.0
  * caller: /opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/albert/codegen/einsum.py
  * node: fv-az985-968
  * system: Linux
  * processor: x86_64
  * release: 6.5.0-1025-azure
"""

from ebcc import numpy as np
from ebcc.util import pack_2e, einsum, dirsum, Namespace


def energy(f=None, t1=None, t2=None, v=None, **kwargs):
    """
    Code generated by `albert` 0.0.0 on 2024-10-20T09:36:03.913273.

    Parameters
    ----------
    f : array
        Fock matrix.
    t1 : array
        T1 amplitudes.
    t2 : array
        T2 amplitudes.
    v : array
        Electron repulsion integrals.

    Returns
    -------
    e_cc : float
        Coupled cluster energy.
    """

    e_cc = einsum(t2, (0, 1, 2, 3), v.ovov, (0, 2, 1, 3), ()) * 2
    e_cc += einsum(t2, (0, 1, 2, 3), v.ovov, (0, 3, 1, 2), ()) * -1
    tmp1 = np.copy(f.ov)
    tmp0 = np.copy(np.transpose(v.ovov, (0, 2, 3, 1))) * -0.5
    tmp0 += np.transpose(v.ovov, (0, 2, 1, 3))
    tmp1 += einsum(t1, (0, 1), tmp0, (0, 2, 1, 3), (2, 3))
    del tmp0
    e_cc += einsum(tmp1, (0, 1), t1, (0, 1), ()) * 2
    del tmp1

    return e_cc

def update_amps(f=None, t1=None, t2=None, v=None, **kwargs):
    """
    Code generated by `albert` 0.0.0 on 2024-10-20T09:40:21.633399.

    Parameters
    ----------
    f : array
        Fock matrix.
    t1 : array
        T1 amplitudes.
    t2 : array
        T2 amplitudes.
    v : array
        Electron repulsion integrals.

    Returns
    -------
    t1new : array
        Updated T1 residuals.
    t2new : array
        Updated T2 residuals.
    """

    t1new = np.copy(f.ov)
    tmp0 = np.copy(v.ovvv)
    tmp0 += np.transpose(v.ovvv, (0, 2, 1, 3)) * -0.5
    t1new += einsum(tmp0, (0, 1, 2, 3), t2, (4, 0, 2, 1), (4, 3)) * 2
    del tmp0
    tmp2 = np.copy(v.ooov) * -0.5
    tmp2 += np.transpose(v.ooov, (0, 2, 1, 3))
    tmp1 = einsum(t1, (0, 1), v.ovov, (2, 3, 4, 1), (0, 2, 4, 3))
    tmp2 += tmp1
    tmp2 += np.transpose(tmp1, (0, 2, 1, 3)) * -0.5
    t1new += einsum(tmp2, (0, 1, 2, 3), t2, (1, 2, 3, 4), (0, 4)) * -2
    del tmp2
    tmp6 = np.copy(np.transpose(t2, (0, 1, 3, 2))) * -1
    tmp6 += t2 * 2
    tmp5 = np.copy(f.ov)
    tmp3 = np.copy(np.transpose(v.ovov, (0, 2, 3, 1))) * -1
    tmp3 += np.transpose(v.ovov, (0, 2, 1, 3)) * 2
    tmp4 = einsum(t1, (0, 1), tmp3, (0, 2, 1, 3), (2, 3))
    tmp5 += tmp4
    t1new += einsum(tmp6, (0, 1, 2, 3), tmp5, (0, 2), (1, 3))
    del tmp6, tmp5
    tmp7 = np.copy(np.transpose(v.ovov, (0, 2, 1, 3))) * 2
    tmp7 += v.oovv * -1
    t1new += einsum(tmp7, (0, 1, 2, 3), t1, (0, 2), (1, 3))
    del tmp7
    tmp9 = np.copy(f.vv)
    tmp8 = np.copy(v.ovvv) * -0.5
    tmp8 += np.transpose(v.ovvv, (0, 2, 1, 3))
    tmp9 += einsum(tmp8, (0, 1, 2, 3), t1, (0, 2), (1, 3)) * 2
    del tmp8
    t1new += einsum(tmp9, (0, 1), t1, (2, 0), (2, 1))
    del tmp9
    tmp14 = np.copy(f.oo) * 0.5
    tmp10 = np.copy(np.transpose(v.ovov, (0, 2, 3, 1))) * 2
    tmp10 += np.transpose(v.ovov, (0, 2, 1, 3)) * -1
    tmp14 += einsum(t2, (0, 1, 2, 3), tmp10, (1, 4, 2, 3), (4, 0)) * 0.5
    del tmp10
    tmp11 = np.copy(v.ooov) * -0.5
    tmp11 += np.transpose(v.ovoo, (0, 2, 3, 1))
    tmp14 += einsum(t1, (0, 1), tmp11, (0, 2, 3, 1), (3, 2))
    del tmp11
    tmp13 = np.copy(f.ov) * 0.5
    tmp12 = np.copy(np.transpose(v.ovov, (0, 2, 3, 1))) * -0.5
    tmp12 += np.transpose(v.ovov, (0, 2, 1, 3))
    tmp13 += einsum(tmp12, (0, 1, 2, 3), t1, (0, 2), (1, 3))
    del tmp12
    tmp14 += einsum(t1, (0, 1), tmp13, (2, 1), (2, 0))
    del tmp13
    t1new += einsum(t1, (0, 1), tmp14, (0, 2), (2, 1)) * -2
    del tmp14
    t2new = np.copy(np.transpose(v.ovov, (0, 2, 1, 3)))
    t2new += einsum(t1, (0, 1), v.ovoo, (2, 3, 4, 0), (2, 4, 3, 1)) * -1
    t2new += einsum(v.oovv, (0, 1, 2, 3), t2, (4, 1, 5, 3), (4, 0, 5, 2)) * -1
    tmp15 = einsum(t2, (0, 1, 2, 3), v.ovov, (4, 5, 1, 2), (0, 4, 3, 5))
    t2new += tmp15 * -1
    t2new += einsum(v.oovv, (0, 1, 2, 3), t2, (4, 1, 3, 5), (4, 0, 2, 5)) * -1
    t2new += einsum(t2, (0, 1, 2, 3), v.ovov, (4, 5, 1, 3), (0, 4, 2, 5)) * 2
    tmp16 = np.copy(t2)
    tmp16 += einsum(t1, (0, 1), t1, (2, 3), (2, 0, 3, 1))
    tmp17 = einsum(t1, (0, 1), v.ovvv, (2, 1, 3, 4), (0, 2, 3, 4))
    tmp18 = einsum(tmp16, (0, 1, 2, 3), tmp17, (4, 0, 3, 5), (1, 4, 2, 5))
    del tmp16
    t2new += np.transpose(tmp18, (1, 0, 2, 3)) * -1
    t2new += np.transpose(tmp18, (0, 1, 3, 2)) * -1
    del tmp18
    tmp19 = einsum(t2, (0, 1, 2, 3), f.vv, (4, 3), (0, 1, 4, 2))
    tmp34 = np.copy(tmp19)
    del tmp19
    tmp20 = einsum(t1, (0, 1), v.ovvv, (2, 3, 4, 1), (0, 2, 3, 4))
    tmp34 += tmp20
    tmp21 = einsum(tmp17, (0, 1, 2, 3), t2, (4, 1, 5, 3), (0, 4, 5, 2))
    del tmp17
    tmp34 += tmp21 * -1
    del tmp21
    tmp22 = np.copy(np.transpose(t2, (0, 1, 3, 2))) * 2
    tmp22 += t2 * -1
    tmp23 = einsum(tmp20, (0, 1, 2, 3), tmp22, (1, 4, 5, 2), (4, 0, 5, 3))
    del tmp20, tmp22
    tmp34 += np.transpose(tmp23, (1, 0, 2, 3))
    del tmp23
    tmp24 = einsum(t1, (0, 1), v.oovv, (2, 3, 4, 1), (0, 2, 3, 4))
    tmp30 = np.copy(np.transpose(tmp24, (0, 2, 1, 3))) * -1
    del tmp24
    tmp25 = einsum(v.ooov, (0, 1, 2, 3), t2, (4, 1, 5, 3), (4, 0, 2, 5))
    tmp30 += np.transpose(tmp25, (0, 2, 1, 3))
    del tmp25
    tmp26 = einsum(t2, (0, 1, 2, 3), tmp1, (4, 5, 1, 2), (4, 0, 5, 3))
    tmp30 += np.transpose(tmp26, (0, 2, 1, 3))
    del tmp26
    tmp27 = einsum(t1, (0, 1), t1, (2, 3), (2, 0, 3, 1))
    tmp27 += np.transpose(t2, (0, 1, 3, 2)) * -2
    tmp27 += t2
    tmp28 = einsum(tmp27, (0, 1, 2, 3), v.ooov, (4, 5, 0, 3), (1, 4, 5, 2))
    del tmp27
    tmp30 += np.transpose(tmp28, (0, 2, 1, 3))
    del tmp28
    tmp29 = einsum(tmp4, (0, 1), t2, (2, 3, 1, 4), (0, 2, 3, 4))
    tmp30 += np.transpose(tmp29, (2, 0, 1, 3)) * -1
    del tmp29
    tmp31 = einsum(tmp30, (0, 1, 2, 3), t1, (1, 4), (0, 2, 3, 4))
    del tmp30
    tmp34 += np.transpose(tmp31, (0, 1, 3, 2))
    del tmp31
    tmp32 = einsum(tmp4, (0, 1), t1, (2, 1), (0, 2))
    del tmp4
    tmp33 = einsum(tmp32, (0, 1), t2, (2, 0, 3, 4), (1, 2, 4, 3))
    del tmp32
    tmp34 += np.transpose(tmp33, (0, 1, 3, 2)) * -1
    del tmp33
    t2new += np.transpose(tmp34, (0, 1, 3, 2))
    t2new += np.transpose(tmp34, (1, 0, 2, 3))
    del tmp34
    tmp35 = einsum(t1, (0, 1), tmp1, (2, 3, 0, 4), (2, 3, 1, 4))
    tmp37 = np.copy(tmp35)
    del tmp35
    tmp36 = einsum(tmp3, (0, 1, 2, 3), t2, (4, 0, 5, 2), (1, 4, 3, 5))
    del tmp3
    tmp37 += np.transpose(tmp36, (1, 0, 3, 2)) * -1
    tmp38 = einsum(tmp37, (0, 1, 2, 3), t2, (4, 1, 3, 5), (0, 4, 2, 5))
    del tmp37
    tmp50 = np.copy(tmp38)
    del tmp38
    tmp39 = np.copy(v.ovvv) * -1
    tmp39 += np.transpose(v.ovvv, (0, 2, 1, 3)) * 2
    tmp40 = einsum(t1, (0, 1), tmp39, (0, 2, 1, 3), (2, 3))
    del tmp39
    tmp41 = einsum(tmp40, (0, 1), t2, (2, 3, 0, 4), (2, 3, 1, 4))
    del tmp40
    tmp50 += np.transpose(tmp41, (1, 0, 3, 2))
    del tmp41
    tmp45 = np.copy(tmp1)
    tmp42 = einsum(v.ooov, (0, 1, 2, 3), t2, (4, 1, 3, 5), (4, 0, 2, 5))
    tmp45 += tmp42 * -1
    del tmp42
    tmp43 = np.copy(tmp1) * -1
    tmp43 += np.transpose(tmp1, (0, 2, 1, 3)) * 2
    del tmp1
    tmp44 = einsum(t2, (0, 1, 2, 3), tmp43, (4, 5, 1, 3), (4, 5, 0, 2))
    del tmp43
    tmp45 += np.transpose(tmp44, (0, 2, 1, 3))
    del tmp44
    tmp46 = einsum(tmp45, (0, 1, 2, 3), t1, (2, 4), (0, 1, 3, 4))
    del tmp45
    tmp50 += np.transpose(tmp46, (0, 1, 3, 2)) * -1
    del tmp46
    tmp47 = np.copy(v.ooov) * -1
    tmp47 += np.transpose(v.ovoo, (0, 2, 3, 1)) * 2
    tmp48 = einsum(tmp47, (0, 1, 2, 3), t1, (0, 3), (1, 2))
    del tmp47
    tmp49 = einsum(tmp48, (0, 1), t2, (2, 1, 3, 4), (0, 2, 4, 3))
    del tmp48
    tmp50 += np.transpose(tmp49, (1, 0, 3, 2)) * -1
    del tmp49
    t2new += tmp50
    t2new += np.transpose(tmp50, (1, 0, 3, 2))
    del tmp50
    tmp51 = einsum(t2, (0, 1, 2, 3), v.ovvv, (4, 2, 5, 3), (0, 1, 4, 5))
    tmp52 = einsum(t1, (0, 1), tmp51, (2, 3, 0, 4), (2, 3, 1, 4))
    del tmp51
    tmp58 = np.copy(tmp52)
    del tmp52
    tmp53 = np.copy(np.transpose(v.ovov, (0, 2, 3, 1)))
    tmp53 += np.transpose(v.ovov, (0, 2, 1, 3)) * -0.5
    tmp54 = einsum(tmp53, (0, 1, 2, 3), t2, (0, 1, 3, 4), (2, 4))
    tmp55 = einsum(tmp54, (0, 1), t2, (2, 3, 0, 4), (2, 3, 1, 4)) * 2
    del tmp54
    tmp58 += np.transpose(tmp55, (1, 0, 3, 2))
    del tmp55
    tmp56 = einsum(t2, (0, 1, 2, 3), tmp53, (1, 4, 2, 3), (4, 0)) * 2
    del tmp53
    tmp57 = einsum(t2, (0, 1, 2, 3), tmp56, (1, 4), (4, 0, 3, 2))
    del tmp56
    tmp58 += np.transpose(tmp57, (1, 0, 3, 2))
    del tmp57
    t2new += tmp58 * -1
    t2new += np.transpose(tmp58, (1, 0, 3, 2)) * -1
    del tmp58
    tmp59 = einsum(v.ooov, (0, 1, 2, 3), t1, (4, 3), (4, 0, 1, 2))
    tmp60 = einsum(tmp59, (0, 1, 2, 3), t2, (3, 2, 4, 5), (0, 1, 5, 4))
    del tmp59
    t2new += np.transpose(tmp60, (0, 1, 3, 2))
    t2new += np.transpose(tmp60, (1, 0, 2, 3))
    del tmp60
    tmp61 = einsum(t2, (0, 1, 2, 3), f.ov, (4, 3), (4, 0, 1, 2))
    tmp62 = einsum(t1, (0, 1), tmp61, (0, 2, 3, 4), (2, 3, 1, 4))
    del tmp61
    tmp66 = np.copy(tmp62)
    del tmp62
    tmp64 = np.copy(f.oo)
    tmp63 = einsum(f.ov, (0, 1), t1, (2, 1), (0, 2))
    tmp64 += tmp63
    del tmp63
    tmp65 = einsum(t2, (0, 1, 2, 3), tmp64, (1, 4), (4, 0, 3, 2))
    del tmp64
    tmp66 += np.transpose(tmp65, (0, 1, 3, 2))
    del tmp65
    t2new += np.transpose(tmp66, (0, 1, 3, 2)) * -1
    t2new += np.transpose(tmp66, (1, 0, 2, 3)) * -1
    del tmp66
    tmp67 = np.copy(np.transpose(v.ovov, (0, 2, 1, 3))) * 2
    tmp67 += v.oovv * -1
    tmp67 += np.transpose(tmp36, (1, 0, 3, 2)) * 2
    del tmp36
    t2new += einsum(tmp67, (0, 1, 2, 3), t2, (4, 1, 5, 3), (0, 4, 2, 5))
    del tmp67
    tmp70 = np.copy(v.oooo)
    tmp68 = np.copy(t2)
    tmp68 += einsum(t1, (0, 1), t1, (2, 3), (2, 0, 3, 1))
    tmp69 = einsum(tmp68, (0, 1, 2, 3), v.ovov, (4, 2, 5, 3), (0, 1, 4, 5))
    tmp70 += np.transpose(tmp69, (3, 1, 2, 0))
    t2new += einsum(tmp70, (0, 1, 2, 3), t2, (0, 2, 4, 5), (1, 3, 4, 5))
    del tmp70
    t2new += einsum(tmp68, (0, 1, 2, 3), v.vvvv, (4, 3, 5, 2), (1, 0, 4, 5))
    del tmp68
    tmp72 = np.copy(np.transpose(v.ooov, (0, 2, 1, 3))) * -1
    tmp71 = np.copy(v.oooo)
    tmp71 += np.transpose(tmp69, (3, 1, 0, 2))
    del tmp69
    tmp72 += einsum(tmp71, (0, 1, 2, 3), t1, (0, 4), (2, 1, 3, 4))
    del tmp71
    t2new += einsum(t1, (0, 1), tmp72, (2, 3, 0, 4), (2, 3, 1, 4))
    del tmp72
    tmp73 = np.copy(v.oovv) * -1
    tmp73 += einsum(v.ovov, (0, 1, 2, 3), t2, (4, 2, 1, 5), (4, 0, 5, 3))
    t2new += einsum(tmp73, (0, 1, 2, 3), t2, (4, 1, 3, 5), (0, 4, 5, 2))
    del tmp73
    tmp74 = np.copy(np.transpose(v.ovov, (0, 2, 1, 3))) * -1
    tmp74 += tmp15
    del tmp15
    t2new += einsum(tmp74, (0, 1, 2, 3), t2, (4, 1, 3, 5), (0, 4, 2, 5))
    del tmp74

    return {f"t1new": t1new, f"t2new": t2new}

def update_lams(f=None, l1=None, l2=None, t1=None, t2=None, v=None, **kwargs):
    """
    Code generated by `albert` 0.0.0 on 2024-10-20T09:50:08.525616.

    Parameters
    ----------
    f : array
        Fock matrix.
    l1 : array
        L1 amplitudes.
    l2 : array
        L2 amplitudes.
    t1 : array
        T1 amplitudes.
    t2 : array
        T2 amplitudes.
    v : array
        Electron repulsion integrals.

    Returns
    -------
    l1new : array
        Updated L1 residuals.
    l2new : array
        Updated L2 residuals.
    """

    l1new = np.copy(np.transpose(f.ov, (1, 0)))
    tmp18 = np.copy(np.transpose(v.ooov, (0, 2, 1, 3))) * -2
    tmp18 += np.transpose(v.ovoo, (0, 2, 3, 1))
    tmp0 = einsum(t2, (0, 1, 2, 3), f.ov, (4, 3), (4, 0, 1, 2))
    tmp18 += np.transpose(tmp0, (1, 2, 0, 3))
    tmp18 += np.transpose(tmp0, (2, 1, 0, 3)) * -2
    del tmp0
    tmp1 = einsum(t2, (0, 1, 2, 3), v.ovvv, (4, 2, 5, 3), (0, 1, 4, 5))
    tmp9 = np.copy(tmp1) * 2
    del tmp1
    tmp2 = einsum(t1, (0, 1), v.ovvv, (2, 1, 3, 4), (0, 2, 3, 4))
    tmp3 = einsum(tmp2, (0, 1, 2, 3), t1, (4, 3), (0, 4, 1, 2))
    tmp9 += tmp3 * 2
    del tmp3
    tmp4 = einsum(v.ovov, (0, 1, 2, 3), t2, (4, 5, 1, 3), (4, 5, 0, 2))
    tmp7 = np.copy(np.transpose(tmp4, (1, 0, 3, 2)))
    del tmp4
    tmp5 = einsum(t1, (0, 1), v.ovov, (2, 3, 4, 1), (0, 2, 4, 3))
    tmp6 = einsum(tmp5, (0, 1, 2, 3), t1, (4, 3), (4, 0, 1, 2))
    tmp7 += tmp6
    del tmp6
    tmp8 = einsum(t1, (0, 1), tmp7, (2, 3, 0, 4), (2, 3, 4, 1)) * 2
    tmp9 += np.transpose(tmp8, (1, 0, 2, 3)) * -1
    del tmp8
    tmp18 += tmp9 * -1
    tmp18 += np.transpose(tmp9, (1, 0, 2, 3)) * 0.5
    del tmp9
    tmp10 = np.copy(np.transpose(v.ovov, (0, 2, 3, 1))) * -0.5
    tmp10 += np.transpose(v.ovov, (0, 2, 1, 3))
    tmp11 = einsum(tmp10, (0, 1, 2, 3), t1, (0, 2), (1, 3)) * 2
    del tmp10
    tmp12 = einsum(tmp11, (0, 1), t2, (2, 3, 1, 4), (2, 3, 0, 4))
    tmp18 += np.transpose(tmp12, (1, 0, 2, 3))
    tmp18 += tmp12 * -2
    del tmp12
    tmp14 = np.copy(np.transpose(t2, (0, 1, 3, 2))) * -0.5
    tmp14 += t2
    tmp13 = np.copy(v.ooov)
    tmp13 += np.transpose(v.ooov, (0, 2, 1, 3)) * -0.5
    tmp13 += tmp5 * -0.5
    tmp13 += np.transpose(tmp5, (0, 2, 1, 3))
    tmp18 += einsum(tmp14, (0, 1, 2, 3), tmp13, (4, 5, 0, 2), (4, 1, 5, 3)) * -4
    del tmp13
    tmp15 = np.copy(np.transpose(v.ovov, (0, 2, 1, 3))) * 2
    tmp15 += v.oovv * -1
    tmp18 += einsum(t1, (0, 1), tmp15, (2, 3, 1, 4), (0, 3, 2, 4)) * -1
    del tmp15
    tmp17 = np.copy(np.transpose(v.oooo, (0, 2, 3, 1))) * 2
    tmp17 += v.oooo * -1
    tmp16 = einsum(v.ooov, (0, 1, 2, 3), t1, (4, 3), (4, 0, 1, 2))
    tmp17 += np.transpose(tmp16, (2, 0, 3, 1)) * 2
    tmp17 += np.transpose(tmp16, (3, 0, 2, 1)) * -1
    tmp18 += einsum(t1, (0, 1), tmp17, (0, 2, 3, 4), (2, 4, 3, 1))
    del tmp17
    l1new += einsum(tmp18, (0, 1, 2, 3), l2, (4, 3, 0, 1), (4, 2))
    del tmp18
    tmp19 = np.copy(np.transpose(t2, (0, 1, 3, 2))) * 2
    tmp19 += t2 * -1
    tmp22 = einsum(tmp19, (0, 1, 2, 3), l2, (4, 2, 0, 5), (5, 1, 4, 3))
    tmp22 += einsum(l2, (0, 1, 2, 3), tmp14, (3, 4, 1, 5), (2, 4, 0, 5)) * 2
    tmp20 = einsum(t1, (0, 1), l2, (2, 1, 3, 4), (3, 4, 0, 2))
    tmp21 = np.copy(tmp20) * -0.5
    tmp21 += np.transpose(tmp20, (1, 0, 2, 3))
    tmp22 += einsum(t1, (0, 1), tmp21, (2, 0, 3, 4), (2, 3, 1, 4)) * 2
    l1new += einsum(v.ovvv, (0, 1, 2, 3), tmp22, (4, 0, 3, 2), (1, 4)) * -1
    del tmp22
    tmp24 = np.copy(np.transpose(v.vvvv, (0, 2, 1, 3))) * 2
    tmp24 += v.vvvv * -1
    tmp23 = einsum(l2, (0, 1, 2, 3), t1, (3, 4), (2, 0, 1, 4))
    l1new += einsum(tmp24, (0, 1, 2, 3), tmp23, (4, 0, 3, 1), (2, 4))
    del tmp24, tmp23
    tmp27 = np.copy(np.transpose(l2, (3, 2, 0, 1)))
    tmp26 = np.copy(np.transpose(t2, (0, 1, 3, 2))) * -1
    tmp26 += t2 * 2
    tmp25 = np.copy(np.transpose(l2, (3, 2, 0, 1))) * 2
    tmp25 += np.transpose(l2, (2, 3, 0, 1)) * -1
    tmp27 += einsum(tmp25, (0, 1, 2, 3), tmp26, (0, 4, 3, 5), (1, 4, 2, 5)) * -1
    del tmp25
    l1new += einsum(v.ovvv, (0, 1, 2, 3), tmp27, (4, 0, 3, 1), (2, 4)) * -1
    del tmp27
    tmp28 = np.copy(v.ooov) * 2
    tmp28 += np.transpose(v.ooov, (0, 2, 1, 3)) * -1
    tmp28 += tmp5 * -1
    tmp28 += np.transpose(tmp5, (0, 2, 1, 3)) * 2
    tmp32 = einsum(tmp28, (0, 1, 2, 3), t2, (4, 2, 5, 3), (0, 4, 1, 5))
    del tmp28
    tmp29 = np.copy(v.ooov) * -1
    tmp29 += np.transpose(v.ooov, (0, 2, 1, 3)) * 2
    tmp29 += tmp5 * 2
    tmp29 += np.transpose(tmp5, (0, 2, 1, 3)) * -1
    tmp32 += einsum(t2, (0, 1, 2, 3), tmp29, (4, 5, 1, 2), (4, 0, 5, 3))
    del tmp29
    tmp30 = np.copy(np.transpose(v.ovov, (0, 2, 1, 3))) * -1
    tmp30 += v.oovv * 2
    tmp32 += einsum(t1, (0, 1), tmp30, (2, 3, 1, 4), (0, 3, 2, 4)) * -1
    del tmp30
    tmp31 = np.copy(np.transpose(tmp16, (0, 2, 1, 3))) * 2
    tmp31 += np.transpose(tmp16, (0, 3, 2, 1)) * -1
    tmp32 += einsum(tmp31, (0, 1, 2, 3), t1, (3, 4), (0, 2, 1, 4))
    del tmp31
    l1new += einsum(l2, (0, 1, 2, 3), tmp32, (3, 2, 4, 1), (0, 4))
    del tmp32
    tmp34 = np.copy(np.transpose(l2, (2, 3, 0, 1)))
    tmp33 = np.copy(tmp20)
    tmp33 += np.transpose(tmp20, (1, 0, 2, 3)) * -0.5
    tmp34 += einsum(t1, (0, 1), tmp33, (2, 0, 3, 4), (2, 3, 4, 1)) * -1
    del tmp33
    l1new += einsum(tmp34, (0, 1, 2, 3), v.ovvv, (1, 3, 4, 2), (4, 0)) * 2
    del tmp34
    tmp35 = einsum(t2, (0, 1, 2, 3), l1, (3, 4), (4, 0, 1, 2))
    tmp40 = np.copy(tmp35) * -0.5
    tmp40 += np.transpose(tmp35, (0, 2, 1, 3))
    del tmp35
    tmp40 += np.transpose(tmp20, (0, 2, 1, 3)) * -0.5
    tmp40 += np.transpose(tmp20, (1, 2, 0, 3))
    tmp36 = einsum(t1, (0, 1), tmp20, (2, 3, 4, 1), (3, 2, 4, 0))
    tmp37 = einsum(t1, (0, 1), tmp36, (0, 2, 3, 4), (2, 4, 3, 1))
    tmp40 += tmp37 * -1
    tmp40 += np.transpose(tmp37, (0, 2, 1, 3)) * 0.5
    del tmp37
    tmp38 = np.copy(tmp20) * 2
    tmp38 += np.transpose(tmp20, (1, 0, 2, 3)) * -1
    tmp39 = np.copy(np.transpose(t2, (0, 1, 3, 2)))
    tmp39 += t2 * -0.5
    tmp40 += einsum(tmp39, (0, 1, 2, 3), tmp38, (0, 4, 5, 3), (4, 5, 1, 2))
    l1new += einsum(v.ovov, (0, 1, 2, 3), tmp40, (4, 2, 0, 1), (3, 4)) * -2
    del tmp40
    tmp41 = einsum(t2, (0, 1, 2, 3), l2, (3, 2, 4, 5), (5, 4, 0, 1))
    tmp42 = einsum(t1, (0, 1), tmp41, (2, 0, 3, 4), (2, 3, 4, 1))
    tmp43 = np.copy(tmp42) * -1
    tmp43 += np.transpose(tmp42, (0, 2, 1, 3)) * 2
    del tmp42
    tmp43 += einsum(t2, (0, 1, 2, 3), tmp38, (1, 4, 5, 3), (4, 5, 0, 2))
    del tmp38
    tmp43 += einsum(tmp21, (0, 1, 2, 3), t2, (4, 0, 3, 5), (1, 2, 4, 5)) * 2
    del tmp21
    l1new += einsum(tmp43, (0, 1, 2, 3), v.ovov, (2, 4, 1, 3), (4, 0))
    del tmp43
    tmp44 = np.copy(tmp20) * 2
    tmp44 += np.transpose(tmp20, (1, 0, 2, 3)) * -1
    l1new += einsum(tmp44, (0, 1, 2, 3), v.oovv, (1, 2, 4, 3), (4, 0)) * -1
    del tmp44
    tmp45 = np.copy(np.transpose(tmp41, (1, 0, 2, 3))) * 2
    tmp45 += np.transpose(tmp41, (1, 0, 3, 2)) * -1
    tmp45 += np.transpose(tmp36, (2, 1, 3, 0)) * 2
    tmp45 += np.transpose(tmp36, (3, 1, 2, 0)) * -1
    l1new += einsum(tmp45, (0, 1, 2, 3), v.ooov, (3, 0, 2, 4), (4, 1))
    del tmp45
    tmp48 = np.copy(v.ovvv) * 2
    tmp48 += np.transpose(v.ovvv, (0, 2, 1, 3)) * -1
    tmp47 = einsum(t1, (0, 1), l1, (2, 0), (2, 1))
    tmp46 = einsum(l2, (0, 1, 2, 3), tmp39, (3, 2, 4, 1), (0, 4)) * 2
    tmp47 += tmp46
    l1new += einsum(tmp48, (0, 1, 2, 3), tmp47, (3, 2), (1, 0))
    del tmp48, tmp47
    tmp51 = np.copy(t1) * -0.5
    tmp51 += einsum(tmp14, (0, 1, 2, 3), tmp20, (0, 1, 4, 2), (4, 3))
    del tmp14
    tmp51 += einsum(tmp26, (0, 1, 2, 3), l1, (2, 0), (1, 3)) * -0.5
    del tmp26
    tmp49 = einsum(t1, (0, 1), l1, (1, 2), (2, 0))
    tmp50 = np.copy(tmp49) * 0.5
    tmp50 += einsum(tmp39, (0, 1, 2, 3), l2, (3, 2, 0, 4), (4, 1))
    tmp51 += einsum(t1, (0, 1), tmp50, (0, 2), (2, 1))
    del tmp50
    tmp52 = np.copy(np.transpose(v.ovov, (0, 2, 3, 1))) * -1
    tmp52 += np.transpose(v.ovov, (0, 2, 1, 3)) * 2
    l1new += einsum(tmp51, (0, 1), tmp52, (0, 2, 1, 3), (3, 2)) * -2
    del tmp51
    tmp55 = np.copy(v.ooov) * 2
    tmp55 += np.transpose(v.ovoo, (0, 2, 3, 1)) * -1
    tmp54 = np.copy(tmp49)
    del tmp49
    tmp53 = einsum(tmp39, (0, 1, 2, 3), l2, (3, 2, 0, 4), (4, 1)) * 2
    del tmp39
    tmp54 += tmp53
    del tmp53
    l1new += einsum(tmp55, (0, 1, 2, 3), tmp54, (1, 0), (3, 2)) * -1
    del tmp55
    tmp56 = np.copy(np.transpose(v.ovov, (0, 2, 1, 3))) * 2
    tmp56 += v.oovv * -1
    l1new += einsum(tmp56, (0, 1, 2, 3), l1, (2, 0), (3, 1))
    del tmp56
    tmp58 = np.copy(f.vv) * 0.5
    tmp57 = np.copy(v.ovvv) * -0.5
    tmp57 += np.transpose(v.ovvv, (0, 2, 1, 3))
    tmp58 += einsum(t1, (0, 1), tmp57, (0, 2, 1, 3), (3, 2))
    del tmp57
    l1new += einsum(l1, (0, 1), tmp58, (0, 2), (2, 1)) * 2
    del tmp58
    tmp59 = np.copy(f.ov)
    tmp59 += tmp11
    del tmp11
    l1new += einsum(tmp54, (0, 1), tmp59, (1, 2), (2, 0)) * -1
    tmp61 = np.copy(f.oo)
    tmp61 += einsum(v.ovov, (0, 1, 2, 3), tmp19, (2, 4, 1, 3), (4, 0))
    tmp60 = np.copy(v.ooov) * -0.5
    tmp60 += np.transpose(v.ovoo, (0, 2, 3, 1))
    tmp61 += einsum(t1, (0, 1), tmp60, (0, 2, 3, 1), (2, 3)) * 2
    del tmp60
    tmp61 += einsum(tmp59, (0, 1), t1, (2, 1), (2, 0))
    del tmp59
    l1new += einsum(tmp61, (0, 1), l1, (2, 0), (2, 1)) * -1
    del tmp61
    l2new = einsum(v.ovov, (0, 1, 2, 3), tmp41, (4, 5, 2, 0), (3, 1, 4, 5))
    del tmp41
    l2new += einsum(tmp36, (0, 1, 2, 3), v.ovov, (3, 4, 2, 5), (4, 5, 1, 0))
    del tmp36
    l2new += np.transpose(v.ovov, (1, 3, 0, 2))
    l2new += einsum(v.oooo, (0, 1, 2, 3), l2, (4, 5, 1, 3), (4, 5, 0, 2))
    l2new += einsum(v.vvvv, (0, 1, 2, 3), l2, (1, 3, 4, 5), (0, 2, 4, 5))
    tmp87 = einsum(f.ov, (0, 1), l1, (2, 3), (0, 3, 1, 2))
    tmp62 = einsum(v.ooov, (0, 1, 2, 3), tmp20, (4, 1, 2, 5), (4, 0, 5, 3))
    tmp87 += tmp62
    del tmp62
    tmp63 = einsum(t1, (0, 1), v.ovvv, (0, 1, 2, 3), (2, 3))
    tmp64 = einsum(tmp63, (0, 1), l2, (2, 1, 3, 4), (3, 4, 2, 0))
    del tmp63
    tmp87 += tmp64 * 2
    del tmp64
    tmp65 = einsum(tmp20, (0, 1, 2, 3), v.ovvv, (2, 4, 5, 3), (1, 0, 4, 5))
    tmp87 += tmp65 * -1
    del tmp65
    tmp66 = einsum(tmp20, (0, 1, 2, 3), tmp5, (0, 4, 2, 5), (1, 4, 3, 5))
    tmp87 += tmp66
    del tmp66
    tmp67 = np.copy(np.transpose(l2, (3, 2, 0, 1))) * 2
    tmp67 += np.transpose(l2, (2, 3, 0, 1)) * -1
    tmp72 = np.copy(np.transpose(v.ovov, (0, 2, 1, 3)))
    tmp68 = einsum(t1, (0, 1), v.ovvv, (2, 3, 4, 1), (0, 2, 3, 4))
    tmp72 += np.transpose(tmp68, (0, 1, 3, 2))
    del tmp68
    tmp69 = einsum(t2, (0, 1, 2, 3), v.ovov, (4, 3, 1, 5), (0, 4, 2, 5))
    tmp72 += tmp69 * -1
    del tmp69
    tmp70 = np.copy(np.transpose(t2, (0, 1, 3, 2))) * 2
    tmp70 += t2 * -1
    tmp71 = einsum(tmp70, (0, 1, 2, 3), v.ovov, (4, 5, 0, 3), (4, 1, 5, 2))
    del tmp70
    tmp72 += np.transpose(tmp71, (1, 0, 3, 2))
    del tmp71
    tmp73 = einsum(tmp72, (0, 1, 2, 3), tmp67, (0, 4, 5, 2), (4, 1, 5, 3))
    del tmp72, tmp67
    tmp87 += tmp73
    del tmp73
    tmp75 = np.copy(v.oovv)
    tmp75 += np.transpose(tmp2, (0, 1, 3, 2))
    del tmp2
    tmp74 = einsum(t2, (0, 1, 2, 3), v.ovov, (4, 2, 1, 5), (0, 4, 3, 5))
    tmp75 += tmp74 * -1
    del tmp74
    tmp76 = einsum(l2, (0, 1, 2, 3), tmp75, (3, 4, 1, 5), (2, 4, 0, 5))
    tmp87 += tmp76 * -1
    del tmp76
    tmp77 = np.copy(tmp20) * -1
    tmp77 += np.transpose(tmp20, (1, 0, 2, 3)) * 2
    tmp78 = einsum(v.ovoo, (0, 1, 2, 3), tmp77, (2, 4, 3, 5), (0, 4, 1, 5))
    del tmp77
    tmp87 += np.transpose(tmp78, (1, 0, 3, 2)) * -1
    del tmp78
    tmp79 = np.copy(tmp5) * -1
    tmp79 += np.transpose(tmp5, (0, 2, 1, 3)) * 2
    tmp80 = einsum(tmp79, (0, 1, 2, 3), tmp20, (4, 0, 1, 5), (4, 2, 5, 3))
    del tmp79
    tmp87 += tmp80 * -1
    del tmp80
    tmp81 = einsum(t1, (0, 1), v.ooov, (2, 0, 3, 1), (2, 3))
    tmp84 = np.copy(tmp81)
    del tmp81
    tmp82 = einsum(tmp52, (0, 1, 2, 3), t1, (0, 2), (1, 3))
    del tmp52
    tmp83 = einsum(tmp82, (0, 1), t1, (2, 1), (2, 0))
    tmp84 += tmp83 * -1
    del tmp83
    tmp85 = einsum(tmp84, (0, 1), l2, (2, 3, 0, 4), (4, 1, 2, 3))
    del tmp84
    tmp87 += np.transpose(tmp85, (0, 1, 3, 2))
    del tmp85
    tmp86 = einsum(tmp20, (0, 1, 2, 3), tmp82, (2, 4), (0, 1, 3, 4))
    tmp87 += tmp86 * -1
    del tmp86
    tmp87 += einsum(tmp82, (0, 1), l1, (2, 3), (3, 0, 2, 1))
    del tmp82
    l2new += np.transpose(tmp87, (2, 3, 0, 1))
    l2new += np.transpose(tmp87, (3, 2, 1, 0))
    del tmp87
    tmp88 = einsum(t1, (0, 1), v.ovvv, (0, 2, 3, 1), (2, 3))
    tmp89 = einsum(l2, (0, 1, 2, 3), tmp88, (4, 1), (2, 3, 0, 4))
    del tmp88
    l2new += np.transpose(tmp89, (2, 3, 0, 1)) * -1
    l2new += np.transpose(tmp89, (3, 2, 1, 0)) * -1
    del tmp89
    tmp90 = einsum(f.vv, (0, 1), l2, (2, 1, 3, 4), (3, 4, 0, 2))
    tmp99 = np.copy(tmp90)
    del tmp90
    tmp91 = einsum(l1, (0, 1), v.ovvv, (2, 3, 4, 0), (1, 2, 3, 4))
    tmp99 += tmp91
    del tmp91
    tmp92 = einsum(f.ov, (0, 1), t1, (2, 1), (0, 2))
    tmp93 = einsum(l2, (0, 1, 2, 3), tmp92, (4, 3), (4, 2, 0, 1))
    del tmp92
    tmp99 += tmp93 * -1
    del tmp93
    tmp94 = einsum(tmp20, (0, 1, 2, 3), f.ov, (2, 4), (0, 1, 4, 3))
    tmp99 += tmp94 * -1
    del tmp94
    tmp95 = einsum(tmp16, (0, 1, 2, 3), l2, (4, 5, 0, 1), (2, 3, 4, 5))
    del tmp16
    tmp99 += tmp95
    del tmp95
    tmp96 = einsum(v.ooov, (0, 1, 2, 3), tmp20, (1, 4, 2, 5), (4, 0, 5, 3))
    tmp99 += tmp96
    del tmp96
    tmp97 = einsum(tmp20, (0, 1, 2, 3), tmp5, (0, 2, 4, 5), (1, 4, 3, 5))
    del tmp20
    tmp99 += tmp97
    del tmp97
    tmp98 = einsum(tmp75, (0, 1, 2, 3), l2, (4, 2, 0, 5), (5, 1, 4, 3))
    del tmp75
    tmp99 += tmp98 * -1
    del tmp98
    l2new += np.transpose(tmp99, (3, 2, 0, 1))
    l2new += np.transpose(tmp99, (2, 3, 1, 0))
    del tmp99
    tmp100 = einsum(l1, (0, 1), v.ooov, (2, 1, 3, 4), (2, 3, 0, 4))
    tmp107 = np.copy(tmp100)
    del tmp100
    tmp101 = einsum(tmp19, (0, 1, 2, 3), v.ovov, (0, 3, 1, 4), (4, 2)) * 0.5
    tmp102 = einsum(l2, (0, 1, 2, 3), tmp101, (4, 1), (3, 2, 0, 4)) * 2
    del tmp101
    tmp107 += np.transpose(tmp102, (1, 0, 2, 3))
    del tmp102
    tmp103 = einsum(v.ooov, (0, 1, 2, 3), t1, (2, 3), (0, 1))
    tmp105 = np.copy(np.transpose(tmp103, (1, 0)))
    del tmp103
    tmp104 = einsum(v.ovov, (0, 1, 2, 3), tmp19, (2, 4, 1, 3), (0, 4)) * 0.5
    del tmp19
    tmp105 += np.transpose(tmp104, (1, 0))
    del tmp104
    tmp106 = einsum(tmp105, (0, 1), l2, (2, 3, 0, 4), (4, 1, 2, 3)) * 2
    del tmp105
    tmp107 += np.transpose(tmp106, (0, 1, 3, 2))
    del tmp106
    l2new += np.transpose(tmp107, (2, 3, 0, 1)) * -1
    l2new += np.transpose(tmp107, (3, 2, 1, 0)) * -1
    del tmp107
    tmp108 = einsum(f.oo, (0, 1), l2, (2, 3, 4, 1), (0, 4, 2, 3))
    tmp112 = np.copy(tmp108)
    del tmp108
    tmp109 = einsum(l1, (0, 1), tmp5, (1, 2, 3, 4), (2, 3, 0, 4))
    del tmp5
    tmp112 += tmp109
    del tmp109
    tmp110 = einsum(tmp46, (0, 1), v.ovov, (2, 1, 3, 4), (2, 3, 4, 0))
    del tmp46
    tmp112 += np.transpose(tmp110, (1, 0, 3, 2))
    del tmp110
    tmp111 = einsum(tmp54, (0, 1), v.ovov, (2, 3, 1, 4), (2, 0, 4, 3))
    del tmp54
    tmp112 += np.transpose(tmp111, (1, 0, 3, 2))
    del tmp111
    l2new += np.transpose(tmp112, (3, 2, 0, 1)) * -1
    l2new += np.transpose(tmp112, (2, 3, 1, 0)) * -1
    del tmp112
    l2new += einsum(l2, (0, 1, 2, 3), tmp7, (3, 2, 4, 5), (0, 1, 5, 4))
    del tmp7

    return {f"l1new": l1new, f"l2new": l2new}

def make_rdm1_f(l1=None, l2=None, t1=None, t2=None, **kwargs):
    """
    Code generated by `albert` 0.0.0 on 2024-10-20T09:50:30.304562.

    Parameters
    ----------
    l1 : array
        L1 amplitudes.
    l2 : array
        L2 amplitudes.
    t1 : array
        T1 amplitudes.
    t2 : array
        T2 amplitudes.

    Returns
    -------
    rdm1 : array
        One-particle reduced density matrix.
    """

    rdm1 = Namespace()
    delta = Namespace(
        oo=np.eye(t2.shape[0]),
        vv=np.eye(t2.shape[-1]),
    )
    rdm1.vo = np.copy(l1) * 2
    rdm1.oo = np.copy(delta.oo) * 2
    del delta
    tmp0 = einsum(t1, (0, 1), l1, (1, 2), (2, 0))
    rdm1.oo += np.transpose(tmp0, (1, 0)) * -2
    tmp1 = np.copy(np.transpose(t2, (0, 1, 3, 2)))
    tmp1 += t2 * -0.5
    rdm1.oo += einsum(tmp1, (0, 1, 2, 3), l2, (3, 2, 0, 4), (1, 4)) * -4
    rdm1.vv = einsum(t1, (0, 1), l1, (2, 0), (2, 1)) * 2
    tmp6 = np.copy(np.transpose(l2, (3, 2, 0, 1))) * 2
    tmp6 += np.transpose(l2, (2, 3, 0, 1)) * -1
    rdm1.vv += einsum(t2, (0, 1, 2, 3), tmp6, (0, 1, 4, 2), (4, 3)) * 2
    del tmp6
    rdm1.ov = np.copy(t1) * 2
    tmp2 = einsum(t1, (0, 1), l2, (2, 1, 3, 4), (3, 4, 0, 2))
    tmp3 = np.copy(tmp2) * -0.5
    tmp3 += np.transpose(tmp2, (1, 0, 2, 3))
    del tmp2
    rdm1.ov += einsum(t2, (0, 1, 2, 3), tmp3, (1, 0, 4, 2), (4, 3)) * -4
    del tmp3
    tmp4 = np.copy(np.transpose(t2, (0, 1, 3, 2))) * -1
    tmp4 += t2 * 2
    rdm1.ov += einsum(tmp4, (0, 1, 2, 3), l1, (2, 0), (1, 3)) * 2
    del tmp4
    tmp5 = np.copy(tmp0) * 0.5
    del tmp0
    tmp5 += einsum(tmp1, (0, 1, 2, 3), l2, (3, 2, 0, 4), (4, 1))
    del tmp1
    rdm1.ov += einsum(t1, (0, 1), tmp5, (0, 2), (2, 1)) * -4
    del tmp5
    rdm1 = np.block([[rdm1.oo, rdm1.ov], [rdm1.vo, rdm1.vv]])

    return rdm1

def make_rdm2_f(l1=None, l2=None, t1=None, t2=None, **kwargs):
    """
    Code generated by `albert` 0.0.0 on 2024-10-20T09:58:35.649490.

    Parameters
    ----------
    l1 : array
        L1 amplitudes.
    l2 : array
        L2 amplitudes.
    t1 : array
        T1 amplitudes.
    t2 : array
        T2 amplitudes.

    Returns
    -------
    rdm2 : array
        Two-particle reduced density matrix.
    """

    rdm2 = Namespace()
    delta = Namespace(
        oo=np.eye(t2.shape[0]),
        vv=np.eye(t2.shape[-1]),
    )
    rdm2.vvoo = np.copy(np.transpose(l2, (0, 1, 3, 2))) * -2
    rdm2.vvoo += l2 * 4
    tmp108 = einsum(l2, (0, 1, 2, 3), t1, (3, 4), (2, 0, 1, 4))
    rdm2.vvov = np.copy(np.transpose(tmp108, (1, 2, 0, 3))) * 4
    rdm2.vvov += np.transpose(tmp108, (2, 1, 0, 3)) * -2
    rdm2.vvvo = np.copy(np.transpose(tmp108, (1, 2, 3, 0))) * -2
    rdm2.vvvo += np.transpose(tmp108, (2, 1, 3, 0)) * 4
    tmp3 = einsum(l2, (0, 1, 2, 3), t1, (4, 1), (2, 3, 4, 0))
    rdm2.ovoo = np.copy(np.transpose(tmp3, (2, 3, 0, 1))) * 2
    rdm2.ovoo += np.transpose(tmp3, (2, 3, 1, 0)) * -4
    rdm2.ovoo += einsum(delta.oo, (0, 1), l1, (2, 3), (0, 2, 3, 1)) * -2
    rdm2.ovoo += einsum(l1, (0, 1), delta.oo, (2, 3), (2, 0, 3, 1)) * 4
    rdm2.vooo = np.copy(np.transpose(tmp3, (3, 2, 0, 1))) * -4
    rdm2.vooo += np.transpose(tmp3, (3, 2, 1, 0)) * 2
    rdm2.vooo += einsum(delta.oo, (0, 1), l1, (2, 3), (2, 0, 3, 1)) * 4
    rdm2.vooo += einsum(l1, (0, 1), delta.oo, (2, 3), (0, 2, 3, 1)) * -2
    tmp109 = einsum(t2, (0, 1, 2, 3), l2, (4, 5, 1, 0), (4, 5, 3, 2))
    tmp111 = np.copy(np.transpose(tmp109, (1, 0, 3, 2)))
    tmp110 = einsum(t1, (0, 1), tmp108, (0, 2, 3, 4), (3, 2, 4, 1))
    del tmp108
    tmp111 += np.transpose(tmp110, (1, 0, 3, 2))
    rdm2.vvvv = np.copy(np.transpose(tmp111, (0, 1, 3, 2))) * -2
    rdm2.vvvv += tmp111 * 2
    del tmp111
    rdm2.vvvv += np.transpose(tmp109, (1, 0, 3, 2)) * 2
    del tmp109
    rdm2.vvvv += np.transpose(tmp110, (1, 0, 3, 2)) * 2
    del tmp110
    rdm2.oooo = einsum(delta.oo, (0, 1), delta.oo, (2, 3), (0, 2, 1, 3)) * 2
    rdm2.oooo += einsum(delta.oo, (0, 1), delta.oo, (2, 3), (0, 2, 3, 1)) * -2
    tmp0 = np.copy(np.transpose(t2, (0, 1, 3, 2)))
    tmp0 += t2 * -0.5
    tmp1 = einsum(tmp0, (0, 1, 2, 3), l2, (3, 2, 0, 4), (4, 1)) * 2
    rdm2.oooo += einsum(tmp1, (0, 1), delta.oo, (2, 3), (1, 2, 0, 3)) * -4
    rdm2.oooo += einsum(delta.oo, (0, 1), tmp1, (2, 3), (0, 3, 2, 1)) * 2
    rdm2.oooo += einsum(delta.oo, (0, 1), tmp1, (2, 3), (3, 0, 1, 2)) * 2
    rdm2.oooo += einsum(delta.oo, (0, 1), tmp1, (2, 3), (0, 3, 1, 2)) * -4
    tmp2 = einsum(t2, (0, 1, 2, 3), l2, (2, 3, 4, 5), (4, 5, 0, 1))
    tmp5 = np.copy(np.transpose(tmp2, (1, 0, 3, 2)))
    tmp4 = einsum(tmp3, (0, 1, 2, 3), t1, (4, 3), (1, 0, 2, 4))
    tmp5 += tmp4
    rdm2.oooo += np.transpose(tmp5, (3, 2, 0, 1)) * -2
    rdm2.oooo += np.transpose(tmp5, (2, 3, 0, 1)) * 2
    tmp6 = einsum(t1, (0, 1), l1, (1, 2), (2, 0))
    rdm2.oooo += einsum(delta.oo, (0, 1), tmp6, (2, 3), (3, 0, 2, 1)) * -2
    rdm2.oooo += einsum(delta.oo, (0, 1), tmp6, (2, 3), (0, 3, 2, 1)) * 2
    rdm2.oooo += einsum(delta.oo, (0, 1), tmp6, (2, 3), (3, 0, 1, 2)) * 2
    rdm2.oooo += einsum(delta.oo, (0, 1), tmp6, (2, 3), (0, 3, 1, 2)) * -4
    rdm2.oooo += np.transpose(tmp2, (3, 2, 1, 0)) * 2
    rdm2.oooo += np.transpose(tmp4, (3, 2, 1, 0)) * 2
    tmp7 = np.copy(delta.oo)
    tmp7 += tmp6 * -1
    rdm2.oooo += einsum(delta.oo, (0, 1), tmp7, (2, 3), (3, 0, 2, 1)) * 2
    del tmp7
    rdm2.ovov = einsum(t1, (0, 1), l1, (2, 3), (0, 2, 3, 1)) * -2
    tmp73 = np.copy(np.transpose(t2, (0, 1, 3, 2)))
    tmp73 += t2 * -1
    tmp74 = einsum(tmp73, (0, 1, 2, 3), l2, (4, 3, 0, 5), (1, 5, 2, 4))
    del tmp73
    rdm2.ovov += np.transpose(tmp74, (0, 3, 1, 2)) * 2
    tmp75 = np.copy(np.transpose(t2, (0, 1, 3, 2))) * 2
    tmp75 += t2 * -1
    tmp76 = einsum(l2, (0, 1, 2, 3), tmp75, (3, 4, 5, 1), (4, 2, 5, 0))
    del tmp75
    rdm2.ovov += np.transpose(tmp76, (0, 3, 1, 2)) * -2
    tmp10 = np.copy(tmp3)
    tmp10 += np.transpose(tmp3, (1, 0, 2, 3)) * -1
    tmp77 = einsum(tmp10, (0, 1, 2, 3), t1, (1, 4), (0, 2, 3, 4))
    rdm2.ovov += np.transpose(tmp77, (1, 2, 0, 3)) * 2
    tmp78 = einsum(t1, (0, 1), l1, (2, 0), (2, 1))
    tmp80 = np.copy(tmp78)
    tmp56 = np.copy(np.transpose(l2, (3, 2, 0, 1))) * 2
    tmp56 += np.transpose(l2, (2, 3, 0, 1)) * -1
    tmp79 = einsum(t2, (0, 1, 2, 3), tmp56, (0, 1, 4, 2), (4, 3))
    tmp80 += tmp79
    del tmp79
    rdm2.ovov += einsum(tmp80, (0, 1), delta.oo, (2, 3), (2, 0, 3, 1)) * 4
    tmp63 = einsum(t2, (0, 1, 2, 3), l2, (4, 2, 1, 5), (5, 0, 4, 3))
    rdm2.ovov += np.transpose(tmp63, (1, 2, 0, 3)) * -2
    tmp81 = einsum(tmp3, (0, 1, 2, 3), t1, (0, 4), (1, 2, 3, 4))
    rdm2.ovov += np.transpose(tmp81, (1, 2, 0, 3)) * -2
    rdm2.ovvo = einsum(t1, (0, 1), l1, (2, 3), (0, 2, 1, 3)) * 4
    tmp40 = np.copy(np.transpose(l2, (3, 2, 0, 1))) * 2
    tmp40 += np.transpose(l2, (2, 3, 0, 1)) * -1
    tmp41 = einsum(tmp40, (0, 1, 2, 3), t2, (4, 0, 5, 3), (1, 4, 2, 5))
    rdm2.ovvo += np.transpose(tmp41, (1, 2, 3, 0)) * 4
    tmp43 = np.copy(np.transpose(l2, (3, 2, 0, 1)))
    tmp43 += np.transpose(l2, (2, 3, 0, 1)) * -1
    tmp44 = einsum(tmp43, (0, 1, 2, 3), t2, (4, 0, 3, 5), (1, 4, 2, 5))
    del tmp43
    rdm2.ovvo += np.transpose(tmp44, (1, 2, 3, 0)) * -2
    rdm2.ovvo += np.transpose(tmp77, (1, 2, 3, 0)) * -2
    del tmp77
    rdm2.ovvo += einsum(tmp80, (0, 1), delta.oo, (2, 3), (2, 0, 1, 3)) * -2
    tmp61 = einsum(t2, (0, 1, 2, 3), l2, (4, 2, 5, 1), (5, 0, 4, 3))
    rdm2.ovvo += np.transpose(tmp61, (1, 2, 3, 0)) * -2
    tmp82 = einsum(tmp3, (0, 1, 2, 3), t1, (1, 4), (0, 2, 3, 4))
    rdm2.ovvo += np.transpose(tmp82, (1, 2, 3, 0)) * -2
    rdm2.vovo = einsum(t1, (0, 1), l1, (2, 3), (2, 0, 1, 3)) * -2
    rdm2.vovo += np.transpose(tmp41, (2, 1, 3, 0)) * -2
    tmp85 = np.copy(np.transpose(l2, (3, 2, 0, 1))) * -1
    tmp85 += np.transpose(l2, (2, 3, 0, 1))
    tmp86 = einsum(tmp85, (0, 1, 2, 3), t2, (4, 0, 3, 5), (1, 4, 2, 5))
    del tmp85
    rdm2.vovo += np.transpose(tmp86, (2, 1, 3, 0)) * -2
    del tmp86
    tmp83 = np.copy(tmp3) * -1
    tmp83 += np.transpose(tmp3, (1, 0, 2, 3))
    tmp84 = einsum(tmp83, (0, 1, 2, 3), t1, (1, 4), (0, 2, 3, 4))
    del tmp83
    rdm2.vovo += np.transpose(tmp84, (2, 1, 3, 0)) * -2
    tmp87 = np.copy(tmp78) * 0.5
    tmp57 = einsum(t2, (0, 1, 2, 3), tmp56, (0, 1, 4, 2), (4, 3)) * 0.5
    tmp87 += tmp57
    rdm2.vovo += einsum(delta.oo, (0, 1), tmp87, (2, 3), (2, 0, 3, 1)) * 8
    rdm2.vovo += np.transpose(tmp63, (2, 1, 3, 0)) * -2
    rdm2.vovo += np.transpose(tmp81, (2, 1, 3, 0)) * -2
    del tmp81
    rdm2.voov = einsum(t1, (0, 1), l1, (2, 3), (2, 0, 3, 1)) * 4
    rdm2.voov += np.transpose(tmp76, (3, 0, 1, 2)) * 2
    del tmp76
    rdm2.voov += np.transpose(tmp74, (3, 0, 1, 2)) * -2
    del tmp74
    rdm2.voov += np.transpose(tmp84, (2, 1, 0, 3)) * 2
    del tmp84
    rdm2.voov += einsum(tmp80, (0, 1), delta.oo, (2, 3), (0, 2, 3, 1)) * -2
    rdm2.voov += np.transpose(tmp61, (2, 1, 0, 3)) * -2
    rdm2.voov += np.transpose(tmp82, (2, 1, 0, 3)) * -2
    rdm2.voov += np.transpose(tmp41, (2, 1, 0, 3)) * 2
    tmp88 = einsum(t2, (0, 1, 2, 3), l1, (4, 1), (0, 4, 2, 3))
    tmp94 = np.copy(tmp88)
    tmp94 += einsum(tmp78, (0, 1), t1, (2, 3), (2, 0, 3, 1))
    del tmp78
    tmp22 = np.copy(np.transpose(t2, (0, 1, 3, 2))) * -1
    tmp22 += t2 * 2
    tmp89 = einsum(l2, (0, 1, 2, 3), tmp22, (3, 4, 1, 5), (4, 2, 5, 0))
    tmp92 = np.copy(np.transpose(tmp89, (1, 0, 3, 2)))
    tmp90 = np.copy(np.transpose(t2, (0, 1, 3, 2))) * -1
    tmp90 += t2
    tmp91 = einsum(tmp90, (0, 1, 2, 3), l2, (4, 2, 0, 5), (1, 5, 3, 4))
    del tmp90
    tmp92 += np.transpose(tmp91, (1, 0, 3, 2)) * -1
    tmp93 = einsum(tmp92, (0, 1, 2, 3), t1, (0, 4), (1, 2, 3, 4))
    del tmp92
    tmp94 += np.transpose(tmp93, (0, 1, 3, 2)) * -1
    del tmp93
    rdm2.ovvv = np.copy(tmp94) * 2
    rdm2.ovvv += np.transpose(tmp94, (0, 1, 3, 2)) * -2
    del tmp94
    tmp95 = einsum(tmp3, (0, 1, 2, 3), t2, (0, 1, 4, 5), (2, 3, 4, 5))
    tmp96 = np.copy(tmp95)
    tmp96 += einsum(t1, (0, 1), tmp57, (2, 3), (0, 2, 1, 3)) * 2
    rdm2.ovvv += tmp96 * 2
    rdm2.ovvv += np.transpose(tmp96, (0, 1, 3, 2)) * -2
    del tmp96
    tmp97 = einsum(t1, (0, 1), tmp82, (0, 2, 3, 4), (2, 3, 1, 4))
    rdm2.ovvv += tmp97 * 2
    rdm2.ovvv += np.transpose(tmp97, (0, 1, 3, 2)) * -2
    del tmp97
    rdm2.ovvv += np.transpose(tmp95, (0, 1, 3, 2)) * -2
    tmp98 = einsum(tmp63, (0, 1, 2, 3), t1, (0, 4), (1, 2, 4, 3))
    rdm2.ovvv += tmp98 * -2
    rdm2.ovvv += tmp88 * 2
    tmp100 = np.copy(tmp61)
    tmp100 += tmp82
    tmp99 = einsum(tmp56, (0, 1, 2, 3), t2, (4, 0, 5, 3), (1, 4, 2, 5))
    del tmp56
    tmp100 += tmp99 * -1
    del tmp99
    tmp101 = einsum(t1, (0, 1), tmp100, (0, 2, 3, 4), (2, 3, 4, 1))
    del tmp100
    rdm2.ovvv += tmp101 * -2
    del tmp101
    rdm2.ovvv += einsum(t1, (0, 1), tmp87, (2, 3), (0, 2, 1, 3)) * 4
    del tmp87
    tmp104 = np.copy(tmp88)
    tmp102 = np.copy(tmp82)
    tmp102 += np.transpose(tmp91, (1, 0, 3, 2))
    del tmp91
    tmp102 += np.transpose(tmp89, (1, 0, 3, 2)) * -1
    del tmp89
    tmp103 = einsum(tmp102, (0, 1, 2, 3), t1, (0, 4), (1, 2, 3, 4))
    del tmp102
    tmp104 += np.transpose(tmp103, (0, 1, 3, 2))
    del tmp103
    rdm2.vovv = np.copy(np.transpose(tmp104, (1, 0, 2, 3))) * -2
    rdm2.vovv += np.transpose(tmp104, (1, 0, 3, 2)) * 2
    del tmp104
    tmp105 = np.copy(tmp95)
    tmp105 += einsum(t1, (0, 1), tmp80, (2, 3), (0, 2, 1, 3))
    rdm2.vovv += np.transpose(tmp105, (1, 0, 2, 3)) * -2
    rdm2.vovv += np.transpose(tmp105, (1, 0, 3, 2)) * 2
    del tmp105
    rdm2.vovv += np.transpose(tmp98, (1, 0, 3, 2)) * -2
    del tmp98
    rdm2.vovv += np.transpose(tmp95, (1, 0, 2, 3)) * -2
    del tmp95
    rdm2.vovv += np.transpose(tmp88, (1, 0, 3, 2)) * 2
    del tmp88
    tmp106 = np.copy(tmp61)
    tmp106 += tmp82
    del tmp82
    tmp106 += tmp41 * -1
    tmp107 = einsum(t1, (0, 1), tmp106, (0, 2, 3, 4), (2, 3, 4, 1))
    del tmp106
    rdm2.vovv += np.transpose(tmp107, (1, 0, 3, 2)) * -2
    del tmp107
    rdm2.vovv += einsum(t1, (0, 1), tmp80, (2, 3), (2, 0, 3, 1)) * 2
    del tmp80
    tmp8 = einsum(t2, (0, 1, 2, 3), l1, (3, 4), (4, 0, 1, 2))
    tmp36 = np.copy(tmp8)
    tmp27 = einsum(t1, (0, 1), tmp5, (0, 2, 3, 4), (2, 3, 4, 1))
    tmp36 += np.transpose(tmp27, (0, 2, 1, 3))
    tmp36 += einsum(t1, (0, 1), tmp1, (2, 3), (2, 0, 3, 1))
    rdm2.oovo = np.copy(np.transpose(tmp36, (1, 2, 3, 0))) * -2
    rdm2.oovo += np.transpose(tmp36, (2, 1, 3, 0)) * 2
    del tmp36
    tmp37 = einsum(t1, (0, 1), tmp6, (2, 3), (2, 0, 3, 1))
    tmp11 = einsum(t2, (0, 1, 2, 3), tmp10, (1, 4, 5, 2), (4, 5, 0, 3))
    del tmp10
    tmp37 += tmp11
    tmp12 = np.copy(tmp3) * 2
    tmp12 += np.transpose(tmp3, (1, 0, 2, 3)) * -1
    tmp13 = einsum(t2, (0, 1, 2, 3), tmp12, (1, 4, 5, 3), (4, 5, 0, 2))
    del tmp12
    tmp37 += tmp13 * -1
    rdm2.oovo += np.transpose(tmp37, (1, 2, 3, 0)) * -2
    rdm2.oovo += np.transpose(tmp37, (2, 1, 3, 0)) * 2
    del tmp37
    tmp15 = np.copy(tmp3) * -1
    tmp15 += np.transpose(tmp3, (1, 0, 2, 3)) * 2
    tmp28 = einsum(t2, (0, 1, 2, 3), tmp15, (0, 1, 4, 3), (4, 2))
    tmp38 = np.copy(tmp28)
    tmp32 = np.copy(tmp6) * 0.5
    tmp31 = einsum(tmp0, (0, 1, 2, 3), l2, (3, 2, 0, 4), (4, 1))
    del tmp0
    tmp32 += tmp31
    del tmp31
    tmp33 = einsum(t1, (0, 1), tmp32, (0, 2), (2, 1)) * 2
    del tmp32
    tmp38 += tmp33
    rdm2.oovo += einsum(tmp38, (0, 1), delta.oo, (2, 3), (0, 2, 1, 3)) * -2
    rdm2.oovo += einsum(delta.oo, (0, 1), tmp38, (2, 3), (0, 2, 3, 1)) * 2
    del tmp38
    rdm2.oovo += einsum(delta.oo, (0, 1), t1, (2, 3), (2, 0, 3, 1)) * 2
    rdm2.oovo += einsum(t1, (0, 1), delta.oo, (2, 3), (2, 0, 1, 3)) * -2
    tmp23 = einsum(tmp22, (0, 1, 2, 3), l1, (2, 0), (1, 3))
    del tmp22
    rdm2.oovo += einsum(delta.oo, (0, 1), tmp23, (2, 3), (2, 0, 3, 1)) * 2
    rdm2.oovo += einsum(delta.oo, (0, 1), tmp23, (2, 3), (0, 2, 3, 1)) * -2
    rdm2.oovo += np.transpose(tmp8, (1, 2, 3, 0)) * -2
    tmp26 = einsum(tmp3, (0, 1, 2, 3), t2, (4, 1, 3, 5), (0, 2, 4, 5))
    rdm2.oovo += np.transpose(tmp26, (1, 2, 3, 0)) * 2
    tmp25 = einsum(tmp3, (0, 1, 2, 3), t2, (4, 0, 3, 5), (1, 2, 4, 5))
    del tmp3
    rdm2.oovo += np.transpose(tmp25, (2, 1, 3, 0)) * 2
    rdm2.oovo += np.transpose(tmp13, (2, 1, 3, 0)) * -2
    rdm2.oovo += np.transpose(tmp27, (1, 2, 3, 0)) * 2
    tmp34 = np.copy(t1) * -1
    tmp34 += tmp28
    del tmp28
    tmp29 = np.copy(np.transpose(t2, (0, 1, 3, 2))) * -1
    tmp29 += t2 * 2
    tmp30 = einsum(tmp29, (0, 1, 2, 3), l1, (2, 0), (1, 3))
    del tmp29
    tmp34 += tmp30 * -1
    del tmp30
    tmp34 += tmp33
    del tmp33
    rdm2.oovo += einsum(tmp34, (0, 1), delta.oo, (2, 3), (0, 2, 1, 3)) * -2
    tmp35 = np.copy(tmp6)
    tmp35 += tmp1
    rdm2.oovo += einsum(tmp35, (0, 1), t1, (2, 3), (2, 1, 3, 0)) * -2
    tmp14 = np.copy(tmp8)
    tmp9 = einsum(tmp4, (0, 1, 2, 3), t1, (0, 4), (1, 3, 2, 4))
    del tmp4
    tmp14 += tmp9
    tmp14 += tmp11
    tmp14 += tmp13 * -1
    rdm2.ooov = np.copy(np.transpose(tmp14, (1, 2, 0, 3))) * 2
    rdm2.ooov += np.transpose(tmp14, (2, 1, 0, 3)) * -2
    del tmp14
    rdm2.ooov += einsum(tmp6, (0, 1), t1, (2, 3), (2, 1, 0, 3)) * 2
    rdm2.ooov += einsum(t1, (0, 1), tmp6, (2, 3), (3, 0, 2, 1)) * -2
    tmp16 = einsum(t2, (0, 1, 2, 3), tmp15, (0, 1, 4, 3), (4, 2)) * 0.5
    del tmp15
    tmp18 = np.copy(tmp16)
    del tmp16
    tmp17 = einsum(t1, (0, 1), tmp1, (0, 2), (2, 1)) * 0.5
    tmp18 += tmp17
    del tmp17
    rdm2.ooov += einsum(tmp18, (0, 1), delta.oo, (2, 3), (0, 2, 3, 1)) * 4
    rdm2.ooov += einsum(tmp18, (0, 1), delta.oo, (2, 3), (2, 0, 3, 1)) * -4
    rdm2.ooov += einsum(delta.oo, (0, 1), t1, (2, 3), (2, 0, 1, 3)) * -2
    rdm2.ooov += einsum(t1, (0, 1), delta.oo, (2, 3), (2, 0, 3, 1)) * 2
    tmp19 = einsum(t1, (0, 1), tmp2, (2, 0, 3, 4), (2, 3, 4, 1))
    del tmp2
    tmp20 = np.copy(tmp19)
    tmp20 += einsum(t1, (0, 1), tmp1, (2, 3), (2, 0, 3, 1))
    rdm2.ooov += np.transpose(tmp20, (1, 2, 0, 3)) * 2
    rdm2.ooov += np.transpose(tmp20, (2, 1, 0, 3)) * -2
    del tmp20
    tmp21 = einsum(t1, (0, 1), tmp6, (0, 2), (2, 1))
    tmp24 = np.copy(tmp21)
    tmp24 += tmp23 * -1
    rdm2.ooov += einsum(delta.oo, (0, 1), tmp24, (2, 3), (2, 0, 1, 3)) * 2
    rdm2.ooov += einsum(delta.oo, (0, 1), tmp24, (2, 3), (0, 2, 1, 3)) * -2
    rdm2.ooov += np.transpose(tmp8, (2, 1, 0, 3)) * -2
    rdm2.ooov += np.transpose(tmp25, (1, 2, 0, 3)) * 2
    rdm2.ooov += np.transpose(tmp26, (2, 1, 0, 3)) * 2
    rdm2.ooov += np.transpose(tmp13, (1, 2, 0, 3)) * -2
    rdm2.ooov += np.transpose(tmp27, (2, 1, 0, 3)) * 2
    rdm2.ooov += einsum(delta.oo, (0, 1), tmp34, (2, 3), (0, 2, 1, 3)) * -2
    del delta, tmp34
    rdm2.ooov += einsum(t1, (0, 1), tmp35, (2, 3), (3, 0, 2, 1)) * -2
    del tmp35
    tmp39 = einsum(t1, (0, 1), tmp9, (0, 2, 3, 4), (2, 3, 1, 4))
    del tmp9
    tmp46 = np.copy(tmp39)
    del tmp39
    tmp42 = einsum(tmp41, (0, 1, 2, 3), t2, (4, 0, 5, 2), (1, 4, 3, 5))
    del tmp41
    tmp46 += tmp42 * 2
    tmp45 = einsum(tmp44, (0, 1, 2, 3), t2, (4, 0, 2, 5), (1, 4, 3, 5))
    del tmp44
    tmp46 += np.transpose(tmp45, (1, 0, 3, 2))
    del tmp45
    rdm2.oovv = np.copy(tmp46) * 2
    rdm2.oovv += np.transpose(tmp46, (0, 1, 3, 2)) * -2
    del tmp46
    tmp47 = einsum(t2, (0, 1, 2, 3), tmp6, (1, 4), (4, 0, 2, 3))
    del tmp6
    tmp52 = np.copy(tmp47)
    tmp48 = einsum(tmp40, (0, 1, 2, 3), t2, (4, 0, 3, 5), (1, 4, 2, 5))
    del tmp40
    tmp49 = einsum(tmp48, (0, 1, 2, 3), t2, (4, 0, 5, 2), (1, 4, 3, 5))
    del tmp48
    tmp52 += np.transpose(tmp49, (1, 0, 3, 2)) * -1
    tmp50 = np.copy(tmp8)
    tmp50 += tmp11
    del tmp11
    tmp50 += tmp13 * -1
    tmp51 = einsum(t1, (0, 1), tmp50, (0, 2, 3, 4), (2, 3, 4, 1))
    del tmp50
    tmp52 += np.transpose(tmp51, (0, 1, 3, 2))
    del tmp51
    tmp52 += einsum(tmp24, (0, 1), t1, (2, 3), (2, 0, 3, 1)) * -1
    del tmp24
    rdm2.oovv += tmp52 * 2
    rdm2.oovv += np.transpose(tmp52, (0, 1, 3, 2)) * -2
    rdm2.oovv += np.transpose(tmp52, (1, 0, 2, 3)) * -2
    rdm2.oovv += np.transpose(tmp52, (1, 0, 3, 2)) * 2
    del tmp52
    tmp53 = einsum(t1, (0, 1), tmp19, (0, 2, 3, 4), (3, 2, 4, 1))
    del tmp19
    tmp55 = np.copy(tmp53)
    del tmp53
    tmp54 = einsum(tmp5, (0, 1, 2, 3), t2, (0, 1, 4, 5), (2, 3, 4, 5))
    del tmp5
    tmp55 += tmp54
    rdm2.oovv += tmp55 * 2
    rdm2.oovv += np.transpose(tmp55, (0, 1, 3, 2)) * -2
    del tmp55
    tmp58 = einsum(tmp57, (0, 1), t2, (2, 3, 0, 4), (2, 3, 1, 4)) * 2
    del tmp57
    tmp60 = np.copy(np.transpose(tmp58, (1, 0, 3, 2)))
    del tmp58
    tmp59 = einsum(tmp1, (0, 1), t2, (2, 0, 3, 4), (2, 1, 4, 3))
    del tmp1
    tmp60 += np.transpose(tmp59, (0, 1, 3, 2))
    del tmp59
    tmp60 += einsum(tmp18, (0, 1), t1, (2, 3), (2, 0, 3, 1)) * 2
    del tmp18
    rdm2.oovv += tmp60 * -4
    rdm2.oovv += np.transpose(tmp60, (0, 1, 3, 2)) * 2
    rdm2.oovv += np.transpose(tmp60, (1, 0, 2, 3)) * 2
    rdm2.oovv += np.transpose(tmp60, (1, 0, 3, 2)) * -4
    del tmp60
    rdm2.oovv += np.transpose(t2, (0, 1, 3, 2)) * -2
    rdm2.oovv += t2 * 4
    rdm2.oovv += einsum(t1, (0, 1), t1, (2, 3), (0, 2, 3, 1)) * -2
    rdm2.oovv += einsum(t1, (0, 1), t1, (2, 3), (2, 0, 3, 1)) * 2
    tmp62 = einsum(t2, (0, 1, 2, 3), tmp61, (1, 4, 2, 5), (4, 0, 5, 3))
    del tmp61
    rdm2.oovv += tmp62 * 2
    del tmp62
    tmp64 = einsum(t2, (0, 1, 2, 3), tmp63, (1, 4, 2, 5), (4, 0, 5, 3))
    del tmp63
    rdm2.oovv += np.transpose(tmp64, (0, 1, 3, 2)) * 2
    del tmp64
    rdm2.oovv += einsum(t1, (0, 1), tmp21, (2, 3), (0, 2, 1, 3)) * -2
    tmp67 = np.copy(np.transpose(tmp49, (1, 0, 3, 2))) * -1
    del tmp49
    tmp65 = np.copy(tmp25)
    del tmp25
    tmp65 += tmp13 * -1
    del tmp13
    tmp66 = einsum(tmp65, (0, 1, 2, 3), t1, (0, 4), (1, 2, 3, 4))
    del tmp65
    tmp67 += np.transpose(tmp66, (0, 1, 3, 2))
    del tmp66
    tmp67 += einsum(tmp23, (0, 1), t1, (2, 3), (2, 0, 3, 1))
    del tmp23
    rdm2.oovv += tmp67 * 2
    rdm2.oovv += np.transpose(tmp67, (1, 0, 3, 2)) * 2
    del tmp67
    tmp70 = np.copy(tmp47)
    del tmp47
    tmp68 = np.copy(tmp8)
    del tmp8
    tmp68 += tmp26 * -1
    del tmp26
    tmp69 = einsum(tmp68, (0, 1, 2, 3), t1, (0, 4), (1, 2, 3, 4))
    del tmp68
    tmp70 += np.transpose(tmp69, (0, 1, 3, 2))
    del tmp69
    rdm2.oovv += np.transpose(tmp70, (0, 1, 3, 2)) * -2
    rdm2.oovv += np.transpose(tmp70, (1, 0, 2, 3)) * -2
    del tmp70
    rdm2.oovv += tmp42 * 4
    del tmp42
    rdm2.oovv += tmp54 * 2
    del tmp54
    tmp71 = einsum(tmp27, (0, 1, 2, 3), t1, (0, 4), (2, 1, 3, 4))
    del tmp27
    rdm2.oovv += np.transpose(tmp71, (0, 1, 3, 2)) * 2
    del tmp71
    tmp72 = np.copy(t1)
    tmp72 += tmp21 * -1
    del tmp21
    rdm2.oovv += einsum(tmp72, (0, 1), t1, (2, 3), (0, 2, 1, 3)) * 2
    del tmp72
    rdm2 = pack_2e(rdm2.oooo, rdm2.ooov, rdm2.oovo, rdm2.ovoo, rdm2.vooo, rdm2.oovv, rdm2.ovov, rdm2.ovvo, rdm2.voov, rdm2.vovo, rdm2.vvoo, rdm2.ovvv, rdm2.vovv, rdm2.vvov, rdm2.vvvo, rdm2.vvvv)
    rdm2 = np.transpose(rdm2, (0, 2, 1, 3))

    return rdm2

def hbar_matvec_ip_intermediates(f=None, t1=None, t2=None, v=None, **kwargs):
    """
    Code generated by `albert` 0.0.0 on 2024-10-20T10:01:08.504387.

    Parameters
    ----------
    f : array
        Fock matrix.
    t1 : array
        T1 amplitudes.
    t2 : array
        T2 amplitudes.
    v : array
        Electron repulsion integrals.

    Returns
    -------
    tmp0 : array
    tmp100 : array
    tmp101 : array
    tmp102 : array
    tmp103 : array
    tmp108 : array
    tmp109 : array
    tmp12 : array
    tmp14 : array
    tmp16 : array
    tmp17 : array
    tmp19 : array
    tmp21 : array
    tmp22 : array
    tmp23 : array
    tmp25 : array
    tmp27 : array
    tmp29 : array
    tmp3 : array
    tmp30 : array
    tmp34 : array
    tmp35 : array
    tmp36 : array
    tmp37 : array
    tmp39 : array
    tmp4 : array
    tmp40 : array
    tmp42 : array
    tmp45 : array
    tmp46 : array
    tmp48 : array
    tmp49 : array
    tmp5 : array
    tmp50 : array
    tmp51 : array
    tmp52 : array
    tmp54 : array
    tmp55 : array
    tmp56 : array
    tmp57 : array
    tmp58 : array
    tmp6 : array
    tmp60 : array
    tmp64 : array
    tmp65 : array
    tmp66 : array
    tmp67 : array
    tmp69 : array
    tmp75 : array
    tmp76 : array
    tmp77 : array
    tmp78 : array
    tmp82 : array
    tmp83 : array
    tmp85 : array
    tmp86 : array
    tmp87 : array
    tmp88 : array
    tmp89 : array
    tmp9 : array
    tmp90 : array
    tmp92 : array
    tmp93 : array
    tmp94 : array
    tmp98 : array
    tmp99 : array
    """

    tmp22 = einsum(t1, (0, 1), v.ovvv, (2, 1, 3, 4), (0, 2, 3, 4))
    tmp23 = einsum(v.ovvv, (0, 1, 2, 3), t2, (4, 5, 1, 3), (4, 5, 0, 2))
    tmp29 = einsum(t1, (0, 1), v.oovv, (2, 0, 3, 1), (2, 3))
    tmp39 = einsum(f.ov, (0, 1), t2, (2, 0, 1, 3), (2, 3))
    tmp42 = einsum(v.oooo, (0, 1, 2, 3), t1, (3, 4), (0, 1, 2, 4))
    tmp58 = einsum(t1, (0, 1), f.oo, (2, 0), (2, 1))
    tmp82 = einsum(t1, (0, 1), f.vv, (2, 1), (0, 2))
    tmp30 = einsum(v.ooov, (0, 1, 2, 3), t1, (4, 3), (4, 0, 1, 2))
    tmp37 = einsum(t1, (0, 1), tmp30, (2, 3, 0, 4), (2, 3, 4, 1))
    tmp40 = einsum(t2, (0, 1, 2, 3), f.ov, (1, 3), (0, 2))
    tmp45 = einsum(v.ooov, (0, 1, 2, 3), t2, (4, 1, 5, 3), (4, 0, 2, 5))
    tmp46 = einsum(v.ooov, (0, 1, 2, 3), t2, (4, 2, 5, 3), (4, 0, 1, 5))
    tmp48 = einsum(v.ooov, (0, 1, 2, 3), t2, (4, 2, 3, 5), (4, 0, 1, 5))
    tmp49 = einsum(v.ovov, (0, 1, 2, 3), t2, (4, 2, 1, 5), (4, 0, 5, 3))
    tmp50 = einsum(v.ovov, (0, 1, 2, 3), t2, (4, 2, 5, 1), (4, 0, 5, 3))
    tmp51 = einsum(t2, (0, 1, 2, 3), v.ovov, (4, 5, 1, 2), (0, 4, 3, 5))
    tmp52 = einsum(t2, (0, 1, 2, 3), v.ovov, (4, 5, 1, 3), (0, 4, 2, 5))
    tmp60 = einsum(t2, (0, 1, 2, 3), f.ov, (4, 3), (4, 0, 1, 2))
    tmp64 = einsum(t2, (0, 1, 2, 3), v.ooov, (4, 0, 1, 2), (4, 3))
    tmp65 = einsum(t2, (0, 1, 2, 3), v.ooov, (4, 1, 0, 2), (4, 3))
    tmp66 = einsum(v.ooov, (0, 1, 2, 3), t2, (4, 1, 3, 5), (4, 0, 2, 5))
    tmp67 = einsum(t2, (0, 1, 2, 3), v.ovov, (0, 4, 1, 2), (3, 4))
    tmp69 = einsum(t2, (0, 1, 2, 3), v.ovov, (0, 2, 1, 4), (3, 4))
    tmp85 = einsum(t2, (0, 1, 2, 3), v.ovvv, (1, 3, 4, 2), (0, 4))
    tmp86 = einsum(t2, (0, 1, 2, 3), v.ovvv, (1, 2, 4, 3), (0, 4))
    tmp94 = einsum(t1, (0, 1), v.oovv, (2, 3, 4, 1), (0, 2, 3, 4))
    tmp103 = einsum(tmp30, (0, 1, 2, 3), t1, (3, 4), (0, 2, 1, 4))
    tmp25 = einsum(t2, (0, 1, 2, 3), v.ovov, (4, 2, 5, 3), (0, 1, 4, 5))
    tmp27 = einsum(t1, (0, 1), tmp25, (2, 3, 0, 4), (3, 2, 4, 1))
    tmp3 = einsum(t1, (0, 1), v.ooov, (2, 0, 3, 1), (2, 3))
    tmp77 = einsum(t1, (0, 1), tmp3, (2, 0), (2, 1))
    tmp4 = einsum(v.ooov, (0, 1, 2, 3), t1, (2, 3), (0, 1))
    tmp78 = einsum(t1, (0, 1), tmp4, (2, 0), (2, 1))
    tmp19 = einsum(t1, (0, 1), v.ovvv, (0, 1, 2, 3), (2, 3))
    tmp87 = einsum(t1, (0, 1), tmp19, (2, 1), (0, 2))
    tmp21 = einsum(t1, (0, 1), v.ovvv, (0, 2, 3, 1), (2, 3))
    tmp88 = einsum(t1, (0, 1), tmp21, (1, 2), (0, 2))
    tmp83 = einsum(t1, (0, 1), v.ovvv, (2, 3, 4, 1), (0, 2, 3, 4))
    tmp89 = einsum(t1, (0, 1), tmp83, (2, 3, 1, 4), (0, 2, 3, 4))
    tmp0 = einsum(f.ov, (0, 1), t1, (2, 1), (0, 2))
    tmp93 = einsum(t1, (0, 1), tmp0, (0, 2), (2, 1))
    tmp9 = einsum(t1, (0, 1), v.ovov, (2, 3, 4, 1), (0, 2, 4, 3))
    tmp34 = einsum(tmp9, (0, 1, 2, 3), t2, (4, 1, 5, 3), (0, 4, 2, 5))
    tmp35 = einsum(tmp9, (0, 1, 2, 3), t2, (4, 2, 5, 3), (0, 4, 1, 5))
    tmp36 = einsum(t2, (0, 1, 2, 3), tmp9, (4, 1, 5, 2), (4, 0, 5, 3))
    tmp5 = einsum(t1, (0, 1), v.ovov, (2, 1, 0, 3), (2, 3))
    tmp54 = einsum(t2, (0, 1, 2, 3), tmp5, (1, 2), (0, 3))
    tmp55 = einsum(t2, (0, 1, 2, 3), tmp5, (1, 3), (0, 2))
    tmp6 = einsum(v.ovov, (0, 1, 2, 3), t1, (2, 3), (0, 1))
    tmp56 = einsum(tmp6, (0, 1), t2, (2, 0, 1, 3), (2, 3))
    tmp57 = einsum(t2, (0, 1, 2, 3), tmp6, (1, 3), (0, 2))
    tmp75 = einsum(t2, (0, 1, 2, 3), tmp5, (4, 3), (0, 1, 4, 2))
    tmp76 = einsum(tmp6, (0, 1), t2, (2, 3, 4, 1), (2, 3, 0, 4))
    tmp90 = einsum(t1, (0, 1), tmp9, (2, 3, 4, 1), (2, 0, 4, 3))
    tmp92 = einsum(t1, (0, 1), tmp90, (2, 3, 0, 4), (3, 2, 4, 1))
    tmp98 = einsum(tmp9, (0, 1, 2, 3), t2, (1, 2, 3, 4), (0, 4))
    tmp99 = einsum(tmp9, (0, 1, 2, 3), t2, (2, 1, 3, 4), (0, 4))
    tmp100 = einsum(t2, (0, 1, 2, 3), tmp9, (4, 5, 1, 2), (4, 0, 5, 3))
    tmp14 = einsum(t2, (0, 1, 2, 3), v.ovov, (4, 2, 1, 3), (0, 4))
    tmp101 = einsum(t1, (0, 1), tmp14, (2, 0), (2, 1))
    tmp12 = einsum(t2, (0, 1, 2, 3), v.ovov, (4, 3, 1, 2), (0, 4))
    tmp102 = einsum(t1, (0, 1), tmp12, (2, 0), (2, 1))
    tmp16 = einsum(tmp5, (0, 1), t1, (2, 1), (2, 0))
    tmp108 = einsum(t1, (0, 1), tmp16, (2, 0), (2, 1))
    tmp17 = einsum(tmp6, (0, 1), t1, (2, 1), (2, 0))
    tmp109 = einsum(t1, (0, 1), tmp17, (2, 0), (2, 1))

    return {f"tmp0": tmp0, f"tmp100": tmp100, f"tmp101": tmp101, f"tmp102": tmp102, f"tmp103": tmp103, f"tmp108": tmp108, f"tmp109": tmp109, f"tmp12": tmp12, f"tmp14": tmp14, f"tmp16": tmp16, f"tmp17": tmp17, f"tmp19": tmp19, f"tmp21": tmp21, f"tmp22": tmp22, f"tmp23": tmp23, f"tmp25": tmp25, f"tmp27": tmp27, f"tmp29": tmp29, f"tmp3": tmp3, f"tmp30": tmp30, f"tmp34": tmp34, f"tmp35": tmp35, f"tmp36": tmp36, f"tmp37": tmp37, f"tmp39": tmp39, f"tmp4": tmp4, f"tmp40": tmp40, f"tmp42": tmp42, f"tmp45": tmp45, f"tmp46": tmp46, f"tmp48": tmp48, f"tmp49": tmp49, f"tmp5": tmp5, f"tmp50": tmp50, f"tmp51": tmp51, f"tmp52": tmp52, f"tmp54": tmp54, f"tmp55": tmp55, f"tmp56": tmp56, f"tmp57": tmp57, f"tmp58": tmp58, f"tmp6": tmp6, f"tmp60": tmp60, f"tmp64": tmp64, f"tmp65": tmp65, f"tmp66": tmp66, f"tmp67": tmp67, f"tmp69": tmp69, f"tmp75": tmp75, f"tmp76": tmp76, f"tmp77": tmp77, f"tmp78": tmp78, f"tmp82": tmp82, f"tmp83": tmp83, f"tmp85": tmp85, f"tmp86": tmp86, f"tmp87": tmp87, f"tmp88": tmp88, f"tmp89": tmp89, f"tmp9": tmp9, f"tmp90": tmp90, f"tmp92": tmp92, f"tmp93": tmp93, f"tmp94": tmp94, f"tmp98": tmp98, f"tmp99": tmp99}

def hbar_matvec_ip(f=None, r1=None, r2=None, t1=None, t2=None, v=None, **kwargs):
    """
    Code generated by `albert` 0.0.0 on 2024-10-20T10:01:10.089802.

    Parameters
    ----------
    f : array
        Fock matrix.
    r1 : array
        R1 amplitudes.
    r2 : array
        R2 amplitudes.
    t1 : array
        T1 amplitudes.
    t2 : array
        T2 amplitudes.
    v : array
        Electron repulsion integrals.

    Returns
    -------
    r1new : array
        Updated R1 residuals.
    r2new : array
        Updated R2 residuals.
    """

    ints = kwargs["ints"]
    r1new = einsum(r2, (0, 1, 2), ints.tmp9, (3, 1, 0, 2), (3,)) * -1
    tmp0 = np.copy(ints.tmp9)
    tmp0 += v.ooov * -0.5
    tmp0 += np.transpose(v.ooov, (0, 2, 1, 3))
    r1new += einsum(r2, (0, 1, 2), tmp0, (3, 0, 1, 2), (3,)) * 2
    del tmp0
    tmp2 = np.copy(r2) * 2
    tmp2 += np.transpose(r2, (1, 0, 2)) * -1
    tmp1 = np.copy(f.ov) * 0.5
    tmp1 += ints.tmp6
    tmp1 += ints.tmp5 * -0.5
    r1new += einsum(tmp2, (0, 1, 2), tmp1, (0, 2), (1,)) * -2
    tmp3 = np.copy(f.oo)
    tmp3 += ints.tmp0
    tmp3 += np.transpose(ints.tmp14, (1, 0)) * 2
    tmp3 += np.transpose(ints.tmp17, (1, 0)) * 2
    tmp3 += np.transpose(ints.tmp4, (1, 0)) * 2
    tmp3 += np.transpose(ints.tmp12, (1, 0)) * -1
    tmp3 += np.transpose(ints.tmp16, (1, 0)) * -1
    tmp3 += np.transpose(ints.tmp3, (1, 0)) * -1
    r1new += einsum(tmp3, (0, 1), r1, (0,), (1,)) * -1
    del tmp3
    tmp4 = np.copy(ints.tmp52) * 2
    tmp4 += np.transpose(ints.tmp83, (0, 1, 3, 2))
    tmp4 += np.transpose(v.ovov, (0, 2, 1, 3))
    tmp4 += ints.tmp50 * -1
    tmp4 += ints.tmp51 * -1
    r2new = einsum(tmp2, (0, 1, 2), tmp4, (3, 0, 4, 2), (3, 1, 4))
    del tmp2, tmp4
    tmp5 = np.copy(ints.tmp22)
    tmp5 += v.oovv
    tmp5 += ints.tmp49 * -1
    r2new += einsum(tmp5, (0, 1, 2, 3), r2, (4, 1, 3), (4, 0, 2)) * -1
    r2new += einsum(tmp5, (0, 1, 2, 3), r2, (1, 4, 3), (0, 4, 2)) * -1
    del tmp5
    tmp6 = np.copy(ints.tmp25)
    tmp6 += np.transpose(ints.tmp30, (1, 0, 2, 3))
    tmp6 += ints.tmp90
    r2new += einsum(tmp6, (0, 1, 2, 3), r2, (3, 2, 4), (1, 0, 4))
    del tmp6
    tmp7 = np.copy(ints.tmp30)
    tmp7 += np.transpose(v.oooo, (0, 2, 3, 1))
    r2new += einsum(tmp7, (0, 1, 2, 3), r2, (2, 3, 4), (1, 0, 4))
    del tmp7
    tmp8 = np.copy(ints.tmp21)
    tmp8 += np.transpose(ints.tmp69, (1, 0)) * 2
    tmp8 += f.vv * -1
    tmp8 += np.transpose(ints.tmp19, (1, 0)) * -2
    tmp8 += np.transpose(ints.tmp67, (1, 0)) * -1
    tmp8 += einsum(t1, (0, 1), tmp1, (0, 2), (2, 1)) * 2
    del tmp1
    r2new += einsum(r2, (0, 1, 2), tmp8, (2, 3), (0, 1, 3)) * -1
    del tmp8
    tmp9 = np.copy(ints.tmp100)
    tmp9 += np.transpose(ints.tmp103, (0, 2, 1, 3))
    tmp9 += np.transpose(ints.tmp27, (1, 0, 2, 3))
    tmp9 += np.transpose(ints.tmp35, (1, 0, 2, 3))
    tmp9 += np.transpose(ints.tmp36, (1, 0, 2, 3))
    tmp9 += np.transpose(ints.tmp37, (1, 0, 2, 3))
    tmp9 += np.transpose(ints.tmp42, (2, 0, 1, 3))
    tmp9 += ints.tmp45
    tmp9 += ints.tmp48
    tmp9 += np.transpose(ints.tmp66, (1, 0, 2, 3))
    tmp9 += ints.tmp75
    tmp9 += np.transpose(ints.tmp92, (1, 0, 2, 3))
    tmp9 += np.transpose(ints.tmp23, (1, 0, 2, 3)) * -1
    tmp9 += np.transpose(ints.tmp34, (1, 0, 2, 3)) * -2
    tmp9 += ints.tmp46 * -2
    tmp9 += np.transpose(ints.tmp60, (1, 2, 0, 3)) * -1
    tmp9 += ints.tmp76 * -2
    tmp9 += np.transpose(ints.tmp89, (1, 0, 2, 3)) * -1
    tmp9 += ints.tmp94 * -1
    tmp9 += np.transpose(ints.tmp9, (1, 0, 2, 3)) * -1
    tmp9 += np.transpose(v.ovoo, (0, 2, 3, 1)) * -1
    r2new += einsum(tmp9, (0, 1, 2, 3), r1, (2,), (0, 1, 3)) * -1
    del tmp9
    tmp10 = np.copy(f.oo) * 0.5
    tmp10 += ints.tmp0 * 0.5
    tmp10 += np.transpose(ints.tmp14, (1, 0))
    tmp10 += np.transpose(ints.tmp17, (1, 0))
    tmp10 += np.transpose(ints.tmp4, (1, 0))
    tmp10 += np.transpose(ints.tmp12, (1, 0)) * -0.5
    tmp10 += np.transpose(ints.tmp16, (1, 0)) * -0.5
    tmp10 += np.transpose(ints.tmp3, (1, 0)) * -0.5
    r2new += einsum(tmp10, (0, 1), r2, (0, 2, 3), (1, 2, 3)) * -2
    r2new += einsum(tmp10, (0, 1), r2, (2, 0, 3), (2, 1, 3)) * -2
    del tmp10
    tmp11 = np.copy(r2) * -1
    tmp11 += np.transpose(r2, (1, 0, 2)) * 2
    tmp12 = np.copy(ints.tmp9)
    tmp12 += np.transpose(v.ooov, (0, 2, 1, 3))
    tmp13 = einsum(tmp12, (0, 1, 2, 3), tmp11, (4, 1, 3), (4, 2, 0)) * -0.5
    del tmp11
    tmp13 += einsum(tmp12, (0, 1, 2, 3), r2, (4, 2, 3), (0, 1, 4)) * 0.5
    tmp13 += einsum(r2, (0, 1, 2), tmp12, (3, 4, 0, 2), (1, 4, 3)) * 0.5
    del tmp12
    r2new += einsum(t1, (0, 1), tmp13, (2, 0, 3), (3, 2, 1)) * 2
    del tmp13
    tmp14 = np.copy(np.transpose(v.ovov, (0, 2, 3, 1))) * -0.5
    tmp14 += np.transpose(v.ovov, (0, 2, 1, 3))
    tmp15 = einsum(r2, (0, 1, 2), tmp14, (0, 1, 2, 3), (3,))
    del tmp14
    r2new += einsum(t2, (0, 1, 2, 3), tmp15, (3,), (0, 1, 2)) * -2
    del tmp15
    tmp16 = np.copy(ints.tmp101) * 2
    tmp16 += ints.tmp109 * 2
    tmp16 += ints.tmp29
    tmp16 += ints.tmp39
    tmp16 += ints.tmp55 * 2
    tmp16 += ints.tmp56 * 2
    tmp16 += ints.tmp58
    tmp16 += ints.tmp65 * 2
    tmp16 += ints.tmp78 * 2
    tmp16 += ints.tmp86
    tmp16 += ints.tmp88
    tmp16 += ints.tmp93
    tmp16 += ints.tmp98 * 2
    tmp16 += f.ov * -1
    tmp16 += ints.tmp102 * -1
    tmp16 += ints.tmp108 * -1
    tmp16 += ints.tmp40 * -2
    tmp16 += ints.tmp54 * -1
    tmp16 += ints.tmp57 * -4
    tmp16 += ints.tmp64 * -1
    tmp16 += ints.tmp6 * -2
    tmp16 += ints.tmp77 * -1
    tmp16 += ints.tmp82 * -1
    tmp16 += ints.tmp85 * -2
    tmp16 += ints.tmp87 * -2
    tmp16 += ints.tmp99 * -1
    r2new += einsum(r1, (0,), tmp16, (1, 2), (1, 0, 2))
    del tmp16

    return {f"r1new": r1new, f"r2new": r2new}

def hbar_matvec_ea_intermediates(f=None, t1=None, t2=None, v=None, **kwargs):
    """
    Code generated by `albert` 0.0.0 on 2024-10-20T10:03:35.138402.

    Parameters
    ----------
    f : array
        Fock matrix.
    t1 : array
        T1 amplitudes.
    t2 : array
        T2 amplitudes.
    v : array
        Electron repulsion integrals.

    Returns
    -------
    tmp102 : array
    tmp103 : array
    tmp104 : array
    tmp106 : array
    tmp107 : array
    tmp108 : array
    tmp109 : array
    tmp14 : array
    tmp16 : array
    tmp25 : array
    tmp28 : array
    tmp3 : array
    tmp32 : array
    tmp33 : array
    tmp34 : array
    tmp36 : array
    tmp46 : array
    tmp47 : array
    tmp49 : array
    tmp5 : array
    tmp51 : array
    tmp52 : array
    tmp54 : array
    tmp55 : array
    tmp56 : array
    tmp58 : array
    tmp6 : array
    tmp60 : array
    tmp61 : array
    tmp63 : array
    tmp64 : array
    tmp66 : array
    tmp67 : array
    tmp7 : array
    tmp72 : array
    tmp73 : array
    tmp74 : array
    tmp75 : array
    tmp76 : array
    tmp81 : array
    tmp82 : array
    tmp83 : array
    tmp88 : array
    tmp89 : array
    tmp90 : array
    tmp91 : array
    tmp93 : array
    tmp94 : array
    tmp97 : array
    tmp98 : array
    tmp99 : array
    """

    tmp14 = einsum(t2, (0, 1, 2, 3), v.ovov, (0, 3, 1, 4), (2, 4))
    tmp32 = einsum(t1, (0, 1), v.oovv, (2, 0, 3, 1), (2, 3))
    tmp25 = einsum(t2, (0, 1, 2, 3), v.ovvv, (1, 4, 5, 2), (0, 3, 4, 5))
    tmp36 = einsum(t2, (0, 1, 2, 3), v.ooov, (4, 0, 1, 5), (4, 2, 3, 5))
    tmp46 = einsum(t1, (0, 1), f.vv, (2, 1), (0, 2))
    tmp49 = einsum(t1, (0, 1), v.vvvv, (2, 3, 4, 1), (0, 2, 3, 4))
    tmp83 = einsum(t1, (0, 1), f.oo, (2, 0), (2, 1))
    tmp16 = einsum(t2, (0, 1, 2, 3), v.ovov, (0, 4, 1, 3), (2, 4))
    tmp28 = einsum(v.ovov, (0, 1, 2, 3), t2, (4, 2, 1, 5), (4, 0, 5, 3))
    tmp51 = einsum(t1, (0, 1), v.ovvv, (2, 1, 3, 4), (0, 2, 3, 4))
    tmp52 = einsum(t1, (0, 1), v.ovvv, (2, 3, 4, 1), (0, 2, 3, 4))
    tmp54 = einsum(t2, (0, 1, 2, 3), v.ovvv, (1, 3, 4, 2), (0, 4))
    tmp55 = einsum(t2, (0, 1, 2, 3), v.ovvv, (1, 2, 4, 3), (0, 4))
    tmp47 = einsum(f.ov, (0, 1), t1, (2, 1), (0, 2))
    tmp72 = einsum(t1, (0, 1), tmp47, (0, 2), (2, 1))
    tmp88 = einsum(t2, (0, 1, 2, 3), v.ooov, (4, 1, 0, 3), (4, 2))
    tmp89 = einsum(t2, (0, 1, 2, 3), v.ooov, (4, 0, 1, 3), (4, 2))
    tmp93 = einsum(f.ov, (0, 1), t2, (2, 0, 1, 3), (2, 3))
    tmp94 = einsum(t2, (0, 1, 2, 3), f.ov, (1, 3), (0, 2))
    tmp97 = einsum(v.ovvv, (0, 1, 2, 3), t2, (4, 0, 5, 1), (4, 5, 2, 3))
    tmp98 = einsum(v.ovvv, (0, 1, 2, 3), t2, (4, 0, 5, 3), (4, 5, 1, 2))
    tmp99 = einsum(v.ovvv, (0, 1, 2, 3), t2, (4, 0, 1, 5), (4, 5, 2, 3))
    tmp102 = einsum(v.ovov, (0, 1, 2, 3), t2, (4, 2, 5, 1), (4, 0, 5, 3))
    tmp103 = einsum(t2, (0, 1, 2, 3), v.ovov, (4, 5, 1, 2), (0, 4, 3, 5))
    tmp104 = einsum(t2, (0, 1, 2, 3), v.ovov, (4, 5, 1, 3), (0, 4, 2, 5))
    tmp3 = einsum(t1, (0, 1), v.ovvv, (0, 1, 2, 3), (2, 3))
    tmp63 = einsum(t1, (0, 1), tmp3, (2, 1), (0, 2))
    tmp5 = einsum(t1, (0, 1), v.ovvv, (0, 2, 3, 1), (2, 3))
    tmp64 = einsum(tmp5, (0, 1), t1, (2, 0), (2, 1))
    tmp33 = einsum(t1, (0, 1), v.ooov, (2, 0, 3, 1), (2, 3))
    tmp90 = einsum(tmp33, (0, 1), t1, (1, 2), (0, 2))
    tmp34 = einsum(v.ooov, (0, 1, 2, 3), t1, (2, 3), (0, 1))
    tmp91 = einsum(t1, (0, 1), tmp34, (2, 0), (2, 1))
    tmp60 = einsum(t1, (0, 1), v.ovov, (2, 3, 4, 1), (0, 2, 4, 3))
    tmp61 = einsum(t2, (0, 1, 2, 3), tmp60, (4, 0, 1, 5), (4, 2, 3, 5))
    tmp73 = einsum(tmp60, (0, 1, 2, 3), t2, (2, 1, 4, 3), (0, 4))
    tmp74 = einsum(t2, (0, 1, 2, 3), tmp60, (4, 0, 1, 3), (4, 2))
    tmp58 = einsum(t2, (0, 1, 2, 3), v.ovov, (4, 2, 1, 3), (0, 4))
    tmp75 = einsum(t1, (0, 1), tmp58, (2, 0), (2, 1))
    tmp56 = einsum(t2, (0, 1, 2, 3), v.ovov, (4, 3, 1, 2), (0, 4))
    tmp76 = einsum(t1, (0, 1), tmp56, (2, 0), (2, 1))
    tmp6 = einsum(t1, (0, 1), v.ovov, (2, 1, 0, 3), (2, 3))
    tmp66 = einsum(tmp6, (0, 1), t1, (2, 1), (2, 0))
    tmp81 = einsum(t1, (0, 1), tmp66, (2, 0), (2, 1))
    tmp7 = einsum(v.ovov, (0, 1, 2, 3), t1, (2, 3), (0, 1))
    tmp67 = einsum(tmp7, (0, 1), t1, (2, 1), (2, 0))
    tmp82 = einsum(t1, (0, 1), tmp67, (2, 0), (2, 1))
    tmp106 = einsum(tmp6, (0, 1), t2, (2, 0, 1, 3), (2, 3))
    tmp107 = einsum(t2, (0, 1, 2, 3), tmp6, (1, 3), (0, 2))
    tmp108 = einsum(tmp7, (0, 1), t2, (2, 0, 1, 3), (2, 3))
    tmp109 = einsum(t2, (0, 1, 2, 3), tmp7, (1, 3), (0, 2))

    return {f"tmp102": tmp102, f"tmp103": tmp103, f"tmp104": tmp104, f"tmp106": tmp106, f"tmp107": tmp107, f"tmp108": tmp108, f"tmp109": tmp109, f"tmp14": tmp14, f"tmp16": tmp16, f"tmp25": tmp25, f"tmp28": tmp28, f"tmp3": tmp3, f"tmp32": tmp32, f"tmp33": tmp33, f"tmp34": tmp34, f"tmp36": tmp36, f"tmp46": tmp46, f"tmp47": tmp47, f"tmp49": tmp49, f"tmp5": tmp5, f"tmp51": tmp51, f"tmp52": tmp52, f"tmp54": tmp54, f"tmp55": tmp55, f"tmp56": tmp56, f"tmp58": tmp58, f"tmp6": tmp6, f"tmp60": tmp60, f"tmp61": tmp61, f"tmp63": tmp63, f"tmp64": tmp64, f"tmp66": tmp66, f"tmp67": tmp67, f"tmp7": tmp7, f"tmp72": tmp72, f"tmp73": tmp73, f"tmp74": tmp74, f"tmp75": tmp75, f"tmp76": tmp76, f"tmp81": tmp81, f"tmp82": tmp82, f"tmp83": tmp83, f"tmp88": tmp88, f"tmp89": tmp89, f"tmp90": tmp90, f"tmp91": tmp91, f"tmp93": tmp93, f"tmp94": tmp94, f"tmp97": tmp97, f"tmp98": tmp98, f"tmp99": tmp99}

def hbar_matvec_ea(f=None, r1=None, r2=None, t1=None, t2=None, v=None, **kwargs):
    """
    Code generated by `albert` 0.0.0 on 2024-10-20T10:03:36.416804.

    Parameters
    ----------
    f : array
        Fock matrix.
    r1 : array
        R1 amplitudes.
    r2 : array
        R2 amplitudes.
    t1 : array
        T1 amplitudes.
    t2 : array
        T2 amplitudes.
    v : array
        Electron repulsion integrals.

    Returns
    -------
    r1new : array
        Updated R1 residuals.
    r2new : array
        Updated R2 residuals.
    """

    ints = kwargs["ints"]
    tmp0 = np.copy(v.ovvv) * -1
    tmp0 += np.transpose(v.ovvv, (0, 2, 1, 3)) * 2
    r1new = einsum(r2, (0, 1, 2), tmp0, (2, 1, 0, 3), (3,)) * -1
    del tmp0
    tmp2 = np.copy(np.transpose(r2, (2, 0, 1))) * -1
    tmp2 += np.transpose(r2, (2, 1, 0)) * 2
    tmp1 = np.copy(f.ov) * 0.5
    tmp1 += ints.tmp7
    tmp1 += ints.tmp6 * -0.5
    r1new += einsum(tmp1, (0, 1), tmp2, (0, 2, 1), (2,)) * -2
    tmp3 = np.copy(f.vv)
    tmp3 += np.transpose(ints.tmp14, (1, 0))
    tmp3 += np.transpose(ints.tmp3, (1, 0)) * 2
    tmp3 += np.transpose(ints.tmp16, (1, 0)) * -2
    tmp3 += ints.tmp5 * -1
    r1new += einsum(tmp3, (0, 1), r1, (0,), (1,))
    del tmp3
    tmp4 = np.copy(np.transpose(v.ovov, (0, 2, 3, 1))) * -1
    tmp4 += np.transpose(v.ovov, (0, 2, 1, 3)) * 2
    tmp5 = einsum(r2, (0, 1, 2), tmp4, (2, 3, 0, 1), (3,)) * 0.5
    del tmp4
    tmp8 = np.copy(tmp5) * -1
    del tmp5
    tmp6 = np.copy(f.ov)
    tmp6 += ints.tmp7 * 2
    tmp6 += ints.tmp6 * -1
    tmp7 = einsum(tmp6, (0, 1), r1, (1,), (0,)) * 0.5
    del tmp6
    tmp8 += tmp7
    del tmp7
    r1new += einsum(tmp8, (0,), t1, (0, 1), (1,)) * -2
    tmp9 = einsum(r2, (0, 1, 2), v.ovov, (3, 0, 4, 1), (2, 3, 4))
    r2new = einsum(t2, (0, 1, 2, 3), tmp9, (4, 0, 1), (2, 3, 4))
    tmp10 = einsum(r2, (0, 1, 2), v.ovvv, (3, 0, 4, 1), (2, 3, 4))
    r2new += einsum(t1, (0, 1), tmp10, (2, 0, 3), (1, 3, 2)) * -1
    del tmp10
    r2new += einsum(r2, (0, 1, 2), v.vvvv, (3, 0, 4, 1), (3, 4, 2))
    tmp12 = np.copy(ints.tmp102)
    tmp12 += ints.tmp103
    tmp12 += ints.tmp104 * -2
    tmp12 += np.transpose(ints.tmp52, (0, 1, 3, 2)) * -1
    tmp12 += np.transpose(v.ovov, (0, 2, 1, 3)) * -1
    tmp11 = np.copy(ints.tmp60)
    tmp11 += np.transpose(v.ooov, (0, 2, 1, 3))
    tmp12 += einsum(t1, (0, 1), tmp11, (2, 3, 0, 4), (2, 3, 1, 4))
    r2new += einsum(tmp12, (0, 1, 2, 3), tmp2, (1, 4, 3), (2, 4, 0)) * -1
    del tmp2, tmp12
    tmp14 = np.copy(ints.tmp51)
    tmp14 += v.oovv
    tmp14 += ints.tmp28 * -1
    tmp13 = np.copy(np.transpose(r2, (2, 0, 1)))
    tmp13 += einsum(t1, (0, 1), r1, (2,), (0, 1, 2)) * -1
    r2new += einsum(tmp13, (0, 1, 2), tmp14, (3, 0, 4, 2), (1, 4, 3)) * -1
    del tmp14
    tmp15 = np.copy(ints.tmp28)
    tmp15 += ints.tmp51 * -1
    tmp15 += v.oovv * -1
    tmp15 += einsum(t1, (0, 1), tmp11, (2, 0, 3, 4), (2, 3, 1, 4))
    r2new += einsum(r2, (0, 1, 2), tmp15, (3, 2, 4, 0), (4, 1, 3))
    del tmp15
    tmp17 = np.copy(np.transpose(ints.tmp16, (1, 0))) * 2
    tmp17 += ints.tmp5
    tmp17 += f.vv * -1
    tmp17 += np.transpose(ints.tmp14, (1, 0)) * -1
    tmp17 += np.transpose(ints.tmp3, (1, 0)) * -2
    tmp16 = einsum(tmp1, (0, 1), t1, (0, 2), (2, 1)) * 2
    del tmp1
    tmp17 += np.transpose(tmp16, (1, 0))
    del tmp16
    r2new += einsum(r2, (0, 1, 2), tmp17, (0, 3), (3, 1, 2)) * -1
    r2new += einsum(tmp17, (0, 1), r2, (2, 0, 3), (2, 1, 3)) * -1
    del tmp17
    tmp18 = np.copy(np.transpose(ints.tmp36, (0, 2, 3, 1)))
    tmp18 += ints.tmp49
    tmp18 += np.transpose(ints.tmp61, (0, 1, 3, 2))
    tmp18 += np.transpose(ints.tmp97, (0, 2, 3, 1)) * 2
    tmp18 += np.transpose(v.ovvv, (0, 2, 3, 1))
    tmp18 += ints.tmp25 * -1
    tmp18 += np.transpose(ints.tmp98, (0, 3, 2, 1)) * -1
    tmp18 += np.transpose(ints.tmp99, (0, 2, 3, 1)) * -1
    r2new += einsum(r1, (0,), tmp18, (1, 2, 0, 3), (3, 2, 1)) * -1
    del tmp18
    tmp20 = einsum(v.ovvv, (0, 1, 2, 3), r2, (3, 1, 4), (4, 0, 2)) * -1
    tmp20 += einsum(t1, (0, 1), tmp9, (2, 0, 3), (2, 3, 1))
    del tmp9
    tmp20 += einsum(tmp13, (0, 1, 2), tmp11, (3, 4, 0, 2), (3, 4, 1))
    del tmp11, tmp13
    tmp19 = np.copy(ints.tmp104)
    tmp19 += np.transpose(ints.tmp52, (0, 1, 3, 2)) * 0.5
    tmp19 += np.transpose(v.ovov, (0, 2, 1, 3)) * 0.5
    tmp19 += ints.tmp102 * -0.5
    tmp19 += ints.tmp103 * -0.5
    tmp20 += einsum(tmp19, (0, 1, 2, 3), r1, (3,), (0, 1, 2)) * 2
    del tmp19
    r2new += einsum(tmp20, (0, 1, 2), t1, (1, 3), (2, 3, 0))
    del tmp20
    tmp21 = np.copy(f.oo)
    tmp21 += np.transpose(ints.tmp34, (1, 0)) * 2
    tmp21 += ints.tmp47
    tmp21 += np.transpose(ints.tmp58, (1, 0)) * 2
    tmp21 += np.transpose(ints.tmp67, (1, 0)) * 2
    tmp21 += np.transpose(ints.tmp33, (1, 0)) * -1
    tmp21 += np.transpose(ints.tmp56, (1, 0)) * -1
    tmp21 += np.transpose(ints.tmp66, (1, 0)) * -1
    r2new += einsum(r2, (0, 1, 2), tmp21, (2, 3), (0, 1, 3)) * -1
    del tmp21
    r2new += einsum(t2, (0, 1, 2, 3), tmp8, (1,), (2, 3, 0)) * 2
    del tmp8
    tmp22 = np.copy(ints.tmp107) * 2
    tmp22 += ints.tmp108 * 2
    tmp22 += ints.tmp32
    tmp22 += ints.tmp55
    tmp22 += ints.tmp64
    tmp22 += ints.tmp72
    tmp22 += ints.tmp73 * 2
    tmp22 += ints.tmp75 * 2
    tmp22 += ints.tmp82 * 2
    tmp22 += ints.tmp83
    tmp22 += ints.tmp89 * 2
    tmp22 += ints.tmp91 * 2
    tmp22 += ints.tmp93
    tmp22 += f.ov * -1
    tmp22 += ints.tmp106 * -1
    tmp22 += ints.tmp109 * -4
    tmp22 += ints.tmp46 * -1
    tmp22 += ints.tmp54 * -2
    tmp22 += ints.tmp63 * -2
    tmp22 += ints.tmp74 * -1
    tmp22 += ints.tmp76 * -1
    tmp22 += ints.tmp7 * -2
    tmp22 += ints.tmp81 * -1
    tmp22 += ints.tmp88 * -1
    tmp22 += ints.tmp90 * -1
    tmp22 += ints.tmp94 * -2
    r2new += einsum(tmp22, (0, 1), r1, (2,), (1, 2, 0))
    del tmp22

    return {f"r1new": r1new, f"r2new": r2new}

def hbar_lmatvec_ip_intermediates(f=None, t1=None, t2=None, v=None, **kwargs):
    """
    Code generated by `albert` 0.0.0 on 2024-10-20T10:08:09.767898.

    Parameters
    ----------
    f : array
        Fock matrix.
    t1 : array
        T1 amplitudes.
    t2 : array
        T2 amplitudes.
    v : array
        Electron repulsion integrals.

    Returns
    -------
    tmp0 : array
    tmp1 : array
    tmp100 : array
    tmp103 : array
    tmp104 : array
    tmp107 : array
    tmp108 : array
    tmp112 : array
    tmp113 : array
    tmp114 : array
    tmp116 : array
    tmp117 : array
    tmp12 : array
    tmp13 : array
    tmp134 : array
    tmp136 : array
    tmp14 : array
    tmp17 : array
    tmp19 : array
    tmp2 : array
    tmp20 : array
    tmp21 : array
    tmp22 : array
    tmp24 : array
    tmp26 : array
    tmp29 : array
    tmp3 : array
    tmp32 : array
    tmp33 : array
    tmp35 : array
    tmp36 : array
    tmp38 : array
    tmp4 : array
    tmp41 : array
    tmp44 : array
    tmp47 : array
    tmp48 : array
    tmp49 : array
    tmp51 : array
    tmp54 : array
    tmp57 : array
    tmp6 : array
    tmp60 : array
    tmp63 : array
    tmp66 : array
    tmp69 : array
    tmp70 : array
    tmp72 : array
    tmp73 : array
    tmp75 : array
    tmp78 : array
    tmp81 : array
    tmp82 : array
    tmp85 : array
    tmp86 : array
    tmp87 : array
    tmp88 : array
    tmp9 : array
    tmp90 : array
    tmp91 : array
    tmp92 : array
    tmp93 : array
    tmp94 : array
    tmp97 : array
    tmp98 : array
    tmp99 : array
    """

    tmp1 = einsum(t1, (0, 1), f.oo, (2, 0), (2, 1))
    tmp3 = einsum(f.ov, (0, 1), t2, (2, 0, 1, 3), (2, 3))
    tmp2 = einsum(t1, (0, 1), f.vv, (2, 1), (0, 2))
    tmp14 = einsum(t1, (0, 1), v.oooo, (2, 3, 4, 0), (2, 3, 4, 1))
    tmp19 = einsum(t1, (0, 1), v.oovv, (2, 0, 3, 1), (2, 3))
    tmp26 = einsum(t2, (0, 1, 2, 3), v.ooov, (4, 1, 0, 3), (4, 2))
    tmp38 = einsum(t2, (0, 1, 2, 3), v.ovvv, (1, 3, 4, 2), (0, 4))
    tmp4 = einsum(t2, (0, 1, 2, 3), f.ov, (1, 3), (0, 2))
    tmp6 = einsum(t2, (0, 1, 2, 3), f.ov, (4, 3), (4, 0, 1, 2))
    tmp21 = einsum(t1, (0, 1), v.oovv, (2, 3, 4, 1), (0, 2, 3, 4))
    tmp29 = einsum(v.ooov, (0, 1, 2, 3), t2, (2, 1, 3, 4), (0, 4))
    tmp32 = einsum(v.ooov, (0, 1, 2, 3), t2, (4, 1, 3, 5), (4, 0, 2, 5))
    tmp33 = einsum(v.ooov, (0, 1, 2, 3), t2, (4, 1, 5, 3), (4, 0, 2, 5))
    tmp35 = einsum(v.ooov, (0, 1, 2, 3), t2, (4, 2, 3, 5), (4, 0, 1, 5))
    tmp36 = einsum(v.ooov, (0, 1, 2, 3), t2, (4, 2, 5, 3), (4, 0, 1, 5))
    tmp41 = einsum(v.ovvv, (0, 1, 2, 3), t2, (4, 0, 1, 3), (4, 2))
    tmp44 = einsum(v.ovvv, (0, 1, 2, 3), t2, (4, 5, 1, 3), (4, 5, 0, 2))
    tmp112 = einsum(t1, (0, 1), v.ovvv, (2, 1, 3, 4), (0, 2, 3, 4))
    tmp113 = einsum(v.ovov, (0, 1, 2, 3), t2, (4, 2, 1, 5), (4, 0, 5, 3))
    tmp114 = einsum(t2, (0, 1, 2, 3), v.ovov, (4, 3, 1, 5), (0, 4, 2, 5))
    tmp116 = einsum(t2, (0, 1, 2, 3), v.ovov, (4, 5, 1, 2), (0, 4, 3, 5))
    tmp117 = einsum(t2, (0, 1, 2, 3), v.ovov, (4, 5, 1, 3), (0, 4, 2, 5))
    tmp134 = einsum(t2, (0, 1, 2, 3), v.ovov, (0, 4, 1, 2), (3, 4))
    tmp136 = einsum(t2, (0, 1, 2, 3), v.ovov, (0, 2, 1, 4), (3, 4))
    tmp0 = einsum(f.ov, (0, 1), t1, (2, 1), (0, 2))
    tmp9 = einsum(t1, (0, 1), tmp0, (0, 2), (2, 1))
    tmp47 = einsum(t1, (0, 1), v.ovov, (2, 1, 0, 3), (2, 3))
    tmp48 = einsum(t2, (0, 1, 2, 3), tmp47, (1, 2), (0, 3))
    tmp49 = einsum(tmp47, (0, 1), t2, (2, 0, 3, 1), (2, 3))
    tmp57 = einsum(t2, (0, 1, 2, 3), tmp47, (4, 3), (0, 1, 4, 2))
    tmp12 = einsum(t1, (0, 1), v.ooov, (2, 0, 3, 1), (2, 3))
    tmp87 = einsum(t1, (0, 1), tmp12, (2, 0), (2, 1))
    tmp13 = einsum(v.ooov, (0, 1, 2, 3), t1, (2, 3), (0, 1))
    tmp88 = einsum(t1, (0, 1), tmp13, (2, 0), (2, 1))
    tmp90 = einsum(v.ooov, (0, 1, 2, 3), t1, (4, 3), (4, 0, 1, 2))
    tmp91 = einsum(tmp90, (0, 1, 2, 3), t1, (2, 4), (0, 1, 3, 4))
    tmp92 = einsum(t1, (0, 1), tmp90, (2, 3, 4, 0), (2, 3, 4, 1))
    tmp93 = einsum(t1, (0, 1), v.ovvv, (0, 1, 2, 3), (2, 3))
    tmp94 = einsum(t1, (0, 1), tmp93, (2, 1), (0, 2))
    tmp97 = einsum(t1, (0, 1), v.ovvv, (0, 2, 3, 1), (2, 3))
    tmp98 = einsum(t1, (0, 1), tmp97, (1, 2), (0, 2))
    tmp99 = einsum(t1, (0, 1), v.ovvv, (2, 3, 4, 1), (0, 2, 3, 4))
    tmp100 = einsum(t1, (0, 1), tmp99, (2, 3, 1, 4), (0, 2, 3, 4))
    tmp85 = einsum(t1, (0, 1), tmp47, (2, 1), (0, 2))
    tmp103 = einsum(t1, (0, 1), tmp85, (2, 0), (2, 1))
    tmp17 = einsum(v.ovov, (0, 1, 2, 3), t1, (2, 3), (0, 1))
    tmp51 = einsum(t2, (0, 1, 2, 3), tmp17, (1, 2), (0, 3))
    tmp54 = einsum(tmp17, (0, 1), t2, (2, 0, 3, 1), (2, 3))
    tmp60 = einsum(tmp17, (0, 1), t2, (2, 3, 4, 1), (2, 3, 0, 4))
    tmp20 = einsum(t1, (0, 1), v.ovov, (2, 3, 4, 1), (0, 2, 4, 3))
    tmp63 = einsum(t2, (0, 1, 2, 3), tmp20, (4, 0, 1, 2), (4, 3))
    tmp66 = einsum(t2, (0, 1, 2, 3), tmp20, (4, 1, 0, 2), (4, 3))
    tmp69 = einsum(t2, (0, 1, 2, 3), tmp20, (4, 1, 5, 2), (4, 0, 5, 3))
    tmp70 = einsum(tmp20, (0, 1, 2, 3), t2, (4, 1, 5, 3), (0, 4, 2, 5))
    tmp72 = einsum(t2, (0, 1, 2, 3), tmp20, (4, 5, 1, 2), (4, 0, 5, 3))
    tmp73 = einsum(t2, (0, 1, 2, 3), tmp20, (4, 5, 1, 3), (4, 0, 5, 2))
    tmp24 = einsum(v.ovov, (0, 1, 2, 3), t2, (4, 2, 1, 3), (4, 0))
    tmp75 = einsum(t1, (0, 1), tmp24, (2, 0), (2, 1))
    tmp22 = einsum(v.ovov, (0, 1, 2, 3), t2, (4, 2, 3, 1), (4, 0))
    tmp78 = einsum(t1, (0, 1), tmp22, (2, 0), (2, 1))
    tmp81 = einsum(t2, (0, 1, 2, 3), v.ovov, (4, 2, 5, 3), (0, 1, 4, 5))
    tmp82 = einsum(tmp81, (0, 1, 2, 3), t1, (2, 4), (1, 0, 3, 4))
    tmp86 = einsum(tmp17, (0, 1), t1, (2, 1), (2, 0))
    tmp104 = einsum(t1, (0, 1), tmp86, (2, 0), (2, 1))
    tmp107 = einsum(tmp20, (0, 1, 2, 3), t1, (4, 3), (4, 0, 1, 2))
    tmp108 = einsum(tmp107, (0, 1, 2, 3), t1, (3, 4), (0, 1, 2, 4))

    return {f"tmp0": tmp0, f"tmp1": tmp1, f"tmp100": tmp100, f"tmp103": tmp103, f"tmp104": tmp104, f"tmp107": tmp107, f"tmp108": tmp108, f"tmp112": tmp112, f"tmp113": tmp113, f"tmp114": tmp114, f"tmp116": tmp116, f"tmp117": tmp117, f"tmp12": tmp12, f"tmp13": tmp13, f"tmp134": tmp134, f"tmp136": tmp136, f"tmp14": tmp14, f"tmp17": tmp17, f"tmp19": tmp19, f"tmp2": tmp2, f"tmp20": tmp20, f"tmp21": tmp21, f"tmp22": tmp22, f"tmp24": tmp24, f"tmp26": tmp26, f"tmp29": tmp29, f"tmp3": tmp3, f"tmp32": tmp32, f"tmp33": tmp33, f"tmp35": tmp35, f"tmp36": tmp36, f"tmp38": tmp38, f"tmp4": tmp4, f"tmp41": tmp41, f"tmp44": tmp44, f"tmp47": tmp47, f"tmp48": tmp48, f"tmp49": tmp49, f"tmp51": tmp51, f"tmp54": tmp54, f"tmp57": tmp57, f"tmp6": tmp6, f"tmp60": tmp60, f"tmp63": tmp63, f"tmp66": tmp66, f"tmp69": tmp69, f"tmp70": tmp70, f"tmp72": tmp72, f"tmp73": tmp73, f"tmp75": tmp75, f"tmp78": tmp78, f"tmp81": tmp81, f"tmp82": tmp82, f"tmp85": tmp85, f"tmp86": tmp86, f"tmp87": tmp87, f"tmp88": tmp88, f"tmp9": tmp9, f"tmp90": tmp90, f"tmp91": tmp91, f"tmp92": tmp92, f"tmp93": tmp93, f"tmp94": tmp94, f"tmp97": tmp97, f"tmp98": tmp98, f"tmp99": tmp99}

def hbar_lmatvec_ip(f=None, r1=None, r2=None, t1=None, t2=None, v=None, **kwargs):
    """
    Code generated by `albert` 0.0.0 on 2024-10-20T10:08:11.411184.

    Parameters
    ----------
    f : array
        Fock matrix.
    r1 : array
        R1 amplitudes.
    r2 : array
        R2 amplitudes.
    t1 : array
        T1 amplitudes.
    t2 : array
        T2 amplitudes.
    v : array
        Electron repulsion integrals.

    Returns
    -------
    r1new : array
        Updated R1 residuals.
    r2new : array
        Updated R2 residuals.
    """

    ints = kwargs["ints"]
    tmp1 = np.copy(ints.tmp108)
    tmp1 += np.transpose(ints.tmp14, (1, 2, 0, 3))
    tmp1 += ints.tmp32
    tmp1 += ints.tmp69
    tmp1 += ints.tmp73
    tmp1 += ints.tmp82
    tmp1 += ints.tmp91
    tmp1 += ints.tmp100 * -1
    tmp1 += ints.tmp20 * -1
    tmp1 += ints.tmp44 * -1
    tmp1 += ints.tmp70 * -2
    tmp0 = np.copy(r2) * -0.5
    tmp0 += np.transpose(r2, (1, 0, 2))
    r1new = einsum(tmp0, (0, 1, 2), tmp1, (0, 1, 3, 2), (3,)) * -2
    del tmp0, tmp1
    tmp3 = np.copy(np.transpose(ints.tmp33, (0, 2, 1, 3)))
    tmp3 += ints.tmp35
    tmp3 += np.transpose(ints.tmp57, (0, 2, 1, 3))
    tmp3 += np.transpose(ints.tmp72, (0, 2, 1, 3))
    tmp3 += ints.tmp92
    tmp3 += ints.tmp21 * -1
    tmp3 += ints.tmp36 * -2
    tmp3 += np.transpose(ints.tmp60, (0, 2, 1, 3)) * -2
    tmp3 += np.transpose(ints.tmp6, (1, 0, 2, 3)) * -1
    tmp2 = np.copy(r2) * 2
    tmp2 += np.transpose(r2, (1, 0, 2)) * -1
    r1new += einsum(tmp2, (0, 1, 2), tmp3, (0, 3, 1, 2), (3,)) * -1
    del tmp3
    tmp4 = np.copy(v.ooov)
    tmp4 += np.transpose(v.ovoo, (0, 2, 3, 1)) * -0.5
    r1new += einsum(tmp4, (0, 1, 2, 3), r2, (2, 0, 3), (1,)) * 2
    del tmp4
    tmp5 = np.copy(ints.tmp104) * 2
    tmp5 += ints.tmp19
    tmp5 += ints.tmp1
    tmp5 += ints.tmp29 * 2
    tmp5 += ints.tmp3
    tmp5 += ints.tmp41
    tmp5 += ints.tmp49 * 2
    tmp5 += ints.tmp51 * 2
    tmp5 += ints.tmp63 * 2
    tmp5 += ints.tmp75 * 2
    tmp5 += ints.tmp88 * 2
    tmp5 += ints.tmp98
    tmp5 += ints.tmp9
    tmp5 += f.ov * -1
    tmp5 += ints.tmp103 * -1
    tmp5 += ints.tmp17 * -2
    tmp5 += ints.tmp26 * -1
    tmp5 += ints.tmp2 * -1
    tmp5 += ints.tmp38 * -2
    tmp5 += ints.tmp48 * -1
    tmp5 += ints.tmp4 * -2
    tmp5 += ints.tmp54 * -4
    tmp5 += ints.tmp66 * -1
    tmp5 += ints.tmp78 * -1
    tmp5 += ints.tmp87 * -1
    tmp5 += ints.tmp94 * -2
    r1new += einsum(tmp2, (0, 1, 2), tmp5, (0, 2), (1,))
    del tmp2, tmp5
    tmp6 = np.copy(f.oo)
    tmp6 += np.transpose(ints.tmp0, (1, 0))
    tmp6 += np.transpose(ints.tmp13, (1, 0)) * 2
    tmp6 += ints.tmp24 * 2
    tmp6 += ints.tmp86 * 2
    tmp6 += ints.tmp12 * -1
    tmp6 += ints.tmp22 * -1
    tmp6 += ints.tmp85 * -1
    r1new += einsum(r1, (0,), tmp6, (0, 1), (1,)) * -1
    del tmp6
    tmp7 = np.copy(r2)
    tmp7 += np.transpose(r2, (1, 0, 2)) * -0.5
    tmp8 = np.copy(ints.tmp117) * 2
    tmp8 += np.transpose(ints.tmp99, (0, 1, 3, 2))
    tmp8 += np.transpose(v.ovov, (0, 2, 1, 3))
    tmp8 += ints.tmp114 * -1
    tmp8 += ints.tmp116 * -1
    r2new = einsum(tmp7, (0, 1, 2), tmp8, (0, 3, 2, 4), (3, 1, 4)) * 2
    del tmp7, tmp8
    tmp9 = np.copy(ints.tmp112)
    tmp9 += v.oovv
    tmp9 += np.transpose(ints.tmp113, (0, 1, 3, 2)) * -1
    r2new += einsum(tmp9, (0, 1, 2, 3), r2, (4, 0, 3), (4, 1, 2)) * -1
    r2new += einsum(tmp9, (0, 1, 2, 3), r2, (0, 4, 3), (1, 4, 2)) * -1
    del tmp9
    tmp10 = einsum(t1, (0, 1), r2, (2, 3, 1), (2, 3, 0))
    tmp11 = np.copy(tmp10)
    tmp11 += np.transpose(tmp10, (1, 0, 2)) * -0.5
    tmp12 = np.copy(ints.tmp20)
    tmp12 += np.transpose(v.ooov, (0, 2, 1, 3))
    r2new += einsum(tmp12, (0, 1, 2, 3), tmp11, (0, 4, 2), (1, 4, 3)) * -2
    del tmp12, tmp11
    tmp13 = np.copy(ints.tmp107)
    tmp13 += np.transpose(ints.tmp90, (0, 1, 3, 2))
    tmp13 += np.transpose(v.oooo, (0, 2, 1, 3))
    r2new += einsum(tmp13, (0, 1, 2, 3), r2, (0, 1, 4), (2, 3, 4))
    del tmp13
    tmp14 = np.copy(ints.tmp81)
    tmp14 += np.transpose(ints.tmp90, (0, 1, 3, 2))
    r2new += einsum(r2, (0, 1, 2), tmp14, (1, 0, 3, 4), (4, 3, 2))
    del tmp14
    tmp15 = np.copy(ints.tmp20)
    tmp15 += np.transpose(v.ooov, (0, 2, 1, 3))
    r2new += einsum(tmp15, (0, 1, 2, 3), tmp10, (4, 0, 1), (4, 2, 3))
    r2new += einsum(tmp15, (0, 1, 2, 3), tmp10, (0, 4, 1), (2, 4, 3))
    del tmp10
    tmp17 = np.copy(ints.tmp136) * 2
    tmp17 += np.transpose(ints.tmp97, (1, 0))
    tmp17 += f.vv * -1
    tmp17 += ints.tmp134 * -1
    tmp17 += ints.tmp93 * -2
    tmp16 = np.copy(f.ov)
    tmp16 += ints.tmp17 * 2
    tmp16 += ints.tmp47 * -1
    tmp17 += einsum(tmp16, (0, 1), t1, (0, 2), (2, 1))
    r2new += einsum(r2, (0, 1, 2), tmp17, (2, 3), (0, 1, 3)) * -1
    del tmp17
    tmp18 = np.copy(f.oo) * 0.5
    tmp18 += np.transpose(ints.tmp0, (1, 0)) * 0.5
    tmp18 += ints.tmp13
    tmp18 += ints.tmp24
    tmp18 += ints.tmp86
    tmp18 += ints.tmp12 * -0.5
    tmp18 += ints.tmp22 * -0.5
    tmp18 += ints.tmp85 * -0.5
    r2new += einsum(r2, (0, 1, 2), tmp18, (0, 3), (3, 1, 2)) * -2
    r2new += einsum(r2, (0, 1, 2), tmp18, (1, 3), (0, 3, 2)) * -2
    del tmp18
    tmp19 = np.copy(np.transpose(t2, (0, 1, 3, 2))) * -0.5
    tmp19 += t2
    tmp20 = einsum(r2, (0, 1, 2), tmp19, (0, 1, 2, 3), (3,))
    del tmp19
    r2new += einsum(tmp20, (0,), v.ovov, (1, 2, 3, 0), (1, 3, 2)) * -2
    del tmp20
    r2new += einsum(tmp15, (0, 1, 2, 3), r1, (0,), (1, 2, 3))
    del tmp15
    r2new += einsum(r1, (0,), tmp16, (1, 2), (1, 0, 2)) * -1
    del tmp16

    return {f"r1new": r1new, f"r2new": r2new}

def hbar_lmatvec_ea_intermediates(f=None, t1=None, t2=None, v=None, **kwargs):
    """
    Code generated by `albert` 0.0.0 on 2024-10-20T10:11:42.301451.

    Parameters
    ----------
    f : array
        Fock matrix.
    t1 : array
        T1 amplitudes.
    t2 : array
        T2 amplitudes.
    v : array
        Electron repulsion integrals.

    Returns
    -------
    tmp1 : array
    tmp10 : array
    tmp103 : array
    tmp106 : array
    tmp107 : array
    tmp109 : array
    tmp11 : array
    tmp110 : array
    tmp111 : array
    tmp112 : array
    tmp113 : array
    tmp14 : array
    tmp16 : array
    tmp17 : array
    tmp19 : array
    tmp2 : array
    tmp24 : array
    tmp27 : array
    tmp29 : array
    tmp3 : array
    tmp31 : array
    tmp34 : array
    tmp37 : array
    tmp4 : array
    tmp40 : array
    tmp43 : array
    tmp46 : array
    tmp48 : array
    tmp51 : array
    tmp53 : array
    tmp55 : array
    tmp56 : array
    tmp57 : array
    tmp59 : array
    tmp62 : array
    tmp69 : array
    tmp70 : array
    tmp73 : array
    tmp76 : array
    tmp79 : array
    tmp80 : array
    tmp83 : array
    tmp84 : array
    tmp87 : array
    tmp88 : array
    tmp90 : array
    tmp92 : array
    tmp95 : array
    tmp96 : array
    tmp97 : array
    tmp98 : array
    """

    tmp1 = einsum(t1, (0, 1), f.oo, (2, 0), (2, 1))
    tmp3 = einsum(f.ov, (0, 1), t2, (2, 0, 1, 3), (2, 3))
    tmp2 = einsum(t1, (0, 1), f.vv, (2, 1), (0, 2))
    tmp19 = einsum(t1, (0, 1), v.oovv, (2, 0, 3, 1), (2, 3))
    tmp24 = einsum(t1, (0, 1), v.vvvv, (2, 3, 4, 1), (0, 2, 3, 4))
    tmp27 = einsum(t2, (0, 1, 2, 3), v.ovov, (0, 4, 1, 2), (3, 4))
    tmp31 = einsum(v.ooov, (0, 1, 2, 3), t2, (1, 2, 3, 4), (0, 4))
    tmp40 = einsum(v.ovvv, (0, 1, 2, 3), t2, (4, 0, 3, 1), (4, 2))
    tmp4 = einsum(t2, (0, 1, 2, 3), f.ov, (1, 3), (0, 2))
    tmp29 = einsum(t2, (0, 1, 2, 3), v.ovov, (0, 4, 1, 3), (2, 4))
    tmp34 = einsum(t2, (0, 1, 2, 3), v.ooov, (4, 0, 1, 3), (4, 2))
    tmp37 = einsum(t2, (0, 1, 2, 3), v.ooov, (4, 0, 1, 5), (4, 2, 3, 5))
    tmp43 = einsum(t2, (0, 1, 2, 3), v.ovvv, (1, 2, 4, 3), (0, 4))
    tmp46 = einsum(t2, (0, 1, 2, 3), v.ovvv, (1, 2, 4, 5), (0, 3, 4, 5))
    tmp48 = einsum(t2, (0, 1, 2, 3), v.ovvv, (1, 3, 4, 5), (0, 2, 4, 5))
    tmp51 = einsum(t2, (0, 1, 2, 3), v.ovvv, (1, 4, 5, 2), (0, 3, 4, 5))
    tmp53 = einsum(t2, (0, 1, 2, 3), v.ovvv, (1, 4, 5, 3), (0, 2, 4, 5))
    tmp87 = einsum(t2, (0, 1, 2, 3), v.ovov, (4, 5, 1, 2), (0, 4, 3, 5))
    tmp88 = einsum(t2, (0, 1, 2, 3), v.ovov, (4, 5, 1, 3), (0, 4, 2, 5))
    tmp90 = einsum(v.ovov, (0, 1, 2, 3), t2, (4, 2, 1, 5), (4, 0, 5, 3))
    tmp92 = einsum(t2, (0, 1, 2, 3), v.ovov, (4, 3, 1, 5), (0, 4, 2, 5))
    tmp107 = einsum(t1, (0, 1), v.ovvv, (2, 1, 3, 4), (0, 2, 3, 4))
    tmp109 = einsum(t1, (0, 1), v.ovvv, (2, 3, 4, 1), (0, 2, 3, 4))
    tmp10 = einsum(f.ov, (0, 1), t1, (2, 1), (0, 2))
    tmp11 = einsum(t1, (0, 1), tmp10, (0, 2), (2, 1))
    tmp95 = einsum(t1, (0, 1), v.ooov, (2, 0, 3, 1), (2, 3))
    tmp96 = einsum(t1, (0, 1), tmp95, (2, 0), (2, 1))
    tmp97 = einsum(v.ooov, (0, 1, 2, 3), t1, (2, 3), (0, 1))
    tmp98 = einsum(t1, (0, 1), tmp97, (2, 0), (2, 1))
    tmp14 = einsum(t1, (0, 1), v.ovvv, (0, 1, 2, 3), (2, 3))
    tmp103 = einsum(tmp14, (0, 1), t1, (2, 1), (2, 0))
    tmp16 = einsum(t1, (0, 1), v.ovvv, (0, 2, 3, 1), (2, 3))
    tmp106 = einsum(t1, (0, 1), tmp16, (1, 2), (0, 2))
    tmp55 = einsum(t1, (0, 1), v.ovov, (2, 1, 0, 3), (2, 3))
    tmp56 = einsum(t2, (0, 1, 2, 3), tmp55, (1, 2), (0, 3))
    tmp57 = einsum(t2, (0, 1, 2, 3), tmp55, (1, 3), (0, 2))
    tmp17 = einsum(v.ovov, (0, 1, 2, 3), t1, (2, 3), (0, 1))
    tmp59 = einsum(t2, (0, 1, 2, 3), tmp17, (1, 2), (0, 3))
    tmp62 = einsum(tmp17, (0, 1), t2, (2, 0, 3, 1), (2, 3))
    tmp69 = einsum(t1, (0, 1), v.ovov, (2, 3, 4, 1), (0, 2, 4, 3))
    tmp70 = einsum(t2, (0, 1, 2, 3), tmp69, (4, 1, 0, 3), (4, 2))
    tmp73 = einsum(t2, (0, 1, 2, 3), tmp69, (4, 0, 1, 3), (4, 2))
    tmp76 = einsum(t2, (0, 1, 2, 3), tmp69, (4, 0, 1, 5), (4, 2, 3, 5))
    tmp79 = einsum(t2, (0, 1, 2, 3), v.ovov, (4, 2, 1, 3), (0, 4))
    tmp80 = einsum(t1, (0, 1), tmp79, (2, 0), (2, 1))
    tmp83 = einsum(v.ovov, (0, 1, 2, 3), t2, (4, 2, 3, 1), (4, 0))
    tmp84 = einsum(t1, (0, 1), tmp83, (2, 0), (2, 1))
    tmp110 = einsum(tmp55, (0, 1), t1, (2, 1), (2, 0))
    tmp111 = einsum(t1, (0, 1), tmp110, (2, 0), (2, 1))
    tmp112 = einsum(tmp17, (0, 1), t1, (2, 1), (2, 0))
    tmp113 = einsum(tmp112, (0, 1), t1, (1, 2), (0, 2))

    return {f"tmp1": tmp1, f"tmp10": tmp10, f"tmp103": tmp103, f"tmp106": tmp106, f"tmp107": tmp107, f"tmp109": tmp109, f"tmp11": tmp11, f"tmp110": tmp110, f"tmp111": tmp111, f"tmp112": tmp112, f"tmp113": tmp113, f"tmp14": tmp14, f"tmp16": tmp16, f"tmp17": tmp17, f"tmp19": tmp19, f"tmp2": tmp2, f"tmp24": tmp24, f"tmp27": tmp27, f"tmp29": tmp29, f"tmp3": tmp3, f"tmp31": tmp31, f"tmp34": tmp34, f"tmp37": tmp37, f"tmp4": tmp4, f"tmp40": tmp40, f"tmp43": tmp43, f"tmp46": tmp46, f"tmp48": tmp48, f"tmp51": tmp51, f"tmp53": tmp53, f"tmp55": tmp55, f"tmp56": tmp56, f"tmp57": tmp57, f"tmp59": tmp59, f"tmp62": tmp62, f"tmp69": tmp69, f"tmp70": tmp70, f"tmp73": tmp73, f"tmp76": tmp76, f"tmp79": tmp79, f"tmp80": tmp80, f"tmp83": tmp83, f"tmp84": tmp84, f"tmp87": tmp87, f"tmp88": tmp88, f"tmp90": tmp90, f"tmp92": tmp92, f"tmp95": tmp95, f"tmp96": tmp96, f"tmp97": tmp97, f"tmp98": tmp98}

def hbar_lmatvec_ea(f=None, r1=None, r2=None, t1=None, t2=None, v=None, **kwargs):
    """
    Code generated by `albert` 0.0.0 on 2024-10-20T10:11:43.116339.

    Parameters
    ----------
    f : array
        Fock matrix.
    r1 : array
        R1 amplitudes.
    r2 : array
        R2 amplitudes.
    t1 : array
        T1 amplitudes.
    t2 : array
        T2 amplitudes.
    v : array
        Electron repulsion integrals.

    Returns
    -------
    r1new : array
        Updated R1 residuals.
    r2new : array
        Updated R2 residuals.
    """

    ints = kwargs["ints"]
    tmp0 = np.copy(ints.tmp24)
    tmp0 += np.transpose(ints.tmp46, (0, 2, 1, 3)) * 2
    tmp0 += np.transpose(ints.tmp53, (0, 2, 1, 3)) * 2
    tmp0 += np.transpose(ints.tmp76, (0, 3, 1, 2))
    tmp0 += np.transpose(ints.tmp37, (0, 3, 1, 2)) * -2
    tmp0 += np.transpose(ints.tmp48, (0, 2, 1, 3)) * -4
    tmp0 += np.transpose(ints.tmp51, (0, 2, 1, 3)) * -1
    tmp0 += np.transpose(v.ovvv, (0, 2, 1, 3)) * -2
    tmp0 += np.transpose(v.ovvv, (0, 2, 3, 1))
    r1new = einsum(r2, (0, 1, 2), tmp0, (2, 3, 0, 1), (3,))
    del tmp0
    tmp1 = np.copy(ints.tmp24)
    tmp1 += np.transpose(ints.tmp46, (0, 2, 1, 3)) * 0.5
    tmp1 += np.transpose(ints.tmp53, (0, 2, 1, 3)) * 0.5
    tmp1 += np.transpose(ints.tmp76, (0, 3, 1, 2))
    tmp1 += np.transpose(ints.tmp37, (0, 3, 1, 2)) * -0.5
    tmp1 += np.transpose(ints.tmp48, (0, 2, 1, 3)) * -1
    tmp1 += np.transpose(ints.tmp51, (0, 2, 1, 3)) * -1
    r1new += einsum(r2, (0, 1, 2), tmp1, (2, 3, 1, 0), (3,)) * -2
    del tmp1
    tmp4 = np.copy(ints.tmp107)
    tmp4 += v.oovv
    tmp4 += np.transpose(ints.tmp90, (0, 1, 3, 2)) * -1
    tmp2 = np.copy(np.transpose(r2, (2, 0, 1))) * -0.5
    tmp2 += np.transpose(r2, (2, 1, 0))
    tmp3 = einsum(tmp2, (0, 1, 2), t1, (3, 2), (0, 3, 1))
    r1new += einsum(tmp3, (0, 1, 2), tmp4, (0, 1, 3, 2), (3,)) * 2
    del tmp3, tmp4
    tmp7 = np.copy(ints.tmp109)
    tmp7 += np.transpose(ints.tmp88, (0, 1, 3, 2)) * 2
    tmp7 += np.transpose(v.ovov, (0, 2, 3, 1))
    tmp7 += np.transpose(ints.tmp87, (0, 1, 3, 2)) * -1
    tmp7 += np.transpose(ints.tmp92, (0, 1, 3, 2)) * -1
    tmp5 = np.copy(np.transpose(r2, (2, 0, 1)))
    tmp5 += np.transpose(r2, (2, 1, 0)) * -0.5
    tmp6 = einsum(t1, (0, 1), tmp5, (2, 3, 1), (2, 0, 3)) * 2
    del tmp5
    r1new += einsum(tmp6, (0, 1, 2), tmp7, (0, 1, 3, 2), (3,))
    del tmp6, tmp7
    tmp9 = np.copy(np.transpose(r2, (2, 0, 1))) * -1
    tmp9 += np.transpose(r2, (2, 1, 0)) * 2
    tmp8 = np.copy(ints.tmp106)
    tmp8 += ints.tmp113 * 2
    tmp8 += ints.tmp11
    tmp8 += ints.tmp19
    tmp8 += ints.tmp1
    tmp8 += ints.tmp34 * 2
    tmp8 += ints.tmp3
    tmp8 += ints.tmp43
    tmp8 += ints.tmp57 * 2
    tmp8 += ints.tmp59 * 2
    tmp8 += ints.tmp70 * 2
    tmp8 += ints.tmp80 * 2
    tmp8 += ints.tmp98 * 2
    tmp8 += f.ov * -1
    tmp8 += ints.tmp103 * -2
    tmp8 += ints.tmp111 * -1
    tmp8 += ints.tmp17 * -2
    tmp8 += ints.tmp2 * -1
    tmp8 += ints.tmp31 * -1
    tmp8 += ints.tmp40 * -2
    tmp8 += ints.tmp4 * -2
    tmp8 += ints.tmp56 * -1
    tmp8 += ints.tmp62 * -4
    tmp8 += ints.tmp73 * -1
    tmp8 += ints.tmp84 * -1
    tmp8 += ints.tmp96 * -1
    r1new += einsum(tmp9, (0, 1, 2), tmp8, (0, 2), (1,))
    del tmp9, tmp8
    tmp10 = einsum(r2, (0, 1, 2), t1, (3, 1), (2, 3, 0))
    tmp11 = einsum(t1, (0, 1), tmp10, (2, 3, 1), (2, 0, 3))
    tmp12 = np.copy(tmp11) * -0.5
    tmp12 += np.transpose(tmp11, (0, 2, 1))
    r1new += einsum(tmp12, (0, 1, 2), ints.tmp69, (0, 1, 2, 3), (3,)) * -2
    del tmp12
    tmp13 = np.copy(tmp11) * 2
    tmp13 += np.transpose(tmp11, (0, 2, 1)) * -1
    del tmp11
    r1new += einsum(v.ooov, (0, 1, 2, 3), tmp13, (0, 1, 2), (3,)) * -1
    del tmp13
    tmp14 = np.copy(f.vv)
    tmp14 += np.transpose(ints.tmp14, (1, 0)) * 2
    tmp14 += ints.tmp27
    tmp14 += np.transpose(ints.tmp16, (1, 0)) * -1
    tmp14 += ints.tmp29 * -2
    r1new += einsum(tmp14, (0, 1), r1, (0,), (1,))
    del tmp14
    tmp15 = einsum(r1, (0,), t1, (1, 0), (1,))
    tmp17 = np.copy(tmp15)
    tmp16 = np.copy(np.transpose(t2, (0, 1, 3, 2))) * -1
    tmp16 += t2 * 2
    tmp17 += einsum(r2, (0, 1, 2), tmp16, (2, 3, 0, 1), (3,)) * -1
    tmp18 = np.copy(f.ov)
    tmp18 += ints.tmp17 * 2
    tmp18 += ints.tmp55 * -1
    r1new += einsum(tmp18, (0, 1), tmp17, (0,), (1,)) * -1
    del tmp17
    r2new = einsum(r1, (0,), v.ovvv, (1, 2, 3, 0), (2, 3, 1)) * -1
    tmp19 = einsum(r2, (0, 1, 2), t1, (3, 0), (2, 3, 1))
    r2new += einsum(v.ovvv, (0, 1, 2, 3), tmp19, (4, 0, 3), (1, 2, 4)) * -1
    del tmp19
    r2new += einsum(v.ovvv, (0, 1, 2, 3), tmp10, (4, 0, 3), (2, 1, 4)) * -1
    del tmp10
    r2new += einsum(r2, (0, 1, 2), v.vvvv, (3, 0, 4, 1), (3, 4, 2))
    tmp21 = np.copy(np.transpose(ints.tmp87, (0, 1, 3, 2)))
    tmp21 += np.transpose(ints.tmp92, (0, 1, 3, 2))
    tmp21 += ints.tmp109 * -1
    tmp21 += np.transpose(ints.tmp88, (0, 1, 3, 2)) * -2
    tmp21 += np.transpose(v.ovov, (0, 2, 3, 1)) * -1
    tmp20 = np.copy(ints.tmp69)
    tmp20 += np.transpose(v.ooov, (0, 2, 1, 3))
    tmp21 += einsum(tmp20, (0, 1, 2, 3), t1, (2, 4), (0, 1, 3, 4))
    r2new += einsum(tmp21, (0, 1, 2, 3), tmp2, (0, 4, 3), (2, 4, 1)) * -2
    del tmp2, tmp21
    tmp23 = np.copy(np.transpose(ints.tmp90, (0, 1, 3, 2)))
    tmp23 += ints.tmp107 * -1
    tmp23 += v.oovv * -1
    tmp22 = einsum(t1, (0, 1), tmp20, (2, 0, 3, 4), (2, 3, 1, 4))
    del tmp20
    tmp23 += np.transpose(tmp22, (0, 1, 3, 2))
    del tmp22
    r2new += einsum(r2, (0, 1, 2), tmp23, (2, 3, 4, 1), (0, 4, 3))
    r2new += einsum(tmp23, (0, 1, 2, 3), r2, (3, 4, 0), (2, 4, 1))
    del tmp23
    tmp24 = np.copy(t2)
    tmp24 += einsum(t1, (0, 1), t1, (2, 3), (2, 0, 3, 1))
    tmp25 = einsum(r2, (0, 1, 2), tmp24, (3, 4, 1, 0), (2, 4, 3))
    del tmp24
    r2new += einsum(v.ovov, (0, 1, 2, 3), tmp25, (4, 2, 0), (3, 1, 4))
    del tmp25
    tmp27 = np.copy(np.transpose(ints.tmp16, (1, 0)))
    tmp27 += ints.tmp29 * 2
    tmp27 += f.vv * -1
    tmp27 += ints.tmp14 * -2
    tmp27 += ints.tmp27 * -1
    tmp26 = einsum(tmp18, (0, 1), t1, (0, 2), (2, 1))
    tmp27 += tmp26
    del tmp26
    r2new += einsum(r2, (0, 1, 2), tmp27, (0, 3), (3, 1, 2)) * -1
    r2new += einsum(tmp27, (0, 1), r2, (2, 0, 3), (2, 1, 3)) * -1
    del tmp27
    tmp28 = np.copy(f.oo)
    tmp28 += np.transpose(ints.tmp10, (1, 0))
    tmp28 += ints.tmp112 * 2
    tmp28 += ints.tmp79 * 2
    tmp28 += ints.tmp97 * 2
    tmp28 += ints.tmp110 * -1
    tmp28 += ints.tmp83 * -1
    tmp28 += ints.tmp95 * -1
    r2new += einsum(r2, (0, 1, 2), tmp28, (2, 3), (0, 1, 3)) * -1
    del tmp28
    tmp29 = np.copy(tmp15) * 0.5
    del tmp15
    tmp29 += einsum(r2, (0, 1, 2), tmp16, (2, 3, 0, 1), (3,)) * -0.5
    del tmp16
    r2new += einsum(v.ovov, (0, 1, 2, 3), tmp29, (2,), (1, 3, 0)) * 2
    del tmp29
    r2new += einsum(tmp18, (0, 1), r1, (2,), (1, 2, 0)) * -1
    del tmp18

    return {f"r1new": r1new, f"r2new": r2new}

