"""
Code generated by `albert`:
https://github.com/obackhouse/albert

  * date: 2024-09-28T14:09:42.957905
  * python version: 3.10.15 (main, Sep  9 2024, 03:02:45) [GCC 11.4.0]
  * albert version: 0.0.0
  * caller: /opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/site-packages/albert/codegen/einsum.py
  * node: fv-az1272-977
  * system: Linux
  * processor: x86_64
  * release: 6.8.0-1014-azure
"""

from ebcc import numpy as np
from ebcc.util import pack_2e, einsum, dirsum, Namespace


def energy(f=None, t1=None, t2=None, v=None, **kwargs):
    """
    Code generated by `albert` 0.0.0 on 2024-09-28T14:09:44.225570.

    Parameters
    ----------
    f : Namespace of arrays
        Fock matrix.
    t1 : Namespace of arrays
        T1 amplitudes.
    t2 : Namespace of arrays
        T2 amplitudes.
    v : Namespace of arrays
        Electron repulsion integrals.

    Returns
    -------
    e_cc : float
        Coupled cluster energy.
    """

    tmp2 = np.copy(np.transpose(v.bbbb.ovov, (0, 2, 3, 1))) * -1
    tmp2 += np.transpose(v.bbbb.ovov, (0, 2, 1, 3))
    tmp0 = np.copy(np.transpose(v.aaaa.ovov, (0, 2, 3, 1)))
    tmp0 += np.transpose(v.aaaa.ovov, (0, 2, 1, 3)) * -1
    tmp3 = np.copy(f.bb.ov) * 2
    tmp3 += einsum(t1.bb, (0, 1), tmp2, (0, 2, 3, 1), (2, 3)) * -1
    del tmp2
    tmp1 = np.copy(f.aa.ov)
    tmp1 += einsum(t1.bb, (0, 1), v.aabb.ovov, (2, 3, 0, 1), (2, 3))
    tmp1 += einsum(tmp0, (0, 1, 2, 3), t1.aa, (0, 2), (1, 3)) * -0.5
    del tmp0
    e_cc = einsum(t2.abab, (0, 1, 2, 3), v.aabb.ovov, (0, 2, 1, 3), ())
    e_cc += einsum(t2.bbbb, (0, 1, 2, 3), v.bbbb.ovov, (0, 2, 1, 3), ())
    e_cc += einsum(t2.aaaa, (0, 1, 2, 3), v.aaaa.ovov, (0, 3, 1, 2), ()) * -1
    e_cc += einsum(t1.aa, (0, 1), tmp1, (0, 1), ())
    del tmp1
    e_cc += einsum(t1.bb, (0, 1), tmp3, (0, 1), ()) * 0.5
    del tmp3

    return e_cc

def update_amps(f=None, t1=None, t2=None, v=None, **kwargs):
    """
    Code generated by `albert` 0.0.0 on 2024-09-28T14:10:39.673112.

    Parameters
    ----------
    f : Namespace of arrays
        Fock matrix.
    t1 : Namespace of arrays
        T1 amplitudes.
    t2 : Namespace of arrays
        T2 amplitudes.
    v : Namespace of arrays
        Electron repulsion integrals.

    Returns
    -------
    t1new : Namespace of arrays
        Updated T1 residuals.
    t2new : Namespace of arrays
        Updated T2 residuals.
    """

    t1new = Namespace()
    t2new = Namespace()
    tmp13 = np.copy(np.transpose(v.bbbb.ovov, (0, 2, 3, 1))) * -1
    tmp13 += np.transpose(v.bbbb.ovov, (0, 2, 1, 3))
    tmp7 = np.copy(np.transpose(v.aaaa.ovov, (0, 2, 3, 1)))
    tmp7 += np.transpose(v.aaaa.ovov, (0, 2, 1, 3)) * -1
    tmp21 = einsum(v.bbbb.ovov, (0, 1, 2, 3), t1.bb, (4, 3), (4, 0, 2, 1))
    tmp158 = np.copy(np.transpose(v.bbbb.ovov, (0, 2, 3, 1))) * -1
    tmp158 += np.transpose(v.bbbb.ovov, (0, 2, 1, 3))
    tmp12 = einsum(v.aabb.ovov, (0, 1, 2, 3), t1.aa, (0, 1), (2, 3))
    tmp14 = einsum(t1.bb, (0, 1), tmp13, (0, 2, 3, 1), (2, 3))
    del tmp13
    tmp54 = np.copy(np.transpose(v.aaaa.ovov, (0, 2, 3, 1)))
    tmp54 += np.transpose(v.aaaa.ovov, (0, 2, 1, 3)) * -1
    tmp2 = einsum(t1.bb, (0, 1), v.aabb.ovov, (2, 3, 0, 1), (2, 3))
    tmp8 = einsum(tmp7, (0, 1, 2, 3), t1.aa, (0, 2), (1, 3))
    del tmp7
    tmp1 = einsum(v.aaaa.ovov, (0, 1, 2, 3), t1.aa, (4, 3), (4, 0, 2, 1))
    tmp177 = np.copy(v.bbbb.ooov) * -1
    tmp177 += np.transpose(v.bbbb.ovoo, (0, 2, 3, 1))
    tmp28 = np.copy(v.bbbb.ooov) * -1
    tmp28 += np.transpose(v.bbbb.ooov, (0, 2, 1, 3))
    tmp139 = np.copy(tmp21)
    tmp139 += np.transpose(tmp21, (0, 2, 1, 3)) * -1
    tmp170 = np.copy(v.bbbb.ovvv) * -1
    tmp170 += np.transpose(v.bbbb.ovvv, (0, 2, 1, 3))
    tmp20 = einsum(v.aabb.ovov, (0, 1, 2, 3), t1.bb, (4, 3), (0, 4, 2, 1))
    tmp159 = einsum(t1.bb, (0, 1), tmp158, (0, 2, 3, 1), (2, 3))
    del tmp158
    tmp15 = np.copy(f.bb.ov)
    tmp15 += tmp12
    tmp15 += tmp14 * -1
    del tmp14
    tmp107 = np.copy(v.bbbb.ovvv)
    tmp107 += np.transpose(v.bbbb.ovvv, (0, 2, 3, 1)) * -1
    tmp17 = np.copy(v.aaaa.ooov)
    tmp17 += np.transpose(v.aaaa.ovoo, (0, 2, 3, 1)) * -1
    tmp55 = einsum(tmp54, (0, 1, 2, 3), t1.aa, (0, 2), (1, 3))
    del tmp54
    tmp0 = einsum(v.aabb.ovov, (0, 1, 2, 3), t1.aa, (4, 1), (4, 0, 2, 3))
    tmp42 = np.copy(v.aaaa.ovvv)
    tmp42 += np.transpose(v.aaaa.ovvv, (0, 2, 3, 1)) * -1
    tmp9 = np.copy(f.aa.ov)
    tmp9 += tmp2
    tmp9 += tmp8 * -1
    del tmp8
    tmp70 = np.copy(tmp1)
    tmp70 += np.transpose(tmp1, (0, 2, 1, 3)) * -1
    tmp68 = np.copy(v.aaaa.ovvv)
    tmp68 += np.transpose(v.aaaa.ovvv, (0, 2, 1, 3)) * -1
    tmp78 = np.copy(v.aaaa.ooov) * -1
    tmp78 += np.transpose(v.aaaa.ovoo, (0, 2, 3, 1))
    tmp119 = einsum(t1.bb, (0, 1), v.aabb.ovoo, (2, 3, 4, 0), (2, 4, 3, 1))
    tmp103 = einsum(t2.abab, (0, 1, 2, 3), v.aaaa.ovov, (4, 5, 0, 2), (4, 1, 5, 3))
    tmp178 = einsum(t1.bb, (0, 1), tmp177, (2, 3, 0, 4), (2, 3, 1, 4))
    del tmp177
    tmp129 = einsum(t2.bbbb, (0, 1, 2, 3), v.bbbb.ovov, (4, 5, 1, 3), (0, 4, 2, 5))
    tmp163 = einsum(t1.bb, (0, 1), v.bbbb.ovvv, (2, 3, 4, 1), (0, 2, 3, 4))
    tmp183 = einsum(tmp21, (0, 1, 2, 3), t1.bb, (4, 3), (0, 4, 2, 1))
    tmp23 = einsum(v.aabb.ovov, (0, 1, 2, 3), t2.abab, (0, 4, 1, 3), (4, 2))
    tmp24 = einsum(v.bbbb.ovov, (0, 1, 2, 3), t2.bbbb, (4, 2, 1, 3), (4, 0))
    tmp27 = einsum(v.aabb.ovoo, (0, 1, 2, 3), t1.aa, (0, 1), (2, 3))
    tmp29 = einsum(t1.bb, (0, 1), tmp28, (2, 3, 0, 1), (2, 3))
    del tmp28
    tmp140 = einsum(t1.bb, (0, 1), tmp139, (2, 0, 3, 4), (2, 3, 1, 4))
    del tmp139
    tmp171 = einsum(t1.bb, (0, 1), tmp170, (2, 1, 3, 4), (0, 2, 3, 4))
    del tmp170
    tmp115 = einsum(t1.bb, (0, 1), tmp20, (2, 3, 0, 4), (2, 3, 4, 1))
    tmp116 = einsum(v.aabb.ovvv, (0, 1, 2, 3), t1.bb, (4, 3), (0, 4, 1, 2))
    tmp160 = np.copy(f.bb.ov)
    tmp160 += tmp12
    tmp160 += tmp159 * -1
    del tmp159
    tmp152 = einsum(v.bbbb.ooov, (0, 1, 2, 3), t1.bb, (4, 3), (4, 0, 1, 2))
    tmp106 = einsum(t2.bbbb, (0, 1, 2, 3), v.bbbb.ovov, (0, 4, 1, 3), (2, 4))
    tmp109 = einsum(tmp15, (0, 1), t1.bb, (0, 2), (2, 1))
    tmp104 = einsum(v.aabb.ovvv, (0, 1, 2, 3), t1.aa, (0, 1), (2, 3))
    tmp105 = einsum(t2.abab, (0, 1, 2, 3), v.aabb.ovov, (0, 2, 1, 4), (3, 4))
    tmp108 = einsum(tmp107, (0, 1, 2, 3), t1.bb, (0, 1), (2, 3))
    del tmp107
    tmp16 = einsum(t1.bb, (0, 1), v.aabb.ooov, (2, 3, 0, 1), (2, 3))
    tmp31 = einsum(tmp17, (0, 1, 2, 3), t1.aa, (0, 3), (1, 2)) * 2
    tmp5 = einsum(v.aaaa.ovov, (0, 1, 2, 3), t2.aaaa, (4, 2, 1, 3), (4, 0))
    tmp6 = einsum(v.aabb.ovov, (0, 1, 2, 3), t2.abab, (4, 2, 1, 3), (4, 0))
    tmp49 = einsum(v.aaaa.ooov, (0, 1, 2, 3), t1.aa, (4, 3), (4, 0, 1, 2))
    tmp56 = np.copy(f.aa.ov)
    tmp56 += tmp2
    tmp56 += tmp55 * -1
    del tmp55
    tmp65 = einsum(t1.aa, (0, 1), tmp0, (2, 0, 3, 4), (2, 3, 1, 4))
    tmp64 = einsum(t1.aa, (0, 1), v.aabb.vvov, (2, 1, 3, 4), (0, 3, 2, 4))
    tmp88 = einsum(t1.aa, (0, 1), tmp1, (2, 3, 4, 1), (2, 0, 4, 3))
    tmp82 = einsum(t1.aa, (0, 1), v.aabb.ooov, (2, 0, 3, 4), (2, 3, 1, 4))
    tmp83 = einsum(t2.abab, (0, 1, 2, 3), v.bbbb.ovov, (4, 5, 1, 3), (0, 4, 2, 5))
    tmp59 = einsum(t1.aa, (0, 1), v.aaaa.ovvv, (2, 3, 4, 1), (0, 2, 3, 4))
    tmp40 = einsum(t2.aaaa, (0, 1, 2, 3), v.aaaa.ovov, (0, 4, 1, 3), (2, 4))
    tmp43 = einsum(tmp42, (0, 1, 2, 3), t1.aa, (0, 1), (2, 3))
    del tmp42
    tmp41 = einsum(v.aabb.ovov, (0, 1, 2, 3), t2.abab, (0, 2, 4, 3), (4, 1))
    tmp44 = einsum(tmp9, (0, 1), t1.aa, (0, 2), (2, 1))
    tmp39 = einsum(t1.bb, (0, 1), v.aabb.vvov, (2, 3, 0, 1), (2, 3))
    tmp71 = einsum(t1.aa, (0, 1), tmp70, (2, 0, 3, 4), (2, 3, 1, 4))
    del tmp70
    tmp69 = einsum(t1.aa, (0, 1), tmp68, (2, 3, 1, 4), (0, 2, 3, 4))
    del tmp68
    tmp79 = einsum(tmp78, (0, 1, 2, 3), t1.aa, (2, 4), (0, 1, 4, 3))
    tmp37 = einsum(t2.aaaa, (0, 1, 2, 3), v.aaaa.ovov, (4, 5, 1, 3), (0, 4, 2, 5))
    tmp185 = einsum(v.bbbb.vvvv, (0, 1, 2, 3), t1.bb, (4, 3), (4, 0, 1, 2))
    tmp181 = np.copy(tmp119) * 2
    tmp181 += tmp103 * -1
    tmp179 = np.copy(v.bbbb.oovv) * -1
    tmp179 += tmp129
    tmp179 += np.transpose(tmp178, (1, 0, 2, 3)) * -1
    del tmp178
    tmp148 = einsum(v.bbbb.oooo, (0, 1, 2, 3), t1.bb, (3, 4), (0, 1, 2, 4))
    tmp187 = einsum(tmp163, (0, 1, 2, 3), t1.bb, (4, 2), (4, 0, 1, 3))
    tmp191 = np.copy(v.bbbb.ovvv)
    tmp191 += einsum(t1.bb, (0, 1), v.bbbb.ovov, (2, 3, 0, 4), (2, 4, 3, 1))
    tmp189 = einsum(tmp183, (0, 1, 2, 3), t1.bb, (2, 4), (1, 0, 3, 4))
    tmp99 = np.copy(f.bb.oo)
    tmp99 += np.transpose(tmp27, (1, 0))
    tmp99 += np.transpose(tmp23, (1, 0)) * 0.5
    tmp99 += np.transpose(tmp24, (1, 0))
    tmp99 += np.transpose(tmp29, (1, 0)) * -1
    tmp154 = einsum(v.bbbb.oovv, (0, 1, 2, 3), t1.bb, (4, 3), (4, 0, 1, 2))
    tmp172 = np.copy(np.transpose(tmp171, (0, 1, 3, 2))) * -1
    del tmp171
    tmp172 += tmp140 * -1
    tmp166 = np.copy(tmp21)
    tmp166 += np.transpose(tmp21, (0, 2, 1, 3)) * -1
    tmp165 = np.copy(v.bbbb.ovvv) * -1
    tmp165 += np.transpose(v.bbbb.ovvv, (0, 2, 1, 3))
    tmp168 = np.copy(tmp116) * -1
    tmp168 += tmp115
    tmp161 = einsum(tmp160, (0, 1), t1.bb, (2, 1), (2, 0))
    del tmp160
    tmp156 = einsum(t1.bb, (0, 1), tmp152, (2, 3, 4, 0), (2, 4, 3, 1))
    tmp102 = einsum(t2.bbbb, (0, 1, 2, 3), v.aabb.ovov, (4, 5, 1, 3), (4, 0, 5, 2))
    tmp110 = np.copy(f.bb.vv) * -1
    tmp110 += np.transpose(tmp104, (1, 0)) * -1
    del tmp104
    tmp110 += np.transpose(tmp105, (1, 0)) * 0.5
    del tmp105
    tmp110 += np.transpose(tmp106, (1, 0))
    del tmp106
    tmp110 += np.transpose(tmp108, (1, 0)) * -1
    del tmp108
    tmp110 += np.transpose(tmp109, (1, 0))
    del tmp109
    tmp142 = np.copy(tmp116)
    tmp142 += tmp115 * -1
    tmp117 = einsum(t1.bb, (0, 1), v.aabb.vvov, (2, 3, 4, 1), (0, 4, 2, 3))
    tmp138 = np.copy(v.bbbb.ovvv)
    tmp138 += np.transpose(v.bbbb.ovvv, (0, 2, 3, 1)) * -1
    tmp18 = einsum(tmp17, (0, 1, 2, 3), t1.aa, (0, 3), (1, 2))
    del tmp17
    tmp38 = einsum(t2.abab, (0, 1, 2, 3), v.aabb.ovov, (4, 5, 1, 3), (0, 4, 2, 5))
    tmp130 = np.copy(v.bbbb.ooov)
    tmp130 += np.transpose(v.bbbb.ooov, (0, 2, 1, 3)) * -1
    tmp128 = einsum(v.aabb.ovov, (0, 1, 2, 3), t2.abab, (0, 4, 1, 5), (4, 2, 5, 3))
    tmp126 = einsum(t2.aaaa, (0, 1, 2, 3), v.aabb.ovov, (1, 3, 4, 5), (0, 4, 2, 5))
    tmp133 = np.copy(np.transpose(v.aabb.vvov, (2, 0, 1, 3)))
    tmp133 += einsum(v.aabb.ovov, (0, 1, 2, 3), t1.aa, (0, 4), (2, 4, 1, 3)) * -1
    tmp136 = np.copy(tmp1) * -1
    tmp136 += np.transpose(tmp1, (0, 2, 1, 3))
    tmp135 = np.copy(v.aaaa.ovvv) * -1
    tmp135 += np.transpose(v.aaaa.ovvv, (0, 2, 1, 3))
    tmp32 = np.copy(f.aa.oo) * 2
    tmp32 += np.transpose(tmp16, (1, 0)) * 2
    tmp32 += np.transpose(tmp5, (1, 0)) * 2
    tmp32 += np.transpose(tmp6, (1, 0))
    tmp32 += np.transpose(tmp31, (1, 0)) * -1
    del tmp31
    tmp94 = einsum(t1.aa, (0, 1), v.aaaa.vvvv, (2, 3, 4, 1), (0, 2, 3, 4))
    tmp51 = einsum(tmp49, (0, 1, 2, 3), t1.aa, (3, 4), (0, 2, 1, 4))
    tmp57 = einsum(tmp56, (0, 1), t1.aa, (2, 1), (2, 0))
    del tmp56
    tmp74 = np.copy(tmp64)
    tmp74 += tmp65 * -1
    tmp90 = einsum(tmp88, (0, 1, 2, 3), t1.aa, (2, 4), (1, 0, 3, 4))
    tmp84 = np.copy(tmp82) * 2
    tmp84 += tmp83 * -1
    tmp96 = np.copy(v.aaaa.ovvv)
    tmp96 += einsum(v.aaaa.ovov, (0, 1, 2, 3), t1.aa, (2, 4), (0, 3, 1, 4))
    tmp92 = einsum(tmp59, (0, 1, 2, 3), t1.aa, (4, 2), (4, 0, 1, 3))
    tmp86 = np.copy(tmp82)
    tmp86 += tmp83 * -0.5
    tmp47 = einsum(v.aaaa.oovv, (0, 1, 2, 3), t1.aa, (4, 3), (4, 0, 1, 2))
    tmp45 = np.copy(f.aa.vv) * -1
    tmp45 += np.transpose(tmp39, (1, 0)) * -1
    del tmp39
    tmp45 += np.transpose(tmp40, (1, 0))
    del tmp40
    tmp45 += np.transpose(tmp41, (1, 0)) * 0.5
    del tmp41
    tmp45 += np.transpose(tmp43, (1, 0)) * -1
    del tmp43
    tmp45 += np.transpose(tmp44, (1, 0))
    del tmp44
    tmp66 = np.copy(tmp64) * -1
    del tmp64
    tmp66 += tmp65
    tmp72 = np.copy(np.transpose(tmp69, (0, 1, 3, 2))) * -1
    del tmp69
    tmp72 += tmp71 * -1
    del tmp71
    tmp80 = np.copy(v.aaaa.oovv) * -1
    tmp80 += tmp37
    tmp80 += np.transpose(tmp79, (1, 0, 2, 3)) * -1
    del tmp79
    tmp61 = np.copy(v.aaaa.ovvv)
    tmp61 += np.transpose(v.aaaa.ovvv, (0, 2, 1, 3)) * -1
    tmp62 = np.copy(tmp1)
    tmp62 += np.transpose(tmp1, (0, 2, 1, 3)) * -1
    tmp186 = einsum(tmp185, (0, 1, 2, 3), t1.bb, (4, 2), (4, 0, 1, 3))
    del tmp185
    tmp182 = einsum(t2.abab, (0, 1, 2, 3), tmp181, (0, 4, 2, 5), (1, 4, 3, 5)) * 0.5
    del tmp181
    tmp180 = einsum(t2.bbbb, (0, 1, 2, 3), tmp179, (4, 1, 5, 3), (0, 4, 2, 5)) * 2
    del tmp179
    tmp149 = einsum(t1.bb, (0, 1), tmp148, (2, 0, 3, 4), (2, 3, 1, 4))
    del tmp148
    tmp193 = einsum(t2.bbbb, (0, 1, 2, 3), v.bbbb.ovvv, (4, 3, 5, 2), (0, 1, 4, 5)) * -1
    tmp175 = einsum(t1.bb, (0, 1), v.bbbb.ooov, (2, 0, 3, 4), (2, 3, 1, 4))
    tmp153 = einsum(tmp152, (0, 1, 2, 3), t2.bbbb, (2, 3, 4, 5), (0, 1, 4, 5))
    del tmp152
    tmp188 = einsum(t1.bb, (0, 1), tmp187, (2, 3, 0, 4), (2, 3, 1, 4))
    del tmp187
    tmp192 = np.copy(v.bbbb.vvvv) * -1
    tmp192 += einsum(tmp191, (0, 1, 2, 3), t1.bb, (0, 4), (1, 4, 3, 2))
    del tmp191
    tmp190 = einsum(t1.bb, (0, 1), tmp189, (2, 3, 0, 4), (2, 3, 1, 4))
    del tmp189
    tmp150 = einsum(tmp99, (0, 1), t2.bbbb, (2, 0, 3, 4), (2, 1, 3, 4)) * -1
    tmp147 = einsum(v.bbbb.oooo, (0, 1, 2, 3), t2.bbbb, (1, 3, 4, 5), (0, 2, 4, 5))
    tmp155 = einsum(tmp154, (0, 1, 2, 3), t1.bb, (2, 4), (0, 1, 4, 3))
    del tmp154
    tmp173 = einsum(tmp172, (0, 1, 2, 3), t2.bbbb, (4, 1, 5, 3), (4, 0, 5, 2))
    del tmp172
    tmp167 = einsum(t1.bb, (0, 1), tmp165, (2, 1, 3, 4), (0, 2, 4, 3)) * -1
    del tmp165
    tmp167 += einsum(tmp166, (0, 1, 2, 3), t1.bb, (1, 4), (0, 2, 4, 3)) * -1
    del tmp166
    tmp164 = einsum(t1.bb, (0, 1), tmp21, (2, 3, 0, 4), (2, 3, 1, 4))
    tmp169 = einsum(tmp168, (0, 1, 2, 3), t2.abab, (0, 4, 2, 5), (4, 1, 5, 3))
    del tmp168
    tmp162 = einsum(t2.bbbb, (0, 1, 2, 3), tmp161, (4, 1), (0, 4, 2, 3)) * -1
    del tmp161
    tmp157 = einsum(tmp156, (0, 1, 2, 3), t1.bb, (1, 4), (0, 2, 4, 3))
    del tmp156
    tmp176 = einsum(tmp102, (0, 1, 2, 3), t2.abab, (0, 4, 2, 5), (4, 1, 5, 3))
    tmp151 = einsum(t2.bbbb, (0, 1, 2, 3), tmp110, (3, 4), (0, 1, 2, 4)) * -2
    tmp184 = einsum(tmp183, (0, 1, 2, 3), t2.bbbb, (3, 2, 4, 5), (1, 0, 4, 5))
    del tmp183
    tmp111 = einsum(t1.bb, (0, 1), tmp15, (2, 1), (0, 2))
    tmp174 = einsum(t2.abab, (0, 1, 2, 3), tmp142, (0, 4, 2, 5), (1, 4, 3, 5))
    tmp3 = np.copy(t2.abab)
    tmp3 += einsum(t1.bb, (0, 1), t1.aa, (2, 3), (2, 0, 3, 1))
    tmp122 = einsum(t1.aa, (0, 1), tmp117, (2, 3, 4, 1), (0, 2, 3, 4))
    tmp124 = einsum(t1.aa, (0, 1), tmp20, (2, 3, 4, 1), (0, 2, 3, 4))
    tmp112 = einsum(t1.bb, (0, 1), v.aabb.ooov, (2, 3, 4, 1), (2, 3, 0, 4))
    tmp141 = einsum(tmp138, (0, 1, 2, 3), t1.bb, (4, 1), (4, 0, 3, 2)) * -1
    del tmp138
    tmp141 += np.transpose(tmp140, (0, 1, 3, 2))
    del tmp140
    tmp121 = np.copy(v.aabb.oovv)
    tmp121 += einsum(v.aabb.ooov, (0, 1, 2, 3), t1.bb, (2, 4), (0, 1, 3, 4)) * -1
    tmp101 = np.copy(f.aa.oo)
    tmp101 += np.transpose(tmp16, (1, 0))
    tmp101 += np.transpose(tmp5, (1, 0))
    tmp101 += np.transpose(tmp6, (1, 0)) * 0.5
    tmp101 += np.transpose(tmp18, (1, 0)) * -1
    tmp125 = np.copy(v.aaaa.oovv) * -1
    tmp125 += np.transpose(tmp37, (1, 0, 3, 2))
    tmp125 += np.transpose(tmp38, (1, 0, 3, 2)) * 0.5
    tmp125 += einsum(t1.aa, (0, 1), tmp78, (0, 2, 3, 4), (3, 2, 4, 1))
    del tmp78
    tmp143 = einsum(v.aabb.ovvv, (0, 1, 2, 3), t1.aa, (4, 1), (4, 0, 2, 3))
    tmp143 += einsum(tmp0, (0, 1, 2, 3), t1.bb, (2, 4), (0, 1, 3, 4)) * -1
    tmp131 = np.copy(v.bbbb.oovv) * -1
    tmp131 += np.transpose(tmp128, (1, 0, 3, 2)) * 0.5
    tmp131 += np.transpose(tmp129, (1, 0, 3, 2))
    tmp131 += einsum(tmp130, (0, 1, 2, 3), t1.bb, (2, 4), (1, 0, 3, 4))
    del tmp130
    tmp120 = np.copy(np.transpose(v.aabb.vvoo, (2, 3, 0, 1)))
    tmp120 += einsum(t1.aa, (0, 1), v.aabb.ovoo, (0, 2, 3, 4), (3, 4, 2, 1)) * -1
    tmp127 = np.copy(tmp82) * -1
    tmp127 += tmp126
    tmp127 += tmp83 * 0.5
    tmp100 = np.copy(t2.abab)
    tmp100 += einsum(t1.bb, (0, 1), t1.aa, (2, 3), (2, 0, 3, 1)) * 2
    tmp145 = einsum(v.aabb.oovv, (0, 1, 2, 3), t1.bb, (4, 3), (0, 1, 4, 2))
    tmp134 = np.copy(v.aabb.vvvv)
    tmp134 += einsum(tmp133, (0, 1, 2, 3), t1.bb, (0, 4), (2, 1, 3, 4)) * -1
    del tmp133
    tmp113 = einsum(v.aabb.vvoo, (0, 1, 2, 3), t1.aa, (4, 1), (4, 2, 3, 0))
    tmp144 = einsum(t2.abab, (0, 1, 2, 3), v.aabb.ovvv, (4, 2, 5, 3), (0, 4, 1, 5))
    tmp114 = einsum(v.aabb.ovoo, (0, 1, 2, 3), t1.aa, (4, 1), (4, 0, 2, 3))
    tmp123 = np.copy(np.transpose(v.aabb.vvov, (2, 0, 1, 3)))
    tmp123 += einsum(v.aabb.vvvv, (0, 1, 2, 3), t1.bb, (4, 3), (4, 0, 1, 2))
    tmp137 = einsum(t1.aa, (0, 1), tmp135, (2, 3, 1, 4), (0, 2, 3, 4)) * -1
    del tmp135
    tmp137 += einsum(t1.aa, (0, 1), tmp136, (2, 3, 0, 4), (2, 3, 4, 1))
    del tmp136
    tmp132 = np.copy(tmp119) * -1
    tmp132 += tmp103 * 0.5
    tmp132 += tmp102
    tmp146 = einsum(t1.aa, (0, 1), tmp116, (2, 3, 1, 4), (0, 2, 3, 4))
    tmp118 = np.copy(np.transpose(tmp117, (0, 1, 3, 2)))
    del tmp117
    tmp118 += einsum(tmp20, (0, 1, 2, 3), t1.aa, (0, 4), (1, 2, 3, 4)) * -1
    tmp33 = einsum(tmp32, (0, 1), t2.aaaa, (2, 0, 3, 4), (2, 1, 3, 4)) * -0.5
    del tmp32
    tmp95 = einsum(t1.aa, (0, 1), tmp94, (2, 3, 1, 4), (0, 2, 3, 4))
    del tmp94
    tmp53 = einsum(tmp9, (0, 1), t1.aa, (2, 1), (2, 0))
    tmp36 = einsum(t1.aa, (0, 1), t1.aa, (2, 3), (2, 0, 1, 3)) * 2
    tmp36 += t2.aaaa * -1
    tmp52 = einsum(tmp51, (0, 1, 2, 3), t1.aa, (1, 4), (0, 2, 4, 3))
    del tmp51
    tmp89 = einsum(t2.aaaa, (0, 1, 2, 3), tmp88, (4, 5, 0, 1), (5, 4, 2, 3)) * -1
    del tmp88
    tmp58 = einsum(t2.aaaa, (0, 1, 2, 3), tmp57, (4, 1), (0, 4, 2, 3)) * -1
    tmp75 = einsum(tmp74, (0, 1, 2, 3), t2.abab, (4, 1, 5, 3), (4, 0, 5, 2))
    tmp34 = np.copy(t2.aaaa)
    tmp34 += einsum(t1.aa, (0, 1), t1.aa, (2, 3), (2, 0, 3, 1)) * 2
    tmp91 = einsum(t1.aa, (0, 1), tmp90, (2, 3, 0, 4), (2, 3, 1, 4))
    del tmp90
    tmp85 = einsum(t2.abab, (0, 1, 2, 3), tmp84, (4, 1, 5, 3), (0, 4, 2, 5)) * 0.5
    del tmp84
    tmp35 = einsum(v.aaaa.oooo, (0, 1, 2, 3), t2.aaaa, (3, 1, 4, 5), (0, 2, 4, 5)) * -1
    tmp60 = einsum(tmp1, (0, 1, 2, 3), t1.aa, (2, 4), (0, 1, 4, 3))
    tmp97 = np.copy(v.aaaa.vvvv)
    tmp97 += einsum(tmp96, (0, 1, 2, 3), t1.aa, (0, 4), (1, 3, 2, 4))
    del tmp96
    tmp93 = einsum(t1.aa, (0, 1), tmp92, (2, 3, 0, 4), (2, 3, 1, 4))
    del tmp92
    tmp98 = einsum(t2.aaaa, (0, 1, 2, 3), v.aaaa.ovvv, (4, 3, 5, 2), (0, 1, 4, 5)) * -1
    tmp87 = einsum(t2.abab, (0, 1, 2, 3), tmp86, (4, 1, 5, 3), (0, 4, 2, 5))
    del tmp86
    tmp48 = einsum(tmp47, (0, 1, 2, 3), t1.aa, (2, 4), (0, 1, 4, 3))
    del tmp47
    tmp46 = einsum(t2.aaaa, (0, 1, 2, 3), tmp45, (3, 4), (0, 1, 2, 4)) * -2
    tmp50 = einsum(tmp49, (0, 1, 2, 3), t2.aaaa, (3, 2, 4, 5), (0, 1, 4, 5)) * -1
    del tmp49
    tmp67 = einsum(t2.abab, (0, 1, 2, 3), tmp66, (4, 1, 5, 3), (0, 4, 2, 5))
    del tmp66
    tmp73 = einsum(t2.aaaa, (0, 1, 2, 3), tmp72, (4, 1, 5, 3), (0, 4, 2, 5))
    del tmp72
    tmp76 = einsum(t1.aa, (0, 1), v.aaaa.ooov, (2, 0, 3, 4), (2, 3, 1, 4))
    tmp81 = einsum(t2.aaaa, (0, 1, 2, 3), tmp80, (4, 1, 5, 3), (0, 4, 2, 5)) * 2
    del tmp80
    tmp77 = einsum(t2.aaaa, (0, 1, 2, 3), tmp38, (4, 1, 5, 3), (0, 4, 2, 5))
    tmp63 = einsum(t1.aa, (0, 1), tmp61, (2, 3, 1, 4), (0, 2, 4, 3)) * -1
    del tmp61
    tmp63 += einsum(t1.aa, (0, 1), tmp62, (2, 0, 3, 4), (2, 3, 1, 4)) * -1
    del tmp62
    tmp25 = np.copy(np.transpose(tmp23, (1, 0))) * 0.5
    del tmp23
    tmp25 += np.transpose(tmp24, (1, 0))
    del tmp24
    tmp25 += einsum(t1.bb, (0, 1), tmp15, (2, 1), (2, 0)) * 0.5
    tmp22 = np.copy(t2.bbbb) * 2
    tmp22 += einsum(t1.bb, (0, 1), t1.bb, (2, 3), (0, 2, 1, 3))
    tmp30 = np.copy(f.bb.oo)
    tmp30 += np.transpose(tmp27, (1, 0))
    del tmp27
    tmp30 += np.transpose(tmp29, (1, 0)) * -1
    del tmp29
    tmp26 = np.copy(f.bb.vv)
    tmp26 += einsum(v.bbbb.ovvv, (0, 1, 2, 3), t1.bb, (0, 1), (2, 3))
    tmp10 = np.copy(np.transpose(tmp5, (1, 0)))
    del tmp5
    tmp10 += np.transpose(tmp6, (1, 0)) * 0.5
    del tmp6
    tmp10 += einsum(t1.aa, (0, 1), tmp9, (2, 1), (2, 0)) * 0.5
    tmp11 = np.copy(f.aa.vv)
    tmp11 += einsum(t1.aa, (0, 1), v.aaaa.ovvv, (0, 1, 2, 3), (2, 3))
    tmp19 = np.copy(f.aa.oo)
    tmp19 += np.transpose(tmp16, (1, 0))
    del tmp16
    tmp19 += np.transpose(tmp18, (1, 0)) * -1
    del tmp18
    tmp4 = np.copy(t2.aaaa) * 2
    tmp4 += einsum(t1.aa, (0, 1), t1.aa, (2, 3), (2, 0, 3, 1))
    t2new.bbbb = np.copy(np.transpose(tmp147, (1, 0, 3, 2))) * 2
    del tmp147
    t2new.bbbb += tmp149
    t2new.bbbb += np.transpose(tmp150, (0, 1, 3, 2)) * -2
    t2new.bbbb += np.transpose(tmp149, (0, 1, 3, 2)) * -1
    del tmp149
    t2new.bbbb += np.transpose(tmp150, (1, 0, 3, 2)) * 2
    del tmp150
    t2new.bbbb += np.transpose(tmp128, (1, 0, 3, 2))
    t2new.bbbb += np.transpose(tmp129, (1, 0, 3, 2)) * 2
    t2new.bbbb += np.transpose(tmp151, (1, 0, 3, 2))
    t2new.bbbb += np.transpose(tmp128, (1, 0, 2, 3)) * -1
    t2new.bbbb += np.transpose(tmp129, (1, 0, 2, 3)) * -2
    t2new.bbbb += np.transpose(tmp151, (1, 0, 2, 3)) * -1
    del tmp151
    t2new.bbbb += np.transpose(tmp153, (1, 0, 3, 2)) * -2
    t2new.bbbb += np.transpose(tmp155, (1, 0, 3, 2))
    t2new.bbbb += np.transpose(tmp157, (1, 0, 2, 3))
    t2new.bbbb += np.transpose(tmp157, (1, 0, 3, 2)) * -1
    t2new.bbbb += einsum(t2.bbbb, (0, 1, 2, 3), tmp111, (4, 1), (0, 4, 2, 3)) * -1
    t2new.bbbb += np.transpose(tmp155, (1, 0, 2, 3)) * -1
    t2new.bbbb += np.transpose(tmp162, (0, 1, 3, 2)) * -1
    t2new.bbbb += np.transpose(tmp153, (0, 1, 3, 2)) * 2
    del tmp153
    t2new.bbbb += np.transpose(tmp155, (0, 1, 3, 2)) * -1
    t2new.bbbb += tmp157 * -1
    t2new.bbbb += np.transpose(tmp157, (0, 1, 3, 2))
    del tmp157
    t2new.bbbb += np.transpose(tmp162, (1, 0, 3, 2)) * 2
    del tmp162
    t2new.bbbb += tmp155
    del tmp155
    t2new.bbbb += np.transpose(tmp163, (1, 0, 2, 3))
    t2new.bbbb += np.transpose(v.bbbb.ovov, (0, 2, 1, 3))
    t2new.bbbb += np.transpose(tmp164, (1, 0, 3, 2)) * -1
    t2new.bbbb += einsum(t2.bbbb, (0, 1, 2, 3), tmp167, (4, 1, 5, 3), (0, 4, 5, 2)) * 2
    del tmp167
    t2new.bbbb += np.transpose(tmp169, (0, 1, 3, 2))
    t2new.bbbb += tmp163 * -1
    t2new.bbbb += np.transpose(v.bbbb.ovov, (0, 2, 3, 1)) * -1
    t2new.bbbb += np.transpose(tmp164, (0, 1, 3, 2))
    t2new.bbbb += np.transpose(tmp173, (1, 0, 3, 2)) * -2
    t2new.bbbb += np.transpose(tmp174, (1, 0, 3, 2))
    t2new.bbbb += np.transpose(tmp175, (0, 1, 3, 2))
    t2new.bbbb += tmp176 * 2
    t2new.bbbb += np.transpose(tmp176, (1, 0, 3, 2)) * 2
    t2new.bbbb += np.transpose(tmp180, (1, 0, 3, 2))
    t2new.bbbb += np.transpose(tmp182, (1, 0, 3, 2)) * -1
    t2new.bbbb += np.transpose(tmp175, (1, 0, 3, 2)) * -1
    t2new.bbbb += np.transpose(tmp176, (0, 1, 3, 2)) * -2
    t2new.bbbb += np.transpose(tmp176, (1, 0, 2, 3)) * -2
    del tmp176
    t2new.bbbb += np.transpose(tmp180, (0, 1, 3, 2)) * -1
    t2new.bbbb += np.transpose(tmp182, (0, 1, 3, 2))
    t2new.bbbb += tmp175 * -1
    t2new.bbbb += np.transpose(tmp180, (1, 0, 2, 3)) * -1
    t2new.bbbb += np.transpose(tmp182, (1, 0, 2, 3))
    t2new.bbbb += np.transpose(tmp175, (1, 0, 2, 3))
    del tmp175
    t2new.bbbb += tmp180
    del tmp180
    t2new.bbbb += tmp182 * -1
    del tmp182
    t2new.bbbb += np.transpose(tmp163, (0, 1, 3, 2))
    t2new.bbbb += np.transpose(tmp184, (0, 1, 3, 2)) * -2
    del tmp184
    t2new.bbbb += tmp186
    t2new.bbbb += np.transpose(tmp186, (0, 1, 3, 2)) * -1
    del tmp186
    t2new.bbbb += np.transpose(tmp188, (0, 1, 3, 2))
    t2new.bbbb += np.transpose(tmp188, (1, 0, 3, 2)) * -1
    t2new.bbbb += tmp190
    t2new.bbbb += np.transpose(tmp190, (0, 1, 3, 2)) * -1
    del tmp190
    t2new.bbbb += np.transpose(tmp163, (1, 0, 3, 2)) * -1
    del tmp163
    t2new.bbbb += einsum(t2.bbbb, (0, 1, 2, 3), tmp192, (2, 4, 5, 3), (0, 1, 5, 4)) * 2
    del tmp192
    t2new.bbbb += np.transpose(tmp128, (0, 1, 3, 2)) * -1
    t2new.bbbb += np.transpose(tmp129, (0, 1, 3, 2)) * -2
    t2new.bbbb += tmp129 * 2
    del tmp129
    t2new.bbbb += tmp128
    del tmp128
    t2new.bbbb += np.transpose(tmp164, (1, 0, 2, 3))
    t2new.bbbb += tmp173 * -2
    t2new.bbbb += tmp169 * -1
    del tmp169
    t2new.bbbb += tmp164 * -1
    del tmp164
    t2new.bbbb += np.transpose(tmp173, (1, 0, 2, 3)) * 2
    del tmp173
    t2new.bbbb += np.transpose(tmp174, (1, 0, 2, 3)) * -1
    del tmp174
    t2new.bbbb += einsum(tmp193, (0, 1, 2, 3), t1.bb, (2, 4), (0, 1, 4, 3)) * -2
    del tmp193
    t2new.bbbb += tmp188 * -1
    t2new.bbbb += np.transpose(tmp188, (1, 0, 2, 3))
    del tmp188
    t2new.abab = einsum(tmp99, (0, 1), t2.abab, (2, 0, 3, 4), (2, 1, 3, 4)) * -1
    del tmp99
    t2new.abab += einsum(tmp100, (0, 1, 2, 3), v.aabb.oooo, (4, 0, 5, 1), (4, 5, 2, 3)) * 0.5
    del tmp100
    t2new.abab += einsum(t2.abab, (0, 1, 2, 3), v.aabb.oooo, (4, 0, 5, 1), (4, 5, 2, 3)) * 0.5
    t2new.abab += einsum(t2.abab, (0, 1, 2, 3), tmp101, (0, 4), (4, 1, 2, 3)) * -1
    del tmp101
    t2new.abab += tmp102 * 2
    del tmp102
    t2new.abab += tmp103
    del tmp103
    t2new.abab += einsum(tmp45, (0, 1), t2.abab, (2, 3, 0, 4), (2, 3, 1, 4)) * -1
    del tmp45
    t2new.abab += einsum(tmp110, (0, 1), t2.abab, (2, 3, 4, 0), (2, 3, 4, 1)) * -1
    del tmp110
    t2new.abab += einsum(t2.abab, (0, 1, 2, 3), tmp111, (4, 1), (0, 4, 2, 3)) * -1
    del tmp111
    t2new.abab += einsum(tmp3, (0, 1, 2, 3), tmp112, (0, 4, 5, 1), (4, 5, 2, 3))
    del tmp112
    t2new.abab += einsum(t1.bb, (0, 1), tmp113, (2, 3, 0, 4), (2, 3, 4, 1)) * -1
    del tmp113
    t2new.abab += einsum(t2.abab, (0, 1, 2, 3), tmp57, (4, 0), (4, 1, 2, 3)) * -1
    del tmp57
    t2new.abab += einsum(tmp114, (0, 1, 2, 3), tmp3, (1, 2, 4, 5), (0, 3, 4, 5))
    del tmp114
    t2new.abab += tmp115 * -1
    del tmp115
    t2new.abab += tmp116
    del tmp116
    t2new.abab += np.transpose(v.aabb.ovov, (0, 2, 1, 3))
    t2new.abab += einsum(tmp118, (0, 1, 2, 3), t2.abab, (4, 1, 2, 5), (4, 0, 3, 5)) * -1
    del tmp118
    t2new.abab += tmp119 * -1
    del tmp119
    t2new.abab += einsum(tmp120, (0, 1, 2, 3), t2.abab, (4, 0, 2, 5), (4, 1, 3, 5)) * -1
    del tmp120
    t2new.abab += tmp82 * -1
    del tmp82
    t2new.abab += einsum(t2.abab, (0, 1, 2, 3), tmp121, (0, 4, 3, 5), (4, 1, 2, 5)) * -1
    del tmp121
    t2new.abab += einsum(t1.bb, (0, 1), tmp122, (2, 3, 0, 4), (2, 3, 4, 1)) * -1
    del tmp122
    t2new.abab += einsum(tmp123, (0, 1, 2, 3), t1.aa, (4, 1), (4, 0, 2, 3))
    del tmp123
    t2new.abab += einsum(tmp124, (0, 1, 2, 3), tmp3, (1, 3, 4, 5), (0, 2, 4, 5))
    del tmp124
    t2new.abab += einsum(tmp125, (0, 1, 2, 3), t2.abab, (0, 4, 2, 5), (1, 4, 3, 5))
    del tmp125
    t2new.abab += einsum(t2.bbbb, (0, 1, 2, 3), tmp127, (4, 1, 5, 3), (4, 0, 5, 2)) * 2
    del tmp127
    t2new.abab += tmp83
    del tmp83
    t2new.abab += tmp126 * 2
    del tmp126
    t2new.abab += einsum(t2.abab, (0, 1, 2, 3), tmp131, (1, 4, 3, 5), (0, 4, 2, 5))
    del tmp131
    t2new.abab += einsum(t2.aaaa, (0, 1, 2, 3), tmp132, (1, 4, 3, 5), (0, 4, 2, 5)) * 2
    del tmp132
    t2new.abab += einsum(t2.abab, (0, 1, 2, 3), tmp134, (2, 4, 3, 5), (0, 1, 4, 5))
    del tmp134
    t2new.abab += einsum(tmp137, (0, 1, 2, 3), t2.abab, (1, 4, 2, 5), (0, 4, 3, 5))
    del tmp137
    t2new.abab += einsum(t2.bbbb, (0, 1, 2, 3), tmp74, (4, 1, 5, 3), (4, 0, 5, 2)) * 2
    del tmp74
    t2new.abab += einsum(t2.abab, (0, 1, 2, 3), tmp141, (4, 1, 3, 5), (0, 4, 2, 5))
    del tmp141
    t2new.abab += einsum(t2.aaaa, (0, 1, 2, 3), tmp142, (1, 4, 3, 5), (0, 4, 2, 5)) * 2
    del tmp142
    t2new.abab += tmp65 * -1
    del tmp65
    t2new.abab += einsum(t2.abab, (0, 1, 2, 3), tmp143, (4, 0, 3, 5), (4, 1, 2, 5)) * -1
    del tmp143
    t2new.abab += einsum(t1.aa, (0, 1), tmp144, (2, 0, 3, 4), (2, 3, 1, 4)) * -1
    del tmp144
    t2new.abab += einsum(t1.aa, (0, 1), tmp145, (2, 0, 3, 4), (2, 3, 1, 4)) * -1
    del tmp145
    t2new.abab += einsum(t1.aa, (0, 1), tmp146, (2, 0, 3, 4), (2, 3, 1, 4)) * -1
    del tmp146
    t2new.aaaa = np.copy(np.transpose(tmp33, (0, 1, 3, 2))) * -2
    t2new.aaaa += einsum(v.aaaa.oooo, (0, 1, 2, 3), tmp34, (3, 1, 4, 5), (0, 2, 5, 4)) * 0.5
    del tmp34
    t2new.aaaa += np.transpose(tmp35, (1, 0, 3, 2))
    del tmp35
    t2new.aaaa += np.transpose(tmp33, (1, 0, 3, 2)) * 2
    del tmp33
    t2new.aaaa += einsum(v.aaaa.oooo, (0, 1, 2, 3), tmp36, (3, 1, 4, 5), (0, 2, 5, 4)) * -0.5
    del tmp36
    t2new.aaaa += np.transpose(tmp37, (1, 0, 3, 2)) * 2
    t2new.aaaa += np.transpose(tmp38, (1, 0, 3, 2))
    t2new.aaaa += np.transpose(tmp46, (1, 0, 3, 2))
    t2new.aaaa += np.transpose(tmp37, (1, 0, 2, 3)) * -2
    t2new.aaaa += np.transpose(tmp38, (1, 0, 2, 3)) * -1
    t2new.aaaa += np.transpose(tmp46, (1, 0, 2, 3)) * -1
    del tmp46
    t2new.aaaa += np.transpose(tmp48, (1, 0, 3, 2))
    t2new.aaaa += np.transpose(tmp50, (1, 0, 3, 2)) * -2
    t2new.aaaa += np.transpose(tmp52, (1, 0, 2, 3))
    t2new.aaaa += np.transpose(tmp52, (1, 0, 3, 2)) * -1
    t2new.aaaa += einsum(t2.aaaa, (0, 1, 2, 3), tmp53, (4, 1), (0, 4, 2, 3)) * -1
    del tmp53
    t2new.aaaa += np.transpose(tmp48, (1, 0, 2, 3)) * -1
    t2new.aaaa += np.transpose(tmp58, (0, 1, 3, 2)) * -1
    t2new.aaaa += np.transpose(tmp48, (0, 1, 3, 2)) * -1
    t2new.aaaa += np.transpose(tmp50, (0, 1, 3, 2)) * 2
    del tmp50
    t2new.aaaa += tmp52 * -1
    t2new.aaaa += np.transpose(tmp52, (0, 1, 3, 2))
    del tmp52
    t2new.aaaa += np.transpose(tmp58, (1, 0, 3, 2)) * 2
    del tmp58
    t2new.aaaa += tmp48
    del tmp48
    t2new.aaaa += np.transpose(tmp59, (1, 0, 2, 3))
    t2new.aaaa += np.transpose(v.aaaa.ovov, (0, 2, 1, 3))
    t2new.aaaa += np.transpose(tmp60, (1, 0, 3, 2)) * -1
    t2new.aaaa += einsum(tmp63, (0, 1, 2, 3), t2.aaaa, (4, 1, 5, 3), (4, 0, 2, 5)) * 2
    del tmp63
    t2new.aaaa += np.transpose(tmp67, (0, 1, 3, 2))
    t2new.aaaa += tmp59 * -1
    t2new.aaaa += np.transpose(v.aaaa.ovov, (0, 2, 3, 1)) * -1
    t2new.aaaa += np.transpose(tmp60, (0, 1, 3, 2))
    t2new.aaaa += np.transpose(tmp73, (1, 0, 3, 2)) * -2
    t2new.aaaa += np.transpose(tmp75, (1, 0, 3, 2))
    t2new.aaaa += np.transpose(tmp76, (0, 1, 3, 2))
    t2new.aaaa += tmp77 * 2
    t2new.aaaa += np.transpose(tmp77, (1, 0, 3, 2)) * 2
    t2new.aaaa += np.transpose(tmp81, (1, 0, 3, 2))
    t2new.aaaa += np.transpose(tmp85, (1, 0, 3, 2)) * -1
    t2new.aaaa += np.transpose(tmp76, (1, 0, 3, 2)) * -1
    t2new.aaaa += np.transpose(tmp77, (0, 1, 3, 2)) * -2
    t2new.aaaa += np.transpose(tmp77, (1, 0, 2, 3)) * -2
    del tmp77
    t2new.aaaa += np.transpose(tmp81, (0, 1, 3, 2)) * -1
    t2new.aaaa += np.transpose(tmp85, (0, 1, 3, 2))
    del tmp85
    t2new.aaaa += tmp76 * -1
    t2new.aaaa += np.transpose(tmp81, (1, 0, 2, 3)) * -1
    t2new.aaaa += np.transpose(tmp87, (1, 0, 2, 3))
    t2new.aaaa += np.transpose(tmp76, (1, 0, 2, 3))
    del tmp76
    t2new.aaaa += tmp81
    del tmp81
    t2new.aaaa += tmp87 * -1
    del tmp87
    t2new.aaaa += np.transpose(tmp59, (0, 1, 3, 2))
    t2new.aaaa += np.transpose(tmp89, (0, 1, 3, 2)) * -2
    del tmp89
    t2new.aaaa += tmp91
    t2new.aaaa += np.transpose(tmp91, (0, 1, 3, 2)) * -1
    del tmp91
    t2new.aaaa += np.transpose(tmp93, (0, 1, 3, 2))
    t2new.aaaa += np.transpose(tmp93, (1, 0, 3, 2)) * -1
    t2new.aaaa += tmp95
    t2new.aaaa += np.transpose(tmp95, (0, 1, 3, 2)) * -1
    del tmp95
    t2new.aaaa += np.transpose(tmp59, (1, 0, 3, 2)) * -1
    del tmp59
    t2new.aaaa += einsum(tmp97, (0, 1, 2, 3), t2.aaaa, (4, 5, 0, 2), (4, 5, 1, 3)) * 2
    del tmp97
    t2new.aaaa += np.transpose(tmp37, (0, 1, 3, 2)) * -2
    t2new.aaaa += np.transpose(tmp38, (0, 1, 3, 2)) * -1
    t2new.aaaa += tmp37 * 2
    del tmp37
    t2new.aaaa += tmp38
    del tmp38
    t2new.aaaa += np.transpose(tmp60, (1, 0, 2, 3))
    t2new.aaaa += tmp73 * -2
    t2new.aaaa += tmp67 * -1
    del tmp67
    t2new.aaaa += tmp60 * -1
    del tmp60
    t2new.aaaa += np.transpose(tmp73, (1, 0, 2, 3)) * 2
    del tmp73
    t2new.aaaa += np.transpose(tmp75, (1, 0, 2, 3)) * -1
    del tmp75
    t2new.aaaa += einsum(tmp98, (0, 1, 2, 3), t1.aa, (2, 4), (0, 1, 4, 3)) * -2
    del tmp98
    t2new.aaaa += tmp93 * -1
    t2new.aaaa += np.transpose(tmp93, (1, 0, 2, 3))
    del tmp93
    t1new.bb = einsum(t1.bb, (0, 1), v.bbbb.ovov, (2, 3, 0, 1), (2, 3))
    t1new.bb += f.bb.ov
    t1new.bb += tmp12
    del tmp12
    t1new.bb += einsum(t2.abab, (0, 1, 2, 3), tmp20, (0, 4, 1, 2), (4, 3)) * -1
    del tmp20
    t1new.bb += einsum(t2.bbbb, (0, 1, 2, 3), tmp21, (4, 1, 0, 3), (4, 2)) * -2
    del tmp21
    t1new.bb += einsum(tmp22, (0, 1, 2, 3), v.bbbb.ovvv, (0, 3, 4, 2), (1, 4)) * -1
    del tmp22
    t1new.bb += einsum(v.aabb.ovvv, (0, 1, 2, 3), tmp3, (0, 4, 1, 3), (4, 2))
    t1new.bb += einsum(t1.bb, (0, 1), tmp25, (0, 2), (2, 1)) * -2
    del tmp25
    t1new.bb += einsum(tmp26, (0, 1), t1.bb, (2, 0), (2, 1))
    del tmp26
    t1new.bb += einsum(v.bbbb.oovv, (0, 1, 2, 3), t1.bb, (1, 3), (0, 2)) * -1
    t1new.bb += einsum(v.bbbb.ooov, (0, 1, 2, 3), t2.bbbb, (1, 2, 4, 3), (0, 4)) * -2
    t1new.bb += einsum(t2.abab, (0, 1, 2, 3), v.aabb.ovoo, (0, 2, 4, 1), (4, 3)) * -1
    t1new.bb += einsum(t2.bbbb, (0, 1, 2, 3), tmp15, (1, 3), (0, 2)) * 2
    t1new.bb += einsum(t2.abab, (0, 1, 2, 3), tmp9, (0, 2), (1, 3))
    t1new.bb += einsum(t1.bb, (0, 1), tmp30, (0, 2), (2, 1)) * -1
    del tmp30
    t1new.aa = np.copy(f.aa.ov)
    t1new.aa += einsum(t2.abab, (0, 1, 2, 3), tmp0, (4, 0, 1, 3), (4, 2)) * -1
    del tmp0
    t1new.aa += einsum(v.aaaa.ovov, (0, 1, 2, 3), t1.aa, (2, 3), (0, 1))
    t1new.aa += einsum(t2.aaaa, (0, 1, 2, 3), tmp1, (4, 1, 0, 3), (4, 2)) * -2
    del tmp1
    t1new.aa += tmp2
    del tmp2
    t1new.aa += einsum(tmp3, (0, 1, 2, 3), v.aabb.vvov, (4, 2, 1, 3), (0, 4))
    del tmp3
    t1new.aa += einsum(tmp4, (0, 1, 2, 3), v.aaaa.ovvv, (0, 3, 4, 2), (1, 4)) * -1
    del tmp4
    t1new.aa += einsum(tmp10, (0, 1), t1.aa, (0, 2), (1, 2)) * -2
    del tmp10
    t1new.aa += einsum(tmp11, (0, 1), t1.aa, (2, 0), (2, 1))
    del tmp11
    t1new.aa += einsum(t2.abab, (0, 1, 2, 3), v.aabb.ooov, (4, 0, 1, 3), (4, 2)) * -1
    t1new.aa += einsum(v.aaaa.oovv, (0, 1, 2, 3), t1.aa, (1, 3), (0, 2)) * -1
    t1new.aa += einsum(v.aaaa.ooov, (0, 1, 2, 3), t2.aaaa, (1, 2, 4, 3), (0, 4)) * -2
    t1new.aa += einsum(t2.abab, (0, 1, 2, 3), tmp15, (1, 3), (0, 2))
    del tmp15
    t1new.aa += einsum(t2.aaaa, (0, 1, 2, 3), tmp9, (1, 3), (0, 2)) * 2
    del tmp9
    t1new.aa += einsum(tmp19, (0, 1), t1.aa, (0, 2), (1, 2)) * -1
    del tmp19

    return {f"t1new": t1new, f"t2new": t2new}

