import numpy as np
import copy
try:
    from pyscf import lib
    einsum = lib.einsum
except ImportError:
    einsum = np.einsum

def ccsd_2_1_energy(cc, T1, T2, S1, U11):
    ''' Calculate CCSD-2-1 energy. 
        Equation generating script using the 'wick' program found in gen_eqns/ccsd_21_amps.py
    '''

    # Fermionic part
    # doubles contrib
    E = 0.25*einsum('ijab,baji->', cc.I.oovv, T2)
    # t1 contribution
    E += einsum('ia,ai->', cc.fock_mo.ov, T1)
    # t1**2 contribution
    E += -0.5*einsum('ijab,bi,aj->', cc.I.oovv, T1, T1)

    # Bosonic and coupling part
    E += einsum('I,I->', cc.G, S1)
    E += einsum('Iai,Iai->', cc.g_mo_blocks.vo, U11)
    E += einsum('Iai,ai,I->', cc.g_mo_blocks.vo, T1, S1)

    return E

def amp_updates_ccsd_2_1(cc, autogen=False):
    ''' Solve residual equations for CCSD.
        Equation generating script using the 'wick' program found in gen_eqns/ccsd_21_amps.py
    '''

    # Copy fock matrix in MO basis, and remove diagonals, as these are the energy denominators
    F = copy.copy(cc.fock_mo)
    F.oo = F.oo - np.diag(cc.eo)
    F.vv = F.vv - np.diag(cc.ev)

    I = cc.I

    T1old = cc.T1old
    T2old = cc.T2old
    S1old = cc.S1old
    S2old = cc.S2old
    U11old = cc.U11old

    g = cc.g_mo_blocks
    h = cc.g_mo_blocks
    G = cc.G.copy()
    H = cc.G.copy()
    
    # Note that we also have to remove diagonals from omega
    # matrix. Since the rest of the code is constrained to have
    # no coupling between bosons, this means that this is actually
    # the zero matrix, but we keep it in here anyway for potential
    # future applications
    w = np.diag(cc.omega).copy()
    w = w - np.diag(np.diag(w))

    # Update T1, T2, S1, S2 and U11
    if autogen:
        T1 = F.vo.copy()
        T1 += 1.0*einsum('I,Iai->ai', G, U11old)
        T1 += -1.0*einsum('ji,aj->ai', F.oo, T1old)
        T1 += 1.0*einsum('ab,bi->ai', F.vv, T1old)
        T1 += 1.0*einsum('Iia,I->ai', g.ov, S1old)
        T1 += -1.0*einsum('jb,abji->ai', F.ov, T2old)
        T1 += -1.0*einsum('Iij,Iaj->ai', g.oo, U11old)
        T1 += 1.0*einsum('Iba,Ibi->ai', g.vv, U11old)
        T1 += -1.0*einsum('jaib,bj->ai', I.ovov, T1old)
        T1 += 0.5*einsum('jkib,abkj->ai', I.ooov, T2old)
        T1 += -0.5*einsum('jabc,cbji->ai', I.ovvv, T2old)
        T1 += -1.0*einsum('jb,bi,aj->ai', F.ov, T1old, T1old)
        T1 += -1.0*einsum('Iij,aj,I->ai', g.oo, T1old, S1old)
        T1 += 1.0*einsum('Iba,bi,I->ai', g.vv, T1old, S1old)
        T1 += -1.0*einsum('Ibj,aj,Ibi->ai', g.vo, T1old, U11old)
        T1 += -1.0*einsum('Ibj,bi,Iaj->ai', g.vo, T1old, U11old)
        T1 += 1.0*einsum('Ibj,bj,Iai->ai', g.vo, T1old, U11old)
        T1 += -1.0*einsum('Ibj,abji,I->ai', g.vo, T2old, S1old)
        T1 += -1.0*einsum('jkib,aj,bk->ai', I.ooov, T1old, T1old)
        T1 += 1.0*einsum('jabc,ci,bj->ai', I.ovvv, T1old, T1old)
        T1 += -0.5*einsum('jkbc,aj,cbki->ai', I.oovv, T1old, T2old)
        T1 += -0.5*einsum('jkbc,ci,abkj->ai', I.oovv, T1old, T2old)
        T1 += 1.0*einsum('jkbc,cj,abki->ai', I.oovv, T1old, T2old)
        T1 += -1.0*einsum('Ibj,bi,aj,I->ai', g.vo, T1old, T1old, S1old)
        T1 += 1.0*einsum('jkbc,ci,aj,bk->ai', I.oovv, T1old, T1old, T1old)
        
        T2 = I.vvoo.copy().transpose((1,0,3,2))
        T2 += 1.0*einsum('ki,bakj->abij', F.oo, T2old)
        T2 += -1.0*einsum('kj,baki->abij', F.oo, T2old)
        T2 += 1.0*einsum('ac,bcji->abij', F.vv, T2old)
        T2 += -1.0*einsum('bc,acji->abij', F.vv, T2old)
        T2 += 1.0*einsum('Iia,Ibj->abij', g.ov, U11old)
        T2 += -1.0*einsum('Iib,Iaj->abij', g.ov, U11old)
        T2 += -1.0*einsum('Ija,Ibi->abij', g.ov, U11old)
        T2 += 1.0*einsum('Ijb,Iai->abij', g.ov, U11old)
        T2 += -1.0*einsum('kaji,bk->abij', I.ovoo, T1old)
        T2 += 1.0*einsum('kbji,ak->abij', I.ovoo, T1old)
        T2 += -1.0*einsum('baic,cj->abij', I.vvov, T1old)
        T2 += 1.0*einsum('bajc,ci->abij', I.vvov, T1old)
        T2 += -0.5*einsum('klji,balk->abij', I.oooo, T2old)
        T2 += 1.0*einsum('kaic,bckj->abij', I.ovov, T2old)
        T2 += -1.0*einsum('kajc,bcki->abij', I.ovov, T2old)
        T2 += -1.0*einsum('kbic,ackj->abij', I.ovov, T2old)
        T2 += 1.0*einsum('kbjc,acki->abij', I.ovov, T2old)
        T2 += -0.5*einsum('bacd,dcji->abij', I.vvvv, T2old)
        T2 += -1.0*einsum('kc,ak,bcji->abij', F.ov, T1old, T2old)
        T2 += 1.0*einsum('kc,bk,acji->abij', F.ov, T1old, T2old)
        T2 += 1.0*einsum('kc,ci,bakj->abij', F.ov, T1old, T2old)
        T2 += -1.0*einsum('kc,cj,baki->abij', F.ov, T1old, T2old)
        T2 += -1.0*einsum('Iik,ak,Ibj->abij', g.oo, T1old, U11old)
        T2 += 1.0*einsum('Iik,bk,Iaj->abij', g.oo, T1old, U11old)
        T2 += 1.0*einsum('Iik,bakj,I->abij', g.oo, T2old, S1old)
        T2 += 1.0*einsum('Ijk,ak,Ibi->abij', g.oo, T1old, U11old)
        T2 += -1.0*einsum('Ijk,bk,Iai->abij', g.oo, T1old, U11old)
        T2 += -1.0*einsum('Ijk,baki,I->abij', g.oo, T2old, S1old)
        T2 += 1.0*einsum('Ica,ci,Ibj->abij', g.vv, T1old, U11old)
        T2 += -1.0*einsum('Ica,cj,Ibi->abij', g.vv, T1old, U11old)
        T2 += 1.0*einsum('Ica,bcji,I->abij', g.vv, T2old, S1old)
        T2 += -1.0*einsum('Icb,ci,Iaj->abij', g.vv, T1old, U11old)
        T2 += 1.0*einsum('Icb,cj,Iai->abij', g.vv, T1old, U11old)
        T2 += -1.0*einsum('Icb,acji,I->abij', g.vv, T2old, S1old)
        T2 += 1.0*einsum('klji,bk,al->abij', I.oooo, T1old, T1old)
        T2 += 1.0*einsum('kaic,cj,bk->abij', I.ovov, T1old, T1old)
        T2 += -1.0*einsum('kajc,ci,bk->abij', I.ovov, T1old, T1old)
        T2 += -1.0*einsum('kbic,cj,ak->abij', I.ovov, T1old, T1old)
        T2 += 1.0*einsum('kbjc,ci,ak->abij', I.ovov, T1old, T1old)
        T2 += 1.0*einsum('bacd,di,cj->abij', I.vvvv, T1old, T1old)
        T2 += 1.0*einsum('Ick,acji,Ibk->abij', g.vo, T2old, U11old)
        T2 += -1.0*einsum('Ick,acki,Ibj->abij', g.vo, T2old, U11old)
        T2 += 1.0*einsum('Ick,ackj,Ibi->abij', g.vo, T2old, U11old)
        T2 += -1.0*einsum('Ick,baki,Icj->abij', g.vo, T2old, U11old)
        T2 += 1.0*einsum('Ick,bakj,Ici->abij', g.vo, T2old, U11old)
        T2 += -1.0*einsum('Ick,bcji,Iak->abij', g.vo, T2old, U11old)
        T2 += 1.0*einsum('Ick,bcki,Iaj->abij', g.vo, T2old, U11old)
        T2 += -1.0*einsum('Ick,bckj,Iai->abij', g.vo, T2old, U11old)
        T2 += 1.0*einsum('klic,ak,bclj->abij', I.ooov, T1old, T2old)
        T2 += -1.0*einsum('klic,bk,aclj->abij', I.ooov, T1old, T2old)
        T2 += 0.5*einsum('klic,cj,balk->abij', I.ooov, T1old, T2old)
        T2 += -1.0*einsum('klic,ck,balj->abij', I.ooov, T1old, T2old)
        T2 += -1.0*einsum('kljc,ak,bcli->abij', I.ooov, T1old, T2old)
        T2 += 1.0*einsum('kljc,bk,acli->abij', I.ooov, T1old, T2old)
        T2 += -0.5*einsum('kljc,ci,balk->abij', I.ooov, T1old, T2old)
        T2 += 1.0*einsum('kljc,ck,bali->abij', I.ooov, T1old, T2old)
        T2 += 0.5*einsum('kacd,bk,dcji->abij', I.ovvv, T1old, T2old)
        T2 += -1.0*einsum('kacd,di,bckj->abij', I.ovvv, T1old, T2old)
        T2 += 1.0*einsum('kacd,dj,bcki->abij', I.ovvv, T1old, T2old)
        T2 += -1.0*einsum('kacd,dk,bcji->abij', I.ovvv, T1old, T2old)
        T2 += -0.5*einsum('kbcd,ak,dcji->abij', I.ovvv, T1old, T2old)
        T2 += 1.0*einsum('kbcd,di,ackj->abij', I.ovvv, T1old, T2old)
        T2 += -1.0*einsum('kbcd,dj,acki->abij', I.ovvv, T1old, T2old)
        T2 += 1.0*einsum('kbcd,dk,acji->abij', I.ovvv, T1old, T2old)
        T2 += 0.5*einsum('klcd,adji,bclk->abij', I.oovv, T2old, T2old)
        T2 += -1.0*einsum('klcd,adki,bclj->abij', I.oovv, T2old, T2old)
        T2 += -0.5*einsum('klcd,baki,dclj->abij', I.oovv, T2old, T2old)
        T2 += -0.5*einsum('klcd,bdji,aclk->abij', I.oovv, T2old, T2old)
        T2 += 1.0*einsum('klcd,bdki,aclj->abij', I.oovv, T2old, T2old)
        T2 += 0.25*einsum('klcd,dcji,balk->abij', I.oovv, T2old, T2old)
        T2 += -0.5*einsum('klcd,dcki,balj->abij', I.oovv, T2old, T2old)
        T2 += -1.0*einsum('Ick,ak,bcji,I->abij', g.vo, T1old, T2old, S1old)
        T2 += 1.0*einsum('Ick,bk,acji,I->abij', g.vo, T1old, T2old, S1old)
        T2 += -1.0*einsum('Ick,ci,ak,Ibj->abij', g.vo, T1old, T1old, U11old)
        T2 += 1.0*einsum('Ick,ci,bk,Iaj->abij', g.vo, T1old, T1old, U11old)
        T2 += 1.0*einsum('Ick,ci,bakj,I->abij', g.vo, T1old, T2old, S1old)
        T2 += 1.0*einsum('Ick,cj,ak,Ibi->abij', g.vo, T1old, T1old, U11old)
        T2 += -1.0*einsum('Ick,cj,bk,Iai->abij', g.vo, T1old, T1old, U11old)
        T2 += -1.0*einsum('Ick,cj,baki,I->abij', g.vo, T1old, T2old, S1old)
        T2 += -1.0*einsum('klic,cj,bk,al->abij', I.ooov, T1old, T1old, T1old)
        T2 += 1.0*einsum('kljc,ci,bk,al->abij', I.ooov, T1old, T1old, T1old)
        T2 += -1.0*einsum('kacd,di,cj,bk->abij', I.ovvv, T1old, T1old, T1old)
        T2 += 1.0*einsum('kbcd,di,cj,ak->abij', I.ovvv, T1old, T1old, T1old)
        T2 += -1.0*einsum('klcd,ak,dl,bcji->abij', I.oovv, T1old, T1old, T2old)
        T2 += -0.5*einsum('klcd,bk,al,dcji->abij', I.oovv, T1old, T1old, T2old)
        T2 += 1.0*einsum('klcd,bk,dl,acji->abij', I.oovv, T1old, T1old, T2old)
        T2 += -1.0*einsum('klcd,di,ak,bclj->abij', I.oovv, T1old, T1old, T2old)
        T2 += 1.0*einsum('klcd,di,bk,aclj->abij', I.oovv, T1old, T1old, T2old)
        T2 += -0.5*einsum('klcd,di,cj,balk->abij', I.oovv, T1old, T1old, T2old)
        T2 += 1.0*einsum('klcd,di,ck,balj->abij', I.oovv, T1old, T1old, T2old)
        T2 += 1.0*einsum('klcd,dj,ak,bcli->abij', I.oovv, T1old, T1old, T2old)
        T2 += -1.0*einsum('klcd,dj,bk,acli->abij', I.oovv, T1old, T1old, T2old)
        T2 += -1.0*einsum('klcd,dj,ck,bali->abij', I.oovv, T1old, T1old, T2old)
        T2 += 1.0*einsum('klcd,di,cj,bk,al->abij', I.oovv, T1old, T1old, T1old, T1old)
        
        S1 = G.copy() 
        S1 += 1.0*einsum('J,IJ->I', G, S2old)
        S1 += 1.0*einsum('IJ,J->I', w, S1old)
        S1 += 1.0*einsum('ia,Iai->I', F.ov, U11old)
        S1 += 1.0*einsum('Iia,ai->I', g.ov, T1old)
        S1 += 1.0*einsum('Jai,J,Iai->I', g.vo, S1old, U11old)
        S1 += 1.0*einsum('Jai,ai,IJ->I', g.vo, T1old, S2old)
        S1 += -1.0*einsum('ijab,bi,Iaj->I', I.oovv, T1old, U11old)
        
        S2 = 1.0*einsum('IK,JK->IJ', w, S2old)
        S2 += 1.0*einsum('JK,IK->IJ', w, S2old)
        S2 += 1.0*einsum('Iia,Jai->IJ', g.ov, U11old)
        S2 += 1.0*einsum('Jia,Iai->IJ', g.ov, U11old)
        S2 += 1.0*einsum('Kai,IK,Jai->IJ', g.vo, S2old, U11old)
        S2 += 1.0*einsum('Kai,JK,Iai->IJ', g.vo, S2old, U11old)
        S2 += -1.0*einsum('ijab,Ibi,Jaj->IJ', I.oovv, U11old, U11old)
        
        U11 = g.vo.copy()
        U11 += -1.0*einsum('ji,Iaj->Iai', F.oo, U11old)
        U11 += 1.0*einsum('ab,Ibi->Iai', F.vv, U11old)
        U11 += 1.0*einsum('IJ,Jai->Iai', w, U11old)
        U11 += -1.0*einsum('Iji,aj->Iai', g.oo, T1old)
        U11 += 1.0*einsum('Iab,bi->Iai', g.vv, T1old)
        U11 += 1.0*einsum('Jia,IJ->Iai', g.ov, S2old)
        U11 += -1.0*einsum('Ijb,abji->Iai', g.ov, T2old)
        U11 += -1.0*einsum('jaib,Ibj->Iai', I.ovov, U11old)
        U11 += -1.0*einsum('jb,aj,Ibi->Iai', F.ov, T1old, U11old)
        U11 += -1.0*einsum('jb,bi,Iaj->Iai', F.ov, T1old, U11old)
        U11 += -1.0*einsum('Ijb,bi,aj->Iai', g.ov, T1old, T1old)
        U11 += -1.0*einsum('Jij,J,Iaj->Iai', g.oo, S1old, U11old)
        U11 += -1.0*einsum('Jij,aj,IJ->Iai', g.oo, T1old, S2old)
        U11 += 1.0*einsum('Jba,J,Ibi->Iai', g.vv, S1old, U11old)
        U11 += 1.0*einsum('Jba,bi,IJ->Iai', g.vv, T1old, S2old)
        U11 += -1.0*einsum('Jbj,Iaj,Jbi->Iai', g.vo, U11old, U11old)
        U11 += -1.0*einsum('Jbj,Ibi,Jaj->Iai', g.vo, U11old, U11old)
        U11 += 1.0*einsum('Jbj,Ibj,Jai->Iai', g.vo, U11old, U11old)
        U11 += -1.0*einsum('Jbj,abji,IJ->Iai', g.vo, T2old, S2old)
        U11 += -1.0*einsum('jkib,aj,Ibk->Iai', I.ooov, T1old, U11old)
        U11 += 1.0*einsum('jkib,bj,Iak->Iai', I.ooov, T1old, U11old)
        U11 += 1.0*einsum('jabc,ci,Ibj->Iai', I.ovvv, T1old, U11old)
        U11 += -1.0*einsum('jabc,cj,Ibi->Iai', I.ovvv, T1old, U11old)
        U11 += 1.0*einsum('jkbc,acji,Ibk->Iai', I.oovv, T2old, U11old)
        U11 += 0.5*einsum('jkbc,ackj,Ibi->Iai', I.oovv, T2old, U11old)
        U11 += 0.5*einsum('jkbc,cbji,Iak->Iai', I.oovv, T2old, U11old)
        U11 += -1.0*einsum('Jbj,aj,J,Ibi->Iai', g.vo, T1old, S1old, U11old)
        U11 += -1.0*einsum('Jbj,bi,J,Iaj->Iai', g.vo, T1old, S1old, U11old)
        U11 += -1.0*einsum('Jbj,bi,aj,IJ->Iai', g.vo, T1old, T1old, S2old)
        U11 += -1.0*einsum('jkbc,aj,ck,Ibi->Iai', I.oovv, T1old, T1old, U11old)
        U11 += 1.0*einsum('jkbc,ci,aj,Ibk->Iai', I.oovv, T1old, T1old, U11old)
        U11 += -1.0*einsum('jkbc,ci,bj,Iak->Iai', I.oovv, T1old, T1old, U11old)

    else:
        # Hand optimized code from epcc. I'm not sure that this will work
        # in the case of a non-symmetric g? To test.
        # If not, need to use autogen code above.
        assert(np.allclose(g.vo, g.ov.transpose((0,2,1))))
        assert(np.allclose(g.oo, g.oo.transpose((0,2,1))))
        assert(np.allclose(g.vv, g.vv.transpose((0,2,1))))
        # CCSD equations
        #T1,T2 = cc_equations.ccsd_simple(F, I, T1old, T2old)
        T1 = F.vo.copy()
        # _S_S
        T1 += einsum('ab,bi->ai', F.vv, T1old)
        T1 -= einsum('ji,aj->ai', F.oo, T1old)
        T1 -= einsum('ajbi,bj->ai', I.vovo, T1old)
        # _S_D
        T1 += einsum('jb,abij->ai', F.ov, T2old)
        T1 += 0.5*einsum('ajbc,bcij->ai', I.vovv, T2old)
        T1 -= 0.5*einsum('jkib,abjk->ai', I.ooov, T2old)
        # _S_SS
        T1 -= einsum('jb,bi,aj->ai', F.ov, T1old, T1old)
        T1 -= einsum('ajbc,bj,ci->ai', I.vovv, T1old, T1old)
        T1 += einsum('jkib,bj,ak->ai', I.ooov, T1old, T1old)
        # _S_SD
        T1 -= 0.5*einsum('jkbc,bi,acjk->ai', I.oovv, T1old, T2old)
        T1 -= 0.5*einsum('jkbc,aj,bcik->ai', I.oovv, T1old, T2old)
        T1 += einsum('jkbc,bj,caki->ai', I.oovv, T1old, T2old)
        # _S_SSS
        T1 += einsum('jkbc,bi,cj,ak->ai', I.oovv, T1old, T1old, T1old)
        T2 = I.vvoo.copy()
        # _D_S
        T2 += einsum('abcj,ci->abij', I.vvvo, T1old)
        T2 -= einsum('abci,cj->abij', I.vvvo, T1old)
        T2 += einsum('bkij,ak->abij', I.vooo, T1old)
        T2 -= einsum('akij,bk->abij', I.vooo, T1old)
        # _D_D
        T2 += einsum('bc,acij->abij', F.vv, T2old)
        T2 -= einsum('ac,bcij->abij', F.vv, T2old)
        T2 -= einsum('kj,abik->abij', F.oo, T2old)
        T2 += einsum('ki,abjk->abij', F.oo, T2old)
        T2 += 0.5*einsum('abcd,cdij->abij', I.vvvv, T2old)
        T2 += 0.5*einsum('klij,abkl->abij', I.oooo, T2old)
        T2 -= einsum('bkcj,acik->abij', I.vovo, T2old)
        T2 += einsum('akcj,bcik->abij', I.vovo, T2old)
        T2 += einsum('bkci,acjk->abij', I.vovo, T2old)
        T2 -= einsum('akci,bcjk->abij', I.vovo, T2old)
        # _D_SS
        T2 += 0.5*einsum('abcd,ci,dj->abij', I.vvvv, T1old, T1old)
        T2 -= 0.5*einsum('abcd,cj,di->abij', I.vvvv, T1old, T1old)
        T2 += 0.5*einsum('klij,ak,bl->abij', I.oooo, T1old, T1old)
        T2 -= 0.5*einsum('klij,bk,al->abij', I.oooo, T1old, T1old)
        T2 -= einsum('akcj,ci,bk->abij', I.vovo, T1old, T1old)
        T2 += einsum('bkcj,ci,ak->abij', I.vovo, T1old, T1old)
        T2 += einsum('akci,cj,bk->abij', I.vovo, T1old, T1old)
        T2 -= einsum('bkci,cj,ak->abij', I.vovo, T1old, T1old)
        # _D_SD
        T2 -= einsum('kc,ci,abkj->abij', F.ov, T1old, T2old)
        T2 += einsum('kc,cj,abki->abij', F.ov, T1old, T2old)
        T2 -= einsum('kc,ak,cbij->abij', F.ov, T1old, T2old)
        T2 += einsum('kc,bk,caij->abij', F.ov, T1old, T2old)
        T2 -= einsum('akcd,ck,dbij->abij', I.vovv, T1old, T2old)
        T2 += einsum('bkcd,ck,daij->abij', I.vovv, T1old, T2old)
        T2 += einsum('klic,ck,ablj->abij', I.ooov, T1old, T2old)
        T2 -= einsum('kljc,ck,abli->abij', I.ooov, T1old, T2old)
        T2 += einsum('akcd,ci,dbkj->abij', I.vovv, T1old, T2old)
        T2 -= einsum('bkcd,ci,dakj->abij', I.vovv, T1old, T2old)
        T2 -= einsum('akcd,cj,dbki->abij', I.vovv, T1old, T2old)
        T2 += einsum('bkcd,cj,daki->abij', I.vovv, T1old, T2old)
        T2 -= einsum('klic,ak,cblj->abij', I.ooov, T1old, T2old)
        T2 += einsum('klic,bk,calj->abij', I.ooov, T1old, T2old)
        T2 += einsum('kljc,ak,cbli->abij', I.ooov, T1old, T2old)
        T2 -= einsum('kljc,bk,cali->abij', I.ooov, T1old, T2old)
        T2 -= 0.5*einsum('kljc,ci,abkl->abij', I.ooov, T1old, T2old)
        T2 += 0.5*einsum('klic,cj,abkl->abij', I.ooov, T1old, T2old)
        T2 += 0.5*einsum('bkcd,ak,cdij->abij', I.vovv, T1old, T2old)
        T2 -= 0.5*einsum('akcd,bk,cdij->abij', I.vovv, T1old, T2old)
        # _D_DD
        T2 += 0.25*einsum('klcd,cdij,abkl->abij', I.oovv, T2old, T2old)
        T2 += einsum('klcd,acik,dblj->abij', I.oovv, T2old, T2old)
        T2 -= einsum('klcd,bcik,dalj->abij', I.oovv, T2old, T2old)
        T2 -= 0.5*einsum('klcd,cakl,dbij->abij', I.oovv, T2old, T2old)
        T2 += 0.5*einsum('klcd,cbkl,daij->abij', I.oovv, T2old, T2old)
        T2 -= 0.5*einsum('klcd,cdki,ablj->abij', I.oovv, T2old, T2old)
        T2 += 0.5*einsum('klcd,cdkj,abli->abij', I.oovv, T2old, T2old)
        # _D_SSS
        T2 += einsum('bkcd,ci,ak,dj->abij', I.vovv, T1old, T1old, T1old)
        T2 -= einsum('akcd,ci,bk,dj->abij', I.vovv, T1old, T1old, T1old)
        T2 -= einsum('kljc,ci,ak,bl->abij', I.ooov, T1old, T1old, T1old)
        T2 += einsum('klic,cj,ak,bl->abij', I.ooov, T1old, T1old, T1old)
        # _D_SSD
        T2 += 0.25*einsum('klcd,ci,dj,abkl->abij', I.oovv, T1old, T1old, T2old)
        T2 -= 0.25*einsum('klcd,cj,di,abkl->abij', I.oovv, T1old, T1old, T2old)
        T2 += 0.25*einsum('klcd,ak,bl,cdij->abij', I.oovv, T1old, T1old, T2old)
        T2 -= 0.25*einsum('klcd,bk,al,cdij->abij', I.oovv, T1old, T1old, T2old)
        T2 -= einsum('klcd,ci,ak,dblj->abij', I.oovv, T1old, T1old, T2old)
        T2 += einsum('klcd,ci,bk,dalj->abij', I.oovv, T1old, T1old, T2old)
        T2 += einsum('klcd,cj,ak,dbli->abij', I.oovv, T1old, T1old, T2old)
        T2 -= einsum('klcd,cj,bk,dali->abij', I.oovv, T1old, T1old, T2old)
        T2 -= einsum('klcd,ck,di,ablj->abij', I.oovv, T1old, T1old, T2old)
        T2 += einsum('klcd,ck,dj,abli->abij', I.oovv, T1old, T1old, T2old)
        T2 -= einsum('klcd,ck,al,dbij->abij', I.oovv, T1old, T1old, T2old)
        T2 += einsum('klcd,ck,bl,daij->abij', I.oovv, T1old, T1old, T2old)
        # _D_SSSS
        T2 += einsum('klcd,ci,ak,bl,dj->abij', I.oovv, T1old, T1old, T1old, T1old)

        # T1
        T1 += 1.0*einsum('I,Iai->ai', G, U11old)
        T1 += 1.0*einsum('Iai,I->ai', g.vo, S1old)
        T1 += -1.0*einsum('Iji,Iaj->ai', g.oo, U11old)
        T1 += 1.0*einsum('Iab,Ibi->ai', g.vv, U11old)
        T1 += -1.0*einsum('Iji,aj,I->ai', g.oo, T1old, S1old)
        T1 += 1.0*einsum('Iab,bi,I->ai', g.vv, T1old, S1old)
        T1 += -1.0*einsum('Ijb,bi,Iaj->ai', g.ov, T1old, U11old)
        T1 += -1.0*einsum('Ijb,aj,Ibi->ai', g.ov, T1old, U11old)
        T1 += 1.0*einsum('Ijb,bj,Iai->ai', g.ov, T1old, U11old)
        T1 += 1.0*einsum('Ijb,abij,I->ai', g.ov, T2old, S1old)
        T1 += -1.0*einsum('Ijb,bi,aj,I->ai', g.ov, T1old, T1old, S1old)

        # T2
        T2 += 1.0*einsum('Iai,Ibj->abij', g.vo, U11old)
        T2 += -1.0*einsum('Ibi,Iaj->abij', g.vo, U11old)
        T2 += -1.0*einsum('Iaj,Ibi->abij', g.vo, U11old)
        T2 += 1.0*einsum('Ibj,Iai->abij', g.vo, U11old)
        T2 += -1.0*einsum('Iki,ak,Ibj->abij', g.oo, T1old, U11old)
        T2 += 1.0*einsum('Iki,bk,Iaj->abij', g.oo, T1old, U11old)
        T2 += 1.0*einsum('Ikj,ak,Ibi->abij', g.oo, T1old, U11old)
        T2 += -1.0*einsum('Ikj,bk,Iai->abij', g.oo, T1old, U11old)
        T2 += 1.0*einsum('Iki,abjk,I->abij', g.oo, T2old, S1old)
        T2 += -1.0*einsum('Ikj,abik,I->abij', g.oo, T2old, S1old)
        T2 += 1.0*einsum('Iac,ci,Ibj->abij', g.vv, T1old, U11old)
        T2 += -1.0*einsum('Ibc,ci,Iaj->abij', g.vv, T1old, U11old)
        T2 += -1.0*einsum('Iac,cj,Ibi->abij', g.vv, T1old, U11old)
        T2 += 1.0*einsum('Ibc,cj,Iai->abij', g.vv, T1old, U11old)
        T2 += -1.0*einsum('Iac,bcij,I->abij', g.vv, T2old, S1old)
        T2 += 1.0*einsum('Ibc,acij,I->abij', g.vv, T2old, S1old)
        T2 += -1.0*einsum('Ikc,acij,Ibk->abij', g.ov, T2old, U11old)
        T2 += -1.0*einsum('Ikc,abik,Icj->abij', g.ov, T2old, U11old)
        T2 += 1.0*einsum('Ikc,acik,Ibj->abij', g.ov, T2old, U11old)
        T2 += 1.0*einsum('Ikc,bcij,Iak->abij', g.ov, T2old, U11old)
        T2 += -1.0*einsum('Ikc,bcik,Iaj->abij', g.ov, T2old, U11old)
        T2 += 1.0*einsum('Ikc,abjk,Ici->abij', g.ov, T2old, U11old)
        T2 += -1.0*einsum('Ikc,acjk,Ibi->abij', g.ov, T2old, U11old)
        T2 += 1.0*einsum('Ikc,bcjk,Iai->abij', g.ov, T2old, U11old)
        T2 += -1.0*einsum('Ikc,ci,ak,Ibj->abij', g.ov, T1old, T1old, U11old)
        T2 += 1.0*einsum('Ikc,ci,bk,Iaj->abij', g.ov, T1old, T1old, U11old)
        T2 += 1.0*einsum('Ikc,ak,cj,Ibi->abij', g.ov, T1old, T1old, U11old)
        T2 += -1.0*einsum('Ikc,cj,bk,Iai->abij', g.ov, T1old, T1old, U11old)
        T2 += 1.0*einsum('Ikc,ci,abjk,I->abij', g.ov, T1old, T2old, S1old)
        T2 += 1.0*einsum('Ikc,ak,bcij,I->abij', g.ov, T1old, T2old, S1old)
        T2 += -1.0*einsum('Ikc,cj,abik,I->abij', g.ov, T1old, T2old, S1old)
        T2 += -1.0*einsum('Ikc,bk,acij,I->abij', g.ov, T1old, T2old, S1old)

        # S1 equation
        S1 = H.copy()
        #S1 += 1.0*einsum('I->I', H)
        #S1 += 1.0*einsum('IJ,J->I', w, S1old)
        S1 += 1.0*einsum('J,IJ->I', G, S2old)
        S1 += 1.0*einsum('ia,Iai->I', F.ov, U11old)
        S1 += 1.0*einsum('Iia,ai->I', h.ov, T1old)
        S1 += 1.0*einsum('Jia,ai,IJ->I', g.ov, T1old, S2old)
        S1 += 1.0*einsum('Jia,J,Iai->I', g.ov, S1old, U11old)
        S1 += -1.0*einsum('ijab,bi,Iaj->I', I.oovv, T1old, U11old)

        # S2 equation
        nm = S1.shape[0]
        S2 = np.zeros((nm,nm))
        #S2 += 1.0*einsum('IK,JK->IJ', w, S2old)
        #S2 += 1.0*einsum('JK,IK->IJ', w, S2old)
        S2 += 1.0*einsum('Iia,Jai->IJ', h.ov, U11old)
        S2 += 1.0*einsum('Jia,Iai->IJ', h.ov, U11old)
        S2 += 1.0*einsum('Kia,IK,Jai->IJ', g.ov, S2old, U11old)
        S2 += 1.0*einsum('Kia,JK,Iai->IJ', g.ov, S2old, U11old)
        S2 += -1.0*einsum('ijab,Ibi,Jaj->IJ', I.oovv, U11old, U11old)

        # U11 equations
        U11 = h.vo.copy()
        #U11 += 1.0*einsum('Iai->Iai', h)
        U11 += -1.0*einsum('ji,Iaj->Iai', F.oo, U11old)
        U11 += 1.0*einsum('ab,Ibi->Iai', F.vv, U11old)
        #U11 += 1.0*einsum('IJ,Jai->Iai', w, U11old)
        U11 += -1.0*einsum('Iji,aj->Iai', h.oo, T1old)
        U11 += 1.0*einsum('Jai,IJ->Iai', g.vo, S2old)
        U11 += 1.0*einsum('Iab,bi->Iai', h.vv, T1old)
        U11 += -1.0*einsum('ajbi,Ibj->Iai', I.vovo, U11old)
        U11 += 1.0*einsum('Ijb,abij->Iai', h.ov, T2old)
        U11 += -1.0*einsum('jb,bi,Iaj->Iai', F.ov, T1old, U11old)
        U11 += -1.0*einsum('jb,aj,Ibi->Iai', F.ov, T1old, U11old)
        U11 += -1.0*einsum('Jji,aj,IJ->Iai', g.oo, T1old, S2old)
        U11 += -1.0*einsum('Jji,J,Iaj->Iai', g.oo, S1old, U11old)
        U11 += -1.0*einsum('Ijb,bi,aj->Iai', h.ov, T1old, T1old)
        U11 += 1.0*einsum('Jab,bi,IJ->Iai', g.vv, T1old, S2old)
        U11 += 1.0*einsum('Jab,J,Ibi->Iai', g.vv, S1old, U11old)
        U11 += -1.0*einsum('jkib,aj,Ibk->Iai', I.ooov, T1old, U11old)
        U11 += 1.0*einsum('jkib,bj,Iak->Iai', I.ooov, T1old, U11old)
        U11 += -1.0*einsum('ajbc,ci,Ibj->Iai', I.vovv, T1old, U11old)
        U11 += 1.0*einsum('ajbc,cj,Ibi->Iai', I.vovv, T1old, U11old)
        U11 += 1.0*einsum('Jjb,abij,IJ->Iai', g.ov, T2old, S2old)
        U11 += -1.0*einsum('Jjb,Ibi,Jaj->Iai', g.ov, U11old, U11old)
        U11 += -1.0*einsum('Jjb,Iaj,Jbi->Iai', g.ov, U11old, U11old)
        U11 += 1.0*einsum('Jjb,Ibj,Jai->Iai', g.ov, U11old, U11old)
        U11 += -1.0*einsum('jkbc,acij,Ibk->Iai', I.oovv, T2old, U11old)
        U11 += -0.5*einsum('jkbc,cbij,Iak->Iai', I.oovv, T2old, U11old)
        U11 += -0.5*einsum('jkbc,acjk,Ibi->Iai', I.oovv, T2old, U11old)
        U11 += -1.0*einsum('Jjb,bi,aj,IJ->Iai', g.ov, T1old, T1old, S2old)
        U11 += -1.0*einsum('Jjb,bi,J,Iaj->Iai', g.ov, T1old, S1old, U11old)
        U11 += -1.0*einsum('Jjb,aj,J,Ibi->Iai', g.ov, T1old, S1old, U11old)
        U11 += 1.0*einsum('jkbc,ci,aj,Ibk->Iai', I.oovv, T1old, T1old, U11old)
        U11 += -1.0*einsum('jkbc,ci,bj,Iak->Iai', I.oovv, T1old, T1old, U11old)
        U11 += -1.0*einsum('jkbc,aj,ck,Ibi->Iai', I.oovv, T1old, T1old, U11old)

    return T1, T2, S1, S2, U11 
