import numpy as np
import copy
try:
    from pyscf import lib
    einsum = lib.einsum
except ImportError:
    einsum = np.einsum

def ccsd_1_1_energy(cc, T1, T2, S1, U11):
    ''' Calculate CCSD-1-1 energy. 
        Equation generating script using the 'wick' program found in gen_eqns/ccsd_11_amps.py
    '''

    # Fermionic part
    # doubles contrib
    E = 0.25*einsum('abij,ijab->', T2, cc.I.oovv)
    # t1 contribution
    E += einsum('ai,ia->', T1, cc.fock_mo.ov)
    # t1**2 contribution
    E += 0.5*einsum('ai,bj,ijab->', T1, T1, cc.I.oovv)

    # Bosonic and coupling part
    E += einsum('I,I->',cc.G,S1)
    E += einsum('Iia,Iai->',cc.g_mo_blocks.ov, U11)
    E += einsum('Iia,ai,I->',cc.g_mo_blocks.ov, T1, S1)

    return E

def lam_updates_ccsd_1_1(cc):
    ''' Solve residual equations for CCSD_1_11.
        Equations generating script using the 'wick' program found in gen_eqns/ccsd_11_lam.py
    '''
    
    # Copy fock matrix in MO basis, and remove diagonals
    F = copy.copy(cc.fock_mo)
    F_full = copy.copy(cc.fock_mo)
    F.oo = F.oo - np.diag(cc.eo)
    F.vv = F.vv - np.diag(cc.ev)
    # eb coupling
    g = copy.copy(cc.g_mo_blocks)
    h = copy.copy(cc.g_mo_blocks)
    # b terms
    G = cc.G.copy()
    H = cc.G.copy()
    
    # Note that we also have to remove diagonals from omega
    # matrix. Since the rest of the code is constrained to have
    # no coupling between bosons, this means that this is actually
    # the zero matrix, but we keep it in here anyway for potential
    # future applications
    w = np.diag(cc.omega).copy()
    w_full = w.copy()
    w = w - np.diag(np.diag(w))

    I = cc.I
    
    T1old = cc.T1old
    T2old = cc.T2old
    S1old = cc.S1old
    U11old = cc.U11old

    L1old = cc.L1old
    L2old = cc.L2old
    LS1old = cc.LS1old
    LU11old = cc.LU11old
    
    # Lambda residuals for 1-fermion deexcitation space
    # Connected piece not proportional to Lambda...
    L1 = F.ov.copy()
    L1 += 1.0*einsum('I,Iia->ia', S1old, g.ov)
    L1 += -1.0*einsum('bj,jiab->ia', T1old, I.oovv)

    # Connected piece proportional to Lambda...
    L1 += 1.0*einsum('Iia,I->ia', g.ov, LS1old)
    L1 += -1.0*einsum('ij,ja->ia', F.oo, L1old)
    L1 += 1.0*einsum('ba,ib->ia', F.vv, L1old)
    L1 += 1.0*einsum('I,Iia->ia', G, LU11old)
    L1 += -1.0*einsum('ibja,jb->ia', I.ovov, L1old)
    L1 += -1.0*einsum('Iij,Ija->ia', g.oo, LU11old)
    L1 += 1.0*einsum('Iba,Iib->ia', g.vv, LU11old)
    L1 += -1.0*einsum('bj,jiab->ia', F.vo, L2old)
    L1 += 0.5*einsum('ibjk,kjab->ia', I.ovoo, L2old)
    L1 += -0.5*einsum('bcja,jicb->ia', I.vvov, L2old)
    L1 += -1.0*einsum('ib,bj,ja->ia', F.ov, T1old, L1old)
    L1 += -1.0*einsum('Iij,I,ja->ia', g.oo, S1old, L1old)
    L1 += -1.0*einsum('ja,bj,ib->ia', F.ov, T1old, L1old)
    L1 += 1.0*einsum('Iba,I,ib->ia', g.vv, S1old, L1old)
    # w_full used here
    L1 += 1.0*einsum('IJ,J,Iia->ia', w_full, S1old, LU11old)
    L1 += -1.0*einsum('jiab,Ibj,I->ia', I.oovv, U11old, LS1old)
    L1 += 1.0*einsum('Iia,Ibj,jb->ia', g.ov, U11old, L1old)
    L1 += -1.0*einsum('jika,bj,kb->ia', I.ooov, T1old, L1old)
    L1 += 1.0*einsum('ibac,cj,jb->ia', I.ovvv, T1old, L1old)
    L1 += -1.0*einsum('Iib,Ibj,ja->ia', g.ov, U11old, L1old)
    L1 += 1.0*einsum('jikb,bj,ka->ia', I.ooov, T1old, L1old)
    L1 += -1.0*einsum('Ija,Ibj,ib->ia', g.ov, U11old, L1old)
    L1 += -1.0*einsum('jbac,cj,ib->ia', I.ovvv, T1old, L1old)
    L1 += -1.0*einsum('ib,Ibj,Ija->ia', F.ov, U11old, LU11old)
    L1 += -1.0*einsum('Iib,bj,Ija->ia', g.ov, T1old, LU11old)
    L1 += -1.0*einsum('ja,Ibj,Iib->ia', F.ov, U11old, LU11old)
    L1 += -1.0*einsum('Ija,bj,Iib->ia', g.ov, T1old, LU11old)
    L1 += 1.0*einsum('jb,Ibj,Iia->ia', F.ov, U11old, LU11old)
    L1 += 1.0*einsum('Ijb,bj,Iia->ia', g.ov, T1old, LU11old)
    L1 += -1.0*einsum('I,Ibj,jiab->ia', G, U11old, L2old)
    L1 += -1.0*einsum('Ibj,I,jiab->ia', g.vo, S1old, L2old)
    # F_full used here
    L1 += 1.0*einsum('jk,bj,kiab->ia', F_full.oo, T1old, L2old)
    L1 += -1.0*einsum('bc,cj,jiab->ia', F_full.vv, T1old, L2old)
    L1 += 1.0*einsum('jiab,cbjk,kc->ia', I.oovv, T2old, L1old)
    L1 += 0.5*einsum('jibc,cbjk,ka->ia', I.oovv, T2old, L1old)
    L1 += 0.5*einsum('jkab,cbkj,ic->ia', I.oovv, T2old, L1old)
    L1 += -1.0*einsum('jika,Ibj,Ikb->ia', I.ooov, U11old, LU11old)
    L1 += 1.0*einsum('ibac,Icj,Ijb->ia', I.ovvv, U11old, LU11old)
    L1 += 1.0*einsum('jikb,Ibj,Ika->ia', I.ooov, U11old, LU11old)
    L1 += -1.0*einsum('jbac,Icj,Iib->ia', I.ovvv, U11old, LU11old)
    L1 += -0.5*einsum('ib,cbjk,kjac->ia', F.ov, T2old, L2old)
    L1 += -1.0*einsum('Iij,Ibk,jkab->ia', g.oo, U11old, L2old)
    L1 += -1.0*einsum('ibjc,ck,jkab->ia', I.ovov, T1old, L2old)
    L1 += 0.5*einsum('jikl,bj,lkab->ia', I.oooo, T1old, L2old)
    L1 += -0.5*einsum('ja,bcjk,kicb->ia', F.ov, T2old, L2old)
    L1 += 1.0*einsum('Iba,Icj,jicb->ia', g.vv, U11old, L2old)
    L1 += -1.0*einsum('jbka,cj,kicb->ia', I.ovov, T1old, L2old)
    L1 += 1.0*einsum('jb,cbjk,kiac->ia', F.ov, T2old, L2old)
    L1 += 1.0*einsum('Ijk,Ibj,kiab->ia', g.oo, U11old, L2old)
    L1 += -1.0*einsum('Ibc,Icj,jiab->ia', g.vv, U11old, L2old)
    L1 += 1.0*einsum('jbkc,cj,kiab->ia', I.ovov, T1old, L2old)
    L1 += 0.5*einsum('bcad,dj,jicb->ia', I.vvvv, T1old, L2old)
    L1 += 0.5*einsum('jika,bcjl,klcb->ia', I.ooov, T2old, L2old)
    L1 += -0.5*einsum('ibac,dcjk,kjdb->ia', I.ovvv, T2old, L2old)
    L1 += -1.0*einsum('jikb,cbjl,klac->ia', I.ooov, T2old, L2old)
    L1 += -0.25*einsum('ibcd,dcjk,kjab->ia', I.ovvv, T2old, L2old)
    L1 += 0.25*einsum('jkla,bckj,licb->ia', I.ooov, T2old, L2old)
    L1 += 1.0*einsum('jbac,dcjk,kidb->ia', I.ovvv, T2old, L2old)
    L1 += -0.5*einsum('jklb,cbkj,liac->ia', I.ooov, T2old, L2old)
    L1 += 0.5*einsum('jbcd,dcjk,kiab->ia', I.ovvv, T2old, L2old)
    L1 += -1.0*einsum('Iib,bj,I,ja->ia', g.ov, T1old, S1old, L1old)
    L1 += -1.0*einsum('Ija,bj,I,ib->ia', g.ov, T1old, S1old, L1old)
    L1 += 1.0*einsum('jiab,bk,cj,kc->ia', I.oovv, T1old, T1old, L1old)
    L1 += -1.0*einsum('jibc,ck,bj,ka->ia', I.oovv, T1old, T1old, L1old)
    L1 += -1.0*einsum('jkab,cj,bk,ic->ia', I.oovv, T1old, T1old, L1old)
    L1 += -1.0*einsum('Iib,I,Jbj,Jja->ia', g.ov, S1old, U11old, LU11old)
    L1 += -1.0*einsum('Ija,I,Jbj,Jib->ia', g.ov, S1old, U11old, LU11old)
    L1 += 1.0*einsum('Ijb,I,Jbj,Jia->ia', g.ov, S1old, U11old, LU11old)
    L1 += 1.0*einsum('jb,bk,cj,kiac->ia', F.ov, T1old, T1old, L2old)
    L1 += 1.0*einsum('Ijk,bj,I,kiab->ia', g.oo, T1old, S1old, L2old)
    L1 += -1.0*einsum('Ibc,cj,I,jiab->ia', g.vv, T1old, S1old, L2old)
    L1 += 1.0*einsum('jiab,cj,Ibk,Ikc->ia', I.oovv, T1old, U11old, LU11old)
    L1 += 1.0*einsum('jiab,bk,Icj,Ikc->ia', I.oovv, T1old, U11old, LU11old)
    L1 += -1.0*einsum('jibc,ck,Ibj,Ika->ia', I.oovv, T1old, U11old, LU11old)
    L1 += 1.0*einsum('jibc,cj,Ibk,Ika->ia', I.oovv, T1old, U11old, LU11old)
    L1 += -1.0*einsum('jkab,cj,Ibk,Iic->ia', I.oovv, T1old, U11old, LU11old)
    L1 += 1.0*einsum('jkab,bj,Ick,Iic->ia', I.oovv, T1old, U11old, LU11old)
    L1 += -1.0*einsum('jkbc,cj,Ibk,Iia->ia', I.oovv, T1old, U11old, LU11old)
    L1 += -1.0*einsum('Iib,bj,Ick,jkac->ia', g.ov, T1old, U11old, L2old)
    L1 += -0.5*einsum('Iib,cbjk,I,kjac->ia', g.ov, T2old, S1old, L2old)
    L1 += -1.0*einsum('jikb,bl,cj,klac->ia', I.ooov, T1old, T1old, L2old)
    L1 += 0.5*einsum('ibcd,dj,ck,jkab->ia', I.ovvv, T1old, T1old, L2old)
    L1 += -1.0*einsum('Ija,bj,Ick,kicb->ia', g.ov, T1old, U11old, L2old)
    L1 += 1.0*einsum('Ijb,cj,Ibk,kiac->ia', g.ov, T1old, U11old, L2old)
    L1 += 1.0*einsum('Ijb,bk,Icj,kiac->ia', g.ov, T1old, U11old, L2old)
    L1 += -1.0*einsum('Ijb,bj,Ick,kiac->ia', g.ov, T1old, U11old, L2old)
    L1 += -0.5*einsum('Ija,bcjk,I,kicb->ia', g.ov, T2old, S1old, L2old)
    L1 += 1.0*einsum('Ijb,cbjk,I,kiac->ia', g.ov, T2old, S1old, L2old)
    L1 += -0.5*einsum('jkla,bj,ck,licb->ia', I.ooov, T1old, T1old, L2old)
    L1 += 1.0*einsum('jbac,ck,dj,kidb->ia', I.ovvv, T1old, T1old, L2old)
    L1 += 1.0*einsum('jklb,cj,bk,liac->ia', I.ooov, T1old, T1old, L2old)
    L1 += -1.0*einsum('jbcd,dk,cj,kiab->ia', I.ovvv, T1old, T1old, L2old)
    L1 += -0.5*einsum('jiab,cj,dbkl,lkdc->ia', I.oovv, T1old, T2old, L2old)
    L1 += -0.5*einsum('jiab,bk,cdjl,kldc->ia', I.oovv, T1old, T2old, L2old)
    L1 += -0.25*einsum('jibc,dj,cbkl,lkad->ia', I.oovv, T1old, T2old, L2old)
    L1 += 1.0*einsum('jibc,ck,dbjl,klad->ia', I.oovv, T1old, T2old, L2old)
    L1 += 0.5*einsum('jibc,cj,dbkl,lkad->ia', I.oovv, T1old, T2old, L2old)
    L1 += 1.0*einsum('jkab,cj,dbkl,lidc->ia', I.oovv, T1old, T2old, L2old)
    L1 += -0.25*einsum('jkab,bl,cdkj,lidc->ia', I.oovv, T1old, T2old, L2old)
    L1 += 0.5*einsum('jkab,bj,cdkl,lidc->ia', I.oovv, T1old, T2old, L2old)
    L1 += 0.5*einsum('jkbc,dj,cbkl,liad->ia', I.oovv, T1old, T2old, L2old)
    L1 += 0.5*einsum('jkbc,cl,dbkj,liad->ia', I.oovv, T1old, T2old, L2old)
    L1 += -1.0*einsum('jkbc,cj,dbkl,liad->ia', I.oovv, T1old, T2old, L2old)
    L1 += 1.0*einsum('Ijb,bk,cj,I,kiac->ia', g.ov, T1old, T1old, S1old, L2old)
    L1 += 0.5*einsum('jibc,ck,bl,dj,klad->ia', I.oovv, T1old, T1old, T1old, L2old)
    L1 += 0.5*einsum('jkab,bl,cj,dk,lidc->ia', I.oovv, T1old, T1old, T1old, L2old)
    L1 += -1.0*einsum('jkbc,cl,dj,bk,liad->ia', I.oovv, T1old, T1old, T1old, L2old)

    # Connected piece not proportional to Lambda...
    L2 = I.oovv.transpose(1,0,3,2).copy()

    # Connected piece proportional to Lambda...
    L2 += 1.0*einsum('jikb,ka->ijab', I.ooov, L1old)
    L2 += -1.0*einsum('jika,kb->ijab', I.ooov, L1old)
    L2 += 1.0*einsum('jcba,ic->ijab', I.ovvv, L1old)
    L2 += -1.0*einsum('icba,jc->ijab', I.ovvv, L1old)
    L2 += 1.0*einsum('Ijb,Iia->ijab', g.ov, LU11old)
    L2 += -1.0*einsum('Ija,Iib->ijab', g.ov, LU11old)
    L2 += -1.0*einsum('Iib,Ija->ijab', g.ov, LU11old)
    L2 += 1.0*einsum('Iia,Ijb->ijab', g.ov, LU11old)
    L2 += -1.0*einsum('jk,kiba->ijab', F.oo, L2old)
    L2 += 1.0*einsum('ik,kjba->ijab', F.oo, L2old)
    L2 += -1.0*einsum('cb,jiac->ijab', F.vv, L2old)
    L2 += 1.0*einsum('ca,jibc->ijab', F.vv, L2old)
    L2 += -0.5*einsum('jikl,lkba->ijab', I.oooo, L2old)
    L2 += 1.0*einsum('jckb,kiac->ijab', I.ovov, L2old)
    L2 += -1.0*einsum('jcka,kibc->ijab', I.ovov, L2old)
    L2 += -1.0*einsum('ickb,kjac->ijab', I.ovov, L2old)
    L2 += 1.0*einsum('icka,kjbc->ijab', I.ovov, L2old)
    L2 += -0.5*einsum('cdba,jidc->ijab', I.vvvv, L2old)
    L2 += -1.0*einsum('jibc,ck,ka->ijab', I.oovv, T1old, L1old)
    L2 += 1.0*einsum('jiac,ck,kb->ijab', I.oovv, T1old, L1old)
    L2 += 1.0*einsum('kjba,ck,ic->ijab', I.oovv, T1old, L1old)
    L2 += -1.0*einsum('kiba,ck,jc->ijab', I.oovv, T1old, L1old)
    L2 += -1.0*einsum('jc,ck,kiba->ijab', F.ov, T1old, L2old)
    L2 += 1.0*einsum('ic,ck,kjba->ijab', F.ov, T1old, L2old)
    L2 += -1.0*einsum('Ijk,I,kiba->ijab', g.oo, S1old, L2old)
    L2 += 1.0*einsum('Iik,I,kjba->ijab', g.oo, S1old, L2old)
    L2 += 1.0*einsum('kb,ck,jiac->ijab', F.ov, T1old, L2old)
    L2 += -1.0*einsum('ka,ck,jibc->ijab', F.ov, T1old, L2old)
    L2 += -1.0*einsum('Icb,I,jiac->ijab', g.vv, S1old, L2old)
    L2 += 1.0*einsum('Ica,I,jibc->ijab', g.vv, S1old, L2old)
    L2 += -1.0*einsum('jibc,Ick,Ika->ijab', I.oovv, U11old, LU11old)
    L2 += 1.0*einsum('jiac,Ick,Ikb->ijab', I.oovv, U11old, LU11old)
    L2 += 1.0*einsum('kjba,Ick,Iic->ijab', I.oovv, U11old, LU11old)
    L2 += -1.0*einsum('kjbc,Ick,Iia->ijab', I.oovv, U11old, LU11old)
    L2 += 1.0*einsum('kjac,Ick,Iib->ijab', I.oovv, U11old, LU11old)
    L2 += -1.0*einsum('kiba,Ick,Ijc->ijab', I.oovv, U11old, LU11old)
    L2 += 1.0*einsum('kibc,Ick,Ija->ijab', I.oovv, U11old, LU11old)
    L2 += -1.0*einsum('kiac,Ick,Ijb->ijab', I.oovv, U11old, LU11old)
    L2 += 1.0*einsum('jikc,cl,klba->ijab', I.ooov, T1old, L2old)
    L2 += -1.0*einsum('Ijb,Ick,kiac->ijab', g.ov, U11old, L2old)
    L2 += 1.0*einsum('Ija,Ick,kibc->ijab', g.ov, U11old, L2old)
    L2 += -1.0*einsum('Ijc,Ick,kiba->ijab', g.ov, U11old, L2old)
    L2 += 1.0*einsum('Iib,Ick,kjac->ijab', g.ov, U11old, L2old)
    L2 += -1.0*einsum('Iia,Ick,kjbc->ijab', g.ov, U11old, L2old)
    L2 += 1.0*einsum('Iic,Ick,kjba->ijab', g.ov, U11old, L2old)
    L2 += 1.0*einsum('kjlb,ck,liac->ijab', I.ooov, T1old, L2old)
    L2 += -1.0*einsum('jcbd,dk,kiac->ijab', I.ovvv, T1old, L2old)
    L2 += -1.0*einsum('kjla,ck,libc->ijab', I.ooov, T1old, L2old)
    L2 += 1.0*einsum('jcad,dk,kibc->ijab', I.ovvv, T1old, L2old)
    L2 += 1.0*einsum('kjlc,ck,liba->ijab', I.ooov, T1old, L2old)
    L2 += -1.0*einsum('kilb,ck,ljac->ijab', I.ooov, T1old, L2old)
    L2 += 1.0*einsum('icbd,dk,kjac->ijab', I.ovvv, T1old, L2old)
    L2 += 1.0*einsum('kila,ck,ljbc->ijab', I.ooov, T1old, L2old)
    L2 += -1.0*einsum('icad,dk,kjbc->ijab', I.ovvv, T1old, L2old)
    L2 += -1.0*einsum('kilc,ck,ljba->ijab', I.ooov, T1old, L2old)
    L2 += 1.0*einsum('Ikb,Ick,jiac->ijab', g.ov, U11old, L2old)
    L2 += -1.0*einsum('Ika,Ick,jibc->ijab', g.ov, U11old, L2old)
    L2 += -1.0*einsum('kcba,dk,jidc->ijab', I.ovvv, T1old, L2old)
    L2 += 1.0*einsum('kcbd,dk,jiac->ijab', I.ovvv, T1old, L2old)
    L2 += -1.0*einsum('kcad,dk,jibc->ijab', I.ovvv, T1old, L2old)
    L2 += -0.5*einsum('jibc,dckl,lkad->ijab', I.oovv, T2old, L2old)
    L2 += 0.5*einsum('jiac,dckl,lkbd->ijab', I.oovv, T2old, L2old)
    L2 += 0.25*einsum('jicd,dckl,lkba->ijab', I.oovv, T2old, L2old)
    L2 += 0.5*einsum('kjba,cdkl,lidc->ijab', I.oovv, T2old, L2old)
    L2 += -1.0*einsum('kjbc,dckl,liad->ijab', I.oovv, T2old, L2old)
    L2 += 1.0*einsum('kjac,dckl,libd->ijab', I.oovv, T2old, L2old)
    L2 += 0.5*einsum('kjcd,dckl,liba->ijab', I.oovv, T2old, L2old)
    L2 += -0.5*einsum('kiba,cdkl,ljdc->ijab', I.oovv, T2old, L2old)
    L2 += 1.0*einsum('kibc,dckl,ljad->ijab', I.oovv, T2old, L2old)
    L2 += -1.0*einsum('kiac,dckl,ljbd->ijab', I.oovv, T2old, L2old)
    L2 += -0.5*einsum('kicd,dckl,ljba->ijab', I.oovv, T2old, L2old)
    L2 += 0.25*einsum('klba,cdlk,jidc->ijab', I.oovv, T2old, L2old)
    L2 += -0.5*einsum('klbc,dclk,jiad->ijab', I.oovv, T2old, L2old)
    L2 += 0.5*einsum('klac,dclk,jibd->ijab', I.oovv, T2old, L2old)
    L2 += -1.0*einsum('Ijc,ck,I,kiba->ijab', g.ov, T1old, S1old, L2old)
    L2 += 1.0*einsum('Iic,ck,I,kjba->ijab', g.ov, T1old, S1old, L2old)
    L2 += 1.0*einsum('Ikb,ck,I,jiac->ijab', g.ov, T1old, S1old, L2old)
    L2 += -1.0*einsum('Ika,ck,I,jibc->ijab', g.ov, T1old, S1old, L2old)
    L2 += -0.5*einsum('jicd,dk,cl,klba->ijab', I.oovv, T1old, T1old, L2old)
    L2 += -1.0*einsum('kjbc,cl,dk,liad->ijab', I.oovv, T1old, T1old, L2old)
    L2 += 1.0*einsum('kjac,cl,dk,libd->ijab', I.oovv, T1old, T1old, L2old)
    L2 += -1.0*einsum('kjcd,dl,ck,liba->ijab', I.oovv, T1old, T1old, L2old)
    L2 += 1.0*einsum('kibc,cl,dk,ljad->ijab', I.oovv, T1old, T1old, L2old)
    L2 += -1.0*einsum('kiac,cl,dk,ljbd->ijab', I.oovv, T1old, T1old, L2old)
    L2 += 1.0*einsum('kicd,dl,ck,ljba->ijab', I.oovv, T1old, T1old, L2old)
    L2 += -0.5*einsum('klba,ck,dl,jidc->ijab', I.oovv, T1old, T1old, L2old)
    L2 += 1.0*einsum('klbc,dk,cl,jiad->ijab', I.oovv, T1old, T1old, L2old)
    L2 += -1.0*einsum('klac,dk,cl,jibd->ijab', I.oovv, T1old, T1old, L2old)

    # Disconnected piece projecting onto single fermionic excitations...
    L2 += 1.0*einsum('jb,ia->ijab', L1old, F.ov)
    L2 += -1.0*einsum('ja,ib->ijab', L1old, F.ov)
    L2 += -1.0*einsum('ib,ja->ijab', L1old, F.ov)
    L2 += 1.0*einsum('ia,jb->ijab', L1old, F.ov)
    L2 += 1.0*einsum('I,jb,Iia->ijab', S1old, L1old, g.ov)
    L2 += -1.0*einsum('I,ja,Iib->ijab', S1old, L1old, g.ov)
    L2 += -1.0*einsum('I,ib,Ija->ijab', S1old, L1old, g.ov)
    L2 += 1.0*einsum('I,ia,Ijb->ijab', S1old, L1old, g.ov)
    L2 += -1.0*einsum('ck,jb,kiac->ijab', T1old, L1old, I.oovv)
    L2 += 1.0*einsum('ck,ja,kibc->ijab', T1old, L1old, I.oovv)
    L2 += 1.0*einsum('ck,ib,kjac->ijab', T1old, L1old, I.oovv)
    L2 += -1.0*einsum('ck,ia,kjbc->ijab', T1old, L1old, I.oovv)

    # Connected piece not proportional to Lambda...
    LS1 = G.copy()
    LS1 += 1.0*einsum('ai,Iia->I', T1old, g.ov)

    # Connected piece proportional to Lambda...
    LS1 += 1.0*einsum('JI,J->I', w, LS1old)
    LS1 += 1.0*einsum('Iai,ia->I', g.vo, L1old)
    LS1 += 1.0*einsum('ai,Iia->I', F.vo, LU11old)
    LS1 += 1.0*einsum('Iia,Jai,J->I', g.ov, U11old, LS1old)
    LS1 += -1.0*einsum('Iij,ai,ja->I', g.oo, T1old, L1old)
    LS1 += 1.0*einsum('Iab,bi,ia->I', g.vv, T1old, L1old)
    LS1 += 1.0*einsum('J,Jai,Iia->I', G, U11old, LU11old)
    LS1 += 1.0*einsum('Jai,J,Iia->I', g.vo, S1old, LU11old)
    # NOTE: Does this want to be full F?
    LS1 += -1.0*einsum('ij,ai,Ija->I', F_full.oo, T1old, LU11old)
    LS1 += 1.0*einsum('ab,bi,Iia->I', F_full.vv, T1old, LU11old)
    LS1 += -1.0*einsum('Iia,baij,jb->I', g.ov, T2old, L1old)
    LS1 += -1.0*einsum('Iij,Jai,Jja->I', g.oo, U11old, LU11old)
    LS1 += 1.0*einsum('Iab,Jbi,Jia->I', g.vv, U11old, LU11old)
    LS1 += -1.0*einsum('ia,baij,Ijb->I', F.ov, T2old, LU11old)
    LS1 += -1.0*einsum('Jij,Jai,Ija->I', g.oo, U11old, LU11old)
    LS1 += 1.0*einsum('Jab,Jbi,Iia->I', g.vv, U11old, LU11old)
    LS1 += -1.0*einsum('iajb,bi,Ija->I', I.ovov, T1old, LU11old)
    LS1 += 0.5*einsum('ijka,baji,Ikb->I', I.ooov, T2old, LU11old)
    LS1 += -0.5*einsum('iabc,cbij,Ija->I', I.ovvv, T2old, LU11old)
    LS1 += 0.5*einsum('Iij,abik,jkba->I', g.oo, T2old, L2old)
    LS1 += -0.5*einsum('Iab,cbij,jica->I', g.vv, T2old, L2old)
    LS1 += -1.0*einsum('Iia,aj,bi,jb->I', g.ov, T1old, T1old, L1old)
    LS1 += -1.0*einsum('ia,aj,bi,Ijb->I', F.ov, T1old, T1old, LU11old)
    LS1 += -1.0*einsum('Jij,ai,J,Ija->I', g.oo, T1old, S1old, LU11old)
    LS1 += 1.0*einsum('Jab,bi,J,Iia->I', g.vv, T1old, S1old, LU11old)
    LS1 += -1.0*einsum('Iia,bi,Jaj,Jjb->I', g.ov, T1old, U11old, LU11old)
    LS1 += -1.0*einsum('Iia,aj,Jbi,Jjb->I', g.ov, T1old, U11old, LU11old)
    LS1 += -1.0*einsum('Jia,bi,Jaj,Ijb->I', g.ov, T1old, U11old, LU11old)
    LS1 += -1.0*einsum('Jia,aj,Jbi,Ijb->I', g.ov, T1old, U11old, LU11old)
    LS1 += 1.0*einsum('Jia,ai,Jbj,Ijb->I', g.ov, T1old, U11old, LU11old)
    LS1 += -1.0*einsum('Jia,baij,J,Ijb->I', g.ov, T2old, S1old, LU11old)
    LS1 += -1.0*einsum('ijka,bi,aj,Ikb->I', I.ooov, T1old, T1old, LU11old)
    LS1 += 1.0*einsum('iabc,cj,bi,Ija->I', I.ovvv, T1old, T1old, LU11old)
    LS1 += -0.5*einsum('ijab,ci,bajk,Ikc->I', I.oovv, T1old, T2old, LU11old)
    LS1 += -0.5*einsum('ijab,bk,caji,Ikc->I', I.oovv, T1old, T2old, LU11old)
    LS1 += 1.0*einsum('ijab,bi,cajk,Ikc->I', I.oovv, T1old, T2old, LU11old)
    LS1 += 0.5*einsum('Iia,bi,cajk,kjcb->I', g.ov, T1old, T2old, L2old)
    LS1 += 0.5*einsum('Iia,aj,bcik,jkcb->I', g.ov, T1old, T2old, L2old)
    LS1 += -1.0*einsum('Jia,aj,bi,J,Ijb->I', g.ov, T1old, T1old, S1old, LU11old)
    LS1 += 1.0*einsum('ijab,bk,ci,aj,Ikc->I', I.oovv, T1old, T1old, T1old, LU11old)

    # Lambda residuals for 1 boson + 1 fermion deexcitation space...
    # Connected piece not proportional to Lambda...
    LU11 = g.ov.copy()

    # Connected piece proportional to Lambda...
    LU11 += -1.0*einsum('Iij,ja->Iia', g.oo, L1old)
    LU11 += 1.0*einsum('Iba,ib->Iia', g.vv, L1old)
    # Three terms below have had their diagonal removed
    LU11 += 1.0*einsum('JI,Jia->Iia', w, LU11old)
    LU11 += -1.0*einsum('ij,Ija->Iia', F.oo, LU11old)
    LU11 += 1.0*einsum('ba,Iib->Iia', F.vv, LU11old)
    LU11 += -1.0*einsum('ibja,Ijb->Iia', I.ovov, LU11old)
    LU11 += -1.0*einsum('Ibj,jiab->Iia', g.vo, L2old)
    LU11 += -1.0*einsum('Iib,bj,ja->Iia', g.ov, T1old, L1old)
    LU11 += -1.0*einsum('Ija,bj,ib->Iia', g.ov, T1old, L1old)
    LU11 += -1.0*einsum('ib,bj,Ija->Iia', F.ov, T1old, LU11old)
    LU11 += -1.0*einsum('ja,bj,Iib->Iia', F.ov, T1old, LU11old)
    LU11 += -1.0*einsum('Jij,J,Ija->Iia', g.oo, S1old, LU11old)
    LU11 += 1.0*einsum('Jba,J,Iib->Iia', g.vv, S1old, LU11old)
    LU11 += -1.0*einsum('Iib,Jbj,Jja->Iia', g.ov, U11old, LU11old)
    LU11 += -1.0*einsum('Ija,Jbj,Jib->Iia', g.ov, U11old, LU11old)
    LU11 += 1.0*einsum('Ijb,Jbj,Jia->Iia', g.ov, U11old, LU11old)
    LU11 += 1.0*einsum('Jia,Jbj,Ijb->Iia', g.ov, U11old, LU11old)
    LU11 += -1.0*einsum('Jib,Jbj,Ija->Iia', g.ov, U11old, LU11old)
    LU11 += -1.0*einsum('Jja,Jbj,Iib->Iia', g.ov, U11old, LU11old)
    LU11 += -1.0*einsum('jika,bj,Ikb->Iia', I.ooov, T1old, LU11old)
    LU11 += 1.0*einsum('ibac,cj,Ijb->Iia', I.ovvv, T1old, LU11old)
    LU11 += 1.0*einsum('jikb,bj,Ika->Iia', I.ooov, T1old, LU11old)
    LU11 += -1.0*einsum('jbac,cj,Iib->Iia', I.ovvv, T1old, LU11old)
    LU11 += 1.0*einsum('Ijk,bj,kiab->Iia', g.oo, T1old, L2old)
    LU11 += -1.0*einsum('Ibc,cj,jiab->Iia', g.vv, T1old, L2old)
    LU11 += 1.0*einsum('jiab,cbjk,Ikc->Iia', I.oovv, T2old, LU11old)
    LU11 += 0.5*einsum('jibc,cbjk,Ika->Iia', I.oovv, T2old, LU11old)
    LU11 += 0.5*einsum('jkab,cbkj,Iic->Iia', I.oovv, T2old, LU11old)
    LU11 += -0.5*einsum('Iib,cbjk,kjac->Iia', g.ov, T2old, L2old)
    LU11 += -0.5*einsum('Ija,bcjk,kicb->Iia', g.ov, T2old, L2old)
    LU11 += 1.0*einsum('Ijb,cbjk,kiac->Iia', g.ov, T2old, L2old)
    LU11 += -1.0*einsum('Jib,bj,J,Ija->Iia', g.ov, T1old, S1old, LU11old)
    LU11 += -1.0*einsum('Jja,bj,J,Iib->Iia', g.ov, T1old, S1old, LU11old)
    LU11 += 1.0*einsum('jiab,bk,cj,Ikc->Iia', I.oovv, T1old, T1old, LU11old)
    LU11 += -1.0*einsum('jibc,ck,bj,Ika->Iia', I.oovv, T1old, T1old, LU11old)
    LU11 += -1.0*einsum('jkab,cj,bk,Iic->Iia', I.oovv, T1old, T1old, LU11old)
    LU11 += 1.0*einsum('Ijb,bk,cj,kiac->Iia', g.ov, T1old, T1old, L2old)

    # Disconnected piece projecting onto single fermionic excitations...
    LU11 += 1.0*einsum('I,ia->Iia', LS1old, F.ov)
    LU11 += 1.0*einsum('J,I,Jia->Iia', S1old, LS1old, g.ov)
    LU11 += -1.0*einsum('bj,I,jiab->Iia', T1old, LS1old, I.oovv)

    # Disconnected piece projecting onto single bosonic excitations...
    LU11 += 1.0*einsum('I,ia->Iia', LS1old, F.ov)
    LU11 += 1.0*einsum('J,I,Jia->Iia', S1old, LS1old, g.ov)
    LU11 += -1.0*einsum('bj,I,jiab->Iia', T1old, LS1old, I.oovv)

    return L1, L2, LS1, LU11

def calc_lam_resid_1_1(F, I, G, g, w_diag, T1old, L1old, T2old, L2old, S1old, LS1old, U11old, LU11old):
    ''' Compute the norm of the residual for the lambda equations (debugging) '''

    w = np.diag(w_diag)

# lambda residuals for 1 fermion deexcitation space...
# connected piece not proportional to Lambda...
    L1 = 1.0*einsum('ia->ia', F.ov)
    L1 += 1.0*einsum('I,Iia->ia', S1old, g.ov)
    L1 += -1.0*einsum('bj,jiab->ia', T1old, I.oovv)

#Computing connected piece proportional to Lambda...
    L1 += 1.0*einsum('Iia,I->ia', g.ov, LS1old)
    L1 += -1.0*einsum('ij,ja->ia', F.oo, L1old)
    L1 += 1.0*einsum('ba,ib->ia', F.vv, L1old)
    L1 += 1.0*einsum('I,Iia->ia', G, LU11old)
    L1 += -1.0*einsum('ibja,jb->ia', I.ovov, L1old)
    L1 += -1.0*einsum('Iij,Ija->ia', g.oo, LU11old)
    L1 += 1.0*einsum('Iba,Iib->ia', g.vv, LU11old)
    L1 += -1.0*einsum('bj,jiab->ia', F.vo, L2old)
    L1 += 0.5*einsum('ibjk,kjab->ia', I.ovoo, L2old)
    L1 += -0.5*einsum('bcja,jicb->ia', I.vvov, L2old)
    L1 += -1.0*einsum('ib,bj,ja->ia', F.ov, T1old, L1old)
    L1 += -1.0*einsum('Iij,I,ja->ia', g.oo, S1old, L1old)
    L1 += -1.0*einsum('ja,bj,ib->ia', F.ov, T1old, L1old)
    L1 += 1.0*einsum('Iba,I,ib->ia', g.vv, S1old, L1old)
    L1 += 1.0*einsum('IJ,J,Iia->ia', w, S1old, LU11old)
    L1 += -1.0*einsum('jiab,Ibj,I->ia', I.oovv, U11old, LS1old)
    L1 += 1.0*einsum('Iia,Ibj,jb->ia', g.ov, U11old, L1old)
    L1 += -1.0*einsum('jika,bj,kb->ia', I.ooov, T1old, L1old)
    L1 += 1.0*einsum('ibac,cj,jb->ia', I.ovvv, T1old, L1old)
    L1 += -1.0*einsum('Iib,Ibj,ja->ia', g.ov, U11old, L1old)
    L1 += 1.0*einsum('jikb,bj,ka->ia', I.ooov, T1old, L1old)
    L1 += -1.0*einsum('Ija,Ibj,ib->ia', g.ov, U11old, L1old)
    L1 += -1.0*einsum('jbac,cj,ib->ia', I.ovvv, T1old, L1old)
    L1 += -1.0*einsum('ib,Ibj,Ija->ia', F.ov, U11old, LU11old)
    L1 += -1.0*einsum('Iib,bj,Ija->ia', g.ov, T1old, LU11old)
    L1 += -1.0*einsum('ja,Ibj,Iib->ia', F.ov, U11old, LU11old)
    L1 += -1.0*einsum('Ija,bj,Iib->ia', g.ov, T1old, LU11old)
    L1 += 1.0*einsum('jb,Ibj,Iia->ia', F.ov, U11old, LU11old)
    L1 += 1.0*einsum('Ijb,bj,Iia->ia', g.ov, T1old, LU11old)
    L1 += -1.0*einsum('I,Ibj,jiab->ia', G, U11old, L2old)
    L1 += -1.0*einsum('Ibj,I,jiab->ia', g.vo, S1old, L2old)
    L1 += 1.0*einsum('jk,bj,kiab->ia', F.oo, T1old, L2old)
    L1 += -1.0*einsum('bc,cj,jiab->ia', F.vv, T1old, L2old)
    L1 += 1.0*einsum('jiab,cbjk,kc->ia', I.oovv, T2old, L1old)
    L1 += 0.5*einsum('jibc,cbjk,ka->ia', I.oovv, T2old, L1old)
    L1 += 0.5*einsum('jkab,cbkj,ic->ia', I.oovv, T2old, L1old)
    L1 += -1.0*einsum('jika,Ibj,Ikb->ia', I.ooov, U11old, LU11old)
    L1 += 1.0*einsum('ibac,Icj,Ijb->ia', I.ovvv, U11old, LU11old)
    L1 += 1.0*einsum('jikb,Ibj,Ika->ia', I.ooov, U11old, LU11old)
    L1 += -1.0*einsum('jbac,Icj,Iib->ia', I.ovvv, U11old, LU11old)
    L1 += -0.5*einsum('ib,cbjk,kjac->ia', F.ov, T2old, L2old)
    L1 += -1.0*einsum('Iij,Ibk,jkab->ia', g.oo, U11old, L2old)
    L1 += -1.0*einsum('ibjc,ck,jkab->ia', I.ovov, T1old, L2old)
    L1 += 0.5*einsum('jikl,bj,lkab->ia', I.oooo, T1old, L2old)
    L1 += -0.5*einsum('ja,bcjk,kicb->ia', F.ov, T2old, L2old)
    L1 += 1.0*einsum('Iba,Icj,jicb->ia', g.vv, U11old, L2old)
    L1 += -1.0*einsum('jbka,cj,kicb->ia', I.ovov, T1old, L2old)
    L1 += 1.0*einsum('jb,cbjk,kiac->ia', F.ov, T2old, L2old)
    L1 += 1.0*einsum('Ijk,Ibj,kiab->ia', g.oo, U11old, L2old)
    L1 += -1.0*einsum('Ibc,Icj,jiab->ia', g.vv, U11old, L2old)
    L1 += 1.0*einsum('jbkc,cj,kiab->ia', I.ovov, T1old, L2old)
    L1 += 0.5*einsum('bcad,dj,jicb->ia', I.vvvv, T1old, L2old)
    L1 += 0.5*einsum('jika,bcjl,klcb->ia', I.ooov, T2old, L2old)
    L1 += -0.5*einsum('ibac,dcjk,kjdb->ia', I.ovvv, T2old, L2old)
    L1 += -1.0*einsum('jikb,cbjl,klac->ia', I.ooov, T2old, L2old)
    L1 += -0.25*einsum('ibcd,dcjk,kjab->ia', I.ovvv, T2old, L2old)
    L1 += 0.25*einsum('jkla,bckj,licb->ia', I.ooov, T2old, L2old)
    L1 += 1.0*einsum('jbac,dcjk,kidb->ia', I.ovvv, T2old, L2old)
    L1 += -0.5*einsum('jklb,cbkj,liac->ia', I.ooov, T2old, L2old)
    L1 += 0.5*einsum('jbcd,dcjk,kiab->ia', I.ovvv, T2old, L2old)
    L1 += -1.0*einsum('Iib,bj,I,ja->ia', g.ov, T1old, S1old, L1old)
    L1 += -1.0*einsum('Ija,bj,I,ib->ia', g.ov, T1old, S1old, L1old)
    L1 += 1.0*einsum('jiab,bk,cj,kc->ia', I.oovv, T1old, T1old, L1old)
    L1 += -1.0*einsum('jibc,ck,bj,ka->ia', I.oovv, T1old, T1old, L1old)
    L1 += -1.0*einsum('jkab,cj,bk,ic->ia', I.oovv, T1old, T1old, L1old)
    L1 += -1.0*einsum('Iib,I,Jbj,Jja->ia', g.ov, S1old, U11old, LU11old)
    L1 += -1.0*einsum('Ija,I,Jbj,Jib->ia', g.ov, S1old, U11old, LU11old)
    L1 += 1.0*einsum('Ijb,I,Jbj,Jia->ia', g.ov, S1old, U11old, LU11old)
    L1 += 1.0*einsum('jb,bk,cj,kiac->ia', F.ov, T1old, T1old, L2old)
    L1 += 1.0*einsum('Ijk,bj,I,kiab->ia', g.oo, T1old, S1old, L2old)
    L1 += -1.0*einsum('Ibc,cj,I,jiab->ia', g.vv, T1old, S1old, L2old)
    L1 += 1.0*einsum('jiab,cj,Ibk,Ikc->ia', I.oovv, T1old, U11old, LU11old)
    L1 += 1.0*einsum('jiab,bk,Icj,Ikc->ia', I.oovv, T1old, U11old, LU11old)
    L1 += -1.0*einsum('jibc,ck,Ibj,Ika->ia', I.oovv, T1old, U11old, LU11old)
    L1 += 1.0*einsum('jibc,cj,Ibk,Ika->ia', I.oovv, T1old, U11old, LU11old)
    L1 += -1.0*einsum('jkab,cj,Ibk,Iic->ia', I.oovv, T1old, U11old, LU11old)
    L1 += 1.0*einsum('jkab,bj,Ick,Iic->ia', I.oovv, T1old, U11old, LU11old)
    L1 += -1.0*einsum('jkbc,cj,Ibk,Iia->ia', I.oovv, T1old, U11old, LU11old)
    L1 += -1.0*einsum('Iib,bj,Ick,jkac->ia', g.ov, T1old, U11old, L2old)
    L1 += -0.5*einsum('Iib,cbjk,I,kjac->ia', g.ov, T2old, S1old, L2old)
    L1 += -1.0*einsum('jikb,bl,cj,klac->ia', I.ooov, T1old, T1old, L2old)
    L1 += 0.5*einsum('ibcd,dj,ck,jkab->ia', I.ovvv, T1old, T1old, L2old)
    L1 += -1.0*einsum('Ija,bj,Ick,kicb->ia', g.ov, T1old, U11old, L2old)
    L1 += 1.0*einsum('Ijb,cj,Ibk,kiac->ia', g.ov, T1old, U11old, L2old)
    L1 += 1.0*einsum('Ijb,bk,Icj,kiac->ia', g.ov, T1old, U11old, L2old)
    L1 += -1.0*einsum('Ijb,bj,Ick,kiac->ia', g.ov, T1old, U11old, L2old)
    L1 += -0.5*einsum('Ija,bcjk,I,kicb->ia', g.ov, T2old, S1old, L2old)
    L1 += 1.0*einsum('Ijb,cbjk,I,kiac->ia', g.ov, T2old, S1old, L2old)
    L1 += -0.5*einsum('jkla,bj,ck,licb->ia', I.ooov, T1old, T1old, L2old)
    L1 += 1.0*einsum('jbac,ck,dj,kidb->ia', I.ovvv, T1old, T1old, L2old)
    L1 += 1.0*einsum('jklb,cj,bk,liac->ia', I.ooov, T1old, T1old, L2old)
    L1 += -1.0*einsum('jbcd,dk,cj,kiab->ia', I.ovvv, T1old, T1old, L2old)
    L1 += -0.5*einsum('jiab,cj,dbkl,lkdc->ia', I.oovv, T1old, T2old, L2old)
    L1 += -0.5*einsum('jiab,bk,cdjl,kldc->ia', I.oovv, T1old, T2old, L2old)
    L1 += -0.25*einsum('jibc,dj,cbkl,lkad->ia', I.oovv, T1old, T2old, L2old)
    L1 += 1.0*einsum('jibc,ck,dbjl,klad->ia', I.oovv, T1old, T2old, L2old)
    L1 += 0.5*einsum('jibc,cj,dbkl,lkad->ia', I.oovv, T1old, T2old, L2old)
    L1 += 1.0*einsum('jkab,cj,dbkl,lidc->ia', I.oovv, T1old, T2old, L2old)
    L1 += -0.25*einsum('jkab,bl,cdkj,lidc->ia', I.oovv, T1old, T2old, L2old)
    L1 += 0.5*einsum('jkab,bj,cdkl,lidc->ia', I.oovv, T1old, T2old, L2old)
    L1 += 0.5*einsum('jkbc,dj,cbkl,liad->ia', I.oovv, T1old, T2old, L2old)
    L1 += 0.5*einsum('jkbc,cl,dbkj,liad->ia', I.oovv, T1old, T2old, L2old)
    L1 += -1.0*einsum('jkbc,cj,dbkl,liad->ia', I.oovv, T1old, T2old, L2old)
    L1 += 1.0*einsum('Ijb,bk,cj,I,kiac->ia', g.ov, T1old, T1old, S1old, L2old)
    L1 += 0.5*einsum('jibc,ck,bl,dj,klad->ia', I.oovv, T1old, T1old, T1old, L2old)
    L1 += 0.5*einsum('jkab,bl,cj,dk,lidc->ia', I.oovv, T1old, T1old, T1old, L2old)
    L1 += -1.0*einsum('jkbc,cl,dj,bk,liad->ia', I.oovv, T1old, T1old, T1old, L2old)

# lambda residuals for 2 fermion deexcitation space...
# connected piece not proportional to Lambda...
    L2 = 1.0*einsum('jiba->ijab', I.oovv)

# connected piece proportional to Lambda...
    L2 += 1.0*einsum('jikb,ka->ijab', I.ooov, L1old)
    L2 += -1.0*einsum('jika,kb->ijab', I.ooov, L1old)
    L2 += 1.0*einsum('jcba,ic->ijab', I.ovvv, L1old)
    L2 += -1.0*einsum('icba,jc->ijab', I.ovvv, L1old)
    L2 += 1.0*einsum('Ijb,Iia->ijab', g.ov, LU11old)
    L2 += -1.0*einsum('Ija,Iib->ijab', g.ov, LU11old)
    L2 += -1.0*einsum('Iib,Ija->ijab', g.ov, LU11old)
    L2 += 1.0*einsum('Iia,Ijb->ijab', g.ov, LU11old)
    L2 += -1.0*einsum('jk,kiba->ijab', F.oo, L2old)
    L2 += 1.0*einsum('ik,kjba->ijab', F.oo, L2old)
    L2 += -1.0*einsum('cb,jiac->ijab', F.vv, L2old)
    L2 += 1.0*einsum('ca,jibc->ijab', F.vv, L2old)
    L2 += -0.5*einsum('jikl,lkba->ijab', I.oooo, L2old)
    L2 += 1.0*einsum('jckb,kiac->ijab', I.ovov, L2old)
    L2 += -1.0*einsum('jcka,kibc->ijab', I.ovov, L2old)
    L2 += -1.0*einsum('ickb,kjac->ijab', I.ovov, L2old)
    L2 += 1.0*einsum('icka,kjbc->ijab', I.ovov, L2old)
    L2 += -0.5*einsum('cdba,jidc->ijab', I.vvvv, L2old)
    L2 += -1.0*einsum('jibc,ck,ka->ijab', I.oovv, T1old, L1old)
    L2 += 1.0*einsum('jiac,ck,kb->ijab', I.oovv, T1old, L1old)
    L2 += 1.0*einsum('kjba,ck,ic->ijab', I.oovv, T1old, L1old)
    L2 += -1.0*einsum('kiba,ck,jc->ijab', I.oovv, T1old, L1old)
    L2 += -1.0*einsum('jc,ck,kiba->ijab', F.ov, T1old, L2old)
    L2 += 1.0*einsum('ic,ck,kjba->ijab', F.ov, T1old, L2old)
    L2 += -1.0*einsum('Ijk,I,kiba->ijab', g.oo, S1old, L2old)
    L2 += 1.0*einsum('Iik,I,kjba->ijab', g.oo, S1old, L2old)
    L2 += 1.0*einsum('kb,ck,jiac->ijab', F.ov, T1old, L2old)
    L2 += -1.0*einsum('ka,ck,jibc->ijab', F.ov, T1old, L2old)
    L2 += -1.0*einsum('Icb,I,jiac->ijab', g.vv, S1old, L2old)
    L2 += 1.0*einsum('Ica,I,jibc->ijab', g.vv, S1old, L2old)
    L2 += -1.0*einsum('jibc,Ick,Ika->ijab', I.oovv, U11old, LU11old)
    L2 += 1.0*einsum('jiac,Ick,Ikb->ijab', I.oovv, U11old, LU11old)
    L2 += 1.0*einsum('kjba,Ick,Iic->ijab', I.oovv, U11old, LU11old)
    L2 += -1.0*einsum('kjbc,Ick,Iia->ijab', I.oovv, U11old, LU11old)
    L2 += 1.0*einsum('kjac,Ick,Iib->ijab', I.oovv, U11old, LU11old)
    L2 += -1.0*einsum('kiba,Ick,Ijc->ijab', I.oovv, U11old, LU11old)
    L2 += 1.0*einsum('kibc,Ick,Ija->ijab', I.oovv, U11old, LU11old)
    L2 += -1.0*einsum('kiac,Ick,Ijb->ijab', I.oovv, U11old, LU11old)
    L2 += 1.0*einsum('jikc,cl,klba->ijab', I.ooov, T1old, L2old)
    L2 += -1.0*einsum('Ijb,Ick,kiac->ijab', g.ov, U11old, L2old)
    L2 += 1.0*einsum('Ija,Ick,kibc->ijab', g.ov, U11old, L2old)
    L2 += -1.0*einsum('Ijc,Ick,kiba->ijab', g.ov, U11old, L2old)
    L2 += 1.0*einsum('Iib,Ick,kjac->ijab', g.ov, U11old, L2old)
    L2 += -1.0*einsum('Iia,Ick,kjbc->ijab', g.ov, U11old, L2old)
    L2 += 1.0*einsum('Iic,Ick,kjba->ijab', g.ov, U11old, L2old)
    L2 += 1.0*einsum('kjlb,ck,liac->ijab', I.ooov, T1old, L2old)
    L2 += -1.0*einsum('jcbd,dk,kiac->ijab', I.ovvv, T1old, L2old)
    L2 += -1.0*einsum('kjla,ck,libc->ijab', I.ooov, T1old, L2old)
    L2 += 1.0*einsum('jcad,dk,kibc->ijab', I.ovvv, T1old, L2old)
    L2 += 1.0*einsum('kjlc,ck,liba->ijab', I.ooov, T1old, L2old)
    L2 += -1.0*einsum('kilb,ck,ljac->ijab', I.ooov, T1old, L2old)
    L2 += 1.0*einsum('icbd,dk,kjac->ijab', I.ovvv, T1old, L2old)
    L2 += 1.0*einsum('kila,ck,ljbc->ijab', I.ooov, T1old, L2old)
    L2 += -1.0*einsum('icad,dk,kjbc->ijab', I.ovvv, T1old, L2old)
    L2 += -1.0*einsum('kilc,ck,ljba->ijab', I.ooov, T1old, L2old)
    L2 += 1.0*einsum('Ikb,Ick,jiac->ijab', g.ov, U11old, L2old)
    L2 += -1.0*einsum('Ika,Ick,jibc->ijab', g.ov, U11old, L2old)
    L2 += -1.0*einsum('kcba,dk,jidc->ijab', I.ovvv, T1old, L2old)
    L2 += 1.0*einsum('kcbd,dk,jiac->ijab', I.ovvv, T1old, L2old)
    L2 += -1.0*einsum('kcad,dk,jibc->ijab', I.ovvv, T1old, L2old)
    L2 += -0.5*einsum('jibc,dckl,lkad->ijab', I.oovv, T2old, L2old)
    L2 += 0.5*einsum('jiac,dckl,lkbd->ijab', I.oovv, T2old, L2old)
    L2 += 0.25*einsum('jicd,dckl,lkba->ijab', I.oovv, T2old, L2old)
    L2 += 0.5*einsum('kjba,cdkl,lidc->ijab', I.oovv, T2old, L2old)
    L2 += -1.0*einsum('kjbc,dckl,liad->ijab', I.oovv, T2old, L2old)
    L2 += 1.0*einsum('kjac,dckl,libd->ijab', I.oovv, T2old, L2old)
    L2 += 0.5*einsum('kjcd,dckl,liba->ijab', I.oovv, T2old, L2old)
    L2 += -0.5*einsum('kiba,cdkl,ljdc->ijab', I.oovv, T2old, L2old)
    L2 += 1.0*einsum('kibc,dckl,ljad->ijab', I.oovv, T2old, L2old)
    L2 += -1.0*einsum('kiac,dckl,ljbd->ijab', I.oovv, T2old, L2old)
    L2 += -0.5*einsum('kicd,dckl,ljba->ijab', I.oovv, T2old, L2old)
    L2 += 0.25*einsum('klba,cdlk,jidc->ijab', I.oovv, T2old, L2old)
    L2 += -0.5*einsum('klbc,dclk,jiad->ijab', I.oovv, T2old, L2old)
    L2 += 0.5*einsum('klac,dclk,jibd->ijab', I.oovv, T2old, L2old)
    L2 += -1.0*einsum('Ijc,ck,I,kiba->ijab', g.ov, T1old, S1old, L2old)
    L2 += 1.0*einsum('Iic,ck,I,kjba->ijab', g.ov, T1old, S1old, L2old)
    L2 += 1.0*einsum('Ikb,ck,I,jiac->ijab', g.ov, T1old, S1old, L2old)
    L2 += -1.0*einsum('Ika,ck,I,jibc->ijab', g.ov, T1old, S1old, L2old)
    L2 += -0.5*einsum('jicd,dk,cl,klba->ijab', I.oovv, T1old, T1old, L2old)
    L2 += -1.0*einsum('kjbc,cl,dk,liad->ijab', I.oovv, T1old, T1old, L2old)
    L2 += 1.0*einsum('kjac,cl,dk,libd->ijab', I.oovv, T1old, T1old, L2old)
    L2 += -1.0*einsum('kjcd,dl,ck,liba->ijab', I.oovv, T1old, T1old, L2old)
    L2 += 1.0*einsum('kibc,cl,dk,ljad->ijab', I.oovv, T1old, T1old, L2old)
    L2 += -1.0*einsum('kiac,cl,dk,ljbd->ijab', I.oovv, T1old, T1old, L2old)
    L2 += 1.0*einsum('kicd,dl,ck,ljba->ijab', I.oovv, T1old, T1old, L2old)
    L2 += -0.5*einsum('klba,ck,dl,jidc->ijab', I.oovv, T1old, T1old, L2old)
    L2 += 1.0*einsum('klbc,dk,cl,jiad->ijab', I.oovv, T1old, T1old, L2old)
    L2 += -1.0*einsum('klac,dk,cl,jibd->ijab', I.oovv, T1old, T1old, L2old)

# disconnected piece projecting onto single fermionic excitations...
    L2 += 1.0*einsum('jb,ia->ijab', L1old, F.ov)
    L2 += -1.0*einsum('ja,ib->ijab', L1old, F.ov)
    L2 += -1.0*einsum('ib,ja->ijab', L1old, F.ov)
    L2 += 1.0*einsum('ia,jb->ijab', L1old, F.ov)
    L2 += 1.0*einsum('I,jb,Iia->ijab', S1old, L1old, g.ov)
    L2 += -1.0*einsum('I,ja,Iib->ijab', S1old, L1old, g.ov)
    L2 += -1.0*einsum('I,ib,Ija->ijab', S1old, L1old, g.ov)
    L2 += 1.0*einsum('I,ia,Ijb->ijab', S1old, L1old, g.ov)
    L2 += -1.0*einsum('ck,jb,kiac->ijab', T1old, L1old, I.oovv)
    L2 += 1.0*einsum('ck,ja,kibc->ijab', T1old, L1old, I.oovv)
    L2 += 1.0*einsum('ck,ib,kjac->ijab', T1old, L1old, I.oovv)
    L2 += -1.0*einsum('ck,ia,kjbc->ijab', T1old, L1old, I.oovv)

# lambda residuals for 1 boson deexcitation space...
# connected piece not proportional to Lambda...
    LS1 = 1.0*einsum('I->I', G)
    LS1 += 1.0*einsum('ai,Iia->I', T1old, g.ov)

# connected piece proportional to Lambda...
    LS1 += 1.0*einsum('JI,J->I', w, LS1old)
    LS1 += 1.0*einsum('Iai,ia->I', g.vo, L1old)
    LS1 += 1.0*einsum('ai,Iia->I', F.vo, LU11old)
    LS1 += 1.0*einsum('Iia,Jai,J->I', g.ov, U11old, LS1old)
    LS1 += -1.0*einsum('Iij,ai,ja->I', g.oo, T1old, L1old)
    LS1 += 1.0*einsum('Iab,bi,ia->I', g.vv, T1old, L1old)
    LS1 += 1.0*einsum('J,Jai,Iia->I', G, U11old, LU11old)
    LS1 += 1.0*einsum('Jai,J,Iia->I', g.vo, S1old, LU11old)
    LS1 += -1.0*einsum('ij,ai,Ija->I', F.oo, T1old, LU11old)
    LS1 += 1.0*einsum('ab,bi,Iia->I', F.vv, T1old, LU11old)
    LS1 += -1.0*einsum('Iia,baij,jb->I', g.ov, T2old, L1old)
    LS1 += -1.0*einsum('Iij,Jai,Jja->I', g.oo, U11old, LU11old)
    LS1 += 1.0*einsum('Iab,Jbi,Jia->I', g.vv, U11old, LU11old)
    LS1 += -1.0*einsum('ia,baij,Ijb->I', F.ov, T2old, LU11old)
    LS1 += -1.0*einsum('Jij,Jai,Ija->I', g.oo, U11old, LU11old)
    LS1 += 1.0*einsum('Jab,Jbi,Iia->I', g.vv, U11old, LU11old)
    LS1 += -1.0*einsum('iajb,bi,Ija->I', I.ovov, T1old, LU11old)
    LS1 += 0.5*einsum('ijka,baji,Ikb->I', I.ooov, T2old, LU11old)
    LS1 += -0.5*einsum('iabc,cbij,Ija->I', I.ovvv, T2old, LU11old)
    LS1 += 0.5*einsum('Iij,abik,jkba->I', g.oo, T2old, L2old)
    LS1 += -0.5*einsum('Iab,cbij,jica->I', g.vv, T2old, L2old)
    LS1 += -1.0*einsum('Iia,aj,bi,jb->I', g.ov, T1old, T1old, L1old)
    LS1 += -1.0*einsum('ia,aj,bi,Ijb->I', F.ov, T1old, T1old, LU11old)
    LS1 += -1.0*einsum('Jij,ai,J,Ija->I', g.oo, T1old, S1old, LU11old)
    LS1 += 1.0*einsum('Jab,bi,J,Iia->I', g.vv, T1old, S1old, LU11old)
    LS1 += -1.0*einsum('Iia,bi,Jaj,Jjb->I', g.ov, T1old, U11old, LU11old)
    LS1 += -1.0*einsum('Iia,aj,Jbi,Jjb->I', g.ov, T1old, U11old, LU11old)
    LS1 += -1.0*einsum('Jia,bi,Jaj,Ijb->I', g.ov, T1old, U11old, LU11old)
    LS1 += -1.0*einsum('Jia,aj,Jbi,Ijb->I', g.ov, T1old, U11old, LU11old)
    LS1 += 1.0*einsum('Jia,ai,Jbj,Ijb->I', g.ov, T1old, U11old, LU11old)
    LS1 += -1.0*einsum('Jia,baij,J,Ijb->I', g.ov, T2old, S1old, LU11old)
    LS1 += -1.0*einsum('ijka,bi,aj,Ikb->I', I.ooov, T1old, T1old, LU11old)
    LS1 += 1.0*einsum('iabc,cj,bi,Ija->I', I.ovvv, T1old, T1old, LU11old)
    LS1 += -0.5*einsum('ijab,ci,bajk,Ikc->I', I.oovv, T1old, T2old, LU11old)
    LS1 += -0.5*einsum('ijab,bk,caji,Ikc->I', I.oovv, T1old, T2old, LU11old)
    LS1 += 1.0*einsum('ijab,bi,cajk,Ikc->I', I.oovv, T1old, T2old, LU11old)
    LS1 += 0.5*einsum('Iia,bi,cajk,kjcb->I', g.ov, T1old, T2old, L2old)
    LS1 += 0.5*einsum('Iia,aj,bcik,jkcb->I', g.ov, T1old, T2old, L2old)
    LS1 += -1.0*einsum('Jia,aj,bi,J,Ijb->I', g.ov, T1old, T1old, S1old, LU11old)
    LS1 += 1.0*einsum('ijab,bk,ci,aj,Ikc->I', I.oovv, T1old, T1old, T1old, LU11old)

# lambda residuals for 1 boson + 1 fermion deexcitation space...
# connected piece not proportional to Lambda...
    LU11 = 1.0*einsum('Iia->Iia', g.ov)

# connected piece proportional to Lambda...
    LU11 += -1.0*einsum('Iij,ja->Iia', g.oo, L1old)
    LU11 += 1.0*einsum('Iba,ib->Iia', g.vv, L1old)
    LU11 += 1.0*einsum('JI,Jia->Iia', w, LU11old)
    LU11 += -1.0*einsum('ij,Ija->Iia', F.oo, LU11old)
    LU11 += 1.0*einsum('ba,Iib->Iia', F.vv, LU11old)
    LU11 += -1.0*einsum('ibja,Ijb->Iia', I.ovov, LU11old)
    LU11 += -1.0*einsum('Ibj,jiab->Iia', g.vo, L2old)
    LU11 += -1.0*einsum('Iib,bj,ja->Iia', g.ov, T1old, L1old)
    LU11 += -1.0*einsum('Ija,bj,ib->Iia', g.ov, T1old, L1old)
    LU11 += -1.0*einsum('ib,bj,Ija->Iia', F.ov, T1old, LU11old)
    LU11 += -1.0*einsum('ja,bj,Iib->Iia', F.ov, T1old, LU11old)
    LU11 += -1.0*einsum('Jij,J,Ija->Iia', g.oo, S1old, LU11old)
    LU11 += 1.0*einsum('Jba,J,Iib->Iia', g.vv, S1old, LU11old)
    LU11 += -1.0*einsum('Iib,Jbj,Jja->Iia', g.ov, U11old, LU11old)
    LU11 += -1.0*einsum('Ija,Jbj,Jib->Iia', g.ov, U11old, LU11old)
    LU11 += 1.0*einsum('Ijb,Jbj,Jia->Iia', g.ov, U11old, LU11old)
    LU11 += 1.0*einsum('Jia,Jbj,Ijb->Iia', g.ov, U11old, LU11old)
    LU11 += -1.0*einsum('Jib,Jbj,Ija->Iia', g.ov, U11old, LU11old)
    LU11 += -1.0*einsum('Jja,Jbj,Iib->Iia', g.ov, U11old, LU11old)
    LU11 += -1.0*einsum('jika,bj,Ikb->Iia', I.ooov, T1old, LU11old)
    LU11 += 1.0*einsum('ibac,cj,Ijb->Iia', I.ovvv, T1old, LU11old)
    LU11 += 1.0*einsum('jikb,bj,Ika->Iia', I.ooov, T1old, LU11old)
    LU11 += -1.0*einsum('jbac,cj,Iib->Iia', I.ovvv, T1old, LU11old)
    LU11 += 1.0*einsum('Ijk,bj,kiab->Iia', g.oo, T1old, L2old)
    LU11 += -1.0*einsum('Ibc,cj,jiab->Iia', g.vv, T1old, L2old)
    LU11 += 1.0*einsum('jiab,cbjk,Ikc->Iia', I.oovv, T2old, LU11old)
    LU11 += 0.5*einsum('jibc,cbjk,Ika->Iia', I.oovv, T2old, LU11old)
    LU11 += 0.5*einsum('jkab,cbkj,Iic->Iia', I.oovv, T2old, LU11old)
    LU11 += -0.5*einsum('Iib,cbjk,kjac->Iia', g.ov, T2old, L2old)
    LU11 += -0.5*einsum('Ija,bcjk,kicb->Iia', g.ov, T2old, L2old)
    LU11 += 1.0*einsum('Ijb,cbjk,kiac->Iia', g.ov, T2old, L2old)
    LU11 += -1.0*einsum('Jib,bj,J,Ija->Iia', g.ov, T1old, S1old, LU11old)
    LU11 += -1.0*einsum('Jja,bj,J,Iib->Iia', g.ov, T1old, S1old, LU11old)
    LU11 += 1.0*einsum('jiab,bk,cj,Ikc->Iia', I.oovv, T1old, T1old, LU11old)
    LU11 += -1.0*einsum('jibc,ck,bj,Ika->Iia', I.oovv, T1old, T1old, LU11old)
    LU11 += -1.0*einsum('jkab,cj,bk,Iic->Iia', I.oovv, T1old, T1old, LU11old)
    LU11 += 1.0*einsum('Ijb,bk,cj,kiac->Iia', g.ov, T1old, T1old, L2old)

# disconnected piece projecting onto single fermionic excitations...
    LU11 += 1.0*einsum('I,ia->Iia', LS1old, F.ov)
    LU11 += 1.0*einsum('J,I,Jia->Iia', S1old, LS1old, g.ov)
    LU11 += -1.0*einsum('bj,I,jiab->Iia', T1old, LS1old, I.oovv)

# disconnected piece projecting onto single bosonic excitations...
    LU11 += 1.0*einsum('I,ia->Iia', LS1old, F.ov)
    LU11 += 1.0*einsum('J,I,Jia->Iia', S1old, LS1old, g.ov)
    LU11 += -1.0*einsum('bj,I,jiab->Iia', T1old, LS1old, I.oovv)

    res_L1 = np.linalg.norm(L1) / np.sqrt(L1.size)
    res_L2 = np.linalg.norm(L2) / np.sqrt(L2.size)
    res_LS1 = np.linalg.norm(LS1) / np.sqrt(LS1.size)
    res_LU11 = np.linalg.norm(LU11) / np.sqrt(LU11.size)
    res = res_L1 + res_L2 + res_LS1 + res_LU11 

    return res

def amp_updates_ccsd_1_1(cc, autogen=False):
    ''' Solve residual equations for CCSD.
        Equation generating script using the 'wick' program found in gen_eqns/ccsd_11_amps.py
    '''

    # Copy fock matrix in MO basis, and remove diagonals
    F = copy.copy(cc.fock_mo)
    F.oo = F.oo - np.diag(cc.eo)
    F.vv = F.vv - np.diag(cc.ev)

    I = cc.I

    T1old = cc.T1old
    T2old = cc.T2old
    S1old = cc.S1old
    U11old = cc.U11old

    g = copy.copy(cc.g_mo_blocks)
    h = copy.copy(cc.g_mo_blocks)
    G = cc.G.copy()
    H = cc.G.copy()

    # Note that we also have to remove diagonals from omega
    # matrix. Since the rest of the code is constrained to have
    # no coupling between bosons, this means that this is actually
    # the zero matrix, but we keep it in here anyway for potential
    # future applications
    w = np.diag(cc.omega).copy()
    w = w - np.diag(np.diag(w))

    # Update T1, T2, S1 and U11
    if autogen:
        if True: 
            # My code generation
            T1 = 1.0*einsum('ai->ai', F.vo)
            T1 += 1.0*einsum('I,Iai->ai', G, U11old)
            T1 += -1.0*einsum('ji,aj->ai', F.oo, T1old)
            T1 += 1.0*einsum('ab,bi->ai', F.vv, T1old)
            T1 += 1.0*einsum('Iai,I->ai', g.vo, S1old)
            T1 += -1.0*einsum('jb,abji->ai', F.ov, T2old)
            T1 += -1.0*einsum('Iji,Iaj->ai', g.oo, U11old)
            T1 += 1.0*einsum('Iab,Ibi->ai', g.vv, U11old)
            T1 += -1.0*einsum('jaib,bj->ai', I.ovov, T1old)
            T1 += 0.5*einsum('jkib,abkj->ai', I.ooov, T2old)
            T1 += -0.5*einsum('jabc,cbji->ai', I.ovvv, T2old)
            T1 += -1.0*einsum('jb,bi,aj->ai', F.ov, T1old, T1old)
            T1 += -1.0*einsum('Iji,aj,I->ai', g.oo, T1old, S1old)
            T1 += 1.0*einsum('Iab,bi,I->ai', g.vv, T1old, S1old)
            T1 += -1.0*einsum('Ijb,aj,Ibi->ai', g.ov, T1old, U11old)
            T1 += -1.0*einsum('Ijb,bi,Iaj->ai', g.ov, T1old, U11old)
            T1 += 1.0*einsum('Ijb,bj,Iai->ai', g.ov, T1old, U11old)
            T1 += -1.0*einsum('Ijb,abji,I->ai', g.ov, T2old, S1old)
            T1 += -1.0*einsum('jkib,aj,bk->ai', I.ooov, T1old, T1old)
            T1 += 1.0*einsum('jabc,ci,bj->ai', I.ovvv, T1old, T1old)
            T1 += -0.5*einsum('jkbc,aj,cbki->ai', I.oovv, T1old, T2old)
            T1 += -0.5*einsum('jkbc,ci,abkj->ai', I.oovv, T1old, T2old)
            T1 += 1.0*einsum('jkbc,cj,abki->ai', I.oovv, T1old, T2old)
            T1 += -1.0*einsum('Ijb,bi,aj,I->ai', g.ov, T1old, T1old, S1old)
            T1 += 1.0*einsum('jkbc,ci,aj,bk->ai', I.oovv, T1old, T1old, T1old)

            T2 = 1.0*einsum('baji->abij', I.vvoo)
            T2 += 1.0*einsum('ki,bakj->abij', F.oo, T2old)
            T2 += -1.0*einsum('kj,baki->abij', F.oo, T2old)
            T2 += 1.0*einsum('ac,bcji->abij', F.vv, T2old)
            T2 += -1.0*einsum('bc,acji->abij', F.vv, T2old)
            T2 += 1.0*einsum('Iai,Ibj->abij', g.vo, U11old)
            T2 += -1.0*einsum('Iaj,Ibi->abij', g.vo, U11old)
            T2 += -1.0*einsum('Ibi,Iaj->abij', g.vo, U11old)
            T2 += 1.0*einsum('Ibj,Iai->abij', g.vo, U11old)
            T2 += -1.0*einsum('kaji,bk->abij', I.ovoo, T1old)
            T2 += 1.0*einsum('kbji,ak->abij', I.ovoo, T1old)
            T2 += -1.0*einsum('baic,cj->abij', I.vvov, T1old)
            T2 += 1.0*einsum('bajc,ci->abij', I.vvov, T1old)
            T2 += -0.5*einsum('klji,balk->abij', I.oooo, T2old)
            T2 += 1.0*einsum('kaic,bckj->abij', I.ovov, T2old)
            T2 += -1.0*einsum('kajc,bcki->abij', I.ovov, T2old)
            T2 += -1.0*einsum('kbic,ackj->abij', I.ovov, T2old)
            T2 += 1.0*einsum('kbjc,acki->abij', I.ovov, T2old)
            T2 += -0.5*einsum('bacd,dcji->abij', I.vvvv, T2old)
            T2 += -1.0*einsum('kc,ak,bcji->abij', F.ov, T1old, T2old)
            T2 += 1.0*einsum('kc,bk,acji->abij', F.ov, T1old, T2old)
            T2 += 1.0*einsum('kc,ci,bakj->abij', F.ov, T1old, T2old)
            T2 += -1.0*einsum('kc,cj,baki->abij', F.ov, T1old, T2old)
            T2 += -1.0*einsum('Iki,ak,Ibj->abij', g.oo, T1old, U11old)
            T2 += 1.0*einsum('Iki,bk,Iaj->abij', g.oo, T1old, U11old)
            T2 += 1.0*einsum('Iki,bakj,I->abij', g.oo, T2old, S1old)
            T2 += 1.0*einsum('Ikj,ak,Ibi->abij', g.oo, T1old, U11old)
            T2 += -1.0*einsum('Ikj,bk,Iai->abij', g.oo, T1old, U11old)
            T2 += -1.0*einsum('Ikj,baki,I->abij', g.oo, T2old, S1old)
            T2 += 1.0*einsum('Iac,ci,Ibj->abij', g.vv, T1old, U11old)
            T2 += -1.0*einsum('Iac,cj,Ibi->abij', g.vv, T1old, U11old)
            T2 += 1.0*einsum('Iac,bcji,I->abij', g.vv, T2old, S1old)
            T2 += -1.0*einsum('Ibc,ci,Iaj->abij', g.vv, T1old, U11old)
            T2 += 1.0*einsum('Ibc,cj,Iai->abij', g.vv, T1old, U11old)
            T2 += -1.0*einsum('Ibc,acji,I->abij', g.vv, T2old, S1old)
            T2 += 1.0*einsum('klji,bk,al->abij', I.oooo, T1old, T1old)
            T2 += 1.0*einsum('kaic,cj,bk->abij', I.ovov, T1old, T1old)
            T2 += -1.0*einsum('kajc,ci,bk->abij', I.ovov, T1old, T1old)
            T2 += -1.0*einsum('kbic,cj,ak->abij', I.ovov, T1old, T1old)
            T2 += 1.0*einsum('kbjc,ci,ak->abij', I.ovov, T1old, T1old)
            T2 += 1.0*einsum('bacd,di,cj->abij', I.vvvv, T1old, T1old)
            T2 += 1.0*einsum('Ikc,acji,Ibk->abij', g.ov, T2old, U11old)
            T2 += -1.0*einsum('Ikc,acki,Ibj->abij', g.ov, T2old, U11old)
            T2 += 1.0*einsum('Ikc,ackj,Ibi->abij', g.ov, T2old, U11old)
            T2 += -1.0*einsum('Ikc,baki,Icj->abij', g.ov, T2old, U11old)
            T2 += 1.0*einsum('Ikc,bakj,Ici->abij', g.ov, T2old, U11old)
            T2 += -1.0*einsum('Ikc,bcji,Iak->abij', g.ov, T2old, U11old)
            T2 += 1.0*einsum('Ikc,bcki,Iaj->abij', g.ov, T2old, U11old)
            T2 += -1.0*einsum('Ikc,bckj,Iai->abij', g.ov, T2old, U11old)
            T2 += 1.0*einsum('klic,ak,bclj->abij', I.ooov, T1old, T2old)
            T2 += -1.0*einsum('klic,bk,aclj->abij', I.ooov, T1old, T2old)
            T2 += 0.5*einsum('klic,cj,balk->abij', I.ooov, T1old, T2old)
            T2 += -1.0*einsum('klic,ck,balj->abij', I.ooov, T1old, T2old)
            T2 += -1.0*einsum('kljc,ak,bcli->abij', I.ooov, T1old, T2old)
            T2 += 1.0*einsum('kljc,bk,acli->abij', I.ooov, T1old, T2old)
            T2 += -0.5*einsum('kljc,ci,balk->abij', I.ooov, T1old, T2old)
            T2 += 1.0*einsum('kljc,ck,bali->abij', I.ooov, T1old, T2old)
            T2 += 0.5*einsum('kacd,bk,dcji->abij', I.ovvv, T1old, T2old)
            T2 += -1.0*einsum('kacd,di,bckj->abij', I.ovvv, T1old, T2old)
            T2 += 1.0*einsum('kacd,dj,bcki->abij', I.ovvv, T1old, T2old)
            T2 += -1.0*einsum('kacd,dk,bcji->abij', I.ovvv, T1old, T2old)
            T2 += -0.5*einsum('kbcd,ak,dcji->abij', I.ovvv, T1old, T2old)
            T2 += 1.0*einsum('kbcd,di,ackj->abij', I.ovvv, T1old, T2old)
            T2 += -1.0*einsum('kbcd,dj,acki->abij', I.ovvv, T1old, T2old)
            T2 += 1.0*einsum('kbcd,dk,acji->abij', I.ovvv, T1old, T2old)
            T2 += 0.5*einsum('klcd,adji,bclk->abij', I.oovv, T2old, T2old)
            T2 += -1.0*einsum('klcd,adki,bclj->abij', I.oovv, T2old, T2old)
            T2 += -0.5*einsum('klcd,baki,dclj->abij', I.oovv, T2old, T2old)
            T2 += -0.5*einsum('klcd,bdji,aclk->abij', I.oovv, T2old, T2old)
            T2 += 1.0*einsum('klcd,bdki,aclj->abij', I.oovv, T2old, T2old)
            T2 += 0.25*einsum('klcd,dcji,balk->abij', I.oovv, T2old, T2old)
            T2 += -0.5*einsum('klcd,dcki,balj->abij', I.oovv, T2old, T2old)
            T2 += -1.0*einsum('Ikc,ak,bcji,I->abij', g.ov, T1old, T2old, S1old)
            T2 += 1.0*einsum('Ikc,bk,acji,I->abij', g.ov, T1old, T2old, S1old)
            T2 += -1.0*einsum('Ikc,ci,ak,Ibj->abij', g.ov, T1old, T1old, U11old)
            T2 += 1.0*einsum('Ikc,ci,bk,Iaj->abij', g.ov, T1old, T1old, U11old)
            T2 += 1.0*einsum('Ikc,ci,bakj,I->abij', g.ov, T1old, T2old, S1old)
            T2 += 1.0*einsum('Ikc,cj,ak,Ibi->abij', g.ov, T1old, T1old, U11old)
            T2 += -1.0*einsum('Ikc,cj,bk,Iai->abij', g.ov, T1old, T1old, U11old)
            T2 += -1.0*einsum('Ikc,cj,baki,I->abij', g.ov, T1old, T2old, S1old)
            T2 += -1.0*einsum('klic,cj,bk,al->abij', I.ooov, T1old, T1old, T1old)
            T2 += 1.0*einsum('kljc,ci,bk,al->abij', I.ooov, T1old, T1old, T1old)
            T2 += -1.0*einsum('kacd,di,cj,bk->abij', I.ovvv, T1old, T1old, T1old)
            T2 += 1.0*einsum('kbcd,di,cj,ak->abij', I.ovvv, T1old, T1old, T1old)
            T2 += -1.0*einsum('klcd,ak,dl,bcji->abij', I.oovv, T1old, T1old, T2old)
            T2 += -0.5*einsum('klcd,bk,al,dcji->abij', I.oovv, T1old, T1old, T2old)
            T2 += 1.0*einsum('klcd,bk,dl,acji->abij', I.oovv, T1old, T1old, T2old)
            T2 += -1.0*einsum('klcd,di,ak,bclj->abij', I.oovv, T1old, T1old, T2old)
            T2 += 1.0*einsum('klcd,di,bk,aclj->abij', I.oovv, T1old, T1old, T2old)
            T2 += -0.5*einsum('klcd,di,cj,balk->abij', I.oovv, T1old, T1old, T2old)
            T2 += 1.0*einsum('klcd,di,ck,balj->abij', I.oovv, T1old, T1old, T2old)
            T2 += 1.0*einsum('klcd,dj,ak,bcli->abij', I.oovv, T1old, T1old, T2old)
            T2 += -1.0*einsum('klcd,dj,bk,acli->abij', I.oovv, T1old, T1old, T2old)
            T2 += -1.0*einsum('klcd,dj,ck,bali->abij', I.oovv, T1old, T1old, T2old)
            T2 += 1.0*einsum('klcd,di,cj,bk,al->abij', I.oovv, T1old, T1old, T1old, T1old)
            
            S1 = G.copy() 
            S1 += 1.0*einsum('IJ,J->I', w, S1old)
            S1 += 1.0*einsum('ia,Iai->I', F.ov, U11old)
            S1 += 1.0*einsum('Iia,ai->I', g.ov, T1old)
            S1 += 1.0*einsum('Jia,J,Iai->I', g.ov, S1old, U11old)
            S1 += -1.0*einsum('ijab,bi,Iaj->I', I.oovv, T1old, U11old)

            U11 = g.vo.copy()
            U11 += -1.0*einsum('ji,Iaj->Iai', F.oo, U11old)
            U11 += 1.0*einsum('ab,Ibi->Iai', F.vv, U11old)
            U11 += 1.0*einsum('IJ,Jai->Iai', w, U11old)
            U11 += -1.0*einsum('Iji,aj->Iai', g.oo, T1old)
            U11 += 1.0*einsum('Iab,bi->Iai', g.vv, T1old)
            U11 += -1.0*einsum('Ijb,abji->Iai', g.ov, T2old)
            U11 += -1.0*einsum('jaib,Ibj->Iai', I.ovov, U11old)
            U11 += -1.0*einsum('jb,aj,Ibi->Iai', F.ov, T1old, U11old)
            U11 += -1.0*einsum('jb,bi,Iaj->Iai', F.ov, T1old, U11old)
            U11 += -1.0*einsum('Ijb,bi,aj->Iai', g.ov, T1old, T1old)
            U11 += -1.0*einsum('Jji,J,Iaj->Iai', g.oo, S1old, U11old)
            U11 += 1.0*einsum('Jab,J,Ibi->Iai', g.vv, S1old, U11old)
            U11 += -1.0*einsum('Jjb,Iaj,Jbi->Iai', g.ov, U11old, U11old)
            U11 += -1.0*einsum('Jjb,Ibi,Jaj->Iai', g.ov, U11old, U11old)
            U11 += 1.0*einsum('Jjb,Ibj,Jai->Iai', g.ov, U11old, U11old)
            U11 += -1.0*einsum('jkib,aj,Ibk->Iai', I.ooov, T1old, U11old)
            U11 += 1.0*einsum('jkib,bj,Iak->Iai', I.ooov, T1old, U11old)
            U11 += 1.0*einsum('jabc,ci,Ibj->Iai', I.ovvv, T1old, U11old)
            U11 += -1.0*einsum('jabc,cj,Ibi->Iai', I.ovvv, T1old, U11old)
            U11 += 1.0*einsum('jkbc,acji,Ibk->Iai', I.oovv, T2old, U11old)
            U11 += 0.5*einsum('jkbc,ackj,Ibi->Iai', I.oovv, T2old, U11old)
            U11 += 0.5*einsum('jkbc,cbji,Iak->Iai', I.oovv, T2old, U11old)
            U11 += -1.0*einsum('Jjb,aj,J,Ibi->Iai', g.ov, T1old, S1old, U11old)
            U11 += -1.0*einsum('Jjb,bi,J,Iaj->Iai', g.ov, T1old, S1old, U11old)
            U11 += -1.0*einsum('jkbc,aj,ck,Ibi->Iai', I.oovv, T1old, T1old, U11old)
            U11 += 1.0*einsum('jkbc,ci,aj,Ibk->Iai', I.oovv, T1old, T1old, U11old)
            U11 += -1.0*einsum('jkbc,ci,bj,Iak->Iai', I.oovv, T1old, T1old, U11old)
        else:
            # Autogen from epcc
            # CCSD equations
            #T1,T2 = cc_equations.ccsd_simple(F, I, T1old, T2old)
            T1 = 1.0*einsum('ai->ai', F.vo)
            T1 += -1.0*einsum('ji,aj->ai', F.oo, T1old)
            T1 += 1.0*einsum('ab,bi->ai', F.vv, T1old)
            T1 += -1.0*einsum('jb,abji->ai', F.ov, T2old)
            T1 += -1.0*einsum('jaib,bj->ai', I.ovov, T1old)
            T1 += 0.5*einsum('jkib,abkj->ai', I.ooov, T2old)
            T1 += -0.5*einsum('jabc,cbji->ai', I.ovvv, T2old)
            T1 += -1.0*einsum('jb,bi,aj->ai', F.ov, T1old, T1old)
            T1 += -1.0*einsum('jkib,aj,bk->ai', I.ooov, T1old, T1old)
            T1 += 1.0*einsum('jabc,ci,bj->ai', I.ovvv, T1old, T1old)
            T1 += -0.5*einsum('jkbc,aj,cbki->ai', I.oovv, T1old, T2old)
            T1 += -0.5*einsum('jkbc,ci,abkj->ai', I.oovv, T1old, T2old)
            T1 += 1.0*einsum('jkbc,cj,abki->ai', I.oovv, T1old, T2old)
            T1 += 1.0*einsum('jkbc,ci,aj,bk->ai', I.oovv, T1old, T1old, T1old)
            T2 = 1.0*einsum('baji->abij', I.vvoo)
            T2 += 1.0*einsum('ki,bakj->abij', F.oo, T2old)
            T2 += -1.0*einsum('kj,baki->abij', F.oo, T2old)
            T2 += 1.0*einsum('ac,bcji->abij', F.vv, T2old)
            T2 += -1.0*einsum('bc,acji->abij', F.vv, T2old)
            T2 += -1.0*einsum('kaji,bk->abij', I.ovoo, T1old)
            T2 += 1.0*einsum('kbji,ak->abij', I.ovoo, T1old)
            T2 += -1.0*einsum('baic,cj->abij', I.vvov, T1old)
            T2 += 1.0*einsum('bajc,ci->abij', I.vvov, T1old)
            T2 += -0.5*einsum('klji,balk->abij', I.oooo, T2old)
            T2 += 1.0*einsum('kaic,bckj->abij', I.ovov, T2old)
            T2 += -1.0*einsum('kajc,bcki->abij', I.ovov, T2old)
            T2 += -1.0*einsum('kbic,ackj->abij', I.ovov, T2old)
            T2 += 1.0*einsum('kbjc,acki->abij', I.ovov, T2old)
            T2 += -0.5*einsum('bacd,dcji->abij', I.vvvv, T2old)
            T2 += -1.0*einsum('kc,ak,bcji->abij', F.ov, T1old, T2old)
            T2 += 1.0*einsum('kc,bk,acji->abij', F.ov, T1old, T2old)
            T2 += 1.0*einsum('kc,ci,bakj->abij', F.ov, T1old, T2old)
            T2 += -1.0*einsum('kc,cj,baki->abij', F.ov, T1old, T2old)
            T2 += 1.0*einsum('klji,bk,al->abij', I.oooo, T1old, T1old)
            T2 += 1.0*einsum('kaic,cj,bk->abij', I.ovov, T1old, T1old)
            T2 += -1.0*einsum('kajc,ci,bk->abij', I.ovov, T1old, T1old)
            T2 += -1.0*einsum('kbic,cj,ak->abij', I.ovov, T1old, T1old)
            T2 += 1.0*einsum('kbjc,ci,ak->abij', I.ovov, T1old, T1old)
            T2 += 1.0*einsum('bacd,di,cj->abij', I.vvvv, T1old, T1old)
            T2 += 1.0*einsum('klic,ak,bclj->abij', I.ooov, T1old, T2old)
            T2 += -1.0*einsum('klic,bk,aclj->abij', I.ooov, T1old, T2old)
            T2 += 0.5*einsum('klic,cj,balk->abij', I.ooov, T1old, T2old)
            T2 += -1.0*einsum('klic,ck,balj->abij', I.ooov, T1old, T2old)
            T2 += -1.0*einsum('kljc,ak,bcli->abij', I.ooov, T1old, T2old)
            T2 += 1.0*einsum('kljc,bk,acli->abij', I.ooov, T1old, T2old)
            T2 += -0.5*einsum('kljc,ci,balk->abij', I.ooov, T1old, T2old)
            T2 += 1.0*einsum('kljc,ck,bali->abij', I.ooov, T1old, T2old)
            T2 += 0.5*einsum('kacd,bk,dcji->abij', I.ovvv, T1old, T2old)
            T2 += -1.0*einsum('kacd,di,bckj->abij', I.ovvv, T1old, T2old)
            T2 += 1.0*einsum('kacd,dj,bcki->abij', I.ovvv, T1old, T2old)
            T2 += -1.0*einsum('kacd,dk,bcji->abij', I.ovvv, T1old, T2old)
            T2 += -0.5*einsum('kbcd,ak,dcji->abij', I.ovvv, T1old, T2old)
            T2 += 1.0*einsum('kbcd,di,ackj->abij', I.ovvv, T1old, T2old)
            T2 += -1.0*einsum('kbcd,dj,acki->abij', I.ovvv, T1old, T2old)
            T2 += 1.0*einsum('kbcd,dk,acji->abij', I.ovvv, T1old, T2old)
            T2 += 0.5*einsum('klcd,adji,bclk->abij', I.oovv, T2old, T2old)
            T2 += -1.0*einsum('klcd,adki,bclj->abij', I.oovv, T2old, T2old)
            T2 += -0.5*einsum('klcd,baki,dclj->abij', I.oovv, T2old, T2old)
            T2 += -0.5*einsum('klcd,bdji,aclk->abij', I.oovv, T2old, T2old)
            T2 += 1.0*einsum('klcd,bdki,aclj->abij', I.oovv, T2old, T2old)
            T2 += 0.25*einsum('klcd,dcji,balk->abij', I.oovv, T2old, T2old)
            T2 += -0.5*einsum('klcd,dcki,balj->abij', I.oovv, T2old, T2old)
            T2 += -1.0*einsum('klic,cj,bk,al->abij', I.ooov, T1old, T1old, T1old)
            T2 += 1.0*einsum('kljc,ci,bk,al->abij', I.ooov, T1old, T1old, T1old)
            T2 += -1.0*einsum('kacd,di,cj,bk->abij', I.ovvv, T1old, T1old, T1old)
            T2 += 1.0*einsum('kbcd,di,cj,ak->abij', I.ovvv, T1old, T1old, T1old)
            T2 += -1.0*einsum('klcd,ak,dl,bcji->abij', I.oovv, T1old, T1old, T2old)
            T2 += -0.5*einsum('klcd,bk,al,dcji->abij', I.oovv, T1old, T1old, T2old)
            T2 += 1.0*einsum('klcd,bk,dl,acji->abij', I.oovv, T1old, T1old, T2old)
            T2 += -1.0*einsum('klcd,di,ak,bclj->abij', I.oovv, T1old, T1old, T2old)
            T2 += 1.0*einsum('klcd,di,bk,aclj->abij', I.oovv, T1old, T1old, T2old)
            T2 += -0.5*einsum('klcd,di,cj,balk->abij', I.oovv, T1old, T1old, T2old)
            T2 += 1.0*einsum('klcd,di,ck,balj->abij', I.oovv, T1old, T1old, T2old)
            T2 += 1.0*einsum('klcd,dj,ak,bcli->abij', I.oovv, T1old, T1old, T2old)
            T2 += -1.0*einsum('klcd,dj,bk,acli->abij', I.oovv, T1old, T1old, T2old)
            T2 += -1.0*einsum('klcd,dj,ck,bali->abij', I.oovv, T1old, T1old, T2old)
            T2 += 1.0*einsum('klcd,di,cj,bk,al->abij', I.oovv, T1old, T1old, T1old, T1old)

            # F1
            T1 += 1.0*einsum('I,Iai->ai', G, U11old)
            T1 += 1.0*einsum('Iai,I->ai', g.vo, S1old)
            T1 += -1.0*einsum('Iji,Iaj->ai', g.oo, U11old)
            T1 += 1.0*einsum('Iab,Ibi->ai', g.vv, U11old)
            T1 += -1.0*einsum('Iji,aj,I->ai', g.oo, T1old, S1old)
            T1 += 1.0*einsum('Iab,bi,I->ai', g.vv, T1old, S1old)
            T1 += -1.0*einsum('Ijb,bi,Iaj->ai', g.ov, T1old, U11old)
            T1 += -1.0*einsum('Ijb,aj,Ibi->ai', g.ov, T1old, U11old)
            T1 += 1.0*einsum('Ijb,bj,Iai->ai', g.ov, T1old, U11old)
            T1 += 1.0*einsum('Ijb,abij,I->ai', g.ov, T2old, S1old)
            T1 += -1.0*einsum('Ijb,bi,aj,I->ai', g.ov, T1old, T1old, S1old)

            # F2
            T2 += 1.0*einsum('Iai,Ibj->abij', g.vo, U11old)
            T2 += -1.0*einsum('Ibi,Iaj->abij', g.vo, U11old)
            T2 += -1.0*einsum('Iaj,Ibi->abij', g.vo, U11old)
            T2 += 1.0*einsum('Ibj,Iai->abij', g.vo, U11old)
            T2 += -1.0*einsum('Iki,ak,Ibj->abij', g.oo, T1old, U11old)
            T2 += 1.0*einsum('Iki,bk,Iaj->abij', g.oo, T1old, U11old)
            T2 += 1.0*einsum('Ikj,ak,Ibi->abij', g.oo, T1old, U11old)
            T2 += -1.0*einsum('Ikj,bk,Iai->abij', g.oo, T1old, U11old)
            T2 += 1.0*einsum('Iki,abjk,I->abij', g.oo, T2old, S1old)
            T2 += -1.0*einsum('Ikj,abik,I->abij', g.oo, T2old, S1old)
            T2 += 1.0*einsum('Iac,ci,Ibj->abij', g.vv, T1old, U11old)
            T2 += -1.0*einsum('Ibc,ci,Iaj->abij', g.vv, T1old, U11old)
            T2 += -1.0*einsum('Iac,cj,Ibi->abij', g.vv, T1old, U11old)
            T2 += 1.0*einsum('Ibc,cj,Iai->abij', g.vv, T1old, U11old)
            T2 += -1.0*einsum('Iac,bcij,I->abij', g.vv, T2old, S1old)
            T2 += 1.0*einsum('Ibc,acij,I->abij', g.vv, T2old, S1old)
            T2 += -1.0*einsum('Ikc,acij,Ibk->abij', g.ov, T2old, U11old)
            T2 += -1.0*einsum('Ikc,abik,Icj->abij', g.ov, T2old, U11old)
            T2 += 1.0*einsum('Ikc,acik,Ibj->abij', g.ov, T2old, U11old)
            T2 += 1.0*einsum('Ikc,bcij,Iak->abij', g.ov, T2old, U11old)
            T2 += -1.0*einsum('Ikc,bcik,Iaj->abij', g.ov, T2old, U11old)
            T2 += 1.0*einsum('Ikc,abjk,Ici->abij', g.ov, T2old, U11old)
            T2 += -1.0*einsum('Ikc,acjk,Ibi->abij', g.ov, T2old, U11old)
            T2 += 1.0*einsum('Ikc,bcjk,Iai->abij', g.ov, T2old, U11old)
            T2 += -1.0*einsum('Ikc,ci,ak,Ibj->abij', g.ov, T1old, T1old, U11old)
            T2 += 1.0*einsum('Ikc,ci,bk,Iaj->abij', g.ov, T1old, T1old, U11old)
            T2 += 1.0*einsum('Ikc,ak,cj,Ibi->abij', g.ov, T1old, T1old, U11old)
            T2 += -1.0*einsum('Ikc,cj,bk,Iai->abij', g.ov, T1old, T1old, U11old)
            T2 += 1.0*einsum('Ikc,ci,abjk,I->abij', g.ov, T1old, T2old, S1old)
            T2 += 1.0*einsum('Ikc,ak,bcij,I->abij', g.ov, T1old, T2old, S1old)
            T2 += -1.0*einsum('Ikc,cj,abik,I->abij', g.ov, T1old, T2old, S1old)
            T2 += -1.0*einsum('Ikc,bk,acij,I->abij', g.ov, T1old, T2old, S1old)

            # S1 equation
            S1 = H.copy()
            #S1 += 1.0*einsum('I,I->I', w, S1)
            S1 += 1.0*einsum('ia,Iai->I', F.ov, U11old)
            S1 += 1.0*einsum('Iia,ai->I', h.ov, T1old)
            S1 += 1.0*einsum('Jia,J,Iai->I', g.ov, S1old, U11old)
            S1 += -1.0*einsum('ijab,bi,Iaj->I', I.oovv, T1old, U11old)

            # U11 equations
            U11 = h.vo.copy()
            #U11 += 1.0*einsum('I,Iai->Iai', w, U11)
            U11 += -1.0*einsum('ji,Iaj->Iai', F.oo, U11old)
            U11 += 1.0*einsum('ab,Ibi->Iai', F.vv, U11old)
            U11 += -1.0*einsum('Iji,aj->Iai', h.oo, T1old)
            U11 += 1.0*einsum('Iab,bi->Iai', h.vv, T1old)
            U11 += -1.0*einsum('ajbi,Ibj->Iai', I.vovo, U11old)
            U11 += 1.0*einsum('Ijb,abij->Iai', h.ov, T2old)
            U11 += -1.0*einsum('jb,bi,Iaj->Iai', F.ov, T1old, U11old)
            U11 += -1.0*einsum('jb,aj,Ibi->Iai', F.ov, T1old, U11old)
            U11 += -1.0*einsum('Jji,J,Iaj->Iai', g.oo, S1old, U11old)
            U11 += -1.0*einsum('Ijb,bi,aj->Iai', h.ov, T1old, T1old)
            U11 += 1.0*einsum('Jab,J,Ibi->Iai', g.vv, S1old, U11old)
            U11 += -1.0*einsum('jkib,aj,Ibk->Iai', I.ooov, T1old, U11old)
            U11 += 1.0*einsum('jkib,bj,Iak->Iai', I.ooov, T1old, U11old)
            U11 += -1.0*einsum('ajbc,ci,Ibj->Iai', I.vovv, T1old, U11old)
            U11 += 1.0*einsum('ajbc,cj,Ibi->Iai', I.vovv, T1old, U11old)
            U11 += -1.0*einsum('Jjb,Ibi,Jaj->Iai', g.ov, U11old, U11old)
            U11 += -1.0*einsum('Jjb,Iaj,Jbi->Iai', g.ov, U11old, U11old)
            U11 += 1.0*einsum('Jjb,Ibj,Jai->Iai', g.ov, U11old, U11old)
            U11 += -1.0*einsum('jkbc,acij,Ibk->Iai', I.oovv, T2old, U11old)
            U11 += -0.5*einsum('jkbc,cbij,Iak->Iai', I.oovv, T2old, U11old)
            U11 += -0.5*einsum('jkbc,acjk,Ibi->Iai', I.oovv, T2old, U11old)
            U11 += -1.0*einsum('Jjb,bi,J,Iaj->Iai', g.ov, T1old, S1old, U11old)
            U11 += -1.0*einsum('Jjb,aj,J,Ibi->Iai', g.ov, T1old, S1old, U11old)
            U11 += 1.0*einsum('jkbc,ci,aj,Ibk->Iai', I.oovv, T1old, T1old, U11old)
            U11 += -1.0*einsum('jkbc,ci,bj,Iak->Iai', I.oovv, T1old, T1old, U11old)
            U11 += -1.0*einsum('jkbc,aj,ck,Ibi->Iai', I.oovv, T1old, T1old, U11old)

        
    else:
        T1 = F.vo.copy()
        T1 += einsum('xai,x->ai', g.vo, S1old)
        T1 += einsum('x,xai->ai',G, U11old)

        T2 = I.vvoo.copy()
        abij_temp = einsum('xai,xbj->abij', g.vo, U11old)
        T2 += abij_temp
        T2 -= abij_temp.transpose((1,0,2,3))
        T2 -= abij_temp.transpose((0,1,3,2))
        T2 += abij_temp.transpose((1,0,3,2))
        abij_temp = None

        T2A = T2old.copy()
        T2A += 0.5*einsum('ai,bj->abij',T1old,T1old)
        T2A -= 0.5*einsum('bi,aj->abij',T1old,T1old)

        Fvv = F.vv.copy()
        Fvv += einsum('xab,x->ab', g.vv, S1old)
        Fvv -= 0.5*einsum('jb,aj->ab',F.ov,T1old)
        Fvv -= einsum('ajcb,cj->ab',I.vovv,T1old)
        Fvv -= 0.5*einsum('jkbc,acjk->ab',I.oovv,T2A)
        Fvv -= einsum('yjb,yaj->ab', g.ov, U11old)

        Foo = F.oo.copy()
        Foo += einsum('xji,x->ji', g.oo, S1old)
        Foo += 0.5*einsum('jb,bi->ji',F.ov,T1old)
        Foo += einsum('jkib,bk->ji',I.ooov,T1old)
        Foo += 0.5*einsum('jkbc,bcik->ji',I.oovv,T2A)
        Foo += einsum('yjb,ybi->ji', g.ov, U11old)
        T2A = None

        gsov = einsum('yia,y->ia', g.ov, S1old)
        gtm = einsum('xjb,bj->x', g.ov, T1old)
        Fov = F.ov.copy()
        Fov += einsum('jkbc,ck->jb',I.oovv,T1old)
        Fov += gsov

        T1 += einsum('ab,bi->ai',Fvv,T1old)
        T1 -= einsum('ji,aj->ai',Foo,T1old)
        T1 += einsum('jb,abij->ai',Fov,T2old)
        T1 -= einsum('ajbi,bj->ai',I.vovo,T1old)
        T1 += 0.5*einsum('ajbc,bcij->ai',I.vovv,T2old)
        T1 -= 0.5*einsum('jkib,abjk->ai',I.ooov,T2old)

        T2B = T2old.copy()
        T2B += einsum('ai,bj->abij',T1old,T1old)
        T2B -= einsum('bi,aj->abij',T1old,T1old)

        Woooo = I.oooo.copy()
        Woooo += einsum('klic,cj->klij',I.ooov,T1old)
        Woooo -= einsum('kljc,ci->klij',I.ooov,T1old)
        Woooo += 0.25*einsum('klcd,cdij->klij',I.oovv,T2B)
        T2 += 0.5*einsum('klij,abkl->abij',Woooo,T2B)
        Woooo = None

        Wvvvv = I.vvvv.copy()
        Wvvvv -= einsum('akcd,bk->abcd',I.vovv,T1old)
        Wvvvv += einsum('bkcd,ak->abcd',I.vovv,T1old)
        Wvvvv += 0.25*einsum('klcd,abkl->abcd',I.oovv,T2B)
        T2 += 0.5*einsum('abcd,cdij->abij',Wvvvv,T2B)
        T2B = None
        Wvvvv = None

        Wovvo = -I.vovo.transpose((1,0,2,3))
        Wovvo -= einsum('bkcd,dj->kbcj',I.vovv,T1old)
        Wovvo += einsum('kljc,bl->kbcj',I.ooov,T1old)
        temp = 0.5*T2old + einsum('dj,bl->dbjl',T1old,T1old)
        Wovvo -= einsum('klcd,dbjl->kbcj',I.oovv,temp)
        temp = einsum('kbcj,acik->abij',Wovvo,T2old)
        temp += einsum('bkcj,ci,ak->abij',I.vovo,T1old,T1old)
        T2 += temp
        T2 -= temp.transpose((0,1,3,2))
        T2 -= temp.transpose((1,0,2,3))
        T2 += temp.transpose((1,0,3,2))
        temp = None
        #Wovvo = None

        Ftemp = Fvv - 0.5*einsum('jb,aj->ab',Fov,T1old)
        temp_ab = einsum('bc,acij->abij',Ftemp,T2old)
        temp_ab += einsum('bkij,ak->abij',I.vooo,T1old)
        T2 += temp_ab
        T2 -= temp_ab.transpose((1,0,2,3))
        temp_ab = None

        Ftemp = Foo + 0.5*einsum('jb,bi->ji',Fov,T1old)
        temp_ij = -einsum('kj,abik->abij',Ftemp,T2old)
        temp_ij += einsum('abcj,ci->abij',I.vvvo,T1old)
        T2 += temp_ij
        T2 -= temp_ij.transpose((0,1,3,2))
        temp_ij = None

        # remaining T1 terms
        T1 += einsum('xab,xbi->ai', g.vv, U11old)
        T1 -= einsum('xji,xaj->ai',g.oo, U11old)

        T1 += einsum('x,xai->ai', gtm, U11old)
        ttt = einsum('jb,bi->ji', gsov, T1old)
        T1 -= einsum('ji,aj->ai', ttt, T1old)

        # Remaining T2 terms
        gtov = einsum('xac,ci->xai', g.vv, T1old)
        gtov -= einsum('xki,ak->xai', g.oo, T1old)
        temp_abij = einsum('xai,xbj->abij', gtov, U11old)
        T2temp = T2old - einsum('bi,aj->abij', T1old, T1old)
        Wmvo = einsum('xkc,acik->xai', g.ov, T2temp)
        temp_abij += einsum('xai,xbj->abij', Wmvo, U11old)
        T2 += temp_abij
        T2 -= temp_abij.transpose((1,0,2,3))
        T2 -= temp_abij.transpose((0,1,3,2))
        T2 += temp_abij.transpose((1,0,3,2))
        temp_abij = None

        gstv = einsum('kc,bk->bc', gsov, T1old)
        temp_ab = -0.5*einsum('bc,acij->abij', gstv, T2old)
        T2 += temp_ab
        T2 -= temp_ab.transpose((1,0,2,3))
        temp_ab = None

        gsto = einsum('kc,cj->kj', gsov, T1old)
        temp_ij = -0.5*einsum('kj,abik->abij', gsto, T2old)
        T2 += temp_ij
        T2 -= temp_ij.transpose((0,1,3,2))
        temp_ij = None

        # S1 and U11 terms
        S1 = H.copy()
        U11 = h.vo.copy()
        S1 += einsum('xia,ai->x', h.ov, T1old)
        S1 += einsum('ia,xai->x', F.ov, U11old)
        S1 += einsum('ia,xai->x', gsov, U11old)

        Xov = einsum('ijab,xbj->xia', I.oovv, U11old)
        S1 += einsum('xia,ai->x', Xov, T1old)

        U11 += 0.5*einsum('xjb,abij->xai', Xov, T2old)

        U11 += einsum('xab,bi->xai', h.vv, T1old)
        U11 -= einsum('xji,aj->xai', h.oo, T1old)

        U11 += einsum('xjb,abij->xai', h.ov, T2temp)

        U11 += einsum('ab,xbi->xai', Fvv, U11old)
        U11 -= einsum('ji,xaj->xai', Foo, U11old)

        U11 += einsum('jabi,xbj->xai', Wovvo, U11old)

        Xvv = einsum('jb,aj->ab', Fov + gsov, T1old)
        U11 -= 0.5*einsum('ab,xbi->xai', Xvv, U11old)

        Xoo = einsum('jb,bi->ji', Fov + gsov, T1old)
        U11 -= 0.5*einsum('ji,xaj->xai', Xoo, U11old)

        Xmm = einsum('yjb,xbj->xy', g.ov, U11old)
        U11 += einsum('xy,yai->xai', Xmm, U11old)

    return T1, T2, S1, U11 
