site_name: ebcc

watch:
- ../ebcc

theme:
  name: terminal

docs_dir: .

site_dir: ../site

plugins:
- search
- gen-files:
    scripts:
    - gen_files.py
- section-index
- include-markdown
- md-to-html
- mkdocstrings:
    default_handler: python
    handlers:
        python:
            rendering:
                show_source: false
            options:
                docstring_style: google
                members_order: source
                line_length: 100
                merge_init_into_class: true
                show_if_no_docstring: false
                show_root_members_full_path: true
                show_object_full_path: true

nav:
- Home: "index.md"
- Features: "features.md"
- Code Reference:
  - Coupled cluster:
    - Restricted: reference/cc/rebcc.html
    - Unrestricted: reference/cc/uebcc.html
    - Generalised: reference/cc/gebcc.html
    - Base: reference/cc/base.html
  - Equation of motion:
    - Restricted: reference/eom/reom.html
    - Unrestricted: reference/eom/ueom.html
    - Generalised: reference/eom/geom.html
    - Base: reference/eom/base.html
  - Orbital optimisation:
    - Brueckner:
      - Restricted: reference/opt/rbrueckner.html
      - Unrestricted: reference/opt/ubrueckner.html
      - Generalised: reference/opt/gbrueckner.html
    - Base: reference/opt/base.html
  - Core:
    - Ansatz: reference/core/ansatz.html
    - Damping: reference/core/damping.html
    - Dumping: reference/core/dump.html
    - Logging: reference/core/logging.html
    - Precision: reference/core/precision.html
  - Hamiltonian:
    - Space: reference/ham/space.html
    - Fock: reference/ham/fock.html
    - ERIs: reference/ham/eris.html
    - CDERIs: reference/ham/cderis.html
    - Bosonic: reference/ham/elbos.html
    - Base: reference/ham/base.html
  - Utility:
    - Permutations: reference/util/permutations.html
    - Einstein summations: reference/util/einsumfunc.html
    - Miscellaneous: reference/util/misc.html
