name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: python ${{ matrix.python-version }} on ${{matrix.os}}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - {python-version: "3.8", os: ubuntu-latest, documentation: True}
          - {python-version: "3.9", os: ubuntu-latest, documentation: False}
          - {python-version: "3.10", os: ubuntu-latest, documentation: False}
          - {python-version: "3.11", os: ubuntu-latest, documentation: False}

    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install ebcc
        run: |
          python -m pip install wheel
          python -m pip install .[dev]
      - name: Linting
        run: |
          python -m black ebcc/ --diff --check --verbose
          python -m isort ebcc/ --diff --check-only --verbose
      - name: Run unit tests
        run: |
          python -m pip install pytest pytest-cov
          pytest --cov ebcc/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
