name: Publish

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  release-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/ebcc
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up python "3.9"
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install ebcc
        run: |
          python -m pip install wheel build
          python -m pip install .[dev]
      - name: Build wheel
        run: |
          python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TESTPYPI_API_TOKEN }}
          verbose: true
